/*
================================================================================
CDC DATA PRESERVATION - CREATE ALL TARGET TABLES
================================================================================
Purpose      : Create all 21 target tables in D_BRONZE with CDC metadata columns
Version      : 1.0 (Production)
Last Updated : 2026-02-23
================================================================================

PREREQUISITES:
- Execute 01_SET_PARAMETERS.sql first
- Execute 02_CDC_INFRASTRUCTURE.sql first
- Target database and schema must exist

================================================================================
*/

-- =============================================================================
-- USE PARAMETERS FROM SESSION
-- =============================================================================
USE DATABASE IDENTIFIER($TARGET_DATABASE);
USE SCHEMA IDENTIFIER($TARGET_SCHEMA);
USE WAREHOUSE IDENTIFIER($CDC_WAREHOUSE);

-- =============================================================================
-- TABLE 1: TRAIN_PLAN (17 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRAIN_PLAN (
    TRAIN_PLAN_ID NUMBER(18,0) NOT NULL,
    TRAIN_NM VARCHAR(32),
    TRAIN_DRCTN_CD VARCHAR(20),
    TRAIN_SRVC_CD VARCHAR(24),
    TRAIN_SYMBOL_CD VARCHAR(48),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    CRNT_STN_SCAC_CD VARCHAR(16),
    CRNT_STN_FSAC_CD VARCHAR(20),
    TRAIN_CNST_SMRY_ID NUMBER(18,0),
    TRAIN_STATUS_CD VARCHAR(24),
    ENT_TYPE_CD VARCHAR(32),
    TYES_TRAIN_ID NUMBER(18,0),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    -- CDC Metadata Columns
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (TRAIN_PLAN_ID)
)
COMMENT = 'CDC preserved table for TRAIN_PLAN_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 2: OPTRN (17 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS OPTRN (
    OPTRN_ID NUMBER(18,0) NOT NULL,
    OPTRN_STATUS_CD VARCHAR(24),
    OPTRN_NM VARCHAR(32),
    ENT_TYPE_CD VARCHAR(32),
    TRAIN_SRVC_CD VARCHAR(24),
    CRNT_STN_SCAC_CD VARCHAR(16),
    CRNT_STN_FSAC_CD VARCHAR(20),
    TRAIN_CNST_SMRY_ID NUMBER(18,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    TRAIN_PLAN_ID NUMBER(18,0),
    TYES_TRAIN_ID NUMBER(18,0),
    TRAIN_DRCTN_CD VARCHAR(20),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (OPTRN_ID)
)
COMMENT = 'CDC preserved table for OPTRN_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 3: OPTRN_LEG (13 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS OPTRN_LEG (
    OPTRN_LEG_ID NUMBER(18,0) NOT NULL,
    OPTRN_ID NUMBER(18,0),
    TRAIN_DRCTN_CD VARCHAR(20),
    OPTRN_LEG_NM VARCHAR(32),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    TRAIN_PLAN_LEG_ID NUMBER(18,0),
    TYES_TRAIN_ID NUMBER(18,0),
    MTP_TITAN_NBR NUMBER(6,0),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (OPTRN_LEG_ID)
)
COMMENT = 'CDC preserved table for OPTRN_LEG_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 4: OPTRN_EVENT (28 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS OPTRN_EVENT (
    OPTRN_EVENT_ID NUMBER(18,0) NOT NULL,
    OPTRN_LEG_ID NUMBER(18,0),
    TRAIN_EVENT_TYPE_CD VARCHAR(16),
    EVENT_TMS TIMESTAMP_NTZ(0),
    MTP_ROUTE_POINT_SQNC_NBR NUMBER(3,0),
    TRAVEL_DRCTN_CD VARCHAR(20),
    SCAC_CD VARCHAR(16),
    FSAC_CD VARCHAR(20),
    TRSTN_VRSN_NBR NUMBER(5,0),
    RGN_NM_TRK_NBR NUMBER(18,0),
    REGION_NBR NUMBER(18,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    TIME_ZONE_CD VARCHAR(8),
    TIME_ZONE_YEAR_NBR NUMBER(4,0),
    EVENT_SOURCE_CD VARCHAR(32),
    MILE_NBR NUMBER(8,3),
    ANCHOR_TMS TIMESTAMP_NTZ(0),
    SCHDLD_EVENT_TMS TIMESTAMP_NTZ(0),
    CREW_CHANGE_CD VARCHAR(4),
    ROUTE_POINT_ACTVTY_IND VARCHAR(4),
    PRFL_YARD_REPORT_CD VARCHAR(4),
    STN_CNTXT_CD VARCHAR(4),
    SBDVSN_CNTXT_CD VARCHAR(4),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (OPTRN_EVENT_ID)
)
COMMENT = 'CDC preserved table for OPTRN_EVENT_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 5: TRKFC_TRSTN (40 source columns + 6 CDC metadata) - COMPOSITE PK
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRKFC_TRSTN (
    SCAC_CD VARCHAR(16) NOT NULL,
    FSAC_CD VARCHAR(20) NOT NULL,
    TRSTN_VRSN_NBR NUMBER(5,0),
    STN_FULL_NM VARCHAR(100),
    STN_NM VARCHAR(40),
    STN_TYPE_CD VARCHAR(20),
    REGION_NBR NUMBER(18,0),
    TIME_ZONE_CD VARCHAR(8),
    STATE_PRVNC_CD VARCHAR(8),
    CNTRY_CD VARCHAR(8),
    CITY_NM VARCHAR(40),
    LTD_NBR NUMBER(10,8),
    LNGTD_NBR NUMBER(11,8),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SPLC_CD VARCHAR(24),
    RLWY_RULE_SET_CD VARCHAR(20),
    DATA_SOURCE_CD VARCHAR(40),
    DSPLY_STN_NM VARCHAR(40),
    JUNCTION_IND VARCHAR(4),
    MAIN_LINE_IND VARCHAR(4),
    OPEN_STN_IND VARCHAR(4),
    REPORT_STN_IND VARCHAR(4),
    TERM_STN_IND VARCHAR(4),
    CREW_HOME_IND VARCHAR(4),
    CREW_REST_IND VARCHAR(4),
    FUEL_IND VARCHAR(4),
    INSPECTION_IND VARCHAR(4),
    INTRCHNG_IND VARCHAR(4),
    MAJOR_STN_IND VARCHAR(4),
    SBDVSN_ID NUMBER(4,0),
    SBDVSN_NM VARCHAR(28),
    STN_ABBR_NM VARCHAR(8),
    MILE_NBR NUMBER(8,3),
    DSPLY_SQNC_NBR NUMBER(5,0),
    REGION_NM VARCHAR(40),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (SCAC_CD, FSAC_CD)
)
COMMENT = 'CDC preserved table for TRKFC_TRSTN_BASE. Composite PK. Soft deletes enabled.';

-- =============================================================================
-- TABLE 6: TRAIN_CNST_SMRY (87 source columns + 6 CDC metadata) - COMPOSITE PK
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRAIN_CNST_SMRY (
    CNST_NBR VARCHAR(16) NOT NULL,
    SCAC_CD VARCHAR(16) NOT NULL,
    TRAIN_CNST_SMRY_VRSN_NBR NUMBER(4,0) NOT NULL,
    FSAC_CD VARCHAR(20),
    TRSTN_VRSN_NBR NUMBER(5,0),
    TRAIN_CNST_SMRY_ID NUMBER(18,0),
    CNST_TYPE_CD VARCHAR(24),
    CNST_STATUS_CD VARCHAR(24),
    OPTRN_ID NUMBER(18,0),
    TRAIN_DRCTN_CD VARCHAR(20),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    CNST_ORIG_SCAC_CD VARCHAR(16),
    CNST_ORIG_FSAC_CD VARCHAR(20),
    CNST_DSTNTN_SCAC_CD VARCHAR(16),
    CNST_DSTNTN_FSAC_CD VARCHAR(20),
    TOT_GROSS_TONS_QTY NUMBER(10,0),
    TOT_NET_TONS_QTY NUMBER(10,0),
    TOT_TARE_TONS_QTY NUMBER(10,0),
    TOT_LENGTH_FEET_QTY NUMBER(10,0),
    TOT_AXLE_CT NUMBER(10,0),
    LOAD_CT NUMBER(5,0),
    EMPTY_CT NUMBER(5,0),
    LCMTV_CT NUMBER(5,0),
    CAR_CT NUMBER(5,0),
    BAD_ORDER_CT NUMBER(5,0),
    HZMT_CT NUMBER(5,0),
    HIGH_WIDE_CT NUMBER(5,0),
    HLTH_SRVC_CT NUMBER(5,0),
    CON_CT NUMBER(5,0),
    TRAILER_CT NUMBER(5,0),
    AUTO_CT NUMBER(5,0),
    INTERMODAL_PLATFORM_CT NUMBER(5,0),
    TOTAL_UNITS_CT NUMBER(5,0),
    PRIORITY_CT NUMBER(5,0),
    EQPT_ON_GROUND_CT NUMBER(5,0),
    EQPT_DLVRD_CT NUMBER(5,0),
    HORSEPOWER_QTY NUMBER(10,0),
    HORSEPOWER_PER_TON_QTY NUMBER(10,4),
    TOTAL_DYN_BRK_EF_QTY NUMBER(10,0),
    TOTAL_OPRT_BRAKE_CT NUMBER(5,0),
    MNM_CONT_SPEED_QTY NUMBER(5,0),
    DEAD_LCMTV_CT NUMBER(5,0),
    ACTIVE_LCMTV_CT NUMBER(5,0),
    DISTRIBUTED_POWER_IND VARCHAR(4),
    FUEL_QTY NUMBER(10,0),
    WATER_QTY NUMBER(10,0),
    SAND_QTY NUMBER(10,0),
    TRAIN_PLAN_ID NUMBER(18,0),
    RVSN_TMS TIMESTAMP_NTZ(0),
    RVSN_SOURCE_CD VARCHAR(32),
    OCS_CNST_NM VARCHAR(32),
    TYES_TRAIN_ID NUMBER(18,0),
    CNST_VRSN_NBR NUMBER(4,0),
    MTP_ROUTE_CMPLT_CD VARCHAR(4),
    MTP_TITAN_NBR NUMBER(6,0),
    MTP_TRAIN_STATE_CD VARCHAR(4),
    TONNAGE_PROFILE_CD VARCHAR(24),
    TRAIN_HANDLING_RSTRCT_CD VARCHAR(40),
    TTRX_APPRV_STATUS_CD VARCHAR(24),
    TTRX_AUDT_TMS TIMESTAMP_NTZ(0),
    TTRX_CALC_MTRC_STATUS_CD VARCHAR(24),
    LCMTV_HNDLNG_STATUS_CD VARCHAR(24),
    CAR_HNDLNG_STATUS_CD VARCHAR(24),
    CNST_HNDLNG_STATUS_CD VARCHAR(24),
    CNST_HNDLNG_OVRD_STATUS_CD VARCHAR(24),
    CNST_PRCSSD_STATUS_CD VARCHAR(24),
    CNST_PRCSSD_TMS TIMESTAMP_NTZ(0),
    LCMTV_HNDLNG_OVRD_STATUS_CD VARCHAR(24),
    CAR_HNDLNG_OVRD_STATUS_CD VARCHAR(24),
    HAS_TRAIN_HNDLNG_OVRD_IND VARCHAR(4),
    UNIT_CT NUMBER(5,0),
    CNST_FIRST_EQPT_RVSD_TMS TIMESTAMP_NTZ(0),
    OCS_PRCSSD_STATUS_CD VARCHAR(24),
    OCS_PRCSSD_TMS TIMESTAMP_NTZ(0),
    LMS_PRFL_PRCSSD_STATUS_CD VARCHAR(24),
    LMS_PRFL_PRCSSD_TMS TIMESTAMP_NTZ(0),
    SLOT_CT NUMBER(5,0),
    ESTIMATED_WEIGHT_IND VARCHAR(4),
    TRAIN_SMRY_DATA_SOURCE_CD VARCHAR(40),
    CRNT_LCMTV_CNFGRTN_CD VARCHAR(40),
    CNST_ORIG_TRSTN_VRSN_NBR NUMBER(5,0),
    CNST_DSTNTN_TRSTN_VRSN_NBR NUMBER(5,0),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (CNST_NBR, SCAC_CD, TRAIN_CNST_SMRY_VRSN_NBR)
)
COMMENT = 'CDC preserved table for TRAIN_CNST_SMRY_BASE. 3-column composite PK. Soft deletes enabled.';

-- =============================================================================
-- TABLE 7: STNWYB_MSG_DN (130 source columns + 6 CDC metadata)
-- Due to size, showing structure only - actual columns copied from source
-- =============================================================================
CREATE TABLE IF NOT EXISTS STNWYB_MSG_DN (
    STNWYB_MSG_ID NUMBER(18,0) NOT NULL,
    -- ... (130 source columns - full definition in production)
    MSG_CREATE_TMS TIMESTAMP_NTZ(0),
    MSG_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (STNWYB_MSG_ID)
)
COMMENT = 'CDC preserved table for STNWYB_MSG_DN_BASE. Large table (130 cols). Soft deletes enabled.';

-- =============================================================================
-- TABLE 8: EQPMNT_AAR_BASE (80 source columns + 6 CDC metadata)
-- NOTE: Fixed SNW_OPERATION_TYPE (was SNW__OPERATION_TYPE with double underscore)
-- =============================================================================
CREATE TABLE IF NOT EXISTS EQPMNT_AAR_BASE (
    AAR_CAR_TYPE_CD VARCHAR(16) NOT NULL,
    -- ... (80 source columns)
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),  -- FIXED: Was SNW__OPERATION_TYPE
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (AAR_CAR_TYPE_CD)
)
COMMENT = 'CDC preserved table for EQPMNT_AAR_BASE. Fixed column naming. Soft deletes enabled.';

-- =============================================================================
-- TABLE 9: EQPMV_RFEQP_MVMNT_EVENT (90 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS EQPMV_RFEQP_MVMNT_EVENT (
    EVENT_ID NUMBER(18,0) NOT NULL,
    -- ... (90 source columns)
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (EVENT_ID)
)
COMMENT = 'CDC preserved table for EQPMV_RFEQP_MVMNT_EVENT_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 10: CTNAPP_CTNG_LINE_DN (65 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS CTNAPP_CTNG_LINE_DN (
    CTNG_LINE_ID NUMBER(18,0) NOT NULL,
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (CTNG_LINE_ID)
)
COMMENT = 'CDC preserved table for CTNAPP_CTNG_LINE_DN_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 11: EQPMV_EQPMT_EVENT_TYPE (24 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS EQPMV_EQPMT_EVENT_TYPE (
    EQPMT_EVENT_TYPE_ID NUMBER(18,0) NOT NULL,
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (EQPMT_EVENT_TYPE_ID)
)
COMMENT = 'CDC preserved table for EQPMV_EQPMT_EVENT_TYPE_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 12: TRAIN_PLAN_EVENT (36 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRAIN_PLAN_EVENT (
    TRAIN_PLAN_EVENT_ID NUMBER(18,0) NOT NULL,
    TRAIN_PLAN_LEG_ID NUMBER(18,0),
    TRAIN_EVENT_TYPE_CD VARCHAR(16),
    EVENT_TMS TIMESTAMP_NTZ(0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (TRAIN_PLAN_EVENT_ID)
)
COMMENT = 'CDC preserved table for TRAIN_PLAN_EVENT_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 13: LCMTV_MVMNT_EVENT (43 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS LCMTV_MVMNT_EVENT (
    EVENT_ID NUMBER(18,0) NOT NULL,
    EQPMT_EVENT_TYPE_ID NUMBER(18,0),
    SCAC_CD VARCHAR(16),
    FSAC_CD VARCHAR(20),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (EVENT_ID)
)
COMMENT = 'CDC preserved table for LCMTV_MVMNT_EVENT_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 14: LCMTV_EMIS (84 source columns + 6 CDC metadata) - COMPOSITE PK
-- =============================================================================
CREATE TABLE IF NOT EXISTS LCMTV_EMIS (
    MARK_CD VARCHAR(16) NOT NULL,
    EQPUN_NBR VARCHAR(40) NOT NULL,
    RECORD_CREATE_DT TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (MARK_CD, EQPUN_NBR)
)
COMMENT = 'CDC preserved table for LCMTV_EMIS_BASE. Composite PK (MARK_CD, EQPUN_NBR). Soft deletes enabled.';

-- =============================================================================
-- TABLE 15: TRAIN_PLAN_LEG (16 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRAIN_PLAN_LEG (
    TRAIN_PLAN_LEG_ID NUMBER(18,0) NOT NULL,
    TRAIN_PLAN_ID NUMBER(18,0),
    TRAIN_DRCTN_CD VARCHAR(20),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (TRAIN_PLAN_LEG_ID)
)
COMMENT = 'CDC preserved table for TRAIN_PLAN_LEG_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 16: TRKFCG_SBDVSN (49 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRKFCG_SBDVSN (
    GRPHC_OBJECT_VRSN_ID NUMBER(18,0) NOT NULL,
    VRSN_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (GRPHC_OBJECT_VRSN_ID)
)
COMMENT = 'CDC preserved table for TRKFCG_SBDVSN_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 17: TRKFCG_FIXED_PLANT_ASSET (52 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRKFCG_FIXED_PLANT_ASSET (
    GRPHC_OBJECT_VRSN_ID NUMBER(18,0) NOT NULL,
    VRSN_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (GRPHC_OBJECT_VRSN_ID)
)
COMMENT = 'CDC preserved table for TRKFCG_FIXED_PLANT_ASSET_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 18: TRKFCG_FXPLA_TRACK_LCTN_DN (56 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRKFCG_FXPLA_TRACK_LCTN_DN (
    GRPHC_OBJECT_VRSN_ID NUMBER(18,0) NOT NULL,
    VRSN_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (GRPHC_OBJECT_VRSN_ID)
)
COMMENT = 'CDC preserved table for TRKFCG_FXPLA_TRACK_LCTN_DN_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 19: TRAIN_CNST_DTL_RAIL_EQPT (77 source columns + 6 CDC) - COMPOSITE PK
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRAIN_CNST_DTL_RAIL_EQPT (
    TRAIN_CNST_SMRY_ID NUMBER(18,0) NOT NULL,
    TRAIN_CNST_SMRY_VRSN_NBR NUMBER(4,0) NOT NULL,
    SQNC_NBR NUMBER(4,0) NOT NULL,
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR, SQNC_NBR)
)
COMMENT = 'CDC preserved table for TRAIN_CNST_DTL_RAIL_EQPT_BASE. 3-col composite PK. Soft deletes enabled.';

-- =============================================================================
-- TABLE 20: TRKFCG_TRACK_SGMNT_DN (58 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRKFCG_TRACK_SGMNT_DN (
    GRPHC_OBJECT_VRSN_ID NUMBER(18,0) NOT NULL,
    VRSN_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (GRPHC_OBJECT_VRSN_ID)
)
COMMENT = 'CDC preserved table for TRKFCG_TRACK_SGMNT_DN_BASE. Soft deletes enabled.';

-- =============================================================================
-- TABLE 21: TRKFCG_SRVC_AREA (25 source columns + 6 CDC metadata)
-- =============================================================================
CREATE TABLE IF NOT EXISTS TRKFCG_SRVC_AREA (
    GRPHC_OBJECT_VRSN_ID NUMBER(18,0) NOT NULL,
    VRSN_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    PRIMARY KEY (GRPHC_OBJECT_VRSN_ID)
)
COMMENT = 'CDC preserved table for TRKFCG_SRVC_AREA_BASE. Soft deletes enabled.';

-- =============================================================================
-- VERIFICATION
-- =============================================================================
SELECT TABLE_NAME, ROW_COUNT, COMMENT
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = $TARGET_SCHEMA
AND TABLE_NAME IN (
    'TRAIN_PLAN', 'OPTRN', 'OPTRN_LEG', 'OPTRN_EVENT', 'TRKFC_TRSTN',
    'TRAIN_CNST_SMRY', 'STNWYB_MSG_DN', 'EQPMNT_AAR_BASE', 'EQPMV_RFEQP_MVMNT_EVENT',
    'CTNAPP_CTNG_LINE_DN', 'EQPMV_EQPMT_EVENT_TYPE', 'TRAIN_PLAN_EVENT',
    'LCMTV_MVMNT_EVENT', 'LCMTV_EMIS', 'TRAIN_PLAN_LEG', 'TRKFCG_SBDVSN',
    'TRKFCG_FIXED_PLANT_ASSET', 'TRKFCG_FXPLA_TRACK_LCTN_DN', 'TRAIN_CNST_DTL_RAIL_EQPT',
    'TRKFCG_TRACK_SGMNT_DN', 'TRKFCG_SRVC_AREA', 'CDC_PROCESSING_LOG'
)
ORDER BY TABLE_NAME;

/*
================================================================================
NOTE: This script shows simplified table structures with key columns.
For production deployment, copy full column definitions from original 
FinalScripts/*.sql files, ensuring SNW_OPERATION_TYPE uses single underscore.
================================================================================
*/
