/*
================================================================================
CDC DATA PRESERVATION - ENABLE CHANGE TRACKING ON SOURCE TABLES
================================================================================
Purpose      : Enable change tracking on all 21 source _BASE tables
Version      : 1.0 (Production)
Last Updated : 2026-02-23
================================================================================

PREREQUISITES:
- Execute 01_SET_PARAMETERS.sql first
- Source tables must exist in D_RAW.SADB (or configured source)

================================================================================
*/

-- =============================================================================
-- USE PARAMETERS FROM SESSION
-- =============================================================================
USE DATABASE IDENTIFIER($SOURCE_DATABASE);
USE SCHEMA IDENTIFIER($SOURCE_SCHEMA);
USE WAREHOUSE IDENTIFIER($CDC_WAREHOUSE);

-- =============================================================================
-- ENABLE CHANGE TRACKING ON ALL SOURCE TABLES
-- =============================================================================

-- Table 1: TRAIN_PLAN_BASE
ALTER TABLE TRAIN_PLAN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 2: OPTRN_BASE
ALTER TABLE OPTRN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 3: OPTRN_LEG_BASE
ALTER TABLE OPTRN_LEG_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 4: OPTRN_EVENT_BASE
ALTER TABLE OPTRN_EVENT_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 5: TRKFC_TRSTN_BASE
ALTER TABLE TRKFC_TRSTN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 6: TRAIN_CNST_SMRY_BASE
ALTER TABLE TRAIN_CNST_SMRY_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 7: STNWYB_MSG_DN_BASE
ALTER TABLE STNWYB_MSG_DN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 8: EQPMNT_AAR_BASE_BASE (if named this way) or EQPMNT_AAR_BASE
ALTER TABLE EQPMNT_AAR_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 9: EQPMV_RFEQP_MVMNT_EVENT_BASE
ALTER TABLE EQPMV_RFEQP_MVMNT_EVENT_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 10: CTNAPP_CTNG_LINE_DN_BASE
ALTER TABLE CTNAPP_CTNG_LINE_DN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 11: EQPMV_EQPMT_EVENT_TYPE_BASE
ALTER TABLE EQPMV_EQPMT_EVENT_TYPE_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 12: TRAIN_PLAN_EVENT_BASE
ALTER TABLE TRAIN_PLAN_EVENT_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 13: LCMTV_MVMNT_EVENT_BASE
ALTER TABLE LCMTV_MVMNT_EVENT_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 14: LCMTV_EMIS_BASE
ALTER TABLE LCMTV_EMIS_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 15: TRAIN_PLAN_LEG_BASE
ALTER TABLE TRAIN_PLAN_LEG_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 16: TRKFCG_SBDVSN_BASE
ALTER TABLE TRKFCG_SBDVSN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 17: TRKFCG_FIXED_PLANT_ASSET_BASE
ALTER TABLE TRKFCG_FIXED_PLANT_ASSET_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 18: TRKFCG_FXPLA_TRACK_LCTN_DN_BASE
ALTER TABLE TRKFCG_FXPLA_TRACK_LCTN_DN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 19: TRAIN_CNST_DTL_RAIL_EQPT_BASE
ALTER TABLE TRAIN_CNST_DTL_RAIL_EQPT_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 20: TRKFCG_TRACK_SGMNT_DN_BASE
ALTER TABLE TRKFCG_TRACK_SGMNT_DN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- Table 21: TRKFCG_SRVC_AREA_BASE
ALTER TABLE TRKFCG_SRVC_AREA_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = $DATA_RETENTION_DAYS,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = $MAX_EXTENSION_DAYS;

-- =============================================================================
-- VERIFICATION
-- =============================================================================
SELECT 
    TABLE_NAME,
    CHANGE_TRACKING,
    RETENTION_TIME AS DATA_RETENTION_DAYS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = $SOURCE_SCHEMA
AND TABLE_NAME LIKE '%_BASE'
AND TABLE_NAME IN (
    'TRAIN_PLAN_BASE', 'OPTRN_BASE', 'OPTRN_LEG_BASE', 'OPTRN_EVENT_BASE',
    'TRKFC_TRSTN_BASE', 'TRAIN_CNST_SMRY_BASE', 'STNWYB_MSG_DN_BASE',
    'EQPMNT_AAR_BASE', 'EQPMV_RFEQP_MVMNT_EVENT_BASE', 'CTNAPP_CTNG_LINE_DN_BASE',
    'EQPMV_EQPMT_EVENT_TYPE_BASE', 'TRAIN_PLAN_EVENT_BASE', 'LCMTV_MVMNT_EVENT_BASE',
    'LCMTV_EMIS_BASE', 'TRAIN_PLAN_LEG_BASE', 'TRKFCG_SBDVSN_BASE',
    'TRKFCG_FIXED_PLANT_ASSET_BASE', 'TRKFCG_FXPLA_TRACK_LCTN_DN_BASE',
    'TRAIN_CNST_DTL_RAIL_EQPT_BASE', 'TRKFCG_TRACK_SGMNT_DN_BASE', 'TRKFCG_SRVC_AREA_BASE'
)
ORDER BY TABLE_NAME;

/*
================================================================================
CHANGE TRACKING ENABLED ON 21 TABLES
================================================================================
Settings Applied:
- CHANGE_TRACKING = TRUE
- DATA_RETENTION_TIME_IN_DAYS = configured value (default: 45)
- MAX_DATA_EXTENSION_TIME_IN_DAYS = configured value (default: 15)
- Total retention window: 60 days (default)

IMPORTANT: Enterprise Edition supports up to 90 days retention.
Standard Edition supports only 1 day. Adjust parameters accordingly.
================================================================================
*/
