/*
================================================================================
CDC DATA PRESERVATION - CREATE ALL TASKS
================================================================================
Purpose      : Create scheduled tasks for all 21 CDC procedures
Version      : 1.0 (Production)
Last Updated : 2026-02-23
================================================================================

PREREQUISITES:
- Execute 01_SET_PARAMETERS.sql first
- Execute 06_CREATE_ALL_PROCEDURES.sql first
- EXECUTE TASK privilege required for role

IMPORTANT: Tasks are created in SUSPENDED state for safety.
Execute 08_RESUME_ALL_TASKS.sql to activate.

================================================================================
*/

-- =============================================================================
-- USE PARAMETERS FROM SESSION
-- =============================================================================
USE DATABASE IDENTIFIER($SOURCE_DATABASE);
USE SCHEMA IDENTIFIER($SOURCE_SCHEMA);
USE WAREHOUSE IDENTIFIER($CDC_WAREHOUSE);

-- =============================================================================
-- CREATE ALL TASKS (SUSPENDED BY DEFAULT)
-- =============================================================================

-- Task 1: TRAIN_PLAN
CREATE OR REPLACE TASK TASK_PROCESS_TRAIN_PLAN
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRAIN_PLAN. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRAIN_PLAN();

-- Task 2: OPTRN
CREATE OR REPLACE TASK TASK_PROCESS_OPTRN
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for OPTRN. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_OPTRN();

-- Task 3: OPTRN_LEG
CREATE OR REPLACE TASK TASK_PROCESS_OPTRN_LEG
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for OPTRN_LEG. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_OPTRN_LEG();

-- Task 4: OPTRN_EVENT
CREATE OR REPLACE TASK TASK_PROCESS_OPTRN_EVENT
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for OPTRN_EVENT. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_OPTRN_EVENT();

-- Task 5: TRKFC_TRSTN
CREATE OR REPLACE TASK TASK_PROCESS_TRKFC_TRSTN
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRKFC_TRSTN. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRKFC_TRSTN();

-- Task 6: TRAIN_CNST_SMRY
CREATE OR REPLACE TASK TASK_PROCESS_TRAIN_CNST_SMRY
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRAIN_CNST_SMRY. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRAIN_CNST_SMRY();

-- Task 7: STNWYB_MSG_DN
CREATE OR REPLACE TASK TASK_PROCESS_STNWYB_MSG_DN
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for STNWYB_MSG_DN. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_STNWYB_MSG_DN();

-- Task 8: EQPMNT_AAR_BASE
CREATE OR REPLACE TASK TASK_PROCESS_EQPMNT_AAR_BASE
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for EQPMNT_AAR_BASE. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_EQPMNT_AAR_BASE();

-- Task 9: EQPMV_RFEQP_MVMNT_EVENT
CREATE OR REPLACE TASK TASK_PROCESS_EQPMV_RFEQP_MVMNT_EVENT
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for EQPMV_RFEQP_MVMNT_EVENT. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_EQPMV_RFEQP_MVMNT_EVENT();

-- Task 10: CTNAPP_CTNG_LINE_DN
CREATE OR REPLACE TASK TASK_PROCESS_CTNAPP_CTNG_LINE_DN
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for CTNAPP_CTNG_LINE_DN. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_CTNAPP_CTNG_LINE_DN();

-- Task 11: EQPMV_EQPMT_EVENT_TYPE
CREATE OR REPLACE TASK TASK_PROCESS_EQPMV_EQPMT_EVENT_TYPE
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for EQPMV_EQPMT_EVENT_TYPE. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_EQPMV_EQPMT_EVENT_TYPE();

-- Task 12: TRAIN_PLAN_EVENT
CREATE OR REPLACE TASK TASK_PROCESS_TRAIN_PLAN_EVENT
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRAIN_PLAN_EVENT. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRAIN_PLAN_EVENT();

-- Task 13: LCMTV_MVMNT_EVENT
CREATE OR REPLACE TASK TASK_PROCESS_LCMTV_MVMNT_EVENT
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for LCMTV_MVMNT_EVENT. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_LCMTV_MVMNT_EVENT();

-- Task 14: LCMTV_EMIS
CREATE OR REPLACE TASK TASK_PROCESS_LCMTV_EMIS
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for LCMTV_EMIS. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_LCMTV_EMIS();

-- Task 15: TRAIN_PLAN_LEG
CREATE OR REPLACE TASK TASK_PROCESS_TRAIN_PLAN_LEG
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRAIN_PLAN_LEG. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRAIN_PLAN_LEG();

-- Task 16: TRKFCG_SBDVSN
CREATE OR REPLACE TASK TASK_PROCESS_TRKFCG_SBDVSN
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRKFCG_SBDVSN. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRKFCG_SBDVSN();

-- Task 17: TRKFCG_FIXED_PLANT_ASSET
CREATE OR REPLACE TASK TASK_PROCESS_TRKFCG_FIXED_PLANT_ASSET
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRKFCG_FIXED_PLANT_ASSET. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRKFCG_FIXED_PLANT_ASSET();

-- Task 18: TRKFCG_FXPLA_TRACK_LCTN_DN
CREATE OR REPLACE TASK TASK_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRKFCG_FXPLA_TRACK_LCTN_DN. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN();

-- Task 19: TRAIN_CNST_DTL_RAIL_EQPT
CREATE OR REPLACE TASK TASK_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRAIN_CNST_DTL_RAIL_EQPT. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT();

-- Task 20: TRKFCG_TRACK_SGMNT_DN
CREATE OR REPLACE TASK TASK_PROCESS_TRKFCG_TRACK_SGMNT_DN
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRKFCG_TRACK_SGMNT_DN. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRKFCG_TRACK_SGMNT_DN();

-- Task 21: TRKFCG_SRVC_AREA
CREATE OR REPLACE TASK TASK_PROCESS_TRKFCG_SRVC_AREA
    WAREHOUSE = IDENTIFIER($CDC_WAREHOUSE)
    SCHEDULE = $TASK_SCHEDULE
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for TRKFCG_SRVC_AREA. Runs every 5 minutes.'
AS
    CALL SP_PROCESS_TRKFCG_SRVC_AREA();

-- =============================================================================
-- VERIFICATION
-- =============================================================================
SHOW TASKS LIKE 'TASK_PROCESS_%' IN SCHEMA IDENTIFIER($SOURCE_DATABASE || '.' || $SOURCE_SCHEMA);

/*
================================================================================
21 CDC TASKS CREATED (SUSPENDED STATE)
================================================================================
Task Configuration:
- SCHEDULE: Configurable via $TASK_SCHEDULE (default: 5 MINUTE)
- ALLOW_OVERLAPPING_EXECUTION: FALSE (prevents duplicate runs)
- All tasks created in SUSPENDED state for safety

IMPORTANT: Tasks will NOT run until resumed!
Execute 08_RESUME_ALL_TASKS.sql to activate all tasks.

Task List:
- TASK_PROCESS_TRAIN_PLAN
- TASK_PROCESS_OPTRN
- TASK_PROCESS_OPTRN_LEG
- TASK_PROCESS_OPTRN_EVENT
- TASK_PROCESS_TRKFC_TRSTN
- TASK_PROCESS_TRAIN_CNST_SMRY
- TASK_PROCESS_STNWYB_MSG_DN
- TASK_PROCESS_EQPMNT_AAR_BASE
- TASK_PROCESS_EQPMV_RFEQP_MVMNT_EVENT
- TASK_PROCESS_CTNAPP_CTNG_LINE_DN
- TASK_PROCESS_EQPMV_EQPMT_EVENT_TYPE
- TASK_PROCESS_TRAIN_PLAN_EVENT
- TASK_PROCESS_LCMTV_MVMNT_EVENT
- TASK_PROCESS_LCMTV_EMIS
- TASK_PROCESS_TRAIN_PLAN_LEG
- TASK_PROCESS_TRKFCG_SBDVSN
- TASK_PROCESS_TRKFCG_FIXED_PLANT_ASSET
- TASK_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN
- TASK_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT
- TASK_PROCESS_TRKFCG_TRACK_SGMNT_DN
- TASK_PROCESS_TRKFCG_SRVC_AREA
================================================================================
*/
