/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.STNWYB_MSG_DN_BASE
================================================================================
Source Table : D_RAW.SADB.STNWYB_MSG_DN_BASE
Target Table : D_BRONZE.SADB.STNWYB_MSG_DN
Stream       : D_RAW.SADB.STNWYB_MSG_DN_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_STNWYB_MSG_DN()
Task         : D_RAW.SADB.TASK_PROCESS_STNWYB_MSG_DN
Primary Key  : STNWYB_MSG_VRSN_ID (Single)
Total Columns: 131 source + 6 CDC metadata = 137
Filter       : SNW_OPERATION_OWNER NOT IN ('TSDPRG','EMEPRG') (exclude purged records)
================================================================================
VERSION      : v1.0
DATE         : 2026-03-13
CHANGES      : 
  - Added SYSTEM$STREAM_GET_STALE_AFTER() for proactive staleness detection
  - Added execution logging to D_BRONZE.MONITORING.CDC_EXECUTION_LOG
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE OR ALTER TABLE D_BRONZE.SADB.STNWYB_MSG_DN (
    STNWYB_MSG_VRSN_ID NUMBER(18,0) NOT NULL,
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    UPDATE_USER_ID VARCHAR(32),
    CRNT_VRSN_CD VARCHAR(4),
    SOURCE_CREATE_TMS TIMESTAMP_NTZ(0),
    SRVASG_EQPMT_ASGNMN_ID NUMBER(18,0),
    SRVASG_SHPSRV_ITEM_SHPMT_ID NUMBER(18,0),
    SRVASG_SHPSRV_ITEM_SQNC_NBR NUMBER(6,0),
    SRVASG_SQNC_NBR NUMBER(6,0),
    SHPSRV_EQPASG_CD VARCHAR(40),
    CYCLE_SERIAL_NBR NUMBER(10,0),
    WYBL_NBR NUMBER(17,0),
    WYBL_CREATE_LOCAL_TMS TIMESTAMP_NTZ(0),
    WYBL_CREATE_TIME_CD VARCHAR(8),
    SHPMT_ID NUMBER(18,0),
    CREATE_DATA_SOURCE_CD VARCHAR(40),
    CREATE_SOURCE_TMS TIMESTAMP_NTZ(0),
    CREATE_SOURCE_USER_ID VARCHAR(32),
    UPDATE_DATA_SOURCE_CD VARCHAR(40),
    UPDATE_SOURCE_TMS TIMESTAMP_NTZ(0),
    UPDATE_SOURCE_USER_ID VARCHAR(32),
    RLS_LOCAL_TMS TIMESTAMP_NTZ(0),
    RLS_TIME_CD VARCHAR(8),
    SHPMT_STATUS_ID NUMBER(18,0),
    WYBL_CANCEL_CD VARCHAR(4),
    MARK_CD VARCHAR(16),
    EQPUN_NBR VARCHAR(40),
    SHPMT_TYPE_CD VARCHAR(4),
    LOAD_EMPTY_CD VARCHAR(4),
    WYBL_CNTNT_WEIGHT_QTY NUMBER(10,0),
    WYBL_CNTNT_WEIGHT_UNIT_CD VARCHAR(4),
    WEIGHT_QLFR_CD VARCHAR(8),
    IN_BOND_CD VARCHAR(4),
    CSA_CD VARCHAR(4),
    CHECK_DIGIT_NBR VARCHAR(8),
    WYBL_TARE_WEIGHT_QTY NUMBER(6,0),
    WYBL_TARE_WEIGHT_UNIT_CD VARCHAR(4),
    LEAD_EQPMT_ASGNMN_ID NUMBER(18,0),
    LEAD_SHPSRV_ITEM_SHPMT_ID NUMBER(18,0),
    LEAD_SHPSRV_ITEM_SQNC_NBR NUMBER(6,0),
    LEAD_SQNC_NBR NUMBER(6,0),
    LEAD_CYCLE_SERIAL_NBR NUMBER(10,0),
    WYBL_MERGE_CD VARCHAR(4),
    PRVS_STCC_CD VARCHAR(28),
    EQPMT_POOL_ID NUMBER(18,0),
    CPR_EQPMT_POOL_ID VARCHAR(28),
    ORIGIN_ROUTE_POINT_ID NUMBER(18,0),
    ORIGIN_SCAC_CD VARCHAR(16),
    ORIGIN_FSAC_CD VARCHAR(20),
    ORIGIN_TRSTN_NM VARCHAR(120),
    ORIGIN_STPRV_CD VARCHAR(8),
    DSTNTN_ROUTE_POINT_ID NUMBER(18,0),
    DSTNTN_SCAC_CD VARCHAR(16),
    DSTNTN_FSAC_CD VARCHAR(20),
    DSTNTN_TRSTN_NM VARCHAR(120),
    DSTNTN_STPRV_CD VARCHAR(8),
    CSTMS_CLRNC_ROUTE_POINT_ID NUMBER(18,0),
    CSTMS_CLRNC_SCAC_CD VARCHAR(16),
    CSTMS_CLRNC_FSAC_CD VARCHAR(20),
    SHPR_SHPMT_PARTY_ID NUMBER(18,0),
    SHPR_CPRS_CSTMR_ID VARCHAR(32),
    CNSGN_SHPMT_PARTY_ID NUMBER(18,0),
    CNSGN_CPRS_CSTMR_ID VARCHAR(32),
    CARE_OF_SHPMT_PARTY_ID NUMBER(18,0),
    CARE_OF_CPRS_CSTMR_ID VARCHAR(32),
    THIRD_PARTY_SHPMT_PARTY_ID NUMBER(18,0),
    THIRD_PARTY_CPRS_CSTMR_ID VARCHAR(32),
    SHPSRV_ITEM_SHPMT_ID NUMBER(18,0),
    SHPSRV_ITEM_SQNC_NBR NUMBER(6,0),
    INTRMD_SRVC_CD VARCHAR(8),
    INTRMD_PLAN_CD VARCHAR(12),
    METHOD_OF_PYMNT_CD VARCHAR(8),
    BOL_RFRNC_ID NUMBER(18,0),
    BOL_RFRNC_TXT VARCHAR(200),
    BOL_RFRNC_LOCAL_TMS TIMESTAMP_NTZ(0),
    BOL_RFRNC_LOCAL_TIME_CD VARCHAR(8),
    COAL_TRAIN_RFRNC_ID NUMBER(18,0),
    COAL_TRAIN_RFRNC_TXT VARCHAR(200),
    STGNG_ATHRZT_RFRNC_ID NUMBER(18,0),
    STGNG_ATHRZT_RFRNC_TXT VARCHAR(200),
    DRCTV_RFRNC_ID NUMBER(18,0),
    DRCTV_RFRNC_TXT VARCHAR(200),
    DRCTV_RFRNC_LOCAL_TMS TIMESTAMP_NTZ(0),
    DRCTV_RFRNC_LOCAL_TIME_CD VARCHAR(8),
    DEP_ORDER_RFRNC_ID NUMBER(18,0),
    DEP_ORDER_RFRNC_TXT VARCHAR(200),
    DEP_ORDER_RFRNC_LOCAL_TMS TIMESTAMP_NTZ(0),
    DEP_ORDER_RFRNC_LOCAL_TIME_CD VARCHAR(8),
    OPRTNL_BOL_TMSTMP_RFRNC_ID NUMBER(18,0),
    OPRTNL_BOL_TMSTMP_RFRNC_TXT VARCHAR(200),
    CR_ASGND_RFRNC_ID NUMBER(18,0),
    CR_ASGND_RFRNC_TXT VARCHAR(200),
    TRNSWR_LOAD_NUMBER_RFRNC_ID NUMBER(18,0),
    TRNSWR_LOAD_NUMBER_RFRNC_TXT VARCHAR(200),
    MVMNT_SRVC_SHPMT_ID NUMBER(18,0),
    MVMNT_SRVC_SQNC_NBR NUMBER(6,0),
    MVMNT_ATHRTY_CD VARCHAR(8),
    RTNG_SQNC_CD VARCHAR(8),
    SWITCH_CD VARCHAR(8),
    CSTMS_CLRNC_CD VARCHAR(4),
    DLVR_TO_SCAC_CD VARCHAR(16),
    ORIGIN_SWITCH_SCAC_CD VARCHAR(16),
    SHPMT_ROUTE_ID NUMBER(18,0),
    RVN_CD VARCHAR(4),
    ADTNL_LADING_ITEM_CD VARCHAR(4),
    EQPMT_LOAD_LADING_ITEM_ID NUMBER(18,0),
    DNG_WEIGHT_QTY NUMBER(6,0),
    DNG_WEIGHT_UNIT_CD VARCHAR(4),
    DNG_WEIGHT_QLFR_CD VARCHAR(8),
    GRAIN_TYPE_CD VARCHAR(8),
    GRAIN_GRADE_CD VARCHAR(16),
    PRTCTV_SRVC_SHPMT_ID NUMBER(18,0),
    PRTCTV_SRVC_SQNC_NBR NUMBER(6,0),
    PRTCTV_SRVC_CD VARCHAR(16),
    PRTCTV_SRVC_RULE_CD VARCHAR(36),
    PRTCTV_SRVC_TMPRTR_QTY NUMBER(8,4),
    PRTCTV_SRVC_TMPRTR_UOM_CD VARCHAR(8),
    SHPMT_ITEM_SHPMT_ID NUMBER(18,0),
    SHPMT_ITEM_SQNC_NBR NUMBER(6,0),
    STCC_CD VARCHAR(28),
    ADTNL_HNDLNG_DSCRPT_CD VARCHAR(4),
    PBLSHD_WYBL_VRSN_NBR NUMBER(4,0),
    FRA_APRVL_AGRMNT_NBR_RFRNC_ID NUMBER(18,0),
    FRA_APRVL_AGRMNT_NBR_RFRNC_TXT VARCHAR(200),
    DESPACHO_HOLD_IND VARCHAR(4),
    CBP_HOLD_IND VARCHAR(4),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ,
    IS_DELETED BOOLEAN,
    RECORD_CREATED_AT TIMESTAMP_NTZ,
    RECORD_UPDATED_AT TIMESTAMP_NTZ,
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    SNW_OPERATION_OWNER VARCHAR(256),

    PRIMARY KEY (STNWYB_MSG_VRSN_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.SADB.STNWYB_MSG_DN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.SADB.STNWYB_MSG_DN_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.STNWYB_MSG_DN_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for STNWYB_MSG_DN_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing (ENHANCED v1)
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.SADB.SP_PROCESS_STNWYB_MSG_DN()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_rows_inserted NUMBER DEFAULT 0;
    v_rows_updated NUMBER DEFAULT 0;
    v_rows_deleted NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
    v_stale_after TIMESTAMP_NTZ;
    v_start_time TIMESTAMP_NTZ;
    v_end_time TIMESTAMP_NTZ;
    v_execution_status VARCHAR DEFAULT 'SUCCESS';
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    v_start_time := CURRENT_TIMESTAMP();
    
    -- =========================================================================
    -- CHECK 1: PROACTIVE staleness detection using SYSTEM$STREAM_GET_STALE_AFTER()
    -- This runs BEFORE reading the stream to prevent processing stale data
    -- =========================================================================
    BEGIN
        SELECT SYSTEM$STREAM_GET_STALE_AFTER('D_RAW.SADB.STNWYB_MSG_DN_BASE_HIST_STREAM') INTO v_stale_after;
        
        IF (v_stale_after IS NOT NULL AND v_stale_after <= CURRENT_TIMESTAMP()) THEN
            v_stream_stale := TRUE;
            v_error_msg := 'Stream stale_after timestamp (' || v_stale_after::VARCHAR || ') is in the past';
        ELSE
            v_stream_stale := FALSE;
        END IF;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := 'Stream staleness check failed: ' || SQLERRM;
    END;
    
    -- =========================================================================
    -- FALLBACK CHECK: Try to read stream to confirm it's accessible
    -- =========================================================================
    IF (v_stream_stale = FALSE) THEN
        BEGIN
            SELECT COUNT(*) INTO v_staging_count 
            FROM D_RAW.SADB.STNWYB_MSG_DN_BASE_HIST_STREAM
            WHERE 1=0;
            
            v_stream_stale := FALSE;
            
        EXCEPTION
            WHEN OTHER THEN
                v_stream_stale := TRUE;
                v_error_msg := NVL(v_error_msg, '') || ' | Stream read failed: ' || SQLERRM;
        END;
    END IF;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        v_execution_status := 'RECOVERY';
        
        CREATE OR REPLACE STREAM D_RAW.SADB.STNWYB_MSG_DN_BASE_HIST_STREAM
        ON TABLE D_RAW.SADB.STNWYB_MSG_DN_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.SADB.STNWYB_MSG_DN AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.SADB.STNWYB_MSG_DN_BASE_HIST_STREAM src
            WHERE NVL(src.SNW_OPERATION_OWNER, '') NOT IN ('TSDPRG', 'EMEPRG')
        ) AS src
        ON tgt.STNWYB_MSG_VRSN_ID = src.STNWYB_MSG_VRSN_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.CRNT_VRSN_CD = src.CRNT_VRSN_CD,
            tgt.SOURCE_CREATE_TMS = src.SOURCE_CREATE_TMS,
            tgt.SRVASG_EQPMT_ASGNMN_ID = src.SRVASG_EQPMT_ASGNMN_ID,
            tgt.SRVASG_SHPSRV_ITEM_SHPMT_ID = src.SRVASG_SHPSRV_ITEM_SHPMT_ID,
            tgt.SRVASG_SHPSRV_ITEM_SQNC_NBR = src.SRVASG_SHPSRV_ITEM_SQNC_NBR,
            tgt.SRVASG_SQNC_NBR = src.SRVASG_SQNC_NBR,
            tgt.SHPSRV_EQPASG_CD = src.SHPSRV_EQPASG_CD,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.WYBL_NBR = src.WYBL_NBR,
            tgt.WYBL_CREATE_LOCAL_TMS = src.WYBL_CREATE_LOCAL_TMS,
            tgt.WYBL_CREATE_TIME_CD = src.WYBL_CREATE_TIME_CD,
            tgt.SHPMT_ID = src.SHPMT_ID,
            tgt.CREATE_DATA_SOURCE_CD = src.CREATE_DATA_SOURCE_CD,
            tgt.CREATE_SOURCE_TMS = src.CREATE_SOURCE_TMS,
            tgt.CREATE_SOURCE_USER_ID = src.CREATE_SOURCE_USER_ID,
            tgt.UPDATE_DATA_SOURCE_CD = src.UPDATE_DATA_SOURCE_CD,
            tgt.UPDATE_SOURCE_TMS = src.UPDATE_SOURCE_TMS,
            tgt.UPDATE_SOURCE_USER_ID = src.UPDATE_SOURCE_USER_ID,
            tgt.RLS_LOCAL_TMS = src.RLS_LOCAL_TMS,
            tgt.RLS_TIME_CD = src.RLS_TIME_CD,
            tgt.SHPMT_STATUS_ID = src.SHPMT_STATUS_ID,
            tgt.WYBL_CANCEL_CD = src.WYBL_CANCEL_CD,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.SHPMT_TYPE_CD = src.SHPMT_TYPE_CD,
            tgt.LOAD_EMPTY_CD = src.LOAD_EMPTY_CD,
            tgt.WYBL_CNTNT_WEIGHT_QTY = src.WYBL_CNTNT_WEIGHT_QTY,
            tgt.WYBL_CNTNT_WEIGHT_UNIT_CD = src.WYBL_CNTNT_WEIGHT_UNIT_CD,
            tgt.WEIGHT_QLFR_CD = src.WEIGHT_QLFR_CD,
            tgt.IN_BOND_CD = src.IN_BOND_CD,
            tgt.CSA_CD = src.CSA_CD,
            tgt.CHECK_DIGIT_NBR = src.CHECK_DIGIT_NBR,
            tgt.WYBL_TARE_WEIGHT_QTY = src.WYBL_TARE_WEIGHT_QTY,
            tgt.WYBL_TARE_WEIGHT_UNIT_CD = src.WYBL_TARE_WEIGHT_UNIT_CD,
            tgt.LEAD_EQPMT_ASGNMN_ID = src.LEAD_EQPMT_ASGNMN_ID,
            tgt.LEAD_SHPSRV_ITEM_SHPMT_ID = src.LEAD_SHPSRV_ITEM_SHPMT_ID,
            tgt.LEAD_SHPSRV_ITEM_SQNC_NBR = src.LEAD_SHPSRV_ITEM_SQNC_NBR,
            tgt.LEAD_SQNC_NBR = src.LEAD_SQNC_NBR,
            tgt.LEAD_CYCLE_SERIAL_NBR = src.LEAD_CYCLE_SERIAL_NBR,
            tgt.WYBL_MERGE_CD = src.WYBL_MERGE_CD,
            tgt.PRVS_STCC_CD = src.PRVS_STCC_CD,
            tgt.EQPMT_POOL_ID = src.EQPMT_POOL_ID,
            tgt.CPR_EQPMT_POOL_ID = src.CPR_EQPMT_POOL_ID,
            tgt.ORIGIN_ROUTE_POINT_ID = src.ORIGIN_ROUTE_POINT_ID,
            tgt.ORIGIN_SCAC_CD = src.ORIGIN_SCAC_CD,
            tgt.ORIGIN_FSAC_CD = src.ORIGIN_FSAC_CD,
            tgt.ORIGIN_TRSTN_NM = src.ORIGIN_TRSTN_NM,
            tgt.ORIGIN_STPRV_CD = src.ORIGIN_STPRV_CD,
            tgt.DSTNTN_ROUTE_POINT_ID = src.DSTNTN_ROUTE_POINT_ID,
            tgt.DSTNTN_SCAC_CD = src.DSTNTN_SCAC_CD,
            tgt.DSTNTN_FSAC_CD = src.DSTNTN_FSAC_CD,
            tgt.DSTNTN_TRSTN_NM = src.DSTNTN_TRSTN_NM,
            tgt.DSTNTN_STPRV_CD = src.DSTNTN_STPRV_CD,
            tgt.CSTMS_CLRNC_ROUTE_POINT_ID = src.CSTMS_CLRNC_ROUTE_POINT_ID,
            tgt.CSTMS_CLRNC_SCAC_CD = src.CSTMS_CLRNC_SCAC_CD,
            tgt.CSTMS_CLRNC_FSAC_CD = src.CSTMS_CLRNC_FSAC_CD,
            tgt.SHPR_SHPMT_PARTY_ID = src.SHPR_SHPMT_PARTY_ID,
            tgt.SHPR_CPRS_CSTMR_ID = src.SHPR_CPRS_CSTMR_ID,
            tgt.CNSGN_SHPMT_PARTY_ID = src.CNSGN_SHPMT_PARTY_ID,
            tgt.CNSGN_CPRS_CSTMR_ID = src.CNSGN_CPRS_CSTMR_ID,
            tgt.CARE_OF_SHPMT_PARTY_ID = src.CARE_OF_SHPMT_PARTY_ID,
            tgt.CARE_OF_CPRS_CSTMR_ID = src.CARE_OF_CPRS_CSTMR_ID,
            tgt.THIRD_PARTY_SHPMT_PARTY_ID = src.THIRD_PARTY_SHPMT_PARTY_ID,
            tgt.THIRD_PARTY_CPRS_CSTMR_ID = src.THIRD_PARTY_CPRS_CSTMR_ID,
            tgt.SHPSRV_ITEM_SHPMT_ID = src.SHPSRV_ITEM_SHPMT_ID,
            tgt.SHPSRV_ITEM_SQNC_NBR = src.SHPSRV_ITEM_SQNC_NBR,
            tgt.INTRMD_SRVC_CD = src.INTRMD_SRVC_CD,
            tgt.INTRMD_PLAN_CD = src.INTRMD_PLAN_CD,
            tgt.METHOD_OF_PYMNT_CD = src.METHOD_OF_PYMNT_CD,
            tgt.BOL_RFRNC_ID = src.BOL_RFRNC_ID,
            tgt.BOL_RFRNC_TXT = src.BOL_RFRNC_TXT,
            tgt.BOL_RFRNC_LOCAL_TMS = src.BOL_RFRNC_LOCAL_TMS,
            tgt.BOL_RFRNC_LOCAL_TIME_CD = src.BOL_RFRNC_LOCAL_TIME_CD,
            tgt.COAL_TRAIN_RFRNC_ID = src.COAL_TRAIN_RFRNC_ID,
            tgt.COAL_TRAIN_RFRNC_TXT = src.COAL_TRAIN_RFRNC_TXT,
            tgt.STGNG_ATHRZT_RFRNC_ID = src.STGNG_ATHRZT_RFRNC_ID,
            tgt.STGNG_ATHRZT_RFRNC_TXT = src.STGNG_ATHRZT_RFRNC_TXT,
            tgt.DRCTV_RFRNC_ID = src.DRCTV_RFRNC_ID,
            tgt.DRCTV_RFRNC_TXT = src.DRCTV_RFRNC_TXT,
            tgt.DRCTV_RFRNC_LOCAL_TMS = src.DRCTV_RFRNC_LOCAL_TMS,
            tgt.DRCTV_RFRNC_LOCAL_TIME_CD = src.DRCTV_RFRNC_LOCAL_TIME_CD,
            tgt.DEP_ORDER_RFRNC_ID = src.DEP_ORDER_RFRNC_ID,
            tgt.DEP_ORDER_RFRNC_TXT = src.DEP_ORDER_RFRNC_TXT,
            tgt.DEP_ORDER_RFRNC_LOCAL_TMS = src.DEP_ORDER_RFRNC_LOCAL_TMS,
            tgt.DEP_ORDER_RFRNC_LOCAL_TIME_CD = src.DEP_ORDER_RFRNC_LOCAL_TIME_CD,
            tgt.OPRTNL_BOL_TMSTMP_RFRNC_ID = src.OPRTNL_BOL_TMSTMP_RFRNC_ID,
            tgt.OPRTNL_BOL_TMSTMP_RFRNC_TXT = src.OPRTNL_BOL_TMSTMP_RFRNC_TXT,
            tgt.CR_ASGND_RFRNC_ID = src.CR_ASGND_RFRNC_ID,
            tgt.CR_ASGND_RFRNC_TXT = src.CR_ASGND_RFRNC_TXT,
            tgt.TRNSWR_LOAD_NUMBER_RFRNC_ID = src.TRNSWR_LOAD_NUMBER_RFRNC_ID,
            tgt.TRNSWR_LOAD_NUMBER_RFRNC_TXT = src.TRNSWR_LOAD_NUMBER_RFRNC_TXT,
            tgt.MVMNT_SRVC_SHPMT_ID = src.MVMNT_SRVC_SHPMT_ID,
            tgt.MVMNT_SRVC_SQNC_NBR = src.MVMNT_SRVC_SQNC_NBR,
            tgt.MVMNT_ATHRTY_CD = src.MVMNT_ATHRTY_CD,
            tgt.RTNG_SQNC_CD = src.RTNG_SQNC_CD,
            tgt.SWITCH_CD = src.SWITCH_CD,
            tgt.CSTMS_CLRNC_CD = src.CSTMS_CLRNC_CD,
            tgt.DLVR_TO_SCAC_CD = src.DLVR_TO_SCAC_CD,
            tgt.ORIGIN_SWITCH_SCAC_CD = src.ORIGIN_SWITCH_SCAC_CD,
            tgt.SHPMT_ROUTE_ID = src.SHPMT_ROUTE_ID,
            tgt.RVN_CD = src.RVN_CD,
            tgt.ADTNL_LADING_ITEM_CD = src.ADTNL_LADING_ITEM_CD,
            tgt.EQPMT_LOAD_LADING_ITEM_ID = src.EQPMT_LOAD_LADING_ITEM_ID,
            tgt.DNG_WEIGHT_QTY = src.DNG_WEIGHT_QTY,
            tgt.DNG_WEIGHT_UNIT_CD = src.DNG_WEIGHT_UNIT_CD,
            tgt.DNG_WEIGHT_QLFR_CD = src.DNG_WEIGHT_QLFR_CD,
            tgt.GRAIN_TYPE_CD = src.GRAIN_TYPE_CD,
            tgt.GRAIN_GRADE_CD = src.GRAIN_GRADE_CD,
            tgt.PRTCTV_SRVC_SHPMT_ID = src.PRTCTV_SRVC_SHPMT_ID,
            tgt.PRTCTV_SRVC_SQNC_NBR = src.PRTCTV_SRVC_SQNC_NBR,
            tgt.PRTCTV_SRVC_CD = src.PRTCTV_SRVC_CD,
            tgt.PRTCTV_SRVC_RULE_CD = src.PRTCTV_SRVC_RULE_CD,
            tgt.PRTCTV_SRVC_TMPRTR_QTY = src.PRTCTV_SRVC_TMPRTR_QTY,
            tgt.PRTCTV_SRVC_TMPRTR_UOM_CD = src.PRTCTV_SRVC_TMPRTR_UOM_CD,
            tgt.SHPMT_ITEM_SHPMT_ID = src.SHPMT_ITEM_SHPMT_ID,
            tgt.SHPMT_ITEM_SQNC_NBR = src.SHPMT_ITEM_SQNC_NBR,
            tgt.STCC_CD = src.STCC_CD,
            tgt.ADTNL_HNDLNG_DSCRPT_CD = src.ADTNL_HNDLNG_DSCRPT_CD,
            tgt.PBLSHD_WYBL_VRSN_NBR = src.PBLSHD_WYBL_VRSN_NBR,
            tgt.FRA_APRVL_AGRMNT_NBR_RFRNC_ID = src.FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
            tgt.FRA_APRVL_AGRMNT_NBR_RFRNC_TXT = src.FRA_APRVL_AGRMNT_NBR_RFRNC_TXT,
            tgt.DESPACHO_HOLD_IND = src.DESPACHO_HOLD_IND,
            tgt.CBP_HOLD_IND = src.CBP_HOLD_IND,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            STNWYB_MSG_VRSN_ID, RECORD_CREATE_TMS, CREATE_USER_ID, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            CRNT_VRSN_CD, SOURCE_CREATE_TMS, SRVASG_EQPMT_ASGNMN_ID, SRVASG_SHPSRV_ITEM_SHPMT_ID, SRVASG_SHPSRV_ITEM_SQNC_NBR,
            SRVASG_SQNC_NBR, SHPSRV_EQPASG_CD, CYCLE_SERIAL_NBR, WYBL_NBR, WYBL_CREATE_LOCAL_TMS,
            WYBL_CREATE_TIME_CD, SHPMT_ID, CREATE_DATA_SOURCE_CD, CREATE_SOURCE_TMS, CREATE_SOURCE_USER_ID,
            UPDATE_DATA_SOURCE_CD, UPDATE_SOURCE_TMS, UPDATE_SOURCE_USER_ID, RLS_LOCAL_TMS, RLS_TIME_CD,
            SHPMT_STATUS_ID, WYBL_CANCEL_CD, MARK_CD, EQPUN_NBR, SHPMT_TYPE_CD,
            LOAD_EMPTY_CD, WYBL_CNTNT_WEIGHT_QTY, WYBL_CNTNT_WEIGHT_UNIT_CD, WEIGHT_QLFR_CD, IN_BOND_CD,
            CSA_CD, CHECK_DIGIT_NBR, WYBL_TARE_WEIGHT_QTY, WYBL_TARE_WEIGHT_UNIT_CD, LEAD_EQPMT_ASGNMN_ID,
            LEAD_SHPSRV_ITEM_SHPMT_ID, LEAD_SHPSRV_ITEM_SQNC_NBR, LEAD_SQNC_NBR, LEAD_CYCLE_SERIAL_NBR, WYBL_MERGE_CD,
            PRVS_STCC_CD, EQPMT_POOL_ID, CPR_EQPMT_POOL_ID, ORIGIN_ROUTE_POINT_ID, ORIGIN_SCAC_CD,
            ORIGIN_FSAC_CD, ORIGIN_TRSTN_NM, ORIGIN_STPRV_CD, DSTNTN_ROUTE_POINT_ID, DSTNTN_SCAC_CD,
            DSTNTN_FSAC_CD, DSTNTN_TRSTN_NM, DSTNTN_STPRV_CD, CSTMS_CLRNC_ROUTE_POINT_ID, CSTMS_CLRNC_SCAC_CD,
            CSTMS_CLRNC_FSAC_CD, SHPR_SHPMT_PARTY_ID, SHPR_CPRS_CSTMR_ID, CNSGN_SHPMT_PARTY_ID, CNSGN_CPRS_CSTMR_ID,
            CARE_OF_SHPMT_PARTY_ID, CARE_OF_CPRS_CSTMR_ID, THIRD_PARTY_SHPMT_PARTY_ID, THIRD_PARTY_CPRS_CSTMR_ID, SHPSRV_ITEM_SHPMT_ID,
            SHPSRV_ITEM_SQNC_NBR, INTRMD_SRVC_CD, INTRMD_PLAN_CD, METHOD_OF_PYMNT_CD, BOL_RFRNC_ID,
            BOL_RFRNC_TXT, BOL_RFRNC_LOCAL_TMS, BOL_RFRNC_LOCAL_TIME_CD, COAL_TRAIN_RFRNC_ID, COAL_TRAIN_RFRNC_TXT,
            STGNG_ATHRZT_RFRNC_ID, STGNG_ATHRZT_RFRNC_TXT, DRCTV_RFRNC_ID, DRCTV_RFRNC_TXT, DRCTV_RFRNC_LOCAL_TMS,
            DRCTV_RFRNC_LOCAL_TIME_CD, DEP_ORDER_RFRNC_ID, DEP_ORDER_RFRNC_TXT, DEP_ORDER_RFRNC_LOCAL_TMS, DEP_ORDER_RFRNC_LOCAL_TIME_CD,
            OPRTNL_BOL_TMSTMP_RFRNC_ID, OPRTNL_BOL_TMSTMP_RFRNC_TXT, CR_ASGND_RFRNC_ID, CR_ASGND_RFRNC_TXT, TRNSWR_LOAD_NUMBER_RFRNC_ID,
            TRNSWR_LOAD_NUMBER_RFRNC_TXT, MVMNT_SRVC_SHPMT_ID, MVMNT_SRVC_SQNC_NBR, MVMNT_ATHRTY_CD, RTNG_SQNC_CD,
            SWITCH_CD, CSTMS_CLRNC_CD, DLVR_TO_SCAC_CD, ORIGIN_SWITCH_SCAC_CD, SHPMT_ROUTE_ID,
            RVN_CD, ADTNL_LADING_ITEM_CD, EQPMT_LOAD_LADING_ITEM_ID, DNG_WEIGHT_QTY, DNG_WEIGHT_UNIT_CD,
            DNG_WEIGHT_QLFR_CD, GRAIN_TYPE_CD, GRAIN_GRADE_CD, PRTCTV_SRVC_SHPMT_ID, PRTCTV_SRVC_SQNC_NBR,
            PRTCTV_SRVC_CD, PRTCTV_SRVC_RULE_CD, PRTCTV_SRVC_TMPRTR_QTY, PRTCTV_SRVC_TMPRTR_UOM_CD, SHPMT_ITEM_SHPMT_ID,
            SHPMT_ITEM_SQNC_NBR, STCC_CD, ADTNL_HNDLNG_DSCRPT_CD, PBLSHD_WYBL_VRSN_NBR, FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
            FRA_APRVL_AGRMNT_NBR_RFRNC_TXT, DESPACHO_HOLD_IND, CBP_HOLD_IND, SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.STNWYB_MSG_VRSN_ID, src.RECORD_CREATE_TMS, src.CREATE_USER_ID, src.RECORD_UPDATE_TMS, src.UPDATE_USER_ID,
            src.CRNT_VRSN_CD, src.SOURCE_CREATE_TMS, src.SRVASG_EQPMT_ASGNMN_ID, src.SRVASG_SHPSRV_ITEM_SHPMT_ID, src.SRVASG_SHPSRV_ITEM_SQNC_NBR,
            src.SRVASG_SQNC_NBR, src.SHPSRV_EQPASG_CD, src.CYCLE_SERIAL_NBR, src.WYBL_NBR, src.WYBL_CREATE_LOCAL_TMS,
            src.WYBL_CREATE_TIME_CD, src.SHPMT_ID, src.CREATE_DATA_SOURCE_CD, src.CREATE_SOURCE_TMS, src.CREATE_SOURCE_USER_ID,
            src.UPDATE_DATA_SOURCE_CD, src.UPDATE_SOURCE_TMS, src.UPDATE_SOURCE_USER_ID, src.RLS_LOCAL_TMS, src.RLS_TIME_CD,
            src.SHPMT_STATUS_ID, src.WYBL_CANCEL_CD, src.MARK_CD, src.EQPUN_NBR, src.SHPMT_TYPE_CD,
            src.LOAD_EMPTY_CD, src.WYBL_CNTNT_WEIGHT_QTY, src.WYBL_CNTNT_WEIGHT_UNIT_CD, src.WEIGHT_QLFR_CD, src.IN_BOND_CD,
            src.CSA_CD, src.CHECK_DIGIT_NBR, src.WYBL_TARE_WEIGHT_QTY, src.WYBL_TARE_WEIGHT_UNIT_CD, src.LEAD_EQPMT_ASGNMN_ID,
            src.LEAD_SHPSRV_ITEM_SHPMT_ID, src.LEAD_SHPSRV_ITEM_SQNC_NBR, src.LEAD_SQNC_NBR, src.LEAD_CYCLE_SERIAL_NBR, src.WYBL_MERGE_CD,
            src.PRVS_STCC_CD, src.EQPMT_POOL_ID, src.CPR_EQPMT_POOL_ID, src.ORIGIN_ROUTE_POINT_ID, src.ORIGIN_SCAC_CD,
            src.ORIGIN_FSAC_CD, src.ORIGIN_TRSTN_NM, src.ORIGIN_STPRV_CD, src.DSTNTN_ROUTE_POINT_ID, src.DSTNTN_SCAC_CD,
            src.DSTNTN_FSAC_CD, src.DSTNTN_TRSTN_NM, src.DSTNTN_STPRV_CD, src.CSTMS_CLRNC_ROUTE_POINT_ID, src.CSTMS_CLRNC_SCAC_CD,
            src.CSTMS_CLRNC_FSAC_CD, src.SHPR_SHPMT_PARTY_ID, src.SHPR_CPRS_CSTMR_ID, src.CNSGN_SHPMT_PARTY_ID, src.CNSGN_CPRS_CSTMR_ID,
            src.CARE_OF_SHPMT_PARTY_ID, src.CARE_OF_CPRS_CSTMR_ID, src.THIRD_PARTY_SHPMT_PARTY_ID, src.THIRD_PARTY_CPRS_CSTMR_ID, src.SHPSRV_ITEM_SHPMT_ID,
            src.SHPSRV_ITEM_SQNC_NBR, src.INTRMD_SRVC_CD, src.INTRMD_PLAN_CD, src.METHOD_OF_PYMNT_CD, src.BOL_RFRNC_ID,
            src.BOL_RFRNC_TXT, src.BOL_RFRNC_LOCAL_TMS, src.BOL_RFRNC_LOCAL_TIME_CD, src.COAL_TRAIN_RFRNC_ID, src.COAL_TRAIN_RFRNC_TXT,
            src.STGNG_ATHRZT_RFRNC_ID, src.STGNG_ATHRZT_RFRNC_TXT, src.DRCTV_RFRNC_ID, src.DRCTV_RFRNC_TXT, src.DRCTV_RFRNC_LOCAL_TMS,
            src.DRCTV_RFRNC_LOCAL_TIME_CD, src.DEP_ORDER_RFRNC_ID, src.DEP_ORDER_RFRNC_TXT, src.DEP_ORDER_RFRNC_LOCAL_TMS, src.DEP_ORDER_RFRNC_LOCAL_TIME_CD,
            src.OPRTNL_BOL_TMSTMP_RFRNC_ID, src.OPRTNL_BOL_TMSTMP_RFRNC_TXT, src.CR_ASGND_RFRNC_ID, src.CR_ASGND_RFRNC_TXT, src.TRNSWR_LOAD_NUMBER_RFRNC_ID,
            src.TRNSWR_LOAD_NUMBER_RFRNC_TXT, src.MVMNT_SRVC_SHPMT_ID, src.MVMNT_SRVC_SQNC_NBR, src.MVMNT_ATHRTY_CD, src.RTNG_SQNC_CD,
            src.SWITCH_CD, src.CSTMS_CLRNC_CD, src.DLVR_TO_SCAC_CD, src.ORIGIN_SWITCH_SCAC_CD, src.SHPMT_ROUTE_ID,
            src.RVN_CD, src.ADTNL_LADING_ITEM_CD, src.EQPMT_LOAD_LADING_ITEM_ID, src.DNG_WEIGHT_QTY, src.DNG_WEIGHT_UNIT_CD,
            src.DNG_WEIGHT_QLFR_CD, src.GRAIN_TYPE_CD, src.GRAIN_GRADE_CD, src.PRTCTV_SRVC_SHPMT_ID, src.PRTCTV_SRVC_SQNC_NBR,
            src.PRTCTV_SRVC_CD, src.PRTCTV_SRVC_RULE_CD, src.PRTCTV_SRVC_TMPRTR_QTY, src.PRTCTV_SRVC_TMPRTR_UOM_CD, src.SHPMT_ITEM_SHPMT_ID,
            src.SHPMT_ITEM_SQNC_NBR, src.STCC_CD, src.ADTNL_HNDLNG_DSCRPT_CD, src.PBLSHD_WYBL_VRSN_NBR, src.FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
            src.FRA_APRVL_AGRMNT_NBR_RFRNC_TXT, src.DESPACHO_HOLD_IND, src.CBP_HOLD_IND, src.SNW_OPERATION_TYPE, src.SNW_OPERATION_OWNER, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        v_end_time := CURRENT_TIMESTAMP();
        
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
            TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME,
            ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED,
            ERROR_MESSAGE, CREATED_AT
        ) VALUES (
            'STNWYB_MSG_DN', :v_batch_id, 'RECOVERY', :v_start_time, :v_end_time,
            :v_rows_merged, :v_rows_merged, 0, 0,
            :v_error_msg, CURRENT_TIMESTAMP()
        );
        
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_STNWYB_MSG_DN AS
    SELECT 
        STNWYB_MSG_VRSN_ID, RECORD_CREATE_TMS, CREATE_USER_ID, RECORD_UPDATE_TMS, UPDATE_USER_ID,
        CRNT_VRSN_CD, SOURCE_CREATE_TMS, SRVASG_EQPMT_ASGNMN_ID, SRVASG_SHPSRV_ITEM_SHPMT_ID, SRVASG_SHPSRV_ITEM_SQNC_NBR,
        SRVASG_SQNC_NBR, SHPSRV_EQPASG_CD, CYCLE_SERIAL_NBR, WYBL_NBR, WYBL_CREATE_LOCAL_TMS,
        WYBL_CREATE_TIME_CD, SHPMT_ID, CREATE_DATA_SOURCE_CD, CREATE_SOURCE_TMS, CREATE_SOURCE_USER_ID,
        UPDATE_DATA_SOURCE_CD, UPDATE_SOURCE_TMS, UPDATE_SOURCE_USER_ID, RLS_LOCAL_TMS, RLS_TIME_CD,
        SHPMT_STATUS_ID, WYBL_CANCEL_CD, MARK_CD, EQPUN_NBR, SHPMT_TYPE_CD,
        LOAD_EMPTY_CD, WYBL_CNTNT_WEIGHT_QTY, WYBL_CNTNT_WEIGHT_UNIT_CD, WEIGHT_QLFR_CD, IN_BOND_CD,
        CSA_CD, CHECK_DIGIT_NBR, WYBL_TARE_WEIGHT_QTY, WYBL_TARE_WEIGHT_UNIT_CD, LEAD_EQPMT_ASGNMN_ID,
        LEAD_SHPSRV_ITEM_SHPMT_ID, LEAD_SHPSRV_ITEM_SQNC_NBR, LEAD_SQNC_NBR, LEAD_CYCLE_SERIAL_NBR, WYBL_MERGE_CD,
        PRVS_STCC_CD, EQPMT_POOL_ID, CPR_EQPMT_POOL_ID, ORIGIN_ROUTE_POINT_ID, ORIGIN_SCAC_CD,
        ORIGIN_FSAC_CD, ORIGIN_TRSTN_NM, ORIGIN_STPRV_CD, DSTNTN_ROUTE_POINT_ID, DSTNTN_SCAC_CD,
        DSTNTN_FSAC_CD, DSTNTN_TRSTN_NM, DSTNTN_STPRV_CD, CSTMS_CLRNC_ROUTE_POINT_ID, CSTMS_CLRNC_SCAC_CD,
        CSTMS_CLRNC_FSAC_CD, SHPR_SHPMT_PARTY_ID, SHPR_CPRS_CSTMR_ID, CNSGN_SHPMT_PARTY_ID, CNSGN_CPRS_CSTMR_ID,
        CARE_OF_SHPMT_PARTY_ID, CARE_OF_CPRS_CSTMR_ID, THIRD_PARTY_SHPMT_PARTY_ID, THIRD_PARTY_CPRS_CSTMR_ID, SHPSRV_ITEM_SHPMT_ID,
        SHPSRV_ITEM_SQNC_NBR, INTRMD_SRVC_CD, INTRMD_PLAN_CD, METHOD_OF_PYMNT_CD, BOL_RFRNC_ID,
        BOL_RFRNC_TXT, BOL_RFRNC_LOCAL_TMS, BOL_RFRNC_LOCAL_TIME_CD, COAL_TRAIN_RFRNC_ID, COAL_TRAIN_RFRNC_TXT,
        STGNG_ATHRZT_RFRNC_ID, STGNG_ATHRZT_RFRNC_TXT, DRCTV_RFRNC_ID, DRCTV_RFRNC_TXT, DRCTV_RFRNC_LOCAL_TMS,
        DRCTV_RFRNC_LOCAL_TIME_CD, DEP_ORDER_RFRNC_ID, DEP_ORDER_RFRNC_TXT, DEP_ORDER_RFRNC_LOCAL_TMS, DEP_ORDER_RFRNC_LOCAL_TIME_CD,
        OPRTNL_BOL_TMSTMP_RFRNC_ID, OPRTNL_BOL_TMSTMP_RFRNC_TXT, CR_ASGND_RFRNC_ID, CR_ASGND_RFRNC_TXT, TRNSWR_LOAD_NUMBER_RFRNC_ID,
        TRNSWR_LOAD_NUMBER_RFRNC_TXT, MVMNT_SRVC_SHPMT_ID, MVMNT_SRVC_SQNC_NBR, MVMNT_ATHRTY_CD, RTNG_SQNC_CD,
        SWITCH_CD, CSTMS_CLRNC_CD, DLVR_TO_SCAC_CD, ORIGIN_SWITCH_SCAC_CD, SHPMT_ROUTE_ID,
        RVN_CD, ADTNL_LADING_ITEM_CD, EQPMT_LOAD_LADING_ITEM_ID, DNG_WEIGHT_QTY, DNG_WEIGHT_UNIT_CD,
        DNG_WEIGHT_QLFR_CD, GRAIN_TYPE_CD, GRAIN_GRADE_CD, PRTCTV_SRVC_SHPMT_ID, PRTCTV_SRVC_SQNC_NBR,
        PRTCTV_SRVC_CD, PRTCTV_SRVC_RULE_CD, PRTCTV_SRVC_TMPRTR_QTY, PRTCTV_SRVC_TMPRTR_UOM_CD, SHPMT_ITEM_SHPMT_ID,
        SHPMT_ITEM_SQNC_NBR, STCC_CD, ADTNL_HNDLNG_DSCRPT_CD, PBLSHD_WYBL_VRSN_NBR, FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
        FRA_APRVL_AGRMNT_NBR_RFRNC_TXT, DESPACHO_HOLD_IND, CBP_HOLD_IND, SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.SADB.STNWYB_MSG_DN_BASE_HIST_STREAM
    WHERE NVL(SNW_OPERATION_OWNER, '') NOT IN ('TSDPRG', 'EMEPRG');
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_STNWYB_MSG_DN;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_STNWYB_MSG_DN;
        v_end_time := CURRENT_TIMESTAMP();
        
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
            TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME,
            ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED,
            ERROR_MESSAGE, CREATED_AT
        ) VALUES (
            'STNWYB_MSG_DN', :v_batch_id, 'NO_DATA', :v_start_time, :v_end_time,
            0, 0, 0, 0,
            NULL, CURRENT_TIMESTAMP()
        );
        
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- PRE-MERGE METRICS: Count by operation type for logging
    -- =========================================================================
    SELECT 
        COUNT(CASE WHEN CDC_ACTION = 'INSERT' AND CDC_IS_UPDATE = FALSE THEN 1 END),
        COUNT(CASE WHEN CDC_ACTION = 'INSERT' AND CDC_IS_UPDATE = TRUE THEN 1 END),
        COUNT(CASE WHEN CDC_ACTION = 'DELETE' AND CDC_IS_UPDATE = FALSE THEN 1 END)
    INTO v_rows_inserted, v_rows_updated, v_rows_deleted
    FROM _CDC_STAGING_STNWYB_MSG_DN;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.SADB.STNWYB_MSG_DN AS tgt
    USING (
        SELECT 
            STNWYB_MSG_VRSN_ID, RECORD_CREATE_TMS, CREATE_USER_ID, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            CRNT_VRSN_CD, SOURCE_CREATE_TMS, SRVASG_EQPMT_ASGNMN_ID, SRVASG_SHPSRV_ITEM_SHPMT_ID, SRVASG_SHPSRV_ITEM_SQNC_NBR,
            SRVASG_SQNC_NBR, SHPSRV_EQPASG_CD, CYCLE_SERIAL_NBR, WYBL_NBR, WYBL_CREATE_LOCAL_TMS,
            WYBL_CREATE_TIME_CD, SHPMT_ID, CREATE_DATA_SOURCE_CD, CREATE_SOURCE_TMS, CREATE_SOURCE_USER_ID,
            UPDATE_DATA_SOURCE_CD, UPDATE_SOURCE_TMS, UPDATE_SOURCE_USER_ID, RLS_LOCAL_TMS, RLS_TIME_CD,
            SHPMT_STATUS_ID, WYBL_CANCEL_CD, MARK_CD, EQPUN_NBR, SHPMT_TYPE_CD,
            LOAD_EMPTY_CD, WYBL_CNTNT_WEIGHT_QTY, WYBL_CNTNT_WEIGHT_UNIT_CD, WEIGHT_QLFR_CD, IN_BOND_CD,
            CSA_CD, CHECK_DIGIT_NBR, WYBL_TARE_WEIGHT_QTY, WYBL_TARE_WEIGHT_UNIT_CD, LEAD_EQPMT_ASGNMN_ID,
            LEAD_SHPSRV_ITEM_SHPMT_ID, LEAD_SHPSRV_ITEM_SQNC_NBR, LEAD_SQNC_NBR, LEAD_CYCLE_SERIAL_NBR, WYBL_MERGE_CD,
            PRVS_STCC_CD, EQPMT_POOL_ID, CPR_EQPMT_POOL_ID, ORIGIN_ROUTE_POINT_ID, ORIGIN_SCAC_CD,
            ORIGIN_FSAC_CD, ORIGIN_TRSTN_NM, ORIGIN_STPRV_CD, DSTNTN_ROUTE_POINT_ID, DSTNTN_SCAC_CD,
            DSTNTN_FSAC_CD, DSTNTN_TRSTN_NM, DSTNTN_STPRV_CD, CSTMS_CLRNC_ROUTE_POINT_ID, CSTMS_CLRNC_SCAC_CD,
            CSTMS_CLRNC_FSAC_CD, SHPR_SHPMT_PARTY_ID, SHPR_CPRS_CSTMR_ID, CNSGN_SHPMT_PARTY_ID, CNSGN_CPRS_CSTMR_ID,
            CARE_OF_SHPMT_PARTY_ID, CARE_OF_CPRS_CSTMR_ID, THIRD_PARTY_SHPMT_PARTY_ID, THIRD_PARTY_CPRS_CSTMR_ID, SHPSRV_ITEM_SHPMT_ID,
            SHPSRV_ITEM_SQNC_NBR, INTRMD_SRVC_CD, INTRMD_PLAN_CD, METHOD_OF_PYMNT_CD, BOL_RFRNC_ID,
            BOL_RFRNC_TXT, BOL_RFRNC_LOCAL_TMS, BOL_RFRNC_LOCAL_TIME_CD, COAL_TRAIN_RFRNC_ID, COAL_TRAIN_RFRNC_TXT,
            STGNG_ATHRZT_RFRNC_ID, STGNG_ATHRZT_RFRNC_TXT, DRCTV_RFRNC_ID, DRCTV_RFRNC_TXT, DRCTV_RFRNC_LOCAL_TMS,
            DRCTV_RFRNC_LOCAL_TIME_CD, DEP_ORDER_RFRNC_ID, DEP_ORDER_RFRNC_TXT, DEP_ORDER_RFRNC_LOCAL_TMS, DEP_ORDER_RFRNC_LOCAL_TIME_CD,
            OPRTNL_BOL_TMSTMP_RFRNC_ID, OPRTNL_BOL_TMSTMP_RFRNC_TXT, CR_ASGND_RFRNC_ID, CR_ASGND_RFRNC_TXT, TRNSWR_LOAD_NUMBER_RFRNC_ID,
            TRNSWR_LOAD_NUMBER_RFRNC_TXT, MVMNT_SRVC_SHPMT_ID, MVMNT_SRVC_SQNC_NBR, MVMNT_ATHRTY_CD, RTNG_SQNC_CD,
            SWITCH_CD, CSTMS_CLRNC_CD, DLVR_TO_SCAC_CD, ORIGIN_SWITCH_SCAC_CD, SHPMT_ROUTE_ID,
            RVN_CD, ADTNL_LADING_ITEM_CD, EQPMT_LOAD_LADING_ITEM_ID, DNG_WEIGHT_QTY, DNG_WEIGHT_UNIT_CD,
            DNG_WEIGHT_QLFR_CD, GRAIN_TYPE_CD, GRAIN_GRADE_CD, PRTCTV_SRVC_SHPMT_ID, PRTCTV_SRVC_SQNC_NBR,
            PRTCTV_SRVC_CD, PRTCTV_SRVC_RULE_CD, PRTCTV_SRVC_TMPRTR_QTY, PRTCTV_SRVC_TMPRTR_UOM_CD, SHPMT_ITEM_SHPMT_ID,
            SHPMT_ITEM_SQNC_NBR, STCC_CD, ADTNL_HNDLNG_DSCRPT_CD, PBLSHD_WYBL_VRSN_NBR, FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
            FRA_APRVL_AGRMNT_NBR_RFRNC_TXT, DESPACHO_HOLD_IND, CBP_HOLD_IND, SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_ACTION,
            CDC_IS_UPDATE,
            ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_STNWYB_MSG_DN
    ) AS src
    ON tgt.STNWYB_MSG_VRSN_ID = src.STNWYB_MSG_VRSN_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.CRNT_VRSN_CD = src.CRNT_VRSN_CD,
            tgt.SOURCE_CREATE_TMS = src.SOURCE_CREATE_TMS,
            tgt.SRVASG_EQPMT_ASGNMN_ID = src.SRVASG_EQPMT_ASGNMN_ID,
            tgt.SRVASG_SHPSRV_ITEM_SHPMT_ID = src.SRVASG_SHPSRV_ITEM_SHPMT_ID,
            tgt.SRVASG_SHPSRV_ITEM_SQNC_NBR = src.SRVASG_SHPSRV_ITEM_SQNC_NBR,
            tgt.SRVASG_SQNC_NBR = src.SRVASG_SQNC_NBR,
            tgt.SHPSRV_EQPASG_CD = src.SHPSRV_EQPASG_CD,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.WYBL_NBR = src.WYBL_NBR,
            tgt.WYBL_CREATE_LOCAL_TMS = src.WYBL_CREATE_LOCAL_TMS,
            tgt.WYBL_CREATE_TIME_CD = src.WYBL_CREATE_TIME_CD,
            tgt.SHPMT_ID = src.SHPMT_ID,
            tgt.CREATE_DATA_SOURCE_CD = src.CREATE_DATA_SOURCE_CD,
            tgt.CREATE_SOURCE_TMS = src.CREATE_SOURCE_TMS,
            tgt.CREATE_SOURCE_USER_ID = src.CREATE_SOURCE_USER_ID,
            tgt.UPDATE_DATA_SOURCE_CD = src.UPDATE_DATA_SOURCE_CD,
            tgt.UPDATE_SOURCE_TMS = src.UPDATE_SOURCE_TMS,
            tgt.UPDATE_SOURCE_USER_ID = src.UPDATE_SOURCE_USER_ID,
            tgt.RLS_LOCAL_TMS = src.RLS_LOCAL_TMS,
            tgt.RLS_TIME_CD = src.RLS_TIME_CD,
            tgt.SHPMT_STATUS_ID = src.SHPMT_STATUS_ID,
            tgt.WYBL_CANCEL_CD = src.WYBL_CANCEL_CD,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.SHPMT_TYPE_CD = src.SHPMT_TYPE_CD,
            tgt.LOAD_EMPTY_CD = src.LOAD_EMPTY_CD,
            tgt.WYBL_CNTNT_WEIGHT_QTY = src.WYBL_CNTNT_WEIGHT_QTY,
            tgt.WYBL_CNTNT_WEIGHT_UNIT_CD = src.WYBL_CNTNT_WEIGHT_UNIT_CD,
            tgt.WEIGHT_QLFR_CD = src.WEIGHT_QLFR_CD,
            tgt.IN_BOND_CD = src.IN_BOND_CD,
            tgt.CSA_CD = src.CSA_CD,
            tgt.CHECK_DIGIT_NBR = src.CHECK_DIGIT_NBR,
            tgt.WYBL_TARE_WEIGHT_QTY = src.WYBL_TARE_WEIGHT_QTY,
            tgt.WYBL_TARE_WEIGHT_UNIT_CD = src.WYBL_TARE_WEIGHT_UNIT_CD,
            tgt.LEAD_EQPMT_ASGNMN_ID = src.LEAD_EQPMT_ASGNMN_ID,
            tgt.LEAD_SHPSRV_ITEM_SHPMT_ID = src.LEAD_SHPSRV_ITEM_SHPMT_ID,
            tgt.LEAD_SHPSRV_ITEM_SQNC_NBR = src.LEAD_SHPSRV_ITEM_SQNC_NBR,
            tgt.LEAD_SQNC_NBR = src.LEAD_SQNC_NBR,
            tgt.LEAD_CYCLE_SERIAL_NBR = src.LEAD_CYCLE_SERIAL_NBR,
            tgt.WYBL_MERGE_CD = src.WYBL_MERGE_CD,
            tgt.PRVS_STCC_CD = src.PRVS_STCC_CD,
            tgt.EQPMT_POOL_ID = src.EQPMT_POOL_ID,
            tgt.CPR_EQPMT_POOL_ID = src.CPR_EQPMT_POOL_ID,
            tgt.ORIGIN_ROUTE_POINT_ID = src.ORIGIN_ROUTE_POINT_ID,
            tgt.ORIGIN_SCAC_CD = src.ORIGIN_SCAC_CD,
            tgt.ORIGIN_FSAC_CD = src.ORIGIN_FSAC_CD,
            tgt.ORIGIN_TRSTN_NM = src.ORIGIN_TRSTN_NM,
            tgt.ORIGIN_STPRV_CD = src.ORIGIN_STPRV_CD,
            tgt.DSTNTN_ROUTE_POINT_ID = src.DSTNTN_ROUTE_POINT_ID,
            tgt.DSTNTN_SCAC_CD = src.DSTNTN_SCAC_CD,
            tgt.DSTNTN_FSAC_CD = src.DSTNTN_FSAC_CD,
            tgt.DSTNTN_TRSTN_NM = src.DSTNTN_TRSTN_NM,
            tgt.DSTNTN_STPRV_CD = src.DSTNTN_STPRV_CD,
            tgt.CSTMS_CLRNC_ROUTE_POINT_ID = src.CSTMS_CLRNC_ROUTE_POINT_ID,
            tgt.CSTMS_CLRNC_SCAC_CD = src.CSTMS_CLRNC_SCAC_CD,
            tgt.CSTMS_CLRNC_FSAC_CD = src.CSTMS_CLRNC_FSAC_CD,
            tgt.SHPR_SHPMT_PARTY_ID = src.SHPR_SHPMT_PARTY_ID,
            tgt.SHPR_CPRS_CSTMR_ID = src.SHPR_CPRS_CSTMR_ID,
            tgt.CNSGN_SHPMT_PARTY_ID = src.CNSGN_SHPMT_PARTY_ID,
            tgt.CNSGN_CPRS_CSTMR_ID = src.CNSGN_CPRS_CSTMR_ID,
            tgt.CARE_OF_SHPMT_PARTY_ID = src.CARE_OF_SHPMT_PARTY_ID,
            tgt.CARE_OF_CPRS_CSTMR_ID = src.CARE_OF_CPRS_CSTMR_ID,
            tgt.THIRD_PARTY_SHPMT_PARTY_ID = src.THIRD_PARTY_SHPMT_PARTY_ID,
            tgt.THIRD_PARTY_CPRS_CSTMR_ID = src.THIRD_PARTY_CPRS_CSTMR_ID,
            tgt.SHPSRV_ITEM_SHPMT_ID = src.SHPSRV_ITEM_SHPMT_ID,
            tgt.SHPSRV_ITEM_SQNC_NBR = src.SHPSRV_ITEM_SQNC_NBR,
            tgt.INTRMD_SRVC_CD = src.INTRMD_SRVC_CD,
            tgt.INTRMD_PLAN_CD = src.INTRMD_PLAN_CD,
            tgt.METHOD_OF_PYMNT_CD = src.METHOD_OF_PYMNT_CD,
            tgt.BOL_RFRNC_ID = src.BOL_RFRNC_ID,
            tgt.BOL_RFRNC_TXT = src.BOL_RFRNC_TXT,
            tgt.BOL_RFRNC_LOCAL_TMS = src.BOL_RFRNC_LOCAL_TMS,
            tgt.BOL_RFRNC_LOCAL_TIME_CD = src.BOL_RFRNC_LOCAL_TIME_CD,
            tgt.COAL_TRAIN_RFRNC_ID = src.COAL_TRAIN_RFRNC_ID,
            tgt.COAL_TRAIN_RFRNC_TXT = src.COAL_TRAIN_RFRNC_TXT,
            tgt.STGNG_ATHRZT_RFRNC_ID = src.STGNG_ATHRZT_RFRNC_ID,
            tgt.STGNG_ATHRZT_RFRNC_TXT = src.STGNG_ATHRZT_RFRNC_TXT,
            tgt.DRCTV_RFRNC_ID = src.DRCTV_RFRNC_ID,
            tgt.DRCTV_RFRNC_TXT = src.DRCTV_RFRNC_TXT,
            tgt.DRCTV_RFRNC_LOCAL_TMS = src.DRCTV_RFRNC_LOCAL_TMS,
            tgt.DRCTV_RFRNC_LOCAL_TIME_CD = src.DRCTV_RFRNC_LOCAL_TIME_CD,
            tgt.DEP_ORDER_RFRNC_ID = src.DEP_ORDER_RFRNC_ID,
            tgt.DEP_ORDER_RFRNC_TXT = src.DEP_ORDER_RFRNC_TXT,
            tgt.DEP_ORDER_RFRNC_LOCAL_TMS = src.DEP_ORDER_RFRNC_LOCAL_TMS,
            tgt.DEP_ORDER_RFRNC_LOCAL_TIME_CD = src.DEP_ORDER_RFRNC_LOCAL_TIME_CD,
            tgt.OPRTNL_BOL_TMSTMP_RFRNC_ID = src.OPRTNL_BOL_TMSTMP_RFRNC_ID,
            tgt.OPRTNL_BOL_TMSTMP_RFRNC_TXT = src.OPRTNL_BOL_TMSTMP_RFRNC_TXT,
            tgt.CR_ASGND_RFRNC_ID = src.CR_ASGND_RFRNC_ID,
            tgt.CR_ASGND_RFRNC_TXT = src.CR_ASGND_RFRNC_TXT,
            tgt.TRNSWR_LOAD_NUMBER_RFRNC_ID = src.TRNSWR_LOAD_NUMBER_RFRNC_ID,
            tgt.TRNSWR_LOAD_NUMBER_RFRNC_TXT = src.TRNSWR_LOAD_NUMBER_RFRNC_TXT,
            tgt.MVMNT_SRVC_SHPMT_ID = src.MVMNT_SRVC_SHPMT_ID,
            tgt.MVMNT_SRVC_SQNC_NBR = src.MVMNT_SRVC_SQNC_NBR,
            tgt.MVMNT_ATHRTY_CD = src.MVMNT_ATHRTY_CD,
            tgt.RTNG_SQNC_CD = src.RTNG_SQNC_CD,
            tgt.SWITCH_CD = src.SWITCH_CD,
            tgt.CSTMS_CLRNC_CD = src.CSTMS_CLRNC_CD,
            tgt.DLVR_TO_SCAC_CD = src.DLVR_TO_SCAC_CD,
            tgt.ORIGIN_SWITCH_SCAC_CD = src.ORIGIN_SWITCH_SCAC_CD,
            tgt.SHPMT_ROUTE_ID = src.SHPMT_ROUTE_ID,
            tgt.RVN_CD = src.RVN_CD,
            tgt.ADTNL_LADING_ITEM_CD = src.ADTNL_LADING_ITEM_CD,
            tgt.EQPMT_LOAD_LADING_ITEM_ID = src.EQPMT_LOAD_LADING_ITEM_ID,
            tgt.DNG_WEIGHT_QTY = src.DNG_WEIGHT_QTY,
            tgt.DNG_WEIGHT_UNIT_CD = src.DNG_WEIGHT_UNIT_CD,
            tgt.DNG_WEIGHT_QLFR_CD = src.DNG_WEIGHT_QLFR_CD,
            tgt.GRAIN_TYPE_CD = src.GRAIN_TYPE_CD,
            tgt.GRAIN_GRADE_CD = src.GRAIN_GRADE_CD,
            tgt.PRTCTV_SRVC_SHPMT_ID = src.PRTCTV_SRVC_SHPMT_ID,
            tgt.PRTCTV_SRVC_SQNC_NBR = src.PRTCTV_SRVC_SQNC_NBR,
            tgt.PRTCTV_SRVC_CD = src.PRTCTV_SRVC_CD,
            tgt.PRTCTV_SRVC_RULE_CD = src.PRTCTV_SRVC_RULE_CD,
            tgt.PRTCTV_SRVC_TMPRTR_QTY = src.PRTCTV_SRVC_TMPRTR_QTY,
            tgt.PRTCTV_SRVC_TMPRTR_UOM_CD = src.PRTCTV_SRVC_TMPRTR_UOM_CD,
            tgt.SHPMT_ITEM_SHPMT_ID = src.SHPMT_ITEM_SHPMT_ID,
            tgt.SHPMT_ITEM_SQNC_NBR = src.SHPMT_ITEM_SQNC_NBR,
            tgt.STCC_CD = src.STCC_CD,
            tgt.ADTNL_HNDLNG_DSCRPT_CD = src.ADTNL_HNDLNG_DSCRPT_CD,
            tgt.PBLSHD_WYBL_VRSN_NBR = src.PBLSHD_WYBL_VRSN_NBR,
            tgt.FRA_APRVL_AGRMNT_NBR_RFRNC_ID = src.FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
            tgt.FRA_APRVL_AGRMNT_NBR_RFRNC_TXT = src.FRA_APRVL_AGRMNT_NBR_RFRNC_TXT,
            tgt.DESPACHO_HOLD_IND = src.DESPACHO_HOLD_IND,
            tgt.CBP_HOLD_IND = src.CBP_HOLD_IND,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.CRNT_VRSN_CD = src.CRNT_VRSN_CD,
            tgt.SOURCE_CREATE_TMS = src.SOURCE_CREATE_TMS,
            tgt.SRVASG_EQPMT_ASGNMN_ID = src.SRVASG_EQPMT_ASGNMN_ID,
            tgt.SRVASG_SHPSRV_ITEM_SHPMT_ID = src.SRVASG_SHPSRV_ITEM_SHPMT_ID,
            tgt.SRVASG_SHPSRV_ITEM_SQNC_NBR = src.SRVASG_SHPSRV_ITEM_SQNC_NBR,
            tgt.SRVASG_SQNC_NBR = src.SRVASG_SQNC_NBR,
            tgt.SHPSRV_EQPASG_CD = src.SHPSRV_EQPASG_CD,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.WYBL_NBR = src.WYBL_NBR,
            tgt.WYBL_CREATE_LOCAL_TMS = src.WYBL_CREATE_LOCAL_TMS,
            tgt.WYBL_CREATE_TIME_CD = src.WYBL_CREATE_TIME_CD,
            tgt.SHPMT_ID = src.SHPMT_ID,
            tgt.CREATE_DATA_SOURCE_CD = src.CREATE_DATA_SOURCE_CD,
            tgt.CREATE_SOURCE_TMS = src.CREATE_SOURCE_TMS,
            tgt.CREATE_SOURCE_USER_ID = src.CREATE_SOURCE_USER_ID,
            tgt.UPDATE_DATA_SOURCE_CD = src.UPDATE_DATA_SOURCE_CD,
            tgt.UPDATE_SOURCE_TMS = src.UPDATE_SOURCE_TMS,
            tgt.UPDATE_SOURCE_USER_ID = src.UPDATE_SOURCE_USER_ID,
            tgt.RLS_LOCAL_TMS = src.RLS_LOCAL_TMS,
            tgt.RLS_TIME_CD = src.RLS_TIME_CD,
            tgt.SHPMT_STATUS_ID = src.SHPMT_STATUS_ID,
            tgt.WYBL_CANCEL_CD = src.WYBL_CANCEL_CD,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.SHPMT_TYPE_CD = src.SHPMT_TYPE_CD,
            tgt.LOAD_EMPTY_CD = src.LOAD_EMPTY_CD,
            tgt.WYBL_CNTNT_WEIGHT_QTY = src.WYBL_CNTNT_WEIGHT_QTY,
            tgt.WYBL_CNTNT_WEIGHT_UNIT_CD = src.WYBL_CNTNT_WEIGHT_UNIT_CD,
            tgt.WEIGHT_QLFR_CD = src.WEIGHT_QLFR_CD,
            tgt.IN_BOND_CD = src.IN_BOND_CD,
            tgt.CSA_CD = src.CSA_CD,
            tgt.CHECK_DIGIT_NBR = src.CHECK_DIGIT_NBR,
            tgt.WYBL_TARE_WEIGHT_QTY = src.WYBL_TARE_WEIGHT_QTY,
            tgt.WYBL_TARE_WEIGHT_UNIT_CD = src.WYBL_TARE_WEIGHT_UNIT_CD,
            tgt.LEAD_EQPMT_ASGNMN_ID = src.LEAD_EQPMT_ASGNMN_ID,
            tgt.LEAD_SHPSRV_ITEM_SHPMT_ID = src.LEAD_SHPSRV_ITEM_SHPMT_ID,
            tgt.LEAD_SHPSRV_ITEM_SQNC_NBR = src.LEAD_SHPSRV_ITEM_SQNC_NBR,
            tgt.LEAD_SQNC_NBR = src.LEAD_SQNC_NBR,
            tgt.LEAD_CYCLE_SERIAL_NBR = src.LEAD_CYCLE_SERIAL_NBR,
            tgt.WYBL_MERGE_CD = src.WYBL_MERGE_CD,
            tgt.PRVS_STCC_CD = src.PRVS_STCC_CD,
            tgt.EQPMT_POOL_ID = src.EQPMT_POOL_ID,
            tgt.CPR_EQPMT_POOL_ID = src.CPR_EQPMT_POOL_ID,
            tgt.ORIGIN_ROUTE_POINT_ID = src.ORIGIN_ROUTE_POINT_ID,
            tgt.ORIGIN_SCAC_CD = src.ORIGIN_SCAC_CD,
            tgt.ORIGIN_FSAC_CD = src.ORIGIN_FSAC_CD,
            tgt.ORIGIN_TRSTN_NM = src.ORIGIN_TRSTN_NM,
            tgt.ORIGIN_STPRV_CD = src.ORIGIN_STPRV_CD,
            tgt.DSTNTN_ROUTE_POINT_ID = src.DSTNTN_ROUTE_POINT_ID,
            tgt.DSTNTN_SCAC_CD = src.DSTNTN_SCAC_CD,
            tgt.DSTNTN_FSAC_CD = src.DSTNTN_FSAC_CD,
            tgt.DSTNTN_TRSTN_NM = src.DSTNTN_TRSTN_NM,
            tgt.DSTNTN_STPRV_CD = src.DSTNTN_STPRV_CD,
            tgt.CSTMS_CLRNC_ROUTE_POINT_ID = src.CSTMS_CLRNC_ROUTE_POINT_ID,
            tgt.CSTMS_CLRNC_SCAC_CD = src.CSTMS_CLRNC_SCAC_CD,
            tgt.CSTMS_CLRNC_FSAC_CD = src.CSTMS_CLRNC_FSAC_CD,
            tgt.SHPR_SHPMT_PARTY_ID = src.SHPR_SHPMT_PARTY_ID,
            tgt.SHPR_CPRS_CSTMR_ID = src.SHPR_CPRS_CSTMR_ID,
            tgt.CNSGN_SHPMT_PARTY_ID = src.CNSGN_SHPMT_PARTY_ID,
            tgt.CNSGN_CPRS_CSTMR_ID = src.CNSGN_CPRS_CSTMR_ID,
            tgt.CARE_OF_SHPMT_PARTY_ID = src.CARE_OF_SHPMT_PARTY_ID,
            tgt.CARE_OF_CPRS_CSTMR_ID = src.CARE_OF_CPRS_CSTMR_ID,
            tgt.THIRD_PARTY_SHPMT_PARTY_ID = src.THIRD_PARTY_SHPMT_PARTY_ID,
            tgt.THIRD_PARTY_CPRS_CSTMR_ID = src.THIRD_PARTY_CPRS_CSTMR_ID,
            tgt.SHPSRV_ITEM_SHPMT_ID = src.SHPSRV_ITEM_SHPMT_ID,
            tgt.SHPSRV_ITEM_SQNC_NBR = src.SHPSRV_ITEM_SQNC_NBR,
            tgt.INTRMD_SRVC_CD = src.INTRMD_SRVC_CD,
            tgt.INTRMD_PLAN_CD = src.INTRMD_PLAN_CD,
            tgt.METHOD_OF_PYMNT_CD = src.METHOD_OF_PYMNT_CD,
            tgt.BOL_RFRNC_ID = src.BOL_RFRNC_ID,
            tgt.BOL_RFRNC_TXT = src.BOL_RFRNC_TXT,
            tgt.BOL_RFRNC_LOCAL_TMS = src.BOL_RFRNC_LOCAL_TMS,
            tgt.BOL_RFRNC_LOCAL_TIME_CD = src.BOL_RFRNC_LOCAL_TIME_CD,
            tgt.COAL_TRAIN_RFRNC_ID = src.COAL_TRAIN_RFRNC_ID,
            tgt.COAL_TRAIN_RFRNC_TXT = src.COAL_TRAIN_RFRNC_TXT,
            tgt.STGNG_ATHRZT_RFRNC_ID = src.STGNG_ATHRZT_RFRNC_ID,
            tgt.STGNG_ATHRZT_RFRNC_TXT = src.STGNG_ATHRZT_RFRNC_TXT,
            tgt.DRCTV_RFRNC_ID = src.DRCTV_RFRNC_ID,
            tgt.DRCTV_RFRNC_TXT = src.DRCTV_RFRNC_TXT,
            tgt.DRCTV_RFRNC_LOCAL_TMS = src.DRCTV_RFRNC_LOCAL_TMS,
            tgt.DRCTV_RFRNC_LOCAL_TIME_CD = src.DRCTV_RFRNC_LOCAL_TIME_CD,
            tgt.DEP_ORDER_RFRNC_ID = src.DEP_ORDER_RFRNC_ID,
            tgt.DEP_ORDER_RFRNC_TXT = src.DEP_ORDER_RFRNC_TXT,
            tgt.DEP_ORDER_RFRNC_LOCAL_TMS = src.DEP_ORDER_RFRNC_LOCAL_TMS,
            tgt.DEP_ORDER_RFRNC_LOCAL_TIME_CD = src.DEP_ORDER_RFRNC_LOCAL_TIME_CD,
            tgt.OPRTNL_BOL_TMSTMP_RFRNC_ID = src.OPRTNL_BOL_TMSTMP_RFRNC_ID,
            tgt.OPRTNL_BOL_TMSTMP_RFRNC_TXT = src.OPRTNL_BOL_TMSTMP_RFRNC_TXT,
            tgt.CR_ASGND_RFRNC_ID = src.CR_ASGND_RFRNC_ID,
            tgt.CR_ASGND_RFRNC_TXT = src.CR_ASGND_RFRNC_TXT,
            tgt.TRNSWR_LOAD_NUMBER_RFRNC_ID = src.TRNSWR_LOAD_NUMBER_RFRNC_ID,
            tgt.TRNSWR_LOAD_NUMBER_RFRNC_TXT = src.TRNSWR_LOAD_NUMBER_RFRNC_TXT,
            tgt.MVMNT_SRVC_SHPMT_ID = src.MVMNT_SRVC_SHPMT_ID,
            tgt.MVMNT_SRVC_SQNC_NBR = src.MVMNT_SRVC_SQNC_NBR,
            tgt.MVMNT_ATHRTY_CD = src.MVMNT_ATHRTY_CD,
            tgt.RTNG_SQNC_CD = src.RTNG_SQNC_CD,
            tgt.SWITCH_CD = src.SWITCH_CD,
            tgt.CSTMS_CLRNC_CD = src.CSTMS_CLRNC_CD,
            tgt.DLVR_TO_SCAC_CD = src.DLVR_TO_SCAC_CD,
            tgt.ORIGIN_SWITCH_SCAC_CD = src.ORIGIN_SWITCH_SCAC_CD,
            tgt.SHPMT_ROUTE_ID = src.SHPMT_ROUTE_ID,
            tgt.RVN_CD = src.RVN_CD,
            tgt.ADTNL_LADING_ITEM_CD = src.ADTNL_LADING_ITEM_CD,
            tgt.EQPMT_LOAD_LADING_ITEM_ID = src.EQPMT_LOAD_LADING_ITEM_ID,
            tgt.DNG_WEIGHT_QTY = src.DNG_WEIGHT_QTY,
            tgt.DNG_WEIGHT_UNIT_CD = src.DNG_WEIGHT_UNIT_CD,
            tgt.DNG_WEIGHT_QLFR_CD = src.DNG_WEIGHT_QLFR_CD,
            tgt.GRAIN_TYPE_CD = src.GRAIN_TYPE_CD,
            tgt.GRAIN_GRADE_CD = src.GRAIN_GRADE_CD,
            tgt.PRTCTV_SRVC_SHPMT_ID = src.PRTCTV_SRVC_SHPMT_ID,
            tgt.PRTCTV_SRVC_SQNC_NBR = src.PRTCTV_SRVC_SQNC_NBR,
            tgt.PRTCTV_SRVC_CD = src.PRTCTV_SRVC_CD,
            tgt.PRTCTV_SRVC_RULE_CD = src.PRTCTV_SRVC_RULE_CD,
            tgt.PRTCTV_SRVC_TMPRTR_QTY = src.PRTCTV_SRVC_TMPRTR_QTY,
            tgt.PRTCTV_SRVC_TMPRTR_UOM_CD = src.PRTCTV_SRVC_TMPRTR_UOM_CD,
            tgt.SHPMT_ITEM_SHPMT_ID = src.SHPMT_ITEM_SHPMT_ID,
            tgt.SHPMT_ITEM_SQNC_NBR = src.SHPMT_ITEM_SQNC_NBR,
            tgt.STCC_CD = src.STCC_CD,
            tgt.ADTNL_HNDLNG_DSCRPT_CD = src.ADTNL_HNDLNG_DSCRPT_CD,
            tgt.PBLSHD_WYBL_VRSN_NBR = src.PBLSHD_WYBL_VRSN_NBR,
            tgt.FRA_APRVL_AGRMNT_NBR_RFRNC_ID = src.FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
            tgt.FRA_APRVL_AGRMNT_NBR_RFRNC_TXT = src.FRA_APRVL_AGRMNT_NBR_RFRNC_TXT,
            tgt.DESPACHO_HOLD_IND = src.DESPACHO_HOLD_IND,
            tgt.CBP_HOLD_IND = src.CBP_HOLD_IND,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            STNWYB_MSG_VRSN_ID, RECORD_CREATE_TMS, CREATE_USER_ID, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            CRNT_VRSN_CD, SOURCE_CREATE_TMS, SRVASG_EQPMT_ASGNMN_ID, SRVASG_SHPSRV_ITEM_SHPMT_ID, SRVASG_SHPSRV_ITEM_SQNC_NBR,
            SRVASG_SQNC_NBR, SHPSRV_EQPASG_CD, CYCLE_SERIAL_NBR, WYBL_NBR, WYBL_CREATE_LOCAL_TMS,
            WYBL_CREATE_TIME_CD, SHPMT_ID, CREATE_DATA_SOURCE_CD, CREATE_SOURCE_TMS, CREATE_SOURCE_USER_ID,
            UPDATE_DATA_SOURCE_CD, UPDATE_SOURCE_TMS, UPDATE_SOURCE_USER_ID, RLS_LOCAL_TMS, RLS_TIME_CD,
            SHPMT_STATUS_ID, WYBL_CANCEL_CD, MARK_CD, EQPUN_NBR, SHPMT_TYPE_CD,
            LOAD_EMPTY_CD, WYBL_CNTNT_WEIGHT_QTY, WYBL_CNTNT_WEIGHT_UNIT_CD, WEIGHT_QLFR_CD, IN_BOND_CD,
            CSA_CD, CHECK_DIGIT_NBR, WYBL_TARE_WEIGHT_QTY, WYBL_TARE_WEIGHT_UNIT_CD, LEAD_EQPMT_ASGNMN_ID,
            LEAD_SHPSRV_ITEM_SHPMT_ID, LEAD_SHPSRV_ITEM_SQNC_NBR, LEAD_SQNC_NBR, LEAD_CYCLE_SERIAL_NBR, WYBL_MERGE_CD,
            PRVS_STCC_CD, EQPMT_POOL_ID, CPR_EQPMT_POOL_ID, ORIGIN_ROUTE_POINT_ID, ORIGIN_SCAC_CD,
            ORIGIN_FSAC_CD, ORIGIN_TRSTN_NM, ORIGIN_STPRV_CD, DSTNTN_ROUTE_POINT_ID, DSTNTN_SCAC_CD,
            DSTNTN_FSAC_CD, DSTNTN_TRSTN_NM, DSTNTN_STPRV_CD, CSTMS_CLRNC_ROUTE_POINT_ID, CSTMS_CLRNC_SCAC_CD,
            CSTMS_CLRNC_FSAC_CD, SHPR_SHPMT_PARTY_ID, SHPR_CPRS_CSTMR_ID, CNSGN_SHPMT_PARTY_ID, CNSGN_CPRS_CSTMR_ID,
            CARE_OF_SHPMT_PARTY_ID, CARE_OF_CPRS_CSTMR_ID, THIRD_PARTY_SHPMT_PARTY_ID, THIRD_PARTY_CPRS_CSTMR_ID, SHPSRV_ITEM_SHPMT_ID,
            SHPSRV_ITEM_SQNC_NBR, INTRMD_SRVC_CD, INTRMD_PLAN_CD, METHOD_OF_PYMNT_CD, BOL_RFRNC_ID,
            BOL_RFRNC_TXT, BOL_RFRNC_LOCAL_TMS, BOL_RFRNC_LOCAL_TIME_CD, COAL_TRAIN_RFRNC_ID, COAL_TRAIN_RFRNC_TXT,
            STGNG_ATHRZT_RFRNC_ID, STGNG_ATHRZT_RFRNC_TXT, DRCTV_RFRNC_ID, DRCTV_RFRNC_TXT, DRCTV_RFRNC_LOCAL_TMS,
            DRCTV_RFRNC_LOCAL_TIME_CD, DEP_ORDER_RFRNC_ID, DEP_ORDER_RFRNC_TXT, DEP_ORDER_RFRNC_LOCAL_TMS, DEP_ORDER_RFRNC_LOCAL_TIME_CD,
            OPRTNL_BOL_TMSTMP_RFRNC_ID, OPRTNL_BOL_TMSTMP_RFRNC_TXT, CR_ASGND_RFRNC_ID, CR_ASGND_RFRNC_TXT, TRNSWR_LOAD_NUMBER_RFRNC_ID,
            TRNSWR_LOAD_NUMBER_RFRNC_TXT, MVMNT_SRVC_SHPMT_ID, MVMNT_SRVC_SQNC_NBR, MVMNT_ATHRTY_CD, RTNG_SQNC_CD,
            SWITCH_CD, CSTMS_CLRNC_CD, DLVR_TO_SCAC_CD, ORIGIN_SWITCH_SCAC_CD, SHPMT_ROUTE_ID,
            RVN_CD, ADTNL_LADING_ITEM_CD, EQPMT_LOAD_LADING_ITEM_ID, DNG_WEIGHT_QTY, DNG_WEIGHT_UNIT_CD,
            DNG_WEIGHT_QLFR_CD, GRAIN_TYPE_CD, GRAIN_GRADE_CD, PRTCTV_SRVC_SHPMT_ID, PRTCTV_SRVC_SQNC_NBR,
            PRTCTV_SRVC_CD, PRTCTV_SRVC_RULE_CD, PRTCTV_SRVC_TMPRTR_QTY, PRTCTV_SRVC_TMPRTR_UOM_CD, SHPMT_ITEM_SHPMT_ID,
            SHPMT_ITEM_SQNC_NBR, STCC_CD, ADTNL_HNDLNG_DSCRPT_CD, PBLSHD_WYBL_VRSN_NBR, FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
            FRA_APRVL_AGRMNT_NBR_RFRNC_TXT, DESPACHO_HOLD_IND, CBP_HOLD_IND, SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.STNWYB_MSG_VRSN_ID, src.RECORD_CREATE_TMS, src.CREATE_USER_ID, src.RECORD_UPDATE_TMS, src.UPDATE_USER_ID,
            src.CRNT_VRSN_CD, src.SOURCE_CREATE_TMS, src.SRVASG_EQPMT_ASGNMN_ID, src.SRVASG_SHPSRV_ITEM_SHPMT_ID, src.SRVASG_SHPSRV_ITEM_SQNC_NBR,
            src.SRVASG_SQNC_NBR, src.SHPSRV_EQPASG_CD, src.CYCLE_SERIAL_NBR, src.WYBL_NBR, src.WYBL_CREATE_LOCAL_TMS,
            src.WYBL_CREATE_TIME_CD, src.SHPMT_ID, src.CREATE_DATA_SOURCE_CD, src.CREATE_SOURCE_TMS, src.CREATE_SOURCE_USER_ID,
            src.UPDATE_DATA_SOURCE_CD, src.UPDATE_SOURCE_TMS, src.UPDATE_SOURCE_USER_ID, src.RLS_LOCAL_TMS, src.RLS_TIME_CD,
            src.SHPMT_STATUS_ID, src.WYBL_CANCEL_CD, src.MARK_CD, src.EQPUN_NBR, src.SHPMT_TYPE_CD,
            src.LOAD_EMPTY_CD, src.WYBL_CNTNT_WEIGHT_QTY, src.WYBL_CNTNT_WEIGHT_UNIT_CD, src.WEIGHT_QLFR_CD, src.IN_BOND_CD,
            src.CSA_CD, src.CHECK_DIGIT_NBR, src.WYBL_TARE_WEIGHT_QTY, src.WYBL_TARE_WEIGHT_UNIT_CD, src.LEAD_EQPMT_ASGNMN_ID,
            src.LEAD_SHPSRV_ITEM_SHPMT_ID, src.LEAD_SHPSRV_ITEM_SQNC_NBR, src.LEAD_SQNC_NBR, src.LEAD_CYCLE_SERIAL_NBR, src.WYBL_MERGE_CD,
            src.PRVS_STCC_CD, src.EQPMT_POOL_ID, src.CPR_EQPMT_POOL_ID, src.ORIGIN_ROUTE_POINT_ID, src.ORIGIN_SCAC_CD,
            src.ORIGIN_FSAC_CD, src.ORIGIN_TRSTN_NM, src.ORIGIN_STPRV_CD, src.DSTNTN_ROUTE_POINT_ID, src.DSTNTN_SCAC_CD,
            src.DSTNTN_FSAC_CD, src.DSTNTN_TRSTN_NM, src.DSTNTN_STPRV_CD, src.CSTMS_CLRNC_ROUTE_POINT_ID, src.CSTMS_CLRNC_SCAC_CD,
            src.CSTMS_CLRNC_FSAC_CD, src.SHPR_SHPMT_PARTY_ID, src.SHPR_CPRS_CSTMR_ID, src.CNSGN_SHPMT_PARTY_ID, src.CNSGN_CPRS_CSTMR_ID,
            src.CARE_OF_SHPMT_PARTY_ID, src.CARE_OF_CPRS_CSTMR_ID, src.THIRD_PARTY_SHPMT_PARTY_ID, src.THIRD_PARTY_CPRS_CSTMR_ID, src.SHPSRV_ITEM_SHPMT_ID,
            src.SHPSRV_ITEM_SQNC_NBR, src.INTRMD_SRVC_CD, src.INTRMD_PLAN_CD, src.METHOD_OF_PYMNT_CD, src.BOL_RFRNC_ID,
            src.BOL_RFRNC_TXT, src.BOL_RFRNC_LOCAL_TMS, src.BOL_RFRNC_LOCAL_TIME_CD, src.COAL_TRAIN_RFRNC_ID, src.COAL_TRAIN_RFRNC_TXT,
            src.STGNG_ATHRZT_RFRNC_ID, src.STGNG_ATHRZT_RFRNC_TXT, src.DRCTV_RFRNC_ID, src.DRCTV_RFRNC_TXT, src.DRCTV_RFRNC_LOCAL_TMS,
            src.DRCTV_RFRNC_LOCAL_TIME_CD, src.DEP_ORDER_RFRNC_ID, src.DEP_ORDER_RFRNC_TXT, src.DEP_ORDER_RFRNC_LOCAL_TMS, src.DEP_ORDER_RFRNC_LOCAL_TIME_CD,
            src.OPRTNL_BOL_TMSTMP_RFRNC_ID, src.OPRTNL_BOL_TMSTMP_RFRNC_TXT, src.CR_ASGND_RFRNC_ID, src.CR_ASGND_RFRNC_TXT, src.TRNSWR_LOAD_NUMBER_RFRNC_ID,
            src.TRNSWR_LOAD_NUMBER_RFRNC_TXT, src.MVMNT_SRVC_SHPMT_ID, src.MVMNT_SRVC_SQNC_NBR, src.MVMNT_ATHRTY_CD, src.RTNG_SQNC_CD,
            src.SWITCH_CD, src.CSTMS_CLRNC_CD, src.DLVR_TO_SCAC_CD, src.ORIGIN_SWITCH_SCAC_CD, src.SHPMT_ROUTE_ID,
            src.RVN_CD, src.ADTNL_LADING_ITEM_CD, src.EQPMT_LOAD_LADING_ITEM_ID, src.DNG_WEIGHT_QTY, src.DNG_WEIGHT_UNIT_CD,
            src.DNG_WEIGHT_QLFR_CD, src.GRAIN_TYPE_CD, src.GRAIN_GRADE_CD, src.PRTCTV_SRVC_SHPMT_ID, src.PRTCTV_SRVC_SQNC_NBR,
            src.PRTCTV_SRVC_CD, src.PRTCTV_SRVC_RULE_CD, src.PRTCTV_SRVC_TMPRTR_QTY, src.PRTCTV_SRVC_TMPRTR_UOM_CD, src.SHPMT_ITEM_SHPMT_ID,
            src.SHPMT_ITEM_SQNC_NBR, src.STCC_CD, src.ADTNL_HNDLNG_DSCRPT_CD, src.PBLSHD_WYBL_VRSN_NBR, src.FRA_APRVL_AGRMNT_NBR_RFRNC_ID,
            src.FRA_APRVL_AGRMNT_NBR_RFRNC_TXT, src.DESPACHO_HOLD_IND, src.CBP_HOLD_IND, src.SNW_OPERATION_TYPE, src.SNW_OPERATION_OWNER, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    v_end_time := CURRENT_TIMESTAMP();
    
    DROP TABLE IF EXISTS _CDC_STAGING_STNWYB_MSG_DN;
    
    -- =========================================================================
    -- EXECUTION LOGGING: Write metrics to CDC_EXECUTION_LOG
    -- =========================================================================
    INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
        TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME,
        ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED,
        ERROR_MESSAGE, CREATED_AT
    ) VALUES (
        'STNWYB_MSG_DN', :v_batch_id, 'SUCCESS', :v_start_time, :v_end_time,
        :v_rows_merged, :v_rows_inserted, :v_rows_updated, :v_rows_deleted,
        NULL, CURRENT_TIMESTAMP()
    );
    
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes (I:' || v_rows_inserted || 
           ' U:' || v_rows_updated || ' D:' || v_rows_deleted || '). Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        v_end_time := CURRENT_TIMESTAMP();
        v_error_msg := SQLERRM;
        
        DROP TABLE IF EXISTS _CDC_STAGING_STNWYB_MSG_DN;
        
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
            TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME,
            ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED,
            ERROR_MESSAGE, CREATED_AT
        ) VALUES (
            'STNWYB_MSG_DN', :v_batch_id, 'ERROR', :v_start_time, :v_end_time,
            0, 0, 0, 0,
            :v_error_msg, CURRENT_TIMESTAMP()
        );
        
        RETURN 'ERROR: ' || v_error_msg || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.SADB.TASK_PROCESS_STNWYB_MSG_DN
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process STNWYB_MSG_DN_BASE CDC changes into data preservation table (v1 - enhanced logging)'
AS
    CALL D_RAW.SADB.SP_PROCESS_STNWYB_MSG_DN();

ALTER TASK D_RAW.SADB.TASK_PROCESS_STNWYB_MSG_DN RESUME;

-- =============================================================================
-- PREREQUISITE: Ensure monitoring table exists (run once before first execution)
-- =============================================================================
/*
CREATE TABLE IF NOT EXISTS D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
    LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME VARCHAR(256) NOT NULL,
    BATCH_ID VARCHAR(100) NOT NULL,
    EXECUTION_STATUS VARCHAR(20) NOT NULL,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    ROWS_PROCESSED NUMBER DEFAULT 0,
    ROWS_INSERTED NUMBER DEFAULT 0,
    ROWS_UPDATED NUMBER DEFAULT 0,
    ROWS_DELETED NUMBER DEFAULT 0,
    ERROR_MESSAGE VARCHAR(4000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
*/

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'STNWYB_MSG_DN%' IN SCHEMA D_BRONZE.SADB;
-- SHOW STREAMS LIKE 'STNWYB_MSG_DN%' IN SCHEMA D_RAW.SADB;
-- SHOW TASKS LIKE 'TASK_PROCESS_STNWYB_MSG_DN%' IN SCHEMA D_RAW.SADB;
-- CALL D_RAW.SADB.SP_PROCESS_STNWYB_MSG_DN();
-- SELECT * FROM D_BRONZE.MONITORING.CDC_EXECUTION_LOG WHERE TABLE_NAME = 'STNWYB_MSG_DN' ORDER BY CREATED_AT DESC LIMIT 10;
