/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE
================================================================================
Source Table : D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE
Target Table : D_BRONZE.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE
Stream       : D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE_HIST_STREAM
Procedure    : D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE()
Task         : D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE
Primary Key  : WYSD_DTCTN_DEVICE_VRSN_ID (Single)
Total Columns: 35 source + 6 CDC metadata = 41
Filter       : NONE (no purge filter required for EHMS schema)
================================================================================
VERSION      : v1.0
DATE         : 2026-03-17
CHANGES      :
  - Added execution logging to D_BRONZE.MONITORING.CDC_EXECUTION_LOG
  - Staleness detection via SELECT COUNT(*) WHERE 1=0 pattern
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE OR ALTER TABLE D_BRONZE.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE (
    WYSD_DTCTN_DEVICE_VRSN_ID NUMBER(18,0) NOT NULL,
    CREATE_USER_ID VARCHAR(32),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    UPDATE_USER_ID VARCHAR(32),
    ASSET_CD VARCHAR(16),
    FIXED_PLANT_ASSET_ID NUMBER(18,0),
    EFCTV_TMS TIMESTAMP_NTZ(0),
    DEVICE_LONG_ENGLSH_NM VARCHAR(320),
    DEVICE_SHORT_ENGLSH_NM VARCHAR(40),
    MLPST_NBR NUMBER(8,3),
    TIME_CD VARCHAR(8),
    TRACK_CD VARCHAR(320),
    REGION_ID NUMBER(18,0),
    SBDVSN_ID NUMBER(4,0),
    SBDVSN_LONG_ENGLSH_NM VARCHAR(320),
    SBDVSN_SHORT_ENGLSH_NM VARCHAR(40),
    SBDVSN_LOW_MILE_ORNTN_CD VARCHAR(20),
    SBDVSN_HIGH_MILE_ORNTN_CD VARCHAR(20),
    EXPRY_TMS TIMESTAMP_NTZ(0),
    SCAC_CD VARCHAR(16),
    FSAC_CD VARCHAR(20),
    TRNDNG_DRCTN VARCHAR(8),
    DST VARCHAR(40),
    WARM_ALARM_DIRECTION VARCHAR(8),
    REPORTING_LATENCY NUMBER(5,0),
    WARM_TERMINAL_ALARM_DIRECTION VARCHAR(8),
    TRACK_BUCKLE_TRIGGER_DRCTN VARCHAR(8),
    IS_WIND VARCHAR(8),
    TRACK_BUCKLE_GRADE_DTCTRS VARCHAR(800),
    SOFTWARE_VERSION VARCHAR(40),
    HARDWARE_VERSION VARCHAR(40),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ,
    IS_DELETED BOOLEAN,
    RECORD_CREATED_AT TIMESTAMP_NTZ,
    RECORD_UPDATED_AT TIMESTAMP_NTZ,
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    SNW_OPERATION_OWNER VARCHAR(256),

    PRIMARY KEY (WYSD_DTCTN_DEVICE_VRSN_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE_HIST_STREAM
ON TABLE D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing (ENHANCED v1)
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_rows_inserted NUMBER DEFAULT 0;
    v_rows_updated NUMBER DEFAULT 0;
    v_rows_deleted NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
    v_start_time TIMESTAMP_NTZ;
    v_end_time TIMESTAMP_NTZ;
    v_execution_status VARCHAR DEFAULT 'SUCCESS';
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    v_start_time := CURRENT_TIMESTAMP();
    
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE_HIST_STREAM
        WHERE 1=0;
        v_stream_stale := FALSE;
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        v_execution_status := 'RECOVERY';
        
        CREATE OR REPLACE STREAM D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE_HIST_STREAM
        ON TABLE D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE AS tgt
        USING (
            SELECT src.*, 'INSERT' AS CDC_OP, :v_batch_id AS BATCH_ID
            FROM D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE_HIST_STREAM src
        ) AS src
        ON tgt.WYSD_DTCTN_DEVICE_VRSN_ID = src.WYSD_DTCTN_DEVICE_VRSN_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.CREATE_USER_ID = src.CREATE_USER_ID, tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS, tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.ASSET_CD = src.ASSET_CD, tgt.FIXED_PLANT_ASSET_ID = src.FIXED_PLANT_ASSET_ID,
            tgt.EFCTV_TMS = src.EFCTV_TMS, tgt.DEVICE_LONG_ENGLSH_NM = src.DEVICE_LONG_ENGLSH_NM,
            tgt.DEVICE_SHORT_ENGLSH_NM = src.DEVICE_SHORT_ENGLSH_NM, tgt.MLPST_NBR = src.MLPST_NBR,
            tgt.TIME_CD = src.TIME_CD, tgt.TRACK_CD = src.TRACK_CD,
            tgt.REGION_ID = src.REGION_ID, tgt.SBDVSN_ID = src.SBDVSN_ID,
            tgt.SBDVSN_LONG_ENGLSH_NM = src.SBDVSN_LONG_ENGLSH_NM, tgt.SBDVSN_SHORT_ENGLSH_NM = src.SBDVSN_SHORT_ENGLSH_NM,
            tgt.SBDVSN_LOW_MILE_ORNTN_CD = src.SBDVSN_LOW_MILE_ORNTN_CD, tgt.SBDVSN_HIGH_MILE_ORNTN_CD = src.SBDVSN_HIGH_MILE_ORNTN_CD,
            tgt.EXPRY_TMS = src.EXPRY_TMS, tgt.SCAC_CD = src.SCAC_CD, tgt.FSAC_CD = src.FSAC_CD,
            tgt.TRNDNG_DRCTN = src.TRNDNG_DRCTN, tgt.DST = src.DST,
            tgt.WARM_ALARM_DIRECTION = src.WARM_ALARM_DIRECTION, tgt.REPORTING_LATENCY = src.REPORTING_LATENCY,
            tgt.WARM_TERMINAL_ALARM_DIRECTION = src.WARM_TERMINAL_ALARM_DIRECTION,
            tgt.TRACK_BUCKLE_TRIGGER_DRCTN = src.TRACK_BUCKLE_TRIGGER_DRCTN, tgt.IS_WIND = src.IS_WIND,
            tgt.TRACK_BUCKLE_GRADE_DTCTRS = src.TRACK_BUCKLE_GRADE_DTCTRS,
            tgt.SOFTWARE_VERSION = src.SOFTWARE_VERSION, tgt.HARDWARE_VERSION = src.HARDWARE_VERSION,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE, tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED', tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE, tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(), tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            WYSD_DTCTN_DEVICE_VRSN_ID, CREATE_USER_ID, RECORD_CREATE_TMS, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            ASSET_CD, FIXED_PLANT_ASSET_ID, EFCTV_TMS, DEVICE_LONG_ENGLSH_NM, DEVICE_SHORT_ENGLSH_NM,
            MLPST_NBR, TIME_CD, TRACK_CD, REGION_ID, SBDVSN_ID,
            SBDVSN_LONG_ENGLSH_NM, SBDVSN_SHORT_ENGLSH_NM, SBDVSN_LOW_MILE_ORNTN_CD, SBDVSN_HIGH_MILE_ORNTN_CD,
            EXPRY_TMS, SCAC_CD, FSAC_CD, TRNDNG_DRCTN, DST,
            WARM_ALARM_DIRECTION, REPORTING_LATENCY, WARM_TERMINAL_ALARM_DIRECTION,
            TRACK_BUCKLE_TRIGGER_DRCTN, IS_WIND, TRACK_BUCKLE_GRADE_DTCTRS, SOFTWARE_VERSION, HARDWARE_VERSION,
            SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.WYSD_DTCTN_DEVICE_VRSN_ID, src.CREATE_USER_ID, src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.UPDATE_USER_ID,
            src.ASSET_CD, src.FIXED_PLANT_ASSET_ID, src.EFCTV_TMS, src.DEVICE_LONG_ENGLSH_NM, src.DEVICE_SHORT_ENGLSH_NM,
            src.MLPST_NBR, src.TIME_CD, src.TRACK_CD, src.REGION_ID, src.SBDVSN_ID,
            src.SBDVSN_LONG_ENGLSH_NM, src.SBDVSN_SHORT_ENGLSH_NM, src.SBDVSN_LOW_MILE_ORNTN_CD, src.SBDVSN_HIGH_MILE_ORNTN_CD,
            src.EXPRY_TMS, src.SCAC_CD, src.FSAC_CD, src.TRNDNG_DRCTN, src.DST,
            src.WARM_ALARM_DIRECTION, src.REPORTING_LATENCY, src.WARM_TERMINAL_ALARM_DIRECTION,
            src.TRACK_BUCKLE_TRIGGER_DRCTN, src.IS_WIND, src.TRACK_BUCKLE_GRADE_DTCTRS, src.SOFTWARE_VERSION, src.HARDWARE_VERSION,
            src.SNW_OPERATION_TYPE, src.SNW_OPERATION_OWNER, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        v_end_time := CURRENT_TIMESTAMP();
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ERROR_MESSAGE, CREATED_AT) VALUES ('EHMSAPP_DTQ_WYSD_DTCTN_DEVICE', :v_batch_id, 'RECOVERY', :v_start_time, :v_end_time, :v_rows_merged, :v_rows_merged, 0, 0, :v_error_msg, CURRENT_TIMESTAMP());
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE AS
    SELECT 
        WYSD_DTCTN_DEVICE_VRSN_ID, CREATE_USER_ID, RECORD_CREATE_TMS, RECORD_UPDATE_TMS, UPDATE_USER_ID,
        ASSET_CD, FIXED_PLANT_ASSET_ID, EFCTV_TMS, DEVICE_LONG_ENGLSH_NM, DEVICE_SHORT_ENGLSH_NM,
        MLPST_NBR, TIME_CD, TRACK_CD, REGION_ID, SBDVSN_ID,
        SBDVSN_LONG_ENGLSH_NM, SBDVSN_SHORT_ENGLSH_NM, SBDVSN_LOW_MILE_ORNTN_CD, SBDVSN_HIGH_MILE_ORNTN_CD,
        EXPRY_TMS, SCAC_CD, FSAC_CD, TRNDNG_DRCTN, DST,
        WARM_ALARM_DIRECTION, REPORTING_LATENCY, WARM_TERMINAL_ALARM_DIRECTION,
        TRACK_BUCKLE_TRIGGER_DRCTN, IS_WIND, TRACK_BUCKLE_GRADE_DTCTRS, SOFTWARE_VERSION, HARDWARE_VERSION,
        SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE;
        v_end_time := CURRENT_TIMESTAMP();
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ERROR_MESSAGE, CREATED_AT) VALUES ('EHMSAPP_DTQ_WYSD_DTCTN_DEVICE', :v_batch_id, 'NO_DATA', :v_start_time, :v_end_time, 0, 0, 0, 0, NULL, CURRENT_TIMESTAMP());
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    SELECT 
        COUNT(CASE WHEN CDC_ACTION = 'INSERT' AND CDC_IS_UPDATE = FALSE THEN 1 END),
        COUNT(CASE WHEN CDC_ACTION = 'INSERT' AND CDC_IS_UPDATE = TRUE THEN 1 END),
        COUNT(CASE WHEN CDC_ACTION = 'DELETE' AND CDC_IS_UPDATE = FALSE THEN 1 END)
    INTO v_rows_inserted, v_rows_updated, v_rows_deleted
    FROM _CDC_STAGING_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE;
    
    MERGE INTO D_BRONZE.EHMS.EHMSAPP_DTQ_WYSD_DTCTN_DEVICE AS tgt
    USING (
        SELECT 
            WYSD_DTCTN_DEVICE_VRSN_ID, CREATE_USER_ID, RECORD_CREATE_TMS, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            ASSET_CD, FIXED_PLANT_ASSET_ID, EFCTV_TMS, DEVICE_LONG_ENGLSH_NM, DEVICE_SHORT_ENGLSH_NM,
            MLPST_NBR, TIME_CD, TRACK_CD, REGION_ID, SBDVSN_ID,
            SBDVSN_LONG_ENGLSH_NM, SBDVSN_SHORT_ENGLSH_NM, SBDVSN_LOW_MILE_ORNTN_CD, SBDVSN_HIGH_MILE_ORNTN_CD,
            EXPRY_TMS, SCAC_CD, FSAC_CD, TRNDNG_DRCTN, DST,
            WARM_ALARM_DIRECTION, REPORTING_LATENCY, WARM_TERMINAL_ALARM_DIRECTION,
            TRACK_BUCKLE_TRIGGER_DRCTN, IS_WIND, TRACK_BUCKLE_GRADE_DTCTRS, SOFTWARE_VERSION, HARDWARE_VERSION,
            SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_ACTION, CDC_IS_UPDATE, ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE
    ) AS src
    ON tgt.WYSD_DTCTN_DEVICE_VRSN_ID = src.WYSD_DTCTN_DEVICE_VRSN_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.CREATE_USER_ID = src.CREATE_USER_ID, tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS, tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.ASSET_CD = src.ASSET_CD, tgt.FIXED_PLANT_ASSET_ID = src.FIXED_PLANT_ASSET_ID,
            tgt.EFCTV_TMS = src.EFCTV_TMS, tgt.DEVICE_LONG_ENGLSH_NM = src.DEVICE_LONG_ENGLSH_NM,
            tgt.DEVICE_SHORT_ENGLSH_NM = src.DEVICE_SHORT_ENGLSH_NM, tgt.MLPST_NBR = src.MLPST_NBR,
            tgt.TIME_CD = src.TIME_CD, tgt.TRACK_CD = src.TRACK_CD,
            tgt.REGION_ID = src.REGION_ID, tgt.SBDVSN_ID = src.SBDVSN_ID,
            tgt.SBDVSN_LONG_ENGLSH_NM = src.SBDVSN_LONG_ENGLSH_NM, tgt.SBDVSN_SHORT_ENGLSH_NM = src.SBDVSN_SHORT_ENGLSH_NM,
            tgt.SBDVSN_LOW_MILE_ORNTN_CD = src.SBDVSN_LOW_MILE_ORNTN_CD, tgt.SBDVSN_HIGH_MILE_ORNTN_CD = src.SBDVSN_HIGH_MILE_ORNTN_CD,
            tgt.EXPRY_TMS = src.EXPRY_TMS, tgt.SCAC_CD = src.SCAC_CD, tgt.FSAC_CD = src.FSAC_CD,
            tgt.TRNDNG_DRCTN = src.TRNDNG_DRCTN, tgt.DST = src.DST,
            tgt.WARM_ALARM_DIRECTION = src.WARM_ALARM_DIRECTION, tgt.REPORTING_LATENCY = src.REPORTING_LATENCY,
            tgt.WARM_TERMINAL_ALARM_DIRECTION = src.WARM_TERMINAL_ALARM_DIRECTION,
            tgt.TRACK_BUCKLE_TRIGGER_DRCTN = src.TRACK_BUCKLE_TRIGGER_DRCTN, tgt.IS_WIND = src.IS_WIND,
            tgt.TRACK_BUCKLE_GRADE_DTCTRS = src.TRACK_BUCKLE_GRADE_DTCTRS,
            tgt.SOFTWARE_VERSION = src.SOFTWARE_VERSION, tgt.HARDWARE_VERSION = src.HARDWARE_VERSION,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE, tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE', tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE, tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(), tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE', tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE, tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(), tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.CREATE_USER_ID = src.CREATE_USER_ID, tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS, tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.ASSET_CD = src.ASSET_CD, tgt.FIXED_PLANT_ASSET_ID = src.FIXED_PLANT_ASSET_ID,
            tgt.EFCTV_TMS = src.EFCTV_TMS, tgt.DEVICE_LONG_ENGLSH_NM = src.DEVICE_LONG_ENGLSH_NM,
            tgt.DEVICE_SHORT_ENGLSH_NM = src.DEVICE_SHORT_ENGLSH_NM, tgt.MLPST_NBR = src.MLPST_NBR,
            tgt.TIME_CD = src.TIME_CD, tgt.TRACK_CD = src.TRACK_CD,
            tgt.REGION_ID = src.REGION_ID, tgt.SBDVSN_ID = src.SBDVSN_ID,
            tgt.SBDVSN_LONG_ENGLSH_NM = src.SBDVSN_LONG_ENGLSH_NM, tgt.SBDVSN_SHORT_ENGLSH_NM = src.SBDVSN_SHORT_ENGLSH_NM,
            tgt.SBDVSN_LOW_MILE_ORNTN_CD = src.SBDVSN_LOW_MILE_ORNTN_CD, tgt.SBDVSN_HIGH_MILE_ORNTN_CD = src.SBDVSN_HIGH_MILE_ORNTN_CD,
            tgt.EXPRY_TMS = src.EXPRY_TMS, tgt.SCAC_CD = src.SCAC_CD, tgt.FSAC_CD = src.FSAC_CD,
            tgt.TRNDNG_DRCTN = src.TRNDNG_DRCTN, tgt.DST = src.DST,
            tgt.WARM_ALARM_DIRECTION = src.WARM_ALARM_DIRECTION, tgt.REPORTING_LATENCY = src.REPORTING_LATENCY,
            tgt.WARM_TERMINAL_ALARM_DIRECTION = src.WARM_TERMINAL_ALARM_DIRECTION,
            tgt.TRACK_BUCKLE_TRIGGER_DRCTN = src.TRACK_BUCKLE_TRIGGER_DRCTN, tgt.IS_WIND = src.IS_WIND,
            tgt.TRACK_BUCKLE_GRADE_DTCTRS = src.TRACK_BUCKLE_GRADE_DTCTRS,
            tgt.SOFTWARE_VERSION = src.SOFTWARE_VERSION, tgt.HARDWARE_VERSION = src.HARDWARE_VERSION,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE, tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT', tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE, tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(), tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            WYSD_DTCTN_DEVICE_VRSN_ID, CREATE_USER_ID, RECORD_CREATE_TMS, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            ASSET_CD, FIXED_PLANT_ASSET_ID, EFCTV_TMS, DEVICE_LONG_ENGLSH_NM, DEVICE_SHORT_ENGLSH_NM,
            MLPST_NBR, TIME_CD, TRACK_CD, REGION_ID, SBDVSN_ID,
            SBDVSN_LONG_ENGLSH_NM, SBDVSN_SHORT_ENGLSH_NM, SBDVSN_LOW_MILE_ORNTN_CD, SBDVSN_HIGH_MILE_ORNTN_CD,
            EXPRY_TMS, SCAC_CD, FSAC_CD, TRNDNG_DRCTN, DST,
            WARM_ALARM_DIRECTION, REPORTING_LATENCY, WARM_TERMINAL_ALARM_DIRECTION,
            TRACK_BUCKLE_TRIGGER_DRCTN, IS_WIND, TRACK_BUCKLE_GRADE_DTCTRS, SOFTWARE_VERSION, HARDWARE_VERSION,
            SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.WYSD_DTCTN_DEVICE_VRSN_ID, src.CREATE_USER_ID, src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.UPDATE_USER_ID,
            src.ASSET_CD, src.FIXED_PLANT_ASSET_ID, src.EFCTV_TMS, src.DEVICE_LONG_ENGLSH_NM, src.DEVICE_SHORT_ENGLSH_NM,
            src.MLPST_NBR, src.TIME_CD, src.TRACK_CD, src.REGION_ID, src.SBDVSN_ID,
            src.SBDVSN_LONG_ENGLSH_NM, src.SBDVSN_SHORT_ENGLSH_NM, src.SBDVSN_LOW_MILE_ORNTN_CD, src.SBDVSN_HIGH_MILE_ORNTN_CD,
            src.EXPRY_TMS, src.SCAC_CD, src.FSAC_CD, src.TRNDNG_DRCTN, src.DST,
            src.WARM_ALARM_DIRECTION, src.REPORTING_LATENCY, src.WARM_TERMINAL_ALARM_DIRECTION,
            src.TRACK_BUCKLE_TRIGGER_DRCTN, src.IS_WIND, src.TRACK_BUCKLE_GRADE_DTCTRS, src.SOFTWARE_VERSION, src.HARDWARE_VERSION,
            src.SNW_OPERATION_TYPE, src.SNW_OPERATION_OWNER, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    v_end_time := CURRENT_TIMESTAMP();
    DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE;
    
    INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ERROR_MESSAGE, CREATED_AT) VALUES ('EHMSAPP_DTQ_WYSD_DTCTN_DEVICE', :v_batch_id, 'SUCCESS', :v_start_time, :v_end_time, :v_rows_merged, :v_rows_inserted, :v_rows_updated, :v_rows_deleted, NULL, CURRENT_TIMESTAMP());
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes (I:' || v_rows_inserted || ' U:' || v_rows_updated || ' D:' || v_rows_deleted || '). Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        v_end_time := CURRENT_TIMESTAMP();
        v_error_msg := SQLERRM;
        DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE;
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ERROR_MESSAGE, CREATED_AT) VALUES ('EHMSAPP_DTQ_WYSD_DTCTN_DEVICE', :v_batch_id, 'ERROR', :v_start_time, :v_end_time, 0, 0, 0, 0, :v_error_msg, CURRENT_TIMESTAMP());
        RETURN 'ERROR: ' || v_error_msg || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process EHMSAPP_DTQ_WYSD_DTCTN_DEVICE_BASE CDC changes into data preservation table'
AS
    CALL D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE();

ALTER TASK D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'EHMSAPP_DTQ_WYSD_DTCTN_DEVICE%' IN SCHEMA D_BRONZE.EHMS;
-- SHOW STREAMS LIKE 'EHMSAPP_DTQ_WYSD_DTCTN_DEVICE%' IN SCHEMA D_RAW.EHMS;
-- SHOW TASKS LIKE 'TASK_PROCESS_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE%' IN SCHEMA D_RAW.EHMS;
-- CALL D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_WYSD_DTCTN_DEVICE();
