/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE
================================================================================
Source Table : D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE
Target Table : D_BRONZE.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN
Stream       : D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE_HIST_STREAM
Procedure    : D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_DTCTD_TRAIN()
Task         : D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_DTCTD_TRAIN
Primary Key  : DTCTD_TRAIN_ID (Single)
Total Columns: 73 source + 6 CDC metadata = 79
Filter       : NONE (no purge filter required for EHMS schema)
================================================================================
VERSION      : v1.0
DATE         : 2026-03-17
CHANGES      :
  - Added execution logging to D_BRONZE.MONITORING.CDC_EXECUTION_LOG
  - Staleness detection via SELECT COUNT(*) WHERE 1=0 pattern
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE OR ALTER TABLE D_BRONZE.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN (
    DTCTD_TRAIN_ID NUMBER(18,0) NOT NULL,
    CREATE_USER_ID VARCHAR(32),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    UPDATE_USER_ID VARCHAR(32),
    PSNG_SMRY_ID NUMBER(18,0),
    SOURCE_CREATE_TMS TIMESTAMP_NTZ(0),
    SOURCE_UPDATE_TMS TIMESTAMP_NTZ(0),
    PSNG_START_TMS TIMESTAMP_NTZ(0),
    RPRTD_AEI_ANTN_0_QTY NUMBER(3,0),
    RPRTD_AEI_ANTN_1_QTY NUMBER(3,0),
    RPRTD_AEI_GOOD_TAG_EQPMNT_QTY NUMBER(3,0),
    RPRTD_AEI_INVLD_TAG_EQPMNT_QTY NUMBER(3,0),
    RPRTD_AEI_ONE_TAG_EQPMNT_QTY NUMBER(3,0),
    RPRTD_AEI_PHNTM_TAG_QTY NUMBER(3,0),
    RPRTD_ALARM_COUNT_QTY NUMBER(4,0),
    RPRTD_AMBNT_TMPRTR_QTY NUMBER(5,2),
    RPRTD_AXLE_QTY NUMBER(4,0),
    RPRTD_CAR_AXLE_QTY NUMBER(4,0),
    RPRTD_CAR_GROSS_WEIGHT_QTY NUMBER(7,2),
    RPRTD_CAR_QTY NUMBER(4,0),
    RPRTD_DAY_INDEX_NBR NUMBER(3,0),
    RPRTD_EOT_MARK_CD VARCHAR(16),
    RPRTD_EOT_EQPMNT_NBR VARCHAR(40),
    RPRTD_INTGRT_COUNT_QTY NUMBER(3,0),
    RPRTD_LCMTV_AXLE_QTY NUMBER(4,0),
    RPRTD_LCMTV_GROSS_WEIGHT_QTY NUMBER(7,2),
    RPRTD_LCMTV_QTY NUMBER(2,0),
    RPRTD_RAIL_PRCSD_CD VARCHAR(4),
    RPRTD_TEST_TRAIN_CD NUMBER(1,0),
    RPRTD_TRAIN_ARVL_SPEED_QTY NUMBER(5,2),
    RPRTD_TRAIN_AVG_SPEED_QTY NUMBER(5,2),
    RPRTD_TRAIN_DPRTR_SPEED_QTY NUMBER(5,2),
    RPRTD_TRAIN_DRCTN_CD VARCHAR(20),
    RPRTD_TRAIN_LENGTH_QTY NUMBER(10,0),
    RPRTD_UNDNTF_AXLE_QTY NUMBER(4,0),
    RPRTD_WRNG_COUNT_QTY NUMBER(3,0),
    RPRTD_INTRNL_TMPRTR_1_QTY NUMBER(5,2),
    RPRTD_INTRNL_TMPRTR_2_QTY NUMBER(5,2),
    RPRTD_RLTV_HMDTY_QTY NUMBER(5,2),
    RPRTD_TRAIN_SQNC_NBR NUMBER(5,0),
    VRFCTN_CD VARCHAR(20),
    VRFD_BY_DTCTD_TRAIN_ID NUMBER(18,0),
    VRFD_CAR_AXLE_QTY NUMBER(4,0),
    VRFD_DATA_VLDTN_RESULT_CD NUMBER(1,0),
    VRFD_LCMTV_AXLE_QTY NUMBER(4,0),
    VRFD_OPTRN_ID NUMBER(18,0),
    VRFD_OPTRN_LEG_ID NUMBER(18,0),
    VRFD_OPTRN_LEG_NM VARCHAR(32),
    VRFD_OPTRN_NM VARCHAR(32),
    VRFD_TRAIN_CNST_SMRY_ID NUMBER(18,0),
    VRFD_TRAIN_DRCTN_CD VARCHAR(20),
    VRFD_TRAIN_KIND_CD VARCHAR(16),
    VRFD_TRAIN_TYPE_CD VARCHAR(16),
    MXM_DYNMC_IMPACT_FORCE_QTY NUMBER(6,3),
    MXM_LTRL_PEAK_FORCE_QTY NUMBER(6,3),
    MXM_TRUCK_HNTNG_INDEX_QTY NUMBER(6,3),
    MXM_VRTCL_PEAK_FORCE_QTY NUMBER(6,3),
    MXM_VRTCL_RATIO_PRCNTG_QTY NUMBER(5,2),
    MAX_PEAK_AT50_QTY NUMBER(6,3),
    MAX_RATIO_AT50_QTY NUMBER(6,3),
    PRVS_TRAIN_NM VARCHAR(32),
    RPRTD_BTRY_VLTG_QTY NUMBER(4,1),
    RPRTD_TOTAL_EQPMNT_QTY NUMBER(3,0),
    PRVS_TRAIN_PRFL_NM VARCHAR(32),
    VRFD_CAR_QTY NUMBER(4,0),
    VRFD_LCMTV_QTY NUMBER(2,0),
    PSNG_SMRY_TMS_IN_ET TIMESTAMP_NTZ(0),
    ENGINEER_NM VARCHAR(244),
    CONDUCTOR_NM VARCHAR(244),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ,
    IS_DELETED BOOLEAN,
    RECORD_CREATED_AT TIMESTAMP_NTZ,
    RECORD_UPDATED_AT TIMESTAMP_NTZ,
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    SNW_OPERATION_OWNER VARCHAR(256),

    PRIMARY KEY (DTCTD_TRAIN_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE_HIST_STREAM
ON TABLE D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for EHMSAPP_DTQ_DTCTD_TRAIN_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing (ENHANCED v1)
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_DTCTD_TRAIN()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_rows_inserted NUMBER DEFAULT 0;
    v_rows_updated NUMBER DEFAULT 0;
    v_rows_deleted NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
    v_start_time TIMESTAMP_NTZ;
    v_end_time TIMESTAMP_NTZ;
    v_execution_status VARCHAR DEFAULT 'SUCCESS';
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    v_start_time := CURRENT_TIMESTAMP();
    
    -- =========================================================================
    -- CHECK 1: Detect if stream is stale (happens after IDMC truncate/reload)
    -- =========================================================================
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        v_execution_status := 'RECOVERY';
        
        CREATE OR REPLACE STREAM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE_HIST_STREAM
        ON TABLE D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE_HIST_STREAM src
        ) AS src
        ON tgt.DTCTD_TRAIN_ID = src.DTCTD_TRAIN_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.PSNG_SMRY_ID = src.PSNG_SMRY_ID,
            tgt.SOURCE_CREATE_TMS = src.SOURCE_CREATE_TMS,
            tgt.SOURCE_UPDATE_TMS = src.SOURCE_UPDATE_TMS,
            tgt.PSNG_START_TMS = src.PSNG_START_TMS,
            tgt.RPRTD_AEI_ANTN_0_QTY = src.RPRTD_AEI_ANTN_0_QTY,
            tgt.RPRTD_AEI_ANTN_1_QTY = src.RPRTD_AEI_ANTN_1_QTY,
            tgt.RPRTD_AEI_GOOD_TAG_EQPMNT_QTY = src.RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_INVLD_TAG_EQPMNT_QTY = src.RPRTD_AEI_INVLD_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_ONE_TAG_EQPMNT_QTY = src.RPRTD_AEI_ONE_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_PHNTM_TAG_QTY = src.RPRTD_AEI_PHNTM_TAG_QTY,
            tgt.RPRTD_ALARM_COUNT_QTY = src.RPRTD_ALARM_COUNT_QTY,
            tgt.RPRTD_AMBNT_TMPRTR_QTY = src.RPRTD_AMBNT_TMPRTR_QTY,
            tgt.RPRTD_AXLE_QTY = src.RPRTD_AXLE_QTY,
            tgt.RPRTD_CAR_AXLE_QTY = src.RPRTD_CAR_AXLE_QTY,
            tgt.RPRTD_CAR_GROSS_WEIGHT_QTY = src.RPRTD_CAR_GROSS_WEIGHT_QTY,
            tgt.RPRTD_CAR_QTY = src.RPRTD_CAR_QTY,
            tgt.RPRTD_DAY_INDEX_NBR = src.RPRTD_DAY_INDEX_NBR,
            tgt.RPRTD_EOT_MARK_CD = src.RPRTD_EOT_MARK_CD,
            tgt.RPRTD_EOT_EQPMNT_NBR = src.RPRTD_EOT_EQPMNT_NBR,
            tgt.RPRTD_INTGRT_COUNT_QTY = src.RPRTD_INTGRT_COUNT_QTY,
            tgt.RPRTD_LCMTV_AXLE_QTY = src.RPRTD_LCMTV_AXLE_QTY,
            tgt.RPRTD_LCMTV_GROSS_WEIGHT_QTY = src.RPRTD_LCMTV_GROSS_WEIGHT_QTY,
            tgt.RPRTD_LCMTV_QTY = src.RPRTD_LCMTV_QTY,
            tgt.RPRTD_RAIL_PRCSD_CD = src.RPRTD_RAIL_PRCSD_CD,
            tgt.RPRTD_TEST_TRAIN_CD = src.RPRTD_TEST_TRAIN_CD,
            tgt.RPRTD_TRAIN_ARVL_SPEED_QTY = src.RPRTD_TRAIN_ARVL_SPEED_QTY,
            tgt.RPRTD_TRAIN_AVG_SPEED_QTY = src.RPRTD_TRAIN_AVG_SPEED_QTY,
            tgt.RPRTD_TRAIN_DPRTR_SPEED_QTY = src.RPRTD_TRAIN_DPRTR_SPEED_QTY,
            tgt.RPRTD_TRAIN_DRCTN_CD = src.RPRTD_TRAIN_DRCTN_CD,
            tgt.RPRTD_TRAIN_LENGTH_QTY = src.RPRTD_TRAIN_LENGTH_QTY,
            tgt.RPRTD_UNDNTF_AXLE_QTY = src.RPRTD_UNDNTF_AXLE_QTY,
            tgt.RPRTD_WRNG_COUNT_QTY = src.RPRTD_WRNG_COUNT_QTY,
            tgt.RPRTD_INTRNL_TMPRTR_1_QTY = src.RPRTD_INTRNL_TMPRTR_1_QTY,
            tgt.RPRTD_INTRNL_TMPRTR_2_QTY = src.RPRTD_INTRNL_TMPRTR_2_QTY,
            tgt.RPRTD_RLTV_HMDTY_QTY = src.RPRTD_RLTV_HMDTY_QTY,
            tgt.RPRTD_TRAIN_SQNC_NBR = src.RPRTD_TRAIN_SQNC_NBR,
            tgt.VRFCTN_CD = src.VRFCTN_CD,
            tgt.VRFD_BY_DTCTD_TRAIN_ID = src.VRFD_BY_DTCTD_TRAIN_ID,
            tgt.VRFD_CAR_AXLE_QTY = src.VRFD_CAR_AXLE_QTY,
            tgt.VRFD_DATA_VLDTN_RESULT_CD = src.VRFD_DATA_VLDTN_RESULT_CD,
            tgt.VRFD_LCMTV_AXLE_QTY = src.VRFD_LCMTV_AXLE_QTY,
            tgt.VRFD_OPTRN_ID = src.VRFD_OPTRN_ID,
            tgt.VRFD_OPTRN_LEG_ID = src.VRFD_OPTRN_LEG_ID,
            tgt.VRFD_OPTRN_LEG_NM = src.VRFD_OPTRN_LEG_NM,
            tgt.VRFD_OPTRN_NM = src.VRFD_OPTRN_NM,
            tgt.VRFD_TRAIN_CNST_SMRY_ID = src.VRFD_TRAIN_CNST_SMRY_ID,
            tgt.VRFD_TRAIN_DRCTN_CD = src.VRFD_TRAIN_DRCTN_CD,
            tgt.VRFD_TRAIN_KIND_CD = src.VRFD_TRAIN_KIND_CD,
            tgt.VRFD_TRAIN_TYPE_CD = src.VRFD_TRAIN_TYPE_CD,
            tgt.MXM_DYNMC_IMPACT_FORCE_QTY = src.MXM_DYNMC_IMPACT_FORCE_QTY,
            tgt.MXM_LTRL_PEAK_FORCE_QTY = src.MXM_LTRL_PEAK_FORCE_QTY,
            tgt.MXM_TRUCK_HNTNG_INDEX_QTY = src.MXM_TRUCK_HNTNG_INDEX_QTY,
            tgt.MXM_VRTCL_PEAK_FORCE_QTY = src.MXM_VRTCL_PEAK_FORCE_QTY,
            tgt.MXM_VRTCL_RATIO_PRCNTG_QTY = src.MXM_VRTCL_RATIO_PRCNTG_QTY,
            tgt.MAX_PEAK_AT50_QTY = src.MAX_PEAK_AT50_QTY,
            tgt.MAX_RATIO_AT50_QTY = src.MAX_RATIO_AT50_QTY,
            tgt.PRVS_TRAIN_NM = src.PRVS_TRAIN_NM,
            tgt.RPRTD_BTRY_VLTG_QTY = src.RPRTD_BTRY_VLTG_QTY,
            tgt.RPRTD_TOTAL_EQPMNT_QTY = src.RPRTD_TOTAL_EQPMNT_QTY,
            tgt.PRVS_TRAIN_PRFL_NM = src.PRVS_TRAIN_PRFL_NM,
            tgt.VRFD_CAR_QTY = src.VRFD_CAR_QTY,
            tgt.VRFD_LCMTV_QTY = src.VRFD_LCMTV_QTY,
            tgt.PSNG_SMRY_TMS_IN_ET = src.PSNG_SMRY_TMS_IN_ET,
            tgt.ENGINEER_NM = src.ENGINEER_NM,
            tgt.CONDUCTOR_NM = src.CONDUCTOR_NM,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            DTCTD_TRAIN_ID, CREATE_USER_ID, RECORD_CREATE_TMS, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            PSNG_SMRY_ID, SOURCE_CREATE_TMS, SOURCE_UPDATE_TMS, PSNG_START_TMS,
            RPRTD_AEI_ANTN_0_QTY, RPRTD_AEI_ANTN_1_QTY, RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
            RPRTD_AEI_INVLD_TAG_EQPMNT_QTY, RPRTD_AEI_ONE_TAG_EQPMNT_QTY, RPRTD_AEI_PHNTM_TAG_QTY,
            RPRTD_ALARM_COUNT_QTY, RPRTD_AMBNT_TMPRTR_QTY, RPRTD_AXLE_QTY,
            RPRTD_CAR_AXLE_QTY, RPRTD_CAR_GROSS_WEIGHT_QTY, RPRTD_CAR_QTY,
            RPRTD_DAY_INDEX_NBR, RPRTD_EOT_MARK_CD, RPRTD_EOT_EQPMNT_NBR,
            RPRTD_INTGRT_COUNT_QTY, RPRTD_LCMTV_AXLE_QTY, RPRTD_LCMTV_GROSS_WEIGHT_QTY,
            RPRTD_LCMTV_QTY, RPRTD_RAIL_PRCSD_CD, RPRTD_TEST_TRAIN_CD,
            RPRTD_TRAIN_ARVL_SPEED_QTY, RPRTD_TRAIN_AVG_SPEED_QTY, RPRTD_TRAIN_DPRTR_SPEED_QTY,
            RPRTD_TRAIN_DRCTN_CD, RPRTD_TRAIN_LENGTH_QTY, RPRTD_UNDNTF_AXLE_QTY,
            RPRTD_WRNG_COUNT_QTY, RPRTD_INTRNL_TMPRTR_1_QTY, RPRTD_INTRNL_TMPRTR_2_QTY,
            RPRTD_RLTV_HMDTY_QTY, RPRTD_TRAIN_SQNC_NBR, VRFCTN_CD,
            VRFD_BY_DTCTD_TRAIN_ID, VRFD_CAR_AXLE_QTY, VRFD_DATA_VLDTN_RESULT_CD,
            VRFD_LCMTV_AXLE_QTY, VRFD_OPTRN_ID, VRFD_OPTRN_LEG_ID,
            VRFD_OPTRN_LEG_NM, VRFD_OPTRN_NM, VRFD_TRAIN_CNST_SMRY_ID,
            VRFD_TRAIN_DRCTN_CD, VRFD_TRAIN_KIND_CD, VRFD_TRAIN_TYPE_CD,
            MXM_DYNMC_IMPACT_FORCE_QTY, MXM_LTRL_PEAK_FORCE_QTY, MXM_TRUCK_HNTNG_INDEX_QTY,
            MXM_VRTCL_PEAK_FORCE_QTY, MXM_VRTCL_RATIO_PRCNTG_QTY, MAX_PEAK_AT50_QTY,
            MAX_RATIO_AT50_QTY, PRVS_TRAIN_NM, RPRTD_BTRY_VLTG_QTY,
            RPRTD_TOTAL_EQPMNT_QTY, PRVS_TRAIN_PRFL_NM, VRFD_CAR_QTY,
            VRFD_LCMTV_QTY, PSNG_SMRY_TMS_IN_ET, ENGINEER_NM, CONDUCTOR_NM,
            SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.DTCTD_TRAIN_ID, src.CREATE_USER_ID, src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.UPDATE_USER_ID,
            src.PSNG_SMRY_ID, src.SOURCE_CREATE_TMS, src.SOURCE_UPDATE_TMS, src.PSNG_START_TMS,
            src.RPRTD_AEI_ANTN_0_QTY, src.RPRTD_AEI_ANTN_1_QTY, src.RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
            src.RPRTD_AEI_INVLD_TAG_EQPMNT_QTY, src.RPRTD_AEI_ONE_TAG_EQPMNT_QTY, src.RPRTD_AEI_PHNTM_TAG_QTY,
            src.RPRTD_ALARM_COUNT_QTY, src.RPRTD_AMBNT_TMPRTR_QTY, src.RPRTD_AXLE_QTY,
            src.RPRTD_CAR_AXLE_QTY, src.RPRTD_CAR_GROSS_WEIGHT_QTY, src.RPRTD_CAR_QTY,
            src.RPRTD_DAY_INDEX_NBR, src.RPRTD_EOT_MARK_CD, src.RPRTD_EOT_EQPMNT_NBR,
            src.RPRTD_INTGRT_COUNT_QTY, src.RPRTD_LCMTV_AXLE_QTY, src.RPRTD_LCMTV_GROSS_WEIGHT_QTY,
            src.RPRTD_LCMTV_QTY, src.RPRTD_RAIL_PRCSD_CD, src.RPRTD_TEST_TRAIN_CD,
            src.RPRTD_TRAIN_ARVL_SPEED_QTY, src.RPRTD_TRAIN_AVG_SPEED_QTY, src.RPRTD_TRAIN_DPRTR_SPEED_QTY,
            src.RPRTD_TRAIN_DRCTN_CD, src.RPRTD_TRAIN_LENGTH_QTY, src.RPRTD_UNDNTF_AXLE_QTY,
            src.RPRTD_WRNG_COUNT_QTY, src.RPRTD_INTRNL_TMPRTR_1_QTY, src.RPRTD_INTRNL_TMPRTR_2_QTY,
            src.RPRTD_RLTV_HMDTY_QTY, src.RPRTD_TRAIN_SQNC_NBR, src.VRFCTN_CD,
            src.VRFD_BY_DTCTD_TRAIN_ID, src.VRFD_CAR_AXLE_QTY, src.VRFD_DATA_VLDTN_RESULT_CD,
            src.VRFD_LCMTV_AXLE_QTY, src.VRFD_OPTRN_ID, src.VRFD_OPTRN_LEG_ID,
            src.VRFD_OPTRN_LEG_NM, src.VRFD_OPTRN_NM, src.VRFD_TRAIN_CNST_SMRY_ID,
            src.VRFD_TRAIN_DRCTN_CD, src.VRFD_TRAIN_KIND_CD, src.VRFD_TRAIN_TYPE_CD,
            src.MXM_DYNMC_IMPACT_FORCE_QTY, src.MXM_LTRL_PEAK_FORCE_QTY, src.MXM_TRUCK_HNTNG_INDEX_QTY,
            src.MXM_VRTCL_PEAK_FORCE_QTY, src.MXM_VRTCL_RATIO_PRCNTG_QTY, src.MAX_PEAK_AT50_QTY,
            src.MAX_RATIO_AT50_QTY, src.PRVS_TRAIN_NM, src.RPRTD_BTRY_VLTG_QTY,
            src.RPRTD_TOTAL_EQPMNT_QTY, src.PRVS_TRAIN_PRFL_NM, src.VRFD_CAR_QTY,
            src.VRFD_LCMTV_QTY, src.PSNG_SMRY_TMS_IN_ET, src.ENGINEER_NM, src.CONDUCTOR_NM,
            src.SNW_OPERATION_TYPE, src.SNW_OPERATION_OWNER, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        v_end_time := CURRENT_TIMESTAMP();
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ERROR_MESSAGE, CREATED_AT) VALUES ('EHMSAPP_DTQ_DTCTD_TRAIN', :v_batch_id, 'RECOVERY', :v_start_time, :v_end_time, :v_rows_merged, :v_rows_merged, 0, 0, :v_error_msg, CURRENT_TIMESTAMP());
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_EHMSAPP_DTQ_DTCTD_TRAIN AS
    SELECT 
        DTCTD_TRAIN_ID, CREATE_USER_ID, RECORD_CREATE_TMS, RECORD_UPDATE_TMS, UPDATE_USER_ID,
        PSNG_SMRY_ID, SOURCE_CREATE_TMS, SOURCE_UPDATE_TMS, PSNG_START_TMS,
        RPRTD_AEI_ANTN_0_QTY, RPRTD_AEI_ANTN_1_QTY, RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
        RPRTD_AEI_INVLD_TAG_EQPMNT_QTY, RPRTD_AEI_ONE_TAG_EQPMNT_QTY, RPRTD_AEI_PHNTM_TAG_QTY,
        RPRTD_ALARM_COUNT_QTY, RPRTD_AMBNT_TMPRTR_QTY, RPRTD_AXLE_QTY,
        RPRTD_CAR_AXLE_QTY, RPRTD_CAR_GROSS_WEIGHT_QTY, RPRTD_CAR_QTY,
        RPRTD_DAY_INDEX_NBR, RPRTD_EOT_MARK_CD, RPRTD_EOT_EQPMNT_NBR,
        RPRTD_INTGRT_COUNT_QTY, RPRTD_LCMTV_AXLE_QTY, RPRTD_LCMTV_GROSS_WEIGHT_QTY,
        RPRTD_LCMTV_QTY, RPRTD_RAIL_PRCSD_CD, RPRTD_TEST_TRAIN_CD,
        RPRTD_TRAIN_ARVL_SPEED_QTY, RPRTD_TRAIN_AVG_SPEED_QTY, RPRTD_TRAIN_DPRTR_SPEED_QTY,
        RPRTD_TRAIN_DRCTN_CD, RPRTD_TRAIN_LENGTH_QTY, RPRTD_UNDNTF_AXLE_QTY,
        RPRTD_WRNG_COUNT_QTY, RPRTD_INTRNL_TMPRTR_1_QTY, RPRTD_INTRNL_TMPRTR_2_QTY,
        RPRTD_RLTV_HMDTY_QTY, RPRTD_TRAIN_SQNC_NBR, VRFCTN_CD,
        VRFD_BY_DTCTD_TRAIN_ID, VRFD_CAR_AXLE_QTY, VRFD_DATA_VLDTN_RESULT_CD,
        VRFD_LCMTV_AXLE_QTY, VRFD_OPTRN_ID, VRFD_OPTRN_LEG_ID,
        VRFD_OPTRN_LEG_NM, VRFD_OPTRN_NM, VRFD_TRAIN_CNST_SMRY_ID,
        VRFD_TRAIN_DRCTN_CD, VRFD_TRAIN_KIND_CD, VRFD_TRAIN_TYPE_CD,
        MXM_DYNMC_IMPACT_FORCE_QTY, MXM_LTRL_PEAK_FORCE_QTY, MXM_TRUCK_HNTNG_INDEX_QTY,
        MXM_VRTCL_PEAK_FORCE_QTY, MXM_VRTCL_RATIO_PRCNTG_QTY, MAX_PEAK_AT50_QTY,
        MAX_RATIO_AT50_QTY, PRVS_TRAIN_NM, RPRTD_BTRY_VLTG_QTY,
        RPRTD_TOTAL_EQPMNT_QTY, PRVS_TRAIN_PRFL_NM, VRFD_CAR_QTY,
        VRFD_LCMTV_QTY, PSNG_SMRY_TMS_IN_ET, ENGINEER_NM, CONDUCTOR_NM,
        SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_EHMSAPP_DTQ_DTCTD_TRAIN;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_DTCTD_TRAIN;
        v_end_time := CURRENT_TIMESTAMP();
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ERROR_MESSAGE, CREATED_AT) VALUES ('EHMSAPP_DTQ_DTCTD_TRAIN', :v_batch_id, 'NO_DATA', :v_start_time, :v_end_time, 0, 0, 0, 0, NULL, CURRENT_TIMESTAMP());
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- PRE-MERGE METRICS
    -- =========================================================================
    SELECT 
        COUNT(CASE WHEN CDC_ACTION = 'INSERT' AND CDC_IS_UPDATE = FALSE THEN 1 END),
        COUNT(CASE WHEN CDC_ACTION = 'INSERT' AND CDC_IS_UPDATE = TRUE THEN 1 END),
        COUNT(CASE WHEN CDC_ACTION = 'DELETE' AND CDC_IS_UPDATE = FALSE THEN 1 END)
    INTO v_rows_inserted, v_rows_updated, v_rows_deleted
    FROM _CDC_STAGING_EHMSAPP_DTQ_DTCTD_TRAIN;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.EHMS.EHMSAPP_DTQ_DTCTD_TRAIN AS tgt
    USING (
        SELECT 
            DTCTD_TRAIN_ID, CREATE_USER_ID, RECORD_CREATE_TMS, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            PSNG_SMRY_ID, SOURCE_CREATE_TMS, SOURCE_UPDATE_TMS, PSNG_START_TMS,
            RPRTD_AEI_ANTN_0_QTY, RPRTD_AEI_ANTN_1_QTY, RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
            RPRTD_AEI_INVLD_TAG_EQPMNT_QTY, RPRTD_AEI_ONE_TAG_EQPMNT_QTY, RPRTD_AEI_PHNTM_TAG_QTY,
            RPRTD_ALARM_COUNT_QTY, RPRTD_AMBNT_TMPRTR_QTY, RPRTD_AXLE_QTY,
            RPRTD_CAR_AXLE_QTY, RPRTD_CAR_GROSS_WEIGHT_QTY, RPRTD_CAR_QTY,
            RPRTD_DAY_INDEX_NBR, RPRTD_EOT_MARK_CD, RPRTD_EOT_EQPMNT_NBR,
            RPRTD_INTGRT_COUNT_QTY, RPRTD_LCMTV_AXLE_QTY, RPRTD_LCMTV_GROSS_WEIGHT_QTY,
            RPRTD_LCMTV_QTY, RPRTD_RAIL_PRCSD_CD, RPRTD_TEST_TRAIN_CD,
            RPRTD_TRAIN_ARVL_SPEED_QTY, RPRTD_TRAIN_AVG_SPEED_QTY, RPRTD_TRAIN_DPRTR_SPEED_QTY,
            RPRTD_TRAIN_DRCTN_CD, RPRTD_TRAIN_LENGTH_QTY, RPRTD_UNDNTF_AXLE_QTY,
            RPRTD_WRNG_COUNT_QTY, RPRTD_INTRNL_TMPRTR_1_QTY, RPRTD_INTRNL_TMPRTR_2_QTY,
            RPRTD_RLTV_HMDTY_QTY, RPRTD_TRAIN_SQNC_NBR, VRFCTN_CD,
            VRFD_BY_DTCTD_TRAIN_ID, VRFD_CAR_AXLE_QTY, VRFD_DATA_VLDTN_RESULT_CD,
            VRFD_LCMTV_AXLE_QTY, VRFD_OPTRN_ID, VRFD_OPTRN_LEG_ID,
            VRFD_OPTRN_LEG_NM, VRFD_OPTRN_NM, VRFD_TRAIN_CNST_SMRY_ID,
            VRFD_TRAIN_DRCTN_CD, VRFD_TRAIN_KIND_CD, VRFD_TRAIN_TYPE_CD,
            MXM_DYNMC_IMPACT_FORCE_QTY, MXM_LTRL_PEAK_FORCE_QTY, MXM_TRUCK_HNTNG_INDEX_QTY,
            MXM_VRTCL_PEAK_FORCE_QTY, MXM_VRTCL_RATIO_PRCNTG_QTY, MAX_PEAK_AT50_QTY,
            MAX_RATIO_AT50_QTY, PRVS_TRAIN_NM, RPRTD_BTRY_VLTG_QTY,
            RPRTD_TOTAL_EQPMNT_QTY, PRVS_TRAIN_PRFL_NM, VRFD_CAR_QTY,
            VRFD_LCMTV_QTY, PSNG_SMRY_TMS_IN_ET, ENGINEER_NM, CONDUCTOR_NM,
            SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_ACTION, CDC_IS_UPDATE, ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_EHMSAPP_DTQ_DTCTD_TRAIN
    ) AS src
    ON tgt.DTCTD_TRAIN_ID = src.DTCTD_TRAIN_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.CREATE_USER_ID = src.CREATE_USER_ID, tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS, tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.PSNG_SMRY_ID = src.PSNG_SMRY_ID, tgt.SOURCE_CREATE_TMS = src.SOURCE_CREATE_TMS,
            tgt.SOURCE_UPDATE_TMS = src.SOURCE_UPDATE_TMS, tgt.PSNG_START_TMS = src.PSNG_START_TMS,
            tgt.RPRTD_AEI_ANTN_0_QTY = src.RPRTD_AEI_ANTN_0_QTY, tgt.RPRTD_AEI_ANTN_1_QTY = src.RPRTD_AEI_ANTN_1_QTY,
            tgt.RPRTD_AEI_GOOD_TAG_EQPMNT_QTY = src.RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_INVLD_TAG_EQPMNT_QTY = src.RPRTD_AEI_INVLD_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_ONE_TAG_EQPMNT_QTY = src.RPRTD_AEI_ONE_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_PHNTM_TAG_QTY = src.RPRTD_AEI_PHNTM_TAG_QTY,
            tgt.RPRTD_ALARM_COUNT_QTY = src.RPRTD_ALARM_COUNT_QTY, tgt.RPRTD_AMBNT_TMPRTR_QTY = src.RPRTD_AMBNT_TMPRTR_QTY,
            tgt.RPRTD_AXLE_QTY = src.RPRTD_AXLE_QTY, tgt.RPRTD_CAR_AXLE_QTY = src.RPRTD_CAR_AXLE_QTY,
            tgt.RPRTD_CAR_GROSS_WEIGHT_QTY = src.RPRTD_CAR_GROSS_WEIGHT_QTY, tgt.RPRTD_CAR_QTY = src.RPRTD_CAR_QTY,
            tgt.RPRTD_DAY_INDEX_NBR = src.RPRTD_DAY_INDEX_NBR, tgt.RPRTD_EOT_MARK_CD = src.RPRTD_EOT_MARK_CD,
            tgt.RPRTD_EOT_EQPMNT_NBR = src.RPRTD_EOT_EQPMNT_NBR, tgt.RPRTD_INTGRT_COUNT_QTY = src.RPRTD_INTGRT_COUNT_QTY,
            tgt.RPRTD_LCMTV_AXLE_QTY = src.RPRTD_LCMTV_AXLE_QTY, tgt.RPRTD_LCMTV_GROSS_WEIGHT_QTY = src.RPRTD_LCMTV_GROSS_WEIGHT_QTY,
            tgt.RPRTD_LCMTV_QTY = src.RPRTD_LCMTV_QTY, tgt.RPRTD_RAIL_PRCSD_CD = src.RPRTD_RAIL_PRCSD_CD,
            tgt.RPRTD_TEST_TRAIN_CD = src.RPRTD_TEST_TRAIN_CD, tgt.RPRTD_TRAIN_ARVL_SPEED_QTY = src.RPRTD_TRAIN_ARVL_SPEED_QTY,
            tgt.RPRTD_TRAIN_AVG_SPEED_QTY = src.RPRTD_TRAIN_AVG_SPEED_QTY, tgt.RPRTD_TRAIN_DPRTR_SPEED_QTY = src.RPRTD_TRAIN_DPRTR_SPEED_QTY,
            tgt.RPRTD_TRAIN_DRCTN_CD = src.RPRTD_TRAIN_DRCTN_CD, tgt.RPRTD_TRAIN_LENGTH_QTY = src.RPRTD_TRAIN_LENGTH_QTY,
            tgt.RPRTD_UNDNTF_AXLE_QTY = src.RPRTD_UNDNTF_AXLE_QTY, tgt.RPRTD_WRNG_COUNT_QTY = src.RPRTD_WRNG_COUNT_QTY,
            tgt.RPRTD_INTRNL_TMPRTR_1_QTY = src.RPRTD_INTRNL_TMPRTR_1_QTY, tgt.RPRTD_INTRNL_TMPRTR_2_QTY = src.RPRTD_INTRNL_TMPRTR_2_QTY,
            tgt.RPRTD_RLTV_HMDTY_QTY = src.RPRTD_RLTV_HMDTY_QTY, tgt.RPRTD_TRAIN_SQNC_NBR = src.RPRTD_TRAIN_SQNC_NBR,
            tgt.VRFCTN_CD = src.VRFCTN_CD, tgt.VRFD_BY_DTCTD_TRAIN_ID = src.VRFD_BY_DTCTD_TRAIN_ID,
            tgt.VRFD_CAR_AXLE_QTY = src.VRFD_CAR_AXLE_QTY, tgt.VRFD_DATA_VLDTN_RESULT_CD = src.VRFD_DATA_VLDTN_RESULT_CD,
            tgt.VRFD_LCMTV_AXLE_QTY = src.VRFD_LCMTV_AXLE_QTY, tgt.VRFD_OPTRN_ID = src.VRFD_OPTRN_ID,
            tgt.VRFD_OPTRN_LEG_ID = src.VRFD_OPTRN_LEG_ID, tgt.VRFD_OPTRN_LEG_NM = src.VRFD_OPTRN_LEG_NM,
            tgt.VRFD_OPTRN_NM = src.VRFD_OPTRN_NM, tgt.VRFD_TRAIN_CNST_SMRY_ID = src.VRFD_TRAIN_CNST_SMRY_ID,
            tgt.VRFD_TRAIN_DRCTN_CD = src.VRFD_TRAIN_DRCTN_CD, tgt.VRFD_TRAIN_KIND_CD = src.VRFD_TRAIN_KIND_CD,
            tgt.VRFD_TRAIN_TYPE_CD = src.VRFD_TRAIN_TYPE_CD, tgt.MXM_DYNMC_IMPACT_FORCE_QTY = src.MXM_DYNMC_IMPACT_FORCE_QTY,
            tgt.MXM_LTRL_PEAK_FORCE_QTY = src.MXM_LTRL_PEAK_FORCE_QTY, tgt.MXM_TRUCK_HNTNG_INDEX_QTY = src.MXM_TRUCK_HNTNG_INDEX_QTY,
            tgt.MXM_VRTCL_PEAK_FORCE_QTY = src.MXM_VRTCL_PEAK_FORCE_QTY, tgt.MXM_VRTCL_RATIO_PRCNTG_QTY = src.MXM_VRTCL_RATIO_PRCNTG_QTY,
            tgt.MAX_PEAK_AT50_QTY = src.MAX_PEAK_AT50_QTY, tgt.MAX_RATIO_AT50_QTY = src.MAX_RATIO_AT50_QTY,
            tgt.PRVS_TRAIN_NM = src.PRVS_TRAIN_NM, tgt.RPRTD_BTRY_VLTG_QTY = src.RPRTD_BTRY_VLTG_QTY,
            tgt.RPRTD_TOTAL_EQPMNT_QTY = src.RPRTD_TOTAL_EQPMNT_QTY, tgt.PRVS_TRAIN_PRFL_NM = src.PRVS_TRAIN_PRFL_NM,
            tgt.VRFD_CAR_QTY = src.VRFD_CAR_QTY, tgt.VRFD_LCMTV_QTY = src.VRFD_LCMTV_QTY,
            tgt.PSNG_SMRY_TMS_IN_ET = src.PSNG_SMRY_TMS_IN_ET, tgt.ENGINEER_NM = src.ENGINEER_NM,
            tgt.CONDUCTOR_NM = src.CONDUCTOR_NM, tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER, tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE', tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE, tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(), tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE', tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE, tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(), tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.CREATE_USER_ID = src.CREATE_USER_ID, tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS, tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.PSNG_SMRY_ID = src.PSNG_SMRY_ID, tgt.SOURCE_CREATE_TMS = src.SOURCE_CREATE_TMS,
            tgt.SOURCE_UPDATE_TMS = src.SOURCE_UPDATE_TMS, tgt.PSNG_START_TMS = src.PSNG_START_TMS,
            tgt.RPRTD_AEI_ANTN_0_QTY = src.RPRTD_AEI_ANTN_0_QTY, tgt.RPRTD_AEI_ANTN_1_QTY = src.RPRTD_AEI_ANTN_1_QTY,
            tgt.RPRTD_AEI_GOOD_TAG_EQPMNT_QTY = src.RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_INVLD_TAG_EQPMNT_QTY = src.RPRTD_AEI_INVLD_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_ONE_TAG_EQPMNT_QTY = src.RPRTD_AEI_ONE_TAG_EQPMNT_QTY,
            tgt.RPRTD_AEI_PHNTM_TAG_QTY = src.RPRTD_AEI_PHNTM_TAG_QTY,
            tgt.RPRTD_ALARM_COUNT_QTY = src.RPRTD_ALARM_COUNT_QTY, tgt.RPRTD_AMBNT_TMPRTR_QTY = src.RPRTD_AMBNT_TMPRTR_QTY,
            tgt.RPRTD_AXLE_QTY = src.RPRTD_AXLE_QTY, tgt.RPRTD_CAR_AXLE_QTY = src.RPRTD_CAR_AXLE_QTY,
            tgt.RPRTD_CAR_GROSS_WEIGHT_QTY = src.RPRTD_CAR_GROSS_WEIGHT_QTY, tgt.RPRTD_CAR_QTY = src.RPRTD_CAR_QTY,
            tgt.RPRTD_DAY_INDEX_NBR = src.RPRTD_DAY_INDEX_NBR, tgt.RPRTD_EOT_MARK_CD = src.RPRTD_EOT_MARK_CD,
            tgt.RPRTD_EOT_EQPMNT_NBR = src.RPRTD_EOT_EQPMNT_NBR, tgt.RPRTD_INTGRT_COUNT_QTY = src.RPRTD_INTGRT_COUNT_QTY,
            tgt.RPRTD_LCMTV_AXLE_QTY = src.RPRTD_LCMTV_AXLE_QTY, tgt.RPRTD_LCMTV_GROSS_WEIGHT_QTY = src.RPRTD_LCMTV_GROSS_WEIGHT_QTY,
            tgt.RPRTD_LCMTV_QTY = src.RPRTD_LCMTV_QTY, tgt.RPRTD_RAIL_PRCSD_CD = src.RPRTD_RAIL_PRCSD_CD,
            tgt.RPRTD_TEST_TRAIN_CD = src.RPRTD_TEST_TRAIN_CD, tgt.RPRTD_TRAIN_ARVL_SPEED_QTY = src.RPRTD_TRAIN_ARVL_SPEED_QTY,
            tgt.RPRTD_TRAIN_AVG_SPEED_QTY = src.RPRTD_TRAIN_AVG_SPEED_QTY, tgt.RPRTD_TRAIN_DPRTR_SPEED_QTY = src.RPRTD_TRAIN_DPRTR_SPEED_QTY,
            tgt.RPRTD_TRAIN_DRCTN_CD = src.RPRTD_TRAIN_DRCTN_CD, tgt.RPRTD_TRAIN_LENGTH_QTY = src.RPRTD_TRAIN_LENGTH_QTY,
            tgt.RPRTD_UNDNTF_AXLE_QTY = src.RPRTD_UNDNTF_AXLE_QTY, tgt.RPRTD_WRNG_COUNT_QTY = src.RPRTD_WRNG_COUNT_QTY,
            tgt.RPRTD_INTRNL_TMPRTR_1_QTY = src.RPRTD_INTRNL_TMPRTR_1_QTY, tgt.RPRTD_INTRNL_TMPRTR_2_QTY = src.RPRTD_INTRNL_TMPRTR_2_QTY,
            tgt.RPRTD_RLTV_HMDTY_QTY = src.RPRTD_RLTV_HMDTY_QTY, tgt.RPRTD_TRAIN_SQNC_NBR = src.RPRTD_TRAIN_SQNC_NBR,
            tgt.VRFCTN_CD = src.VRFCTN_CD, tgt.VRFD_BY_DTCTD_TRAIN_ID = src.VRFD_BY_DTCTD_TRAIN_ID,
            tgt.VRFD_CAR_AXLE_QTY = src.VRFD_CAR_AXLE_QTY, tgt.VRFD_DATA_VLDTN_RESULT_CD = src.VRFD_DATA_VLDTN_RESULT_CD,
            tgt.VRFD_LCMTV_AXLE_QTY = src.VRFD_LCMTV_AXLE_QTY, tgt.VRFD_OPTRN_ID = src.VRFD_OPTRN_ID,
            tgt.VRFD_OPTRN_LEG_ID = src.VRFD_OPTRN_LEG_ID, tgt.VRFD_OPTRN_LEG_NM = src.VRFD_OPTRN_LEG_NM,
            tgt.VRFD_OPTRN_NM = src.VRFD_OPTRN_NM, tgt.VRFD_TRAIN_CNST_SMRY_ID = src.VRFD_TRAIN_CNST_SMRY_ID,
            tgt.VRFD_TRAIN_DRCTN_CD = src.VRFD_TRAIN_DRCTN_CD, tgt.VRFD_TRAIN_KIND_CD = src.VRFD_TRAIN_KIND_CD,
            tgt.VRFD_TRAIN_TYPE_CD = src.VRFD_TRAIN_TYPE_CD, tgt.MXM_DYNMC_IMPACT_FORCE_QTY = src.MXM_DYNMC_IMPACT_FORCE_QTY,
            tgt.MXM_LTRL_PEAK_FORCE_QTY = src.MXM_LTRL_PEAK_FORCE_QTY, tgt.MXM_TRUCK_HNTNG_INDEX_QTY = src.MXM_TRUCK_HNTNG_INDEX_QTY,
            tgt.MXM_VRTCL_PEAK_FORCE_QTY = src.MXM_VRTCL_PEAK_FORCE_QTY, tgt.MXM_VRTCL_RATIO_PRCNTG_QTY = src.MXM_VRTCL_RATIO_PRCNTG_QTY,
            tgt.MAX_PEAK_AT50_QTY = src.MAX_PEAK_AT50_QTY, tgt.MAX_RATIO_AT50_QTY = src.MAX_RATIO_AT50_QTY,
            tgt.PRVS_TRAIN_NM = src.PRVS_TRAIN_NM, tgt.RPRTD_BTRY_VLTG_QTY = src.RPRTD_BTRY_VLTG_QTY,
            tgt.RPRTD_TOTAL_EQPMNT_QTY = src.RPRTD_TOTAL_EQPMNT_QTY, tgt.PRVS_TRAIN_PRFL_NM = src.PRVS_TRAIN_PRFL_NM,
            tgt.VRFD_CAR_QTY = src.VRFD_CAR_QTY, tgt.VRFD_LCMTV_QTY = src.VRFD_LCMTV_QTY,
            tgt.PSNG_SMRY_TMS_IN_ET = src.PSNG_SMRY_TMS_IN_ET, tgt.ENGINEER_NM = src.ENGINEER_NM,
            tgt.CONDUCTOR_NM = src.CONDUCTOR_NM, tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_OPERATION_OWNER = src.SNW_OPERATION_OWNER, tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT', tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE, tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(), tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            DTCTD_TRAIN_ID, CREATE_USER_ID, RECORD_CREATE_TMS, RECORD_UPDATE_TMS, UPDATE_USER_ID,
            PSNG_SMRY_ID, SOURCE_CREATE_TMS, SOURCE_UPDATE_TMS, PSNG_START_TMS,
            RPRTD_AEI_ANTN_0_QTY, RPRTD_AEI_ANTN_1_QTY, RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
            RPRTD_AEI_INVLD_TAG_EQPMNT_QTY, RPRTD_AEI_ONE_TAG_EQPMNT_QTY, RPRTD_AEI_PHNTM_TAG_QTY,
            RPRTD_ALARM_COUNT_QTY, RPRTD_AMBNT_TMPRTR_QTY, RPRTD_AXLE_QTY,
            RPRTD_CAR_AXLE_QTY, RPRTD_CAR_GROSS_WEIGHT_QTY, RPRTD_CAR_QTY,
            RPRTD_DAY_INDEX_NBR, RPRTD_EOT_MARK_CD, RPRTD_EOT_EQPMNT_NBR,
            RPRTD_INTGRT_COUNT_QTY, RPRTD_LCMTV_AXLE_QTY, RPRTD_LCMTV_GROSS_WEIGHT_QTY,
            RPRTD_LCMTV_QTY, RPRTD_RAIL_PRCSD_CD, RPRTD_TEST_TRAIN_CD,
            RPRTD_TRAIN_ARVL_SPEED_QTY, RPRTD_TRAIN_AVG_SPEED_QTY, RPRTD_TRAIN_DPRTR_SPEED_QTY,
            RPRTD_TRAIN_DRCTN_CD, RPRTD_TRAIN_LENGTH_QTY, RPRTD_UNDNTF_AXLE_QTY,
            RPRTD_WRNG_COUNT_QTY, RPRTD_INTRNL_TMPRTR_1_QTY, RPRTD_INTRNL_TMPRTR_2_QTY,
            RPRTD_RLTV_HMDTY_QTY, RPRTD_TRAIN_SQNC_NBR, VRFCTN_CD,
            VRFD_BY_DTCTD_TRAIN_ID, VRFD_CAR_AXLE_QTY, VRFD_DATA_VLDTN_RESULT_CD,
            VRFD_LCMTV_AXLE_QTY, VRFD_OPTRN_ID, VRFD_OPTRN_LEG_ID,
            VRFD_OPTRN_LEG_NM, VRFD_OPTRN_NM, VRFD_TRAIN_CNST_SMRY_ID,
            VRFD_TRAIN_DRCTN_CD, VRFD_TRAIN_KIND_CD, VRFD_TRAIN_TYPE_CD,
            MXM_DYNMC_IMPACT_FORCE_QTY, MXM_LTRL_PEAK_FORCE_QTY, MXM_TRUCK_HNTNG_INDEX_QTY,
            MXM_VRTCL_PEAK_FORCE_QTY, MXM_VRTCL_RATIO_PRCNTG_QTY, MAX_PEAK_AT50_QTY,
            MAX_RATIO_AT50_QTY, PRVS_TRAIN_NM, RPRTD_BTRY_VLTG_QTY,
            RPRTD_TOTAL_EQPMNT_QTY, PRVS_TRAIN_PRFL_NM, VRFD_CAR_QTY,
            VRFD_LCMTV_QTY, PSNG_SMRY_TMS_IN_ET, ENGINEER_NM, CONDUCTOR_NM,
            SNW_OPERATION_TYPE, SNW_OPERATION_OWNER, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.DTCTD_TRAIN_ID, src.CREATE_USER_ID, src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.UPDATE_USER_ID,
            src.PSNG_SMRY_ID, src.SOURCE_CREATE_TMS, src.SOURCE_UPDATE_TMS, src.PSNG_START_TMS,
            src.RPRTD_AEI_ANTN_0_QTY, src.RPRTD_AEI_ANTN_1_QTY, src.RPRTD_AEI_GOOD_TAG_EQPMNT_QTY,
            src.RPRTD_AEI_INVLD_TAG_EQPMNT_QTY, src.RPRTD_AEI_ONE_TAG_EQPMNT_QTY, src.RPRTD_AEI_PHNTM_TAG_QTY,
            src.RPRTD_ALARM_COUNT_QTY, src.RPRTD_AMBNT_TMPRTR_QTY, src.RPRTD_AXLE_QTY,
            src.RPRTD_CAR_AXLE_QTY, src.RPRTD_CAR_GROSS_WEIGHT_QTY, src.RPRTD_CAR_QTY,
            src.RPRTD_DAY_INDEX_NBR, src.RPRTD_EOT_MARK_CD, src.RPRTD_EOT_EQPMNT_NBR,
            src.RPRTD_INTGRT_COUNT_QTY, src.RPRTD_LCMTV_AXLE_QTY, src.RPRTD_LCMTV_GROSS_WEIGHT_QTY,
            src.RPRTD_LCMTV_QTY, src.RPRTD_RAIL_PRCSD_CD, src.RPRTD_TEST_TRAIN_CD,
            src.RPRTD_TRAIN_ARVL_SPEED_QTY, src.RPRTD_TRAIN_AVG_SPEED_QTY, src.RPRTD_TRAIN_DPRTR_SPEED_QTY,
            src.RPRTD_TRAIN_DRCTN_CD, src.RPRTD_TRAIN_LENGTH_QTY, src.RPRTD_UNDNTF_AXLE_QTY,
            src.RPRTD_WRNG_COUNT_QTY, src.RPRTD_INTRNL_TMPRTR_1_QTY, src.RPRTD_INTRNL_TMPRTR_2_QTY,
            src.RPRTD_RLTV_HMDTY_QTY, src.RPRTD_TRAIN_SQNC_NBR, src.VRFCTN_CD,
            src.VRFD_BY_DTCTD_TRAIN_ID, src.VRFD_CAR_AXLE_QTY, src.VRFD_DATA_VLDTN_RESULT_CD,
            src.VRFD_LCMTV_AXLE_QTY, src.VRFD_OPTRN_ID, src.VRFD_OPTRN_LEG_ID,
            src.VRFD_OPTRN_LEG_NM, src.VRFD_OPTRN_NM, src.VRFD_TRAIN_CNST_SMRY_ID,
            src.VRFD_TRAIN_DRCTN_CD, src.VRFD_TRAIN_KIND_CD, src.VRFD_TRAIN_TYPE_CD,
            src.MXM_DYNMC_IMPACT_FORCE_QTY, src.MXM_LTRL_PEAK_FORCE_QTY, src.MXM_TRUCK_HNTNG_INDEX_QTY,
            src.MXM_VRTCL_PEAK_FORCE_QTY, src.MXM_VRTCL_RATIO_PRCNTG_QTY, src.MAX_PEAK_AT50_QTY,
            src.MAX_RATIO_AT50_QTY, src.PRVS_TRAIN_NM, src.RPRTD_BTRY_VLTG_QTY,
            src.RPRTD_TOTAL_EQPMNT_QTY, src.PRVS_TRAIN_PRFL_NM, src.VRFD_CAR_QTY,
            src.VRFD_LCMTV_QTY, src.PSNG_SMRY_TMS_IN_ET, src.ENGINEER_NM, src.CONDUCTOR_NM,
            src.SNW_OPERATION_TYPE, src.SNW_OPERATION_OWNER, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    v_end_time := CURRENT_TIMESTAMP();
    DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_DTCTD_TRAIN;
    
    INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ERROR_MESSAGE, CREATED_AT) VALUES ('EHMSAPP_DTQ_DTCTD_TRAIN', :v_batch_id, 'SUCCESS', :v_start_time, :v_end_time, :v_rows_merged, :v_rows_inserted, :v_rows_updated, :v_rows_deleted, NULL, CURRENT_TIMESTAMP());
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes (I:' || v_rows_inserted || ' U:' || v_rows_updated || ' D:' || v_rows_deleted || '). Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        v_end_time := CURRENT_TIMESTAMP();
        v_error_msg := SQLERRM;
        DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_DTCTD_TRAIN;
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME, BATCH_ID, EXECUTION_STATUS, START_TIME, END_TIME, ROWS_PROCESSED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ERROR_MESSAGE, CREATED_AT) VALUES ('EHMSAPP_DTQ_DTCTD_TRAIN', :v_batch_id, 'ERROR', :v_start_time, :v_end_time, 0, 0, 0, 0, :v_error_msg, CURRENT_TIMESTAMP());
        RETURN 'ERROR: ' || v_error_msg || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_DTCTD_TRAIN
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process EHMSAPP_DTQ_DTCTD_TRAIN_BASE CDC changes into data preservation table'
AS
    CALL D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_DTCTD_TRAIN();

ALTER TASK D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_DTCTD_TRAIN RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'EHMSAPP_DTQ_DTCTD_TRAIN%' IN SCHEMA D_BRONZE.EHMS;
-- SHOW STREAMS LIKE 'EHMSAPP_DTQ_DTCTD_TRAIN%' IN SCHEMA D_RAW.EHMS;
-- SHOW TASKS LIKE 'TASK_PROCESS_EHMSAPP_DTQ_DTCTD_TRAIN%' IN SCHEMA D_RAW.EHMS;
-- CALL D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_DTCTD_TRAIN();
