/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE
================================================================================
Source Table : D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE
Target Table : D_BRONZE.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT
Stream       : D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE_HIST_STREAM
Procedure    : D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT()
Task         : D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT
Primary Key  : DTCTD_EQPMNT_CMPNT_ID (Single)
Total Columns: 128 source + 6 CDC metadata = 134
Filter       : NONE (no purge filter required for EHMS schema)
================================================================================
VERSION      : v1.0
DATE         : 2026-03-17
CHANGES      :
  - Added execution logging to D_BRONZE.MONITORING.CDC_EXECUTION_LOG
  - Staleness detection via SELECT COUNT(*) WHERE 1=0 pattern
NOTE         : Largest EHMS table (351M rows). Monitor initial load execution.
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE OR ALTER TABLE D_BRONZE.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT (
    DTCTD_EQPMNT_CMPNT_ID NUMBER(18,0) NOT NULL,
    CREATE_USER_ID VARCHAR(32),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    UPDATE_USER_ID VARCHAR(32),
    DTCTD_EQPMNT_ID NUMBER(18,0),
    SOURCE_CREATE_TMS TIMESTAMP_NTZ(0),
    SOURCE_UPDATE_TMS TIMESTAMP_NTZ(0),
    RPRTD_EQPMNT_CMPNT_NM VARCHAR(40),
    RPRTD_CMPNT_ON_TRAIN_SQNC_NBR NUMBER(4,0),
    RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR NUMBER(4,0),
    RPRTD_CMPNT_ON_PARENT_SQNC_NBR NUMBER(4,0),
    PARENT_DTCTD_EQPMNT_CMPNT_ID NUMBER(18,0),
    RPRTD_AAR_TRUCK_ID VARCHAR(4),
    RPRTD_CMPNT_AXLE_FILE_NM VARCHAR(120),
    RPRTD_CMPNT_SIDE_CD VARCHAR(20),
    RPRTD_WHEEL_TMPRTR_CHNL_1_QTY NUMBER(5,2),
    RPRTD_WHEEL_TMPRTR_CHNL_2_QTY NUMBER(5,2),
    RPRTD_BRNG_HEAT_CHNL_1_QTY NUMBER(5,2),
    RPRTD_BRNG_HEAT_CHNL_2_QTY NUMBER(5,2),
    RPRTD_INVLD_DATA_DSCRPT_TXT VARCHAR(128),
    VRFD_RAIL_SIDE_CD VARCHAR(20),
    VRFD_EQPMNT_CMPNT_LCTN_CD VARCHAR(20),
    RPRTD_ANGLE_OF_ATTACK_QTY NUMBER(6,3),
    RPRTD_BRNG_ALARM_RAIL_1_CD_OLD NUMBER(1,0),
    RPRTD_BRNG_ALARM_RAIL_2_CD_OLD NUMBER(1,0),
    RPRTD_WHL_ALARM_RAIL_1_CD_OLD NUMBER(1,0),
    RPRTD_WHL_ALARM_RAIL_2_CD_OLD NUMBER(1,0),
    RPRTD_DRGNG_EQPMNT_ALARM_CD NUMBER(1,0),
    RPRTD_HIGH_LOAD_ALARM_CD NUMBER(1,0),
    RPRTD_WIDE_LOAD_ALARM_CD NUMBER(1,0),
    RPRTD_BID_DCLRD_CD NUMBER(1,0),
    RPRTD_BID_RAW_CHNL_1_CD NUMBER(1,0),
    RPRTD_BID_RAW_CHNL_2_CD NUMBER(1,0),
    RPRTD_MISS_OPEN_CD NUMBER(1,0),
    RPRTD_TBOGI_CMPNT_SPEED_QTY NUMBER(6,3),
    RPRTD_WPD_CMPNT_SPEED_QTY NUMBER(6,3),
    RPRTD_CMPNT_SUB_CTGRY_CD VARCHAR(8),
    RPRTD_CNFDNC_NBR NUMBER(4,3),
    RPRTD_DEVICE_RLTV_DRCTN_CD NUMBER(1,0),
    RPRTD_CMPNT_PRMRY_SPEED_QTY NUMBER(6,3),
    RPRTD_HNTNG_INDEX_NBR NUMBER(6,3),
    RPRTD_CMPNT_LDNG_SPAN_QTY NUMBER(7,3),
    RPRTD_CMPNT_LENGTH_QTY NUMBER(6,3),
    RPRTD_DSTNC_FROM_PRVCMP_QTY NUMBER(7,3),
    RPRTD_CMPNT_TMPRTR_QTY NUMBER(6,3),
    RPRTD_DRTN_SCNDS_QTY NUMBER(6,3),
    RPRTD_TRCKNG_OFFSET_QTY NUMBER(6,3),
    RPRTD_TRUCK_NMNL_WEIGHT_QTY NUMBER(6,3),
    RPRTD_CMPNT_WEIGHT_QTY NUMBER(6,3),
    WHEEL_SIGMA_CHNL_1_NBR NUMBER(7,4),
    WHEEL_SIGMA_CHNL_2_NBR NUMBER(7,4),
    BRNG_SIGMA_CHNL_1_NBR NUMBER(7,4),
    BRNG_SIGMA_CHNL_2_NBR NUMBER(7,4),
    RPRTD_PITCH_QTY NUMBER(6,3),
    RPRTD_BUILD_UP_TREAD_QTY NUMBER(6,3),
    RPRTD_ECNTRC_FORCE_QTY NUMBER(8,4),
    RPRTD_ECNTRC_VRTN_FORCE_QTY NUMBER(8,4),
    RPRTD_FLANGE_ANGLE_QTY NUMBER(6,3),
    RPRTD_FLANGE_GRDNT_QTY NUMBER(6,3),
    RPRTD_FLANGE_HEIGHT_QTY NUMBER(6,3),
    RPRTD_FLANGE_THCKNS_QTY NUMBER(6,3),
    RPRTD_GRVD_TREAD_LENGTH_QTY NUMBER(6,3),
    RPRTD_LOAD_QTY NUMBER(6,3),
    RPRTD_LTRL_AVRG_LOAD_QTY NUMBER(6,3),
    RPRTD_LTRL_PEAK_LOAD_QTY NUMBER(6,3),
    RPRTD_NEW_AVRG_QTY NUMBER(8,4),
    RPRTD_PEAK_FORCE_QTY NUMBER(6,3),
    RPRTD_RIM_THCKNS_QTY NUMBER(6,3),
    RPRTD_THIN_FLANGE_LENGTH_QTY NUMBER(6,3),
    RPRTD_TREAD_HOLLOW_LENGTH_QTY NUMBER(6,3),
    RPRTD_TREAD_TAPER_LENGTH_QTY NUMBER(6,3),
    RPRTD_VRTCL_FLANGE_QTY NUMBER(6,3),
    RPRTD_GAUGE_QTY NUMBER(6,3),
    RPRTD_TIME_FROM_FIRST_AXLE_QTY NUMBER(9,3),
    RPRTD_LRWHL_DELTA_DMTR_QTY NUMBER(6,3),
    RPRTD_WHEEL_BKTOBK_DSTNC_QTY NUMBER(6,3),
    RPRTD_LRWHL_DELTA_DMTR_CD VARCHAR(4),
    RPRTD_WHEEL_BKTOBK_DSTNC_CD VARCHAR(4),
    RPRTD_ANGLE_OF_ATTACK_CD VARCHAR(4),
    RPRTD_WHEEL_PSTN_ON_RAIL_QTY NUMBER(6,3),
    RPRTD_BRKSHO_UPR_THCKNS_QTY NUMBER(6,3),
    RPRTD_BRKSHO_LWR_THCKNS_QTY NUMBER(6,3),
    RPRTD_FLANGE_HEIGHT_CD VARCHAR(4),
    RPRTD_FLANGE_THCKNS_CD VARCHAR(4),
    RPRTD_RIM_THCKNS_CD VARCHAR(4),
    RPRTD_CMPNT_LENGTH_CD VARCHAR(4),
    RPRTD_TREAD_HOLLOW_LENGTH_CD VARCHAR(4),
    RPRTD_FLANGE_ANGLE_CD VARCHAR(4),
    RPRTD_WHEEL_PSTN_ON_RAIL_CD VARCHAR(4),
    RPRTD_BRKSHO_UPR_THCKNS_CD VARCHAR(4),
    RPRTD_BRKSHO_LWR_THCKNS_CD VARCHAR(4),
    BRNG_SIZE_CLASS_CD VARCHAR(4),
    BRNG_DEFECT_CODE_TXT VARCHAR(36),
    BRNG_DEFECT_RNKNG_CD NUMBER(1,0),
    BRNG_NOISE_PRCSR_QTY NUMBER(4,3),
    BRNG_NOISE_CLSFR_VALUE_QTY NUMBER(6,3),
    BRNG_NON_BRNG_NOISE_CD VARCHAR(20),
    RPRTD_BRNG_ALARM_RAIL_1_CD VARCHAR(4),
    RPRTD_BRNG_ALARM_RAIL_2_CD VARCHAR(4),
    RPRTD_WHEEL_ALARM_RAIL_1_CD VARCHAR(4),
    RPRTD_WHEEL_ALARM_RAIL_2_CD VARCHAR(4),
    RPRTD_TIME_SCNR_OFF_SCNDS_QTY NUMBER(6,3),
    RPRTD_TIME_SCNR_ON_SCNDS_QTY NUMBER(6,3),
    KVALUE_TRN_CH1 NUMBER(7,3),
    KVALUE_TRN_CH2 NUMBER(7,3),
    KVALUE_EQP_CH1 NUMBER(7,3),
    KVALUE_EQP_CH2 NUMBER(7,3),
    TRUCK_OVERLOAD NUMBER(10,3),
    RPRTD_TAPINGPTY_COORD NUMBER(6,3),
    RPRTD_CMPNT_WIDTH_QTY NUMBER(6,3),
    RPRTD_DATA_QUALITY_FLAG NUMBER(1,0),
    RPRTD_LV_RATIO_CRIB1 NUMBER(6,3),
    RPRTD_LV_RATIO_CRIB2 NUMBER(6,3),
    RPRTD_HUNTING_P NUMBER(6,3),
    RPRTD_HUNTING_A NUMBER(6,3),
    RPRTD_HUNTING_F NUMBER(6,3),
    RPRTD_HUNTING_W NUMBER(6,3),
    RPRTD_IAM NUMBER(6,3),
    RPRTD_ROT NUMBER(6,3),
    RPRTD_TE NUMBER(6,3),
    RPRTD_SHIFT NUMBER(6,3),
    RPRTD_AOA NUMBER(6,3),
    RPRTD_TP NUMBER(6,3),
    RPRTD_TRUCKSPACING NUMBER(6,3),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ,
    IS_DELETED BOOLEAN,
    RECORD_CREATED_AT TIMESTAMP_NTZ,
    RECORD_UPDATED_AT TIMESTAMP_NTZ,
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    SNW_OPERATION_OWNER VARCHAR(256),

    PRIMARY KEY (DTCTD_EQPMNT_CMPNT_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE_HIST_STREAM
ON TABLE D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing (ENHANCED v1)
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_rows_inserted NUMBER DEFAULT 0;
    v_rows_updated NUMBER DEFAULT 0;
    v_rows_deleted NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
    v_start_time TIMESTAMP_NTZ;
    v_end_time TIMESTAMP_NTZ;
    v_execution_status VARCHAR DEFAULT 'SUCCESS';
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    v_start_time := CURRENT_TIMESTAMP();
    
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE_HIST_STREAM
        WHERE 1=0;
        v_stream_stale := FALSE;
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    IF (v_stream_stale = TRUE) THEN
        v_execution_status := 'RECOVERY';
        
        CREATE OR REPLACE STREAM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE_HIST_STREAM
        ON TABLE D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT AS tgt
        USING (
            SELECT src.*, 'INSERT' AS CDC_OP, :v_batch_id AS BATCH_ID
            FROM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE_HIST_STREAM src
        ) AS src
        ON tgt.DTCTD_EQPMNT_CMPNT_ID = src.DTCTD_EQPMNT_CMPNT_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.CREATE_USER_ID=src.CREATE_USER_ID,tgt.RECORD_CREATE_TMS=src.RECORD_CREATE_TMS,tgt.RECORD_UPDATE_TMS=src.RECORD_UPDATE_TMS,tgt.UPDATE_USER_ID=src.UPDATE_USER_ID,tgt.DTCTD_EQPMNT_ID=src.DTCTD_EQPMNT_ID,tgt.SOURCE_CREATE_TMS=src.SOURCE_CREATE_TMS,tgt.SOURCE_UPDATE_TMS=src.SOURCE_UPDATE_TMS,tgt.RPRTD_EQPMNT_CMPNT_NM=src.RPRTD_EQPMNT_CMPNT_NM,tgt.RPRTD_CMPNT_ON_TRAIN_SQNC_NBR=src.RPRTD_CMPNT_ON_TRAIN_SQNC_NBR,tgt.RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR=src.RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR,tgt.RPRTD_CMPNT_ON_PARENT_SQNC_NBR=src.RPRTD_CMPNT_ON_PARENT_SQNC_NBR,tgt.PARENT_DTCTD_EQPMNT_CMPNT_ID=src.PARENT_DTCTD_EQPMNT_CMPNT_ID,tgt.RPRTD_AAR_TRUCK_ID=src.RPRTD_AAR_TRUCK_ID,tgt.RPRTD_CMPNT_AXLE_FILE_NM=src.RPRTD_CMPNT_AXLE_FILE_NM,tgt.RPRTD_CMPNT_SIDE_CD=src.RPRTD_CMPNT_SIDE_CD,tgt.RPRTD_WHEEL_TMPRTR_CHNL_1_QTY=src.RPRTD_WHEEL_TMPRTR_CHNL_1_QTY,tgt.RPRTD_WHEEL_TMPRTR_CHNL_2_QTY=src.RPRTD_WHEEL_TMPRTR_CHNL_2_QTY,tgt.RPRTD_BRNG_HEAT_CHNL_1_QTY=src.RPRTD_BRNG_HEAT_CHNL_1_QTY,tgt.RPRTD_BRNG_HEAT_CHNL_2_QTY=src.RPRTD_BRNG_HEAT_CHNL_2_QTY,tgt.RPRTD_INVLD_DATA_DSCRPT_TXT=src.RPRTD_INVLD_DATA_DSCRPT_TXT,tgt.VRFD_RAIL_SIDE_CD=src.VRFD_RAIL_SIDE_CD,tgt.VRFD_EQPMNT_CMPNT_LCTN_CD=src.VRFD_EQPMNT_CMPNT_LCTN_CD,tgt.RPRTD_ANGLE_OF_ATTACK_QTY=src.RPRTD_ANGLE_OF_ATTACK_QTY,tgt.RPRTD_BRNG_ALARM_RAIL_1_CD_OLD=src.RPRTD_BRNG_ALARM_RAIL_1_CD_OLD,tgt.RPRTD_BRNG_ALARM_RAIL_2_CD_OLD=src.RPRTD_BRNG_ALARM_RAIL_2_CD_OLD,tgt.RPRTD_WHL_ALARM_RAIL_1_CD_OLD=src.RPRTD_WHL_ALARM_RAIL_1_CD_OLD,tgt.RPRTD_WHL_ALARM_RAIL_2_CD_OLD=src.RPRTD_WHL_ALARM_RAIL_2_CD_OLD,tgt.RPRTD_DRGNG_EQPMNT_ALARM_CD=src.RPRTD_DRGNG_EQPMNT_ALARM_CD,tgt.RPRTD_HIGH_LOAD_ALARM_CD=src.RPRTD_HIGH_LOAD_ALARM_CD,tgt.RPRTD_WIDE_LOAD_ALARM_CD=src.RPRTD_WIDE_LOAD_ALARM_CD,tgt.RPRTD_BID_DCLRD_CD=src.RPRTD_BID_DCLRD_CD,tgt.RPRTD_BID_RAW_CHNL_1_CD=src.RPRTD_BID_RAW_CHNL_1_CD,tgt.RPRTD_BID_RAW_CHNL_2_CD=src.RPRTD_BID_RAW_CHNL_2_CD,tgt.RPRTD_MISS_OPEN_CD=src.RPRTD_MISS_OPEN_CD,tgt.RPRTD_TBOGI_CMPNT_SPEED_QTY=src.RPRTD_TBOGI_CMPNT_SPEED_QTY,tgt.RPRTD_WPD_CMPNT_SPEED_QTY=src.RPRTD_WPD_CMPNT_SPEED_QTY,tgt.RPRTD_CMPNT_SUB_CTGRY_CD=src.RPRTD_CMPNT_SUB_CTGRY_CD,tgt.RPRTD_CNFDNC_NBR=src.RPRTD_CNFDNC_NBR,tgt.RPRTD_DEVICE_RLTV_DRCTN_CD=src.RPRTD_DEVICE_RLTV_DRCTN_CD,tgt.RPRTD_CMPNT_PRMRY_SPEED_QTY=src.RPRTD_CMPNT_PRMRY_SPEED_QTY,tgt.RPRTD_HNTNG_INDEX_NBR=src.RPRTD_HNTNG_INDEX_NBR,tgt.RPRTD_CMPNT_LDNG_SPAN_QTY=src.RPRTD_CMPNT_LDNG_SPAN_QTY,tgt.RPRTD_CMPNT_LENGTH_QTY=src.RPRTD_CMPNT_LENGTH_QTY,tgt.RPRTD_DSTNC_FROM_PRVCMP_QTY=src.RPRTD_DSTNC_FROM_PRVCMP_QTY,tgt.RPRTD_CMPNT_TMPRTR_QTY=src.RPRTD_CMPNT_TMPRTR_QTY,tgt.RPRTD_DRTN_SCNDS_QTY=src.RPRTD_DRTN_SCNDS_QTY,tgt.RPRTD_TRCKNG_OFFSET_QTY=src.RPRTD_TRCKNG_OFFSET_QTY,tgt.RPRTD_TRUCK_NMNL_WEIGHT_QTY=src.RPRTD_TRUCK_NMNL_WEIGHT_QTY,tgt.RPRTD_CMPNT_WEIGHT_QTY=src.RPRTD_CMPNT_WEIGHT_QTY,tgt.WHEEL_SIGMA_CHNL_1_NBR=src.WHEEL_SIGMA_CHNL_1_NBR,tgt.WHEEL_SIGMA_CHNL_2_NBR=src.WHEEL_SIGMA_CHNL_2_NBR,tgt.BRNG_SIGMA_CHNL_1_NBR=src.BRNG_SIGMA_CHNL_1_NBR,tgt.BRNG_SIGMA_CHNL_2_NBR=src.BRNG_SIGMA_CHNL_2_NBR,tgt.RPRTD_PITCH_QTY=src.RPRTD_PITCH_QTY,tgt.RPRTD_BUILD_UP_TREAD_QTY=src.RPRTD_BUILD_UP_TREAD_QTY,tgt.RPRTD_ECNTRC_FORCE_QTY=src.RPRTD_ECNTRC_FORCE_QTY,tgt.RPRTD_ECNTRC_VRTN_FORCE_QTY=src.RPRTD_ECNTRC_VRTN_FORCE_QTY,tgt.RPRTD_FLANGE_ANGLE_QTY=src.RPRTD_FLANGE_ANGLE_QTY,tgt.RPRTD_FLANGE_GRDNT_QTY=src.RPRTD_FLANGE_GRDNT_QTY,tgt.RPRTD_FLANGE_HEIGHT_QTY=src.RPRTD_FLANGE_HEIGHT_QTY,tgt.RPRTD_FLANGE_THCKNS_QTY=src.RPRTD_FLANGE_THCKNS_QTY,tgt.RPRTD_GRVD_TREAD_LENGTH_QTY=src.RPRTD_GRVD_TREAD_LENGTH_QTY,tgt.RPRTD_LOAD_QTY=src.RPRTD_LOAD_QTY,tgt.RPRTD_LTRL_AVRG_LOAD_QTY=src.RPRTD_LTRL_AVRG_LOAD_QTY,tgt.RPRTD_LTRL_PEAK_LOAD_QTY=src.RPRTD_LTRL_PEAK_LOAD_QTY,tgt.RPRTD_NEW_AVRG_QTY=src.RPRTD_NEW_AVRG_QTY,tgt.RPRTD_PEAK_FORCE_QTY=src.RPRTD_PEAK_FORCE_QTY,tgt.RPRTD_RIM_THCKNS_QTY=src.RPRTD_RIM_THCKNS_QTY,tgt.RPRTD_THIN_FLANGE_LENGTH_QTY=src.RPRTD_THIN_FLANGE_LENGTH_QTY,tgt.RPRTD_TREAD_HOLLOW_LENGTH_QTY=src.RPRTD_TREAD_HOLLOW_LENGTH_QTY,tgt.RPRTD_TREAD_TAPER_LENGTH_QTY=src.RPRTD_TREAD_TAPER_LENGTH_QTY,tgt.RPRTD_VRTCL_FLANGE_QTY=src.RPRTD_VRTCL_FLANGE_QTY,tgt.RPRTD_GAUGE_QTY=src.RPRTD_GAUGE_QTY,tgt.RPRTD_TIME_FROM_FIRST_AXLE_QTY=src.RPRTD_TIME_FROM_FIRST_AXLE_QTY,tgt.RPRTD_LRWHL_DELTA_DMTR_QTY=src.RPRTD_LRWHL_DELTA_DMTR_QTY,tgt.RPRTD_WHEEL_BKTOBK_DSTNC_QTY=src.RPRTD_WHEEL_BKTOBK_DSTNC_QTY,tgt.RPRTD_LRWHL_DELTA_DMTR_CD=src.RPRTD_LRWHL_DELTA_DMTR_CD,tgt.RPRTD_WHEEL_BKTOBK_DSTNC_CD=src.RPRTD_WHEEL_BKTOBK_DSTNC_CD,tgt.RPRTD_ANGLE_OF_ATTACK_CD=src.RPRTD_ANGLE_OF_ATTACK_CD,tgt.RPRTD_WHEEL_PSTN_ON_RAIL_QTY=src.RPRTD_WHEEL_PSTN_ON_RAIL_QTY,tgt.RPRTD_BRKSHO_UPR_THCKNS_QTY=src.RPRTD_BRKSHO_UPR_THCKNS_QTY,tgt.RPRTD_BRKSHO_LWR_THCKNS_QTY=src.RPRTD_BRKSHO_LWR_THCKNS_QTY,tgt.RPRTD_FLANGE_HEIGHT_CD=src.RPRTD_FLANGE_HEIGHT_CD,tgt.RPRTD_FLANGE_THCKNS_CD=src.RPRTD_FLANGE_THCKNS_CD,tgt.RPRTD_RIM_THCKNS_CD=src.RPRTD_RIM_THCKNS_CD,tgt.RPRTD_CMPNT_LENGTH_CD=src.RPRTD_CMPNT_LENGTH_CD,tgt.RPRTD_TREAD_HOLLOW_LENGTH_CD=src.RPRTD_TREAD_HOLLOW_LENGTH_CD,tgt.RPRTD_FLANGE_ANGLE_CD=src.RPRTD_FLANGE_ANGLE_CD,tgt.RPRTD_WHEEL_PSTN_ON_RAIL_CD=src.RPRTD_WHEEL_PSTN_ON_RAIL_CD,tgt.RPRTD_BRKSHO_UPR_THCKNS_CD=src.RPRTD_BRKSHO_UPR_THCKNS_CD,tgt.RPRTD_BRKSHO_LWR_THCKNS_CD=src.RPRTD_BRKSHO_LWR_THCKNS_CD,tgt.BRNG_SIZE_CLASS_CD=src.BRNG_SIZE_CLASS_CD,tgt.BRNG_DEFECT_CODE_TXT=src.BRNG_DEFECT_CODE_TXT,tgt.BRNG_DEFECT_RNKNG_CD=src.BRNG_DEFECT_RNKNG_CD,tgt.BRNG_NOISE_PRCSR_QTY=src.BRNG_NOISE_PRCSR_QTY,tgt.BRNG_NOISE_CLSFR_VALUE_QTY=src.BRNG_NOISE_CLSFR_VALUE_QTY,tgt.BRNG_NON_BRNG_NOISE_CD=src.BRNG_NON_BRNG_NOISE_CD,tgt.RPRTD_BRNG_ALARM_RAIL_1_CD=src.RPRTD_BRNG_ALARM_RAIL_1_CD,tgt.RPRTD_BRNG_ALARM_RAIL_2_CD=src.RPRTD_BRNG_ALARM_RAIL_2_CD,tgt.RPRTD_WHEEL_ALARM_RAIL_1_CD=src.RPRTD_WHEEL_ALARM_RAIL_1_CD,tgt.RPRTD_WHEEL_ALARM_RAIL_2_CD=src.RPRTD_WHEEL_ALARM_RAIL_2_CD,tgt.RPRTD_TIME_SCNR_OFF_SCNDS_QTY=src.RPRTD_TIME_SCNR_OFF_SCNDS_QTY,tgt.RPRTD_TIME_SCNR_ON_SCNDS_QTY=src.RPRTD_TIME_SCNR_ON_SCNDS_QTY,tgt.KVALUE_TRN_CH1=src.KVALUE_TRN_CH1,tgt.KVALUE_TRN_CH2=src.KVALUE_TRN_CH2,tgt.KVALUE_EQP_CH1=src.KVALUE_EQP_CH1,tgt.KVALUE_EQP_CH2=src.KVALUE_EQP_CH2,tgt.TRUCK_OVERLOAD=src.TRUCK_OVERLOAD,tgt.RPRTD_TAPINGPTY_COORD=src.RPRTD_TAPINGPTY_COORD,tgt.RPRTD_CMPNT_WIDTH_QTY=src.RPRTD_CMPNT_WIDTH_QTY,tgt.RPRTD_DATA_QUALITY_FLAG=src.RPRTD_DATA_QUALITY_FLAG,tgt.RPRTD_LV_RATIO_CRIB1=src.RPRTD_LV_RATIO_CRIB1,tgt.RPRTD_LV_RATIO_CRIB2=src.RPRTD_LV_RATIO_CRIB2,tgt.RPRTD_HUNTING_P=src.RPRTD_HUNTING_P,tgt.RPRTD_HUNTING_A=src.RPRTD_HUNTING_A,tgt.RPRTD_HUNTING_F=src.RPRTD_HUNTING_F,tgt.RPRTD_HUNTING_W=src.RPRTD_HUNTING_W,tgt.RPRTD_IAM=src.RPRTD_IAM,tgt.RPRTD_ROT=src.RPRTD_ROT,tgt.RPRTD_TE=src.RPRTD_TE,tgt.RPRTD_SHIFT=src.RPRTD_SHIFT,tgt.RPRTD_AOA=src.RPRTD_AOA,tgt.RPRTD_TP=src.RPRTD_TP,tgt.RPRTD_TRUCKSPACING=src.RPRTD_TRUCKSPACING,tgt.SNW_OPERATION_TYPE=src.SNW_OPERATION_TYPE,tgt.SNW_OPERATION_OWNER=src.SNW_OPERATION_OWNER,tgt.SNW_LAST_REPLICATED=src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION='RELOADED',tgt.CDC_TIMESTAMP=CURRENT_TIMESTAMP(),tgt.IS_DELETED=FALSE,tgt.RECORD_UPDATED_AT=CURRENT_TIMESTAMP(),tgt.SOURCE_LOAD_BATCH_ID=src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (DTCTD_EQPMNT_CMPNT_ID,CREATE_USER_ID,RECORD_CREATE_TMS,RECORD_UPDATE_TMS,UPDATE_USER_ID,DTCTD_EQPMNT_ID,SOURCE_CREATE_TMS,SOURCE_UPDATE_TMS,RPRTD_EQPMNT_CMPNT_NM,RPRTD_CMPNT_ON_TRAIN_SQNC_NBR,RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR,RPRTD_CMPNT_ON_PARENT_SQNC_NBR,PARENT_DTCTD_EQPMNT_CMPNT_ID,RPRTD_AAR_TRUCK_ID,RPRTD_CMPNT_AXLE_FILE_NM,RPRTD_CMPNT_SIDE_CD,RPRTD_WHEEL_TMPRTR_CHNL_1_QTY,RPRTD_WHEEL_TMPRTR_CHNL_2_QTY,RPRTD_BRNG_HEAT_CHNL_1_QTY,RPRTD_BRNG_HEAT_CHNL_2_QTY,RPRTD_INVLD_DATA_DSCRPT_TXT,VRFD_RAIL_SIDE_CD,VRFD_EQPMNT_CMPNT_LCTN_CD,RPRTD_ANGLE_OF_ATTACK_QTY,RPRTD_BRNG_ALARM_RAIL_1_CD_OLD,RPRTD_BRNG_ALARM_RAIL_2_CD_OLD,RPRTD_WHL_ALARM_RAIL_1_CD_OLD,RPRTD_WHL_ALARM_RAIL_2_CD_OLD,RPRTD_DRGNG_EQPMNT_ALARM_CD,RPRTD_HIGH_LOAD_ALARM_CD,RPRTD_WIDE_LOAD_ALARM_CD,RPRTD_BID_DCLRD_CD,RPRTD_BID_RAW_CHNL_1_CD,RPRTD_BID_RAW_CHNL_2_CD,RPRTD_MISS_OPEN_CD,RPRTD_TBOGI_CMPNT_SPEED_QTY,RPRTD_WPD_CMPNT_SPEED_QTY,RPRTD_CMPNT_SUB_CTGRY_CD,RPRTD_CNFDNC_NBR,RPRTD_DEVICE_RLTV_DRCTN_CD,RPRTD_CMPNT_PRMRY_SPEED_QTY,RPRTD_HNTNG_INDEX_NBR,RPRTD_CMPNT_LDNG_SPAN_QTY,RPRTD_CMPNT_LENGTH_QTY,RPRTD_DSTNC_FROM_PRVCMP_QTY,RPRTD_CMPNT_TMPRTR_QTY,RPRTD_DRTN_SCNDS_QTY,RPRTD_TRCKNG_OFFSET_QTY,RPRTD_TRUCK_NMNL_WEIGHT_QTY,RPRTD_CMPNT_WEIGHT_QTY,WHEEL_SIGMA_CHNL_1_NBR,WHEEL_SIGMA_CHNL_2_NBR,BRNG_SIGMA_CHNL_1_NBR,BRNG_SIGMA_CHNL_2_NBR,RPRTD_PITCH_QTY,RPRTD_BUILD_UP_TREAD_QTY,RPRTD_ECNTRC_FORCE_QTY,RPRTD_ECNTRC_VRTN_FORCE_QTY,RPRTD_FLANGE_ANGLE_QTY,RPRTD_FLANGE_GRDNT_QTY,RPRTD_FLANGE_HEIGHT_QTY,RPRTD_FLANGE_THCKNS_QTY,RPRTD_GRVD_TREAD_LENGTH_QTY,RPRTD_LOAD_QTY,RPRTD_LTRL_AVRG_LOAD_QTY,RPRTD_LTRL_PEAK_LOAD_QTY,RPRTD_NEW_AVRG_QTY,RPRTD_PEAK_FORCE_QTY,RPRTD_RIM_THCKNS_QTY,RPRTD_THIN_FLANGE_LENGTH_QTY,RPRTD_TREAD_HOLLOW_LENGTH_QTY,RPRTD_TREAD_TAPER_LENGTH_QTY,RPRTD_VRTCL_FLANGE_QTY,RPRTD_GAUGE_QTY,RPRTD_TIME_FROM_FIRST_AXLE_QTY,RPRTD_LRWHL_DELTA_DMTR_QTY,RPRTD_WHEEL_BKTOBK_DSTNC_QTY,RPRTD_LRWHL_DELTA_DMTR_CD,RPRTD_WHEEL_BKTOBK_DSTNC_CD,RPRTD_ANGLE_OF_ATTACK_CD,RPRTD_WHEEL_PSTN_ON_RAIL_QTY,RPRTD_BRKSHO_UPR_THCKNS_QTY,RPRTD_BRKSHO_LWR_THCKNS_QTY,RPRTD_FLANGE_HEIGHT_CD,RPRTD_FLANGE_THCKNS_CD,RPRTD_RIM_THCKNS_CD,RPRTD_CMPNT_LENGTH_CD,RPRTD_TREAD_HOLLOW_LENGTH_CD,RPRTD_FLANGE_ANGLE_CD,RPRTD_WHEEL_PSTN_ON_RAIL_CD,RPRTD_BRKSHO_UPR_THCKNS_CD,RPRTD_BRKSHO_LWR_THCKNS_CD,BRNG_SIZE_CLASS_CD,BRNG_DEFECT_CODE_TXT,BRNG_DEFECT_RNKNG_CD,BRNG_NOISE_PRCSR_QTY,BRNG_NOISE_CLSFR_VALUE_QTY,BRNG_NON_BRNG_NOISE_CD,RPRTD_BRNG_ALARM_RAIL_1_CD,RPRTD_BRNG_ALARM_RAIL_2_CD,RPRTD_WHEEL_ALARM_RAIL_1_CD,RPRTD_WHEEL_ALARM_RAIL_2_CD,RPRTD_TIME_SCNR_OFF_SCNDS_QTY,RPRTD_TIME_SCNR_ON_SCNDS_QTY,KVALUE_TRN_CH1,KVALUE_TRN_CH2,KVALUE_EQP_CH1,KVALUE_EQP_CH2,TRUCK_OVERLOAD,RPRTD_TAPINGPTY_COORD,RPRTD_CMPNT_WIDTH_QTY,RPRTD_DATA_QUALITY_FLAG,RPRTD_LV_RATIO_CRIB1,RPRTD_LV_RATIO_CRIB2,RPRTD_HUNTING_P,RPRTD_HUNTING_A,RPRTD_HUNTING_F,RPRTD_HUNTING_W,RPRTD_IAM,RPRTD_ROT,RPRTD_TE,RPRTD_SHIFT,RPRTD_AOA,RPRTD_TP,RPRTD_TRUCKSPACING,SNW_OPERATION_TYPE,SNW_OPERATION_OWNER,SNW_LAST_REPLICATED,CDC_OPERATION,CDC_TIMESTAMP,IS_DELETED,RECORD_CREATED_AT,RECORD_UPDATED_AT,SOURCE_LOAD_BATCH_ID)
        VALUES (src.DTCTD_EQPMNT_CMPNT_ID,src.CREATE_USER_ID,src.RECORD_CREATE_TMS,src.RECORD_UPDATE_TMS,src.UPDATE_USER_ID,src.DTCTD_EQPMNT_ID,src.SOURCE_CREATE_TMS,src.SOURCE_UPDATE_TMS,src.RPRTD_EQPMNT_CMPNT_NM,src.RPRTD_CMPNT_ON_TRAIN_SQNC_NBR,src.RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR,src.RPRTD_CMPNT_ON_PARENT_SQNC_NBR,src.PARENT_DTCTD_EQPMNT_CMPNT_ID,src.RPRTD_AAR_TRUCK_ID,src.RPRTD_CMPNT_AXLE_FILE_NM,src.RPRTD_CMPNT_SIDE_CD,src.RPRTD_WHEEL_TMPRTR_CHNL_1_QTY,src.RPRTD_WHEEL_TMPRTR_CHNL_2_QTY,src.RPRTD_BRNG_HEAT_CHNL_1_QTY,src.RPRTD_BRNG_HEAT_CHNL_2_QTY,src.RPRTD_INVLD_DATA_DSCRPT_TXT,src.VRFD_RAIL_SIDE_CD,src.VRFD_EQPMNT_CMPNT_LCTN_CD,src.RPRTD_ANGLE_OF_ATTACK_QTY,src.RPRTD_BRNG_ALARM_RAIL_1_CD_OLD,src.RPRTD_BRNG_ALARM_RAIL_2_CD_OLD,src.RPRTD_WHL_ALARM_RAIL_1_CD_OLD,src.RPRTD_WHL_ALARM_RAIL_2_CD_OLD,src.RPRTD_DRGNG_EQPMNT_ALARM_CD,src.RPRTD_HIGH_LOAD_ALARM_CD,src.RPRTD_WIDE_LOAD_ALARM_CD,src.RPRTD_BID_DCLRD_CD,src.RPRTD_BID_RAW_CHNL_1_CD,src.RPRTD_BID_RAW_CHNL_2_CD,src.RPRTD_MISS_OPEN_CD,src.RPRTD_TBOGI_CMPNT_SPEED_QTY,src.RPRTD_WPD_CMPNT_SPEED_QTY,src.RPRTD_CMPNT_SUB_CTGRY_CD,src.RPRTD_CNFDNC_NBR,src.RPRTD_DEVICE_RLTV_DRCTN_CD,src.RPRTD_CMPNT_PRMRY_SPEED_QTY,src.RPRTD_HNTNG_INDEX_NBR,src.RPRTD_CMPNT_LDNG_SPAN_QTY,src.RPRTD_CMPNT_LENGTH_QTY,src.RPRTD_DSTNC_FROM_PRVCMP_QTY,src.RPRTD_CMPNT_TMPRTR_QTY,src.RPRTD_DRTN_SCNDS_QTY,src.RPRTD_TRCKNG_OFFSET_QTY,src.RPRTD_TRUCK_NMNL_WEIGHT_QTY,src.RPRTD_CMPNT_WEIGHT_QTY,src.WHEEL_SIGMA_CHNL_1_NBR,src.WHEEL_SIGMA_CHNL_2_NBR,src.BRNG_SIGMA_CHNL_1_NBR,src.BRNG_SIGMA_CHNL_2_NBR,src.RPRTD_PITCH_QTY,src.RPRTD_BUILD_UP_TREAD_QTY,src.RPRTD_ECNTRC_FORCE_QTY,src.RPRTD_ECNTRC_VRTN_FORCE_QTY,src.RPRTD_FLANGE_ANGLE_QTY,src.RPRTD_FLANGE_GRDNT_QTY,src.RPRTD_FLANGE_HEIGHT_QTY,src.RPRTD_FLANGE_THCKNS_QTY,src.RPRTD_GRVD_TREAD_LENGTH_QTY,src.RPRTD_LOAD_QTY,src.RPRTD_LTRL_AVRG_LOAD_QTY,src.RPRTD_LTRL_PEAK_LOAD_QTY,src.RPRTD_NEW_AVRG_QTY,src.RPRTD_PEAK_FORCE_QTY,src.RPRTD_RIM_THCKNS_QTY,src.RPRTD_THIN_FLANGE_LENGTH_QTY,src.RPRTD_TREAD_HOLLOW_LENGTH_QTY,src.RPRTD_TREAD_TAPER_LENGTH_QTY,src.RPRTD_VRTCL_FLANGE_QTY,src.RPRTD_GAUGE_QTY,src.RPRTD_TIME_FROM_FIRST_AXLE_QTY,src.RPRTD_LRWHL_DELTA_DMTR_QTY,src.RPRTD_WHEEL_BKTOBK_DSTNC_QTY,src.RPRTD_LRWHL_DELTA_DMTR_CD,src.RPRTD_WHEEL_BKTOBK_DSTNC_CD,src.RPRTD_ANGLE_OF_ATTACK_CD,src.RPRTD_WHEEL_PSTN_ON_RAIL_QTY,src.RPRTD_BRKSHO_UPR_THCKNS_QTY,src.RPRTD_BRKSHO_LWR_THCKNS_QTY,src.RPRTD_FLANGE_HEIGHT_CD,src.RPRTD_FLANGE_THCKNS_CD,src.RPRTD_RIM_THCKNS_CD,src.RPRTD_CMPNT_LENGTH_CD,src.RPRTD_TREAD_HOLLOW_LENGTH_CD,src.RPRTD_FLANGE_ANGLE_CD,src.RPRTD_WHEEL_PSTN_ON_RAIL_CD,src.RPRTD_BRKSHO_UPR_THCKNS_CD,src.RPRTD_BRKSHO_LWR_THCKNS_CD,src.BRNG_SIZE_CLASS_CD,src.BRNG_DEFECT_CODE_TXT,src.BRNG_DEFECT_RNKNG_CD,src.BRNG_NOISE_PRCSR_QTY,src.BRNG_NOISE_CLSFR_VALUE_QTY,src.BRNG_NON_BRNG_NOISE_CD,src.RPRTD_BRNG_ALARM_RAIL_1_CD,src.RPRTD_BRNG_ALARM_RAIL_2_CD,src.RPRTD_WHEEL_ALARM_RAIL_1_CD,src.RPRTD_WHEEL_ALARM_RAIL_2_CD,src.RPRTD_TIME_SCNR_OFF_SCNDS_QTY,src.RPRTD_TIME_SCNR_ON_SCNDS_QTY,src.KVALUE_TRN_CH1,src.KVALUE_TRN_CH2,src.KVALUE_EQP_CH1,src.KVALUE_EQP_CH2,src.TRUCK_OVERLOAD,src.RPRTD_TAPINGPTY_COORD,src.RPRTD_CMPNT_WIDTH_QTY,src.RPRTD_DATA_QUALITY_FLAG,src.RPRTD_LV_RATIO_CRIB1,src.RPRTD_LV_RATIO_CRIB2,src.RPRTD_HUNTING_P,src.RPRTD_HUNTING_A,src.RPRTD_HUNTING_F,src.RPRTD_HUNTING_W,src.RPRTD_IAM,src.RPRTD_ROT,src.RPRTD_TE,src.RPRTD_SHIFT,src.RPRTD_AOA,src.RPRTD_TP,src.RPRTD_TRUCKSPACING,src.SNW_OPERATION_TYPE,src.SNW_OPERATION_OWNER,src.SNW_LAST_REPLICATED,'INSERT',CURRENT_TIMESTAMP(),FALSE,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),src.BATCH_ID);
        
        v_rows_merged := SQLROWCOUNT;
        v_end_time := CURRENT_TIMESTAMP();
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME,BATCH_ID,EXECUTION_STATUS,START_TIME,END_TIME,ROWS_PROCESSED,ROWS_INSERTED,ROWS_UPDATED,ROWS_DELETED,ERROR_MESSAGE,CREATED_AT) VALUES ('EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT',:v_batch_id,'RECOVERY',:v_start_time,:v_end_time,:v_rows_merged,:v_rows_merged,0,0,:v_error_msg,CURRENT_TIMESTAMP());
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT AS
    SELECT DTCTD_EQPMNT_CMPNT_ID,CREATE_USER_ID,RECORD_CREATE_TMS,RECORD_UPDATE_TMS,UPDATE_USER_ID,DTCTD_EQPMNT_ID,SOURCE_CREATE_TMS,SOURCE_UPDATE_TMS,RPRTD_EQPMNT_CMPNT_NM,RPRTD_CMPNT_ON_TRAIN_SQNC_NBR,RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR,RPRTD_CMPNT_ON_PARENT_SQNC_NBR,PARENT_DTCTD_EQPMNT_CMPNT_ID,RPRTD_AAR_TRUCK_ID,RPRTD_CMPNT_AXLE_FILE_NM,RPRTD_CMPNT_SIDE_CD,RPRTD_WHEEL_TMPRTR_CHNL_1_QTY,RPRTD_WHEEL_TMPRTR_CHNL_2_QTY,RPRTD_BRNG_HEAT_CHNL_1_QTY,RPRTD_BRNG_HEAT_CHNL_2_QTY,RPRTD_INVLD_DATA_DSCRPT_TXT,VRFD_RAIL_SIDE_CD,VRFD_EQPMNT_CMPNT_LCTN_CD,RPRTD_ANGLE_OF_ATTACK_QTY,RPRTD_BRNG_ALARM_RAIL_1_CD_OLD,RPRTD_BRNG_ALARM_RAIL_2_CD_OLD,RPRTD_WHL_ALARM_RAIL_1_CD_OLD,RPRTD_WHL_ALARM_RAIL_2_CD_OLD,RPRTD_DRGNG_EQPMNT_ALARM_CD,RPRTD_HIGH_LOAD_ALARM_CD,RPRTD_WIDE_LOAD_ALARM_CD,RPRTD_BID_DCLRD_CD,RPRTD_BID_RAW_CHNL_1_CD,RPRTD_BID_RAW_CHNL_2_CD,RPRTD_MISS_OPEN_CD,RPRTD_TBOGI_CMPNT_SPEED_QTY,RPRTD_WPD_CMPNT_SPEED_QTY,RPRTD_CMPNT_SUB_CTGRY_CD,RPRTD_CNFDNC_NBR,RPRTD_DEVICE_RLTV_DRCTN_CD,RPRTD_CMPNT_PRMRY_SPEED_QTY,RPRTD_HNTNG_INDEX_NBR,RPRTD_CMPNT_LDNG_SPAN_QTY,RPRTD_CMPNT_LENGTH_QTY,RPRTD_DSTNC_FROM_PRVCMP_QTY,RPRTD_CMPNT_TMPRTR_QTY,RPRTD_DRTN_SCNDS_QTY,RPRTD_TRCKNG_OFFSET_QTY,RPRTD_TRUCK_NMNL_WEIGHT_QTY,RPRTD_CMPNT_WEIGHT_QTY,WHEEL_SIGMA_CHNL_1_NBR,WHEEL_SIGMA_CHNL_2_NBR,BRNG_SIGMA_CHNL_1_NBR,BRNG_SIGMA_CHNL_2_NBR,RPRTD_PITCH_QTY,RPRTD_BUILD_UP_TREAD_QTY,RPRTD_ECNTRC_FORCE_QTY,RPRTD_ECNTRC_VRTN_FORCE_QTY,RPRTD_FLANGE_ANGLE_QTY,RPRTD_FLANGE_GRDNT_QTY,RPRTD_FLANGE_HEIGHT_QTY,RPRTD_FLANGE_THCKNS_QTY,RPRTD_GRVD_TREAD_LENGTH_QTY,RPRTD_LOAD_QTY,RPRTD_LTRL_AVRG_LOAD_QTY,RPRTD_LTRL_PEAK_LOAD_QTY,RPRTD_NEW_AVRG_QTY,RPRTD_PEAK_FORCE_QTY,RPRTD_RIM_THCKNS_QTY,RPRTD_THIN_FLANGE_LENGTH_QTY,RPRTD_TREAD_HOLLOW_LENGTH_QTY,RPRTD_TREAD_TAPER_LENGTH_QTY,RPRTD_VRTCL_FLANGE_QTY,RPRTD_GAUGE_QTY,RPRTD_TIME_FROM_FIRST_AXLE_QTY,RPRTD_LRWHL_DELTA_DMTR_QTY,RPRTD_WHEEL_BKTOBK_DSTNC_QTY,RPRTD_LRWHL_DELTA_DMTR_CD,RPRTD_WHEEL_BKTOBK_DSTNC_CD,RPRTD_ANGLE_OF_ATTACK_CD,RPRTD_WHEEL_PSTN_ON_RAIL_QTY,RPRTD_BRKSHO_UPR_THCKNS_QTY,RPRTD_BRKSHO_LWR_THCKNS_QTY,RPRTD_FLANGE_HEIGHT_CD,RPRTD_FLANGE_THCKNS_CD,RPRTD_RIM_THCKNS_CD,RPRTD_CMPNT_LENGTH_CD,RPRTD_TREAD_HOLLOW_LENGTH_CD,RPRTD_FLANGE_ANGLE_CD,RPRTD_WHEEL_PSTN_ON_RAIL_CD,RPRTD_BRKSHO_UPR_THCKNS_CD,RPRTD_BRKSHO_LWR_THCKNS_CD,BRNG_SIZE_CLASS_CD,BRNG_DEFECT_CODE_TXT,BRNG_DEFECT_RNKNG_CD,BRNG_NOISE_PRCSR_QTY,BRNG_NOISE_CLSFR_VALUE_QTY,BRNG_NON_BRNG_NOISE_CD,RPRTD_BRNG_ALARM_RAIL_1_CD,RPRTD_BRNG_ALARM_RAIL_2_CD,RPRTD_WHEEL_ALARM_RAIL_1_CD,RPRTD_WHEEL_ALARM_RAIL_2_CD,RPRTD_TIME_SCNR_OFF_SCNDS_QTY,RPRTD_TIME_SCNR_ON_SCNDS_QTY,KVALUE_TRN_CH1,KVALUE_TRN_CH2,KVALUE_EQP_CH1,KVALUE_EQP_CH2,TRUCK_OVERLOAD,RPRTD_TAPINGPTY_COORD,RPRTD_CMPNT_WIDTH_QTY,RPRTD_DATA_QUALITY_FLAG,RPRTD_LV_RATIO_CRIB1,RPRTD_LV_RATIO_CRIB2,RPRTD_HUNTING_P,RPRTD_HUNTING_A,RPRTD_HUNTING_F,RPRTD_HUNTING_W,RPRTD_IAM,RPRTD_ROT,RPRTD_TE,RPRTD_SHIFT,RPRTD_AOA,RPRTD_TP,RPRTD_TRUCKSPACING,SNW_OPERATION_TYPE,SNW_OPERATION_OWNER,SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION, METADATA$ISUPDATE AS CDC_IS_UPDATE, METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT;
        v_end_time := CURRENT_TIMESTAMP();
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME,BATCH_ID,EXECUTION_STATUS,START_TIME,END_TIME,ROWS_PROCESSED,ROWS_INSERTED,ROWS_UPDATED,ROWS_DELETED,ERROR_MESSAGE,CREATED_AT) VALUES ('EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT',:v_batch_id,'NO_DATA',:v_start_time,:v_end_time,0,0,0,0,NULL,CURRENT_TIMESTAMP());
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    SELECT COUNT(CASE WHEN CDC_ACTION='INSERT' AND CDC_IS_UPDATE=FALSE THEN 1 END),COUNT(CASE WHEN CDC_ACTION='INSERT' AND CDC_IS_UPDATE=TRUE THEN 1 END),COUNT(CASE WHEN CDC_ACTION='DELETE' AND CDC_IS_UPDATE=FALSE THEN 1 END) INTO v_rows_inserted,v_rows_updated,v_rows_deleted FROM _CDC_STAGING_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT;
    
    MERGE INTO D_BRONZE.EHMS.EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT AS tgt
    USING (SELECT *,:v_batch_id AS BATCH_ID FROM _CDC_STAGING_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT) AS src
    ON tgt.DTCTD_EQPMNT_CMPNT_ID = src.DTCTD_EQPMNT_CMPNT_ID
    
    WHEN MATCHED AND src.CDC_ACTION='INSERT' AND src.CDC_IS_UPDATE=TRUE THEN UPDATE SET
        tgt.CREATE_USER_ID=src.CREATE_USER_ID,tgt.RECORD_CREATE_TMS=src.RECORD_CREATE_TMS,tgt.RECORD_UPDATE_TMS=src.RECORD_UPDATE_TMS,tgt.UPDATE_USER_ID=src.UPDATE_USER_ID,tgt.DTCTD_EQPMNT_ID=src.DTCTD_EQPMNT_ID,tgt.SOURCE_CREATE_TMS=src.SOURCE_CREATE_TMS,tgt.SOURCE_UPDATE_TMS=src.SOURCE_UPDATE_TMS,tgt.RPRTD_EQPMNT_CMPNT_NM=src.RPRTD_EQPMNT_CMPNT_NM,tgt.RPRTD_CMPNT_ON_TRAIN_SQNC_NBR=src.RPRTD_CMPNT_ON_TRAIN_SQNC_NBR,tgt.RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR=src.RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR,tgt.RPRTD_CMPNT_ON_PARENT_SQNC_NBR=src.RPRTD_CMPNT_ON_PARENT_SQNC_NBR,tgt.PARENT_DTCTD_EQPMNT_CMPNT_ID=src.PARENT_DTCTD_EQPMNT_CMPNT_ID,tgt.RPRTD_AAR_TRUCK_ID=src.RPRTD_AAR_TRUCK_ID,tgt.RPRTD_CMPNT_AXLE_FILE_NM=src.RPRTD_CMPNT_AXLE_FILE_NM,tgt.RPRTD_CMPNT_SIDE_CD=src.RPRTD_CMPNT_SIDE_CD,tgt.RPRTD_WHEEL_TMPRTR_CHNL_1_QTY=src.RPRTD_WHEEL_TMPRTR_CHNL_1_QTY,tgt.RPRTD_WHEEL_TMPRTR_CHNL_2_QTY=src.RPRTD_WHEEL_TMPRTR_CHNL_2_QTY,tgt.RPRTD_BRNG_HEAT_CHNL_1_QTY=src.RPRTD_BRNG_HEAT_CHNL_1_QTY,tgt.RPRTD_BRNG_HEAT_CHNL_2_QTY=src.RPRTD_BRNG_HEAT_CHNL_2_QTY,tgt.RPRTD_INVLD_DATA_DSCRPT_TXT=src.RPRTD_INVLD_DATA_DSCRPT_TXT,tgt.VRFD_RAIL_SIDE_CD=src.VRFD_RAIL_SIDE_CD,tgt.VRFD_EQPMNT_CMPNT_LCTN_CD=src.VRFD_EQPMNT_CMPNT_LCTN_CD,tgt.RPRTD_ANGLE_OF_ATTACK_QTY=src.RPRTD_ANGLE_OF_ATTACK_QTY,tgt.RPRTD_BRNG_ALARM_RAIL_1_CD_OLD=src.RPRTD_BRNG_ALARM_RAIL_1_CD_OLD,tgt.RPRTD_BRNG_ALARM_RAIL_2_CD_OLD=src.RPRTD_BRNG_ALARM_RAIL_2_CD_OLD,tgt.RPRTD_WHL_ALARM_RAIL_1_CD_OLD=src.RPRTD_WHL_ALARM_RAIL_1_CD_OLD,tgt.RPRTD_WHL_ALARM_RAIL_2_CD_OLD=src.RPRTD_WHL_ALARM_RAIL_2_CD_OLD,tgt.RPRTD_DRGNG_EQPMNT_ALARM_CD=src.RPRTD_DRGNG_EQPMNT_ALARM_CD,tgt.RPRTD_HIGH_LOAD_ALARM_CD=src.RPRTD_HIGH_LOAD_ALARM_CD,tgt.RPRTD_WIDE_LOAD_ALARM_CD=src.RPRTD_WIDE_LOAD_ALARM_CD,tgt.RPRTD_BID_DCLRD_CD=src.RPRTD_BID_DCLRD_CD,tgt.RPRTD_BID_RAW_CHNL_1_CD=src.RPRTD_BID_RAW_CHNL_1_CD,tgt.RPRTD_BID_RAW_CHNL_2_CD=src.RPRTD_BID_RAW_CHNL_2_CD,tgt.RPRTD_MISS_OPEN_CD=src.RPRTD_MISS_OPEN_CD,tgt.RPRTD_TBOGI_CMPNT_SPEED_QTY=src.RPRTD_TBOGI_CMPNT_SPEED_QTY,tgt.RPRTD_WPD_CMPNT_SPEED_QTY=src.RPRTD_WPD_CMPNT_SPEED_QTY,tgt.RPRTD_CMPNT_SUB_CTGRY_CD=src.RPRTD_CMPNT_SUB_CTGRY_CD,tgt.RPRTD_CNFDNC_NBR=src.RPRTD_CNFDNC_NBR,tgt.RPRTD_DEVICE_RLTV_DRCTN_CD=src.RPRTD_DEVICE_RLTV_DRCTN_CD,tgt.RPRTD_CMPNT_PRMRY_SPEED_QTY=src.RPRTD_CMPNT_PRMRY_SPEED_QTY,tgt.RPRTD_HNTNG_INDEX_NBR=src.RPRTD_HNTNG_INDEX_NBR,tgt.RPRTD_CMPNT_LDNG_SPAN_QTY=src.RPRTD_CMPNT_LDNG_SPAN_QTY,tgt.RPRTD_CMPNT_LENGTH_QTY=src.RPRTD_CMPNT_LENGTH_QTY,tgt.RPRTD_DSTNC_FROM_PRVCMP_QTY=src.RPRTD_DSTNC_FROM_PRVCMP_QTY,tgt.RPRTD_CMPNT_TMPRTR_QTY=src.RPRTD_CMPNT_TMPRTR_QTY,tgt.RPRTD_DRTN_SCNDS_QTY=src.RPRTD_DRTN_SCNDS_QTY,tgt.RPRTD_TRCKNG_OFFSET_QTY=src.RPRTD_TRCKNG_OFFSET_QTY,tgt.RPRTD_TRUCK_NMNL_WEIGHT_QTY=src.RPRTD_TRUCK_NMNL_WEIGHT_QTY,tgt.RPRTD_CMPNT_WEIGHT_QTY=src.RPRTD_CMPNT_WEIGHT_QTY,tgt.WHEEL_SIGMA_CHNL_1_NBR=src.WHEEL_SIGMA_CHNL_1_NBR,tgt.WHEEL_SIGMA_CHNL_2_NBR=src.WHEEL_SIGMA_CHNL_2_NBR,tgt.BRNG_SIGMA_CHNL_1_NBR=src.BRNG_SIGMA_CHNL_1_NBR,tgt.BRNG_SIGMA_CHNL_2_NBR=src.BRNG_SIGMA_CHNL_2_NBR,tgt.RPRTD_PITCH_QTY=src.RPRTD_PITCH_QTY,tgt.RPRTD_BUILD_UP_TREAD_QTY=src.RPRTD_BUILD_UP_TREAD_QTY,tgt.RPRTD_ECNTRC_FORCE_QTY=src.RPRTD_ECNTRC_FORCE_QTY,tgt.RPRTD_ECNTRC_VRTN_FORCE_QTY=src.RPRTD_ECNTRC_VRTN_FORCE_QTY,tgt.RPRTD_FLANGE_ANGLE_QTY=src.RPRTD_FLANGE_ANGLE_QTY,tgt.RPRTD_FLANGE_GRDNT_QTY=src.RPRTD_FLANGE_GRDNT_QTY,tgt.RPRTD_FLANGE_HEIGHT_QTY=src.RPRTD_FLANGE_HEIGHT_QTY,tgt.RPRTD_FLANGE_THCKNS_QTY=src.RPRTD_FLANGE_THCKNS_QTY,tgt.RPRTD_GRVD_TREAD_LENGTH_QTY=src.RPRTD_GRVD_TREAD_LENGTH_QTY,tgt.RPRTD_LOAD_QTY=src.RPRTD_LOAD_QTY,tgt.RPRTD_LTRL_AVRG_LOAD_QTY=src.RPRTD_LTRL_AVRG_LOAD_QTY,tgt.RPRTD_LTRL_PEAK_LOAD_QTY=src.RPRTD_LTRL_PEAK_LOAD_QTY,tgt.RPRTD_NEW_AVRG_QTY=src.RPRTD_NEW_AVRG_QTY,tgt.RPRTD_PEAK_FORCE_QTY=src.RPRTD_PEAK_FORCE_QTY,tgt.RPRTD_RIM_THCKNS_QTY=src.RPRTD_RIM_THCKNS_QTY,tgt.RPRTD_THIN_FLANGE_LENGTH_QTY=src.RPRTD_THIN_FLANGE_LENGTH_QTY,tgt.RPRTD_TREAD_HOLLOW_LENGTH_QTY=src.RPRTD_TREAD_HOLLOW_LENGTH_QTY,tgt.RPRTD_TREAD_TAPER_LENGTH_QTY=src.RPRTD_TREAD_TAPER_LENGTH_QTY,tgt.RPRTD_VRTCL_FLANGE_QTY=src.RPRTD_VRTCL_FLANGE_QTY,tgt.RPRTD_GAUGE_QTY=src.RPRTD_GAUGE_QTY,tgt.RPRTD_TIME_FROM_FIRST_AXLE_QTY=src.RPRTD_TIME_FROM_FIRST_AXLE_QTY,tgt.RPRTD_LRWHL_DELTA_DMTR_QTY=src.RPRTD_LRWHL_DELTA_DMTR_QTY,tgt.RPRTD_WHEEL_BKTOBK_DSTNC_QTY=src.RPRTD_WHEEL_BKTOBK_DSTNC_QTY,tgt.RPRTD_LRWHL_DELTA_DMTR_CD=src.RPRTD_LRWHL_DELTA_DMTR_CD,tgt.RPRTD_WHEEL_BKTOBK_DSTNC_CD=src.RPRTD_WHEEL_BKTOBK_DSTNC_CD,tgt.RPRTD_ANGLE_OF_ATTACK_CD=src.RPRTD_ANGLE_OF_ATTACK_CD,tgt.RPRTD_WHEEL_PSTN_ON_RAIL_QTY=src.RPRTD_WHEEL_PSTN_ON_RAIL_QTY,tgt.RPRTD_BRKSHO_UPR_THCKNS_QTY=src.RPRTD_BRKSHO_UPR_THCKNS_QTY,tgt.RPRTD_BRKSHO_LWR_THCKNS_QTY=src.RPRTD_BRKSHO_LWR_THCKNS_QTY,tgt.RPRTD_FLANGE_HEIGHT_CD=src.RPRTD_FLANGE_HEIGHT_CD,tgt.RPRTD_FLANGE_THCKNS_CD=src.RPRTD_FLANGE_THCKNS_CD,tgt.RPRTD_RIM_THCKNS_CD=src.RPRTD_RIM_THCKNS_CD,tgt.RPRTD_CMPNT_LENGTH_CD=src.RPRTD_CMPNT_LENGTH_CD,tgt.RPRTD_TREAD_HOLLOW_LENGTH_CD=src.RPRTD_TREAD_HOLLOW_LENGTH_CD,tgt.RPRTD_FLANGE_ANGLE_CD=src.RPRTD_FLANGE_ANGLE_CD,tgt.RPRTD_WHEEL_PSTN_ON_RAIL_CD=src.RPRTD_WHEEL_PSTN_ON_RAIL_CD,tgt.RPRTD_BRKSHO_UPR_THCKNS_CD=src.RPRTD_BRKSHO_UPR_THCKNS_CD,tgt.RPRTD_BRKSHO_LWR_THCKNS_CD=src.RPRTD_BRKSHO_LWR_THCKNS_CD,tgt.BRNG_SIZE_CLASS_CD=src.BRNG_SIZE_CLASS_CD,tgt.BRNG_DEFECT_CODE_TXT=src.BRNG_DEFECT_CODE_TXT,tgt.BRNG_DEFECT_RNKNG_CD=src.BRNG_DEFECT_RNKNG_CD,tgt.BRNG_NOISE_PRCSR_QTY=src.BRNG_NOISE_PRCSR_QTY,tgt.BRNG_NOISE_CLSFR_VALUE_QTY=src.BRNG_NOISE_CLSFR_VALUE_QTY,tgt.BRNG_NON_BRNG_NOISE_CD=src.BRNG_NON_BRNG_NOISE_CD,tgt.RPRTD_BRNG_ALARM_RAIL_1_CD=src.RPRTD_BRNG_ALARM_RAIL_1_CD,tgt.RPRTD_BRNG_ALARM_RAIL_2_CD=src.RPRTD_BRNG_ALARM_RAIL_2_CD,tgt.RPRTD_WHEEL_ALARM_RAIL_1_CD=src.RPRTD_WHEEL_ALARM_RAIL_1_CD,tgt.RPRTD_WHEEL_ALARM_RAIL_2_CD=src.RPRTD_WHEEL_ALARM_RAIL_2_CD,tgt.RPRTD_TIME_SCNR_OFF_SCNDS_QTY=src.RPRTD_TIME_SCNR_OFF_SCNDS_QTY,tgt.RPRTD_TIME_SCNR_ON_SCNDS_QTY=src.RPRTD_TIME_SCNR_ON_SCNDS_QTY,tgt.KVALUE_TRN_CH1=src.KVALUE_TRN_CH1,tgt.KVALUE_TRN_CH2=src.KVALUE_TRN_CH2,tgt.KVALUE_EQP_CH1=src.KVALUE_EQP_CH1,tgt.KVALUE_EQP_CH2=src.KVALUE_EQP_CH2,tgt.TRUCK_OVERLOAD=src.TRUCK_OVERLOAD,tgt.RPRTD_TAPINGPTY_COORD=src.RPRTD_TAPINGPTY_COORD,tgt.RPRTD_CMPNT_WIDTH_QTY=src.RPRTD_CMPNT_WIDTH_QTY,tgt.RPRTD_DATA_QUALITY_FLAG=src.RPRTD_DATA_QUALITY_FLAG,tgt.RPRTD_LV_RATIO_CRIB1=src.RPRTD_LV_RATIO_CRIB1,tgt.RPRTD_LV_RATIO_CRIB2=src.RPRTD_LV_RATIO_CRIB2,tgt.RPRTD_HUNTING_P=src.RPRTD_HUNTING_P,tgt.RPRTD_HUNTING_A=src.RPRTD_HUNTING_A,tgt.RPRTD_HUNTING_F=src.RPRTD_HUNTING_F,tgt.RPRTD_HUNTING_W=src.RPRTD_HUNTING_W,tgt.RPRTD_IAM=src.RPRTD_IAM,tgt.RPRTD_ROT=src.RPRTD_ROT,tgt.RPRTD_TE=src.RPRTD_TE,tgt.RPRTD_SHIFT=src.RPRTD_SHIFT,tgt.RPRTD_AOA=src.RPRTD_AOA,tgt.RPRTD_TP=src.RPRTD_TP,tgt.RPRTD_TRUCKSPACING=src.RPRTD_TRUCKSPACING,tgt.SNW_OPERATION_TYPE=src.SNW_OPERATION_TYPE,tgt.SNW_OPERATION_OWNER=src.SNW_OPERATION_OWNER,tgt.SNW_LAST_REPLICATED=src.SNW_LAST_REPLICATED,
        tgt.CDC_OPERATION='UPDATE',tgt.CDC_TIMESTAMP=CURRENT_TIMESTAMP(),tgt.IS_DELETED=FALSE,tgt.RECORD_UPDATED_AT=CURRENT_TIMESTAMP(),tgt.SOURCE_LOAD_BATCH_ID=src.BATCH_ID
    
    WHEN MATCHED AND src.CDC_ACTION='DELETE' AND src.CDC_IS_UPDATE=FALSE THEN UPDATE SET
        tgt.CDC_OPERATION='DELETE',tgt.CDC_TIMESTAMP=CURRENT_TIMESTAMP(),tgt.IS_DELETED=TRUE,tgt.RECORD_UPDATED_AT=CURRENT_TIMESTAMP(),tgt.SOURCE_LOAD_BATCH_ID=src.BATCH_ID
    
    WHEN MATCHED AND src.CDC_ACTION='INSERT' AND src.CDC_IS_UPDATE=FALSE THEN UPDATE SET
        tgt.CREATE_USER_ID=src.CREATE_USER_ID,tgt.RECORD_CREATE_TMS=src.RECORD_CREATE_TMS,tgt.RECORD_UPDATE_TMS=src.RECORD_UPDATE_TMS,tgt.UPDATE_USER_ID=src.UPDATE_USER_ID,tgt.DTCTD_EQPMNT_ID=src.DTCTD_EQPMNT_ID,tgt.SOURCE_CREATE_TMS=src.SOURCE_CREATE_TMS,tgt.SOURCE_UPDATE_TMS=src.SOURCE_UPDATE_TMS,tgt.RPRTD_EQPMNT_CMPNT_NM=src.RPRTD_EQPMNT_CMPNT_NM,tgt.RPRTD_CMPNT_ON_TRAIN_SQNC_NBR=src.RPRTD_CMPNT_ON_TRAIN_SQNC_NBR,tgt.RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR=src.RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR,tgt.RPRTD_CMPNT_ON_PARENT_SQNC_NBR=src.RPRTD_CMPNT_ON_PARENT_SQNC_NBR,tgt.PARENT_DTCTD_EQPMNT_CMPNT_ID=src.PARENT_DTCTD_EQPMNT_CMPNT_ID,tgt.RPRTD_AAR_TRUCK_ID=src.RPRTD_AAR_TRUCK_ID,tgt.RPRTD_CMPNT_AXLE_FILE_NM=src.RPRTD_CMPNT_AXLE_FILE_NM,tgt.RPRTD_CMPNT_SIDE_CD=src.RPRTD_CMPNT_SIDE_CD,tgt.RPRTD_WHEEL_TMPRTR_CHNL_1_QTY=src.RPRTD_WHEEL_TMPRTR_CHNL_1_QTY,tgt.RPRTD_WHEEL_TMPRTR_CHNL_2_QTY=src.RPRTD_WHEEL_TMPRTR_CHNL_2_QTY,tgt.RPRTD_BRNG_HEAT_CHNL_1_QTY=src.RPRTD_BRNG_HEAT_CHNL_1_QTY,tgt.RPRTD_BRNG_HEAT_CHNL_2_QTY=src.RPRTD_BRNG_HEAT_CHNL_2_QTY,tgt.RPRTD_INVLD_DATA_DSCRPT_TXT=src.RPRTD_INVLD_DATA_DSCRPT_TXT,tgt.VRFD_RAIL_SIDE_CD=src.VRFD_RAIL_SIDE_CD,tgt.VRFD_EQPMNT_CMPNT_LCTN_CD=src.VRFD_EQPMNT_CMPNT_LCTN_CD,tgt.RPRTD_ANGLE_OF_ATTACK_QTY=src.RPRTD_ANGLE_OF_ATTACK_QTY,tgt.RPRTD_BRNG_ALARM_RAIL_1_CD_OLD=src.RPRTD_BRNG_ALARM_RAIL_1_CD_OLD,tgt.RPRTD_BRNG_ALARM_RAIL_2_CD_OLD=src.RPRTD_BRNG_ALARM_RAIL_2_CD_OLD,tgt.RPRTD_WHL_ALARM_RAIL_1_CD_OLD=src.RPRTD_WHL_ALARM_RAIL_1_CD_OLD,tgt.RPRTD_WHL_ALARM_RAIL_2_CD_OLD=src.RPRTD_WHL_ALARM_RAIL_2_CD_OLD,tgt.RPRTD_DRGNG_EQPMNT_ALARM_CD=src.RPRTD_DRGNG_EQPMNT_ALARM_CD,tgt.RPRTD_HIGH_LOAD_ALARM_CD=src.RPRTD_HIGH_LOAD_ALARM_CD,tgt.RPRTD_WIDE_LOAD_ALARM_CD=src.RPRTD_WIDE_LOAD_ALARM_CD,tgt.RPRTD_BID_DCLRD_CD=src.RPRTD_BID_DCLRD_CD,tgt.RPRTD_BID_RAW_CHNL_1_CD=src.RPRTD_BID_RAW_CHNL_1_CD,tgt.RPRTD_BID_RAW_CHNL_2_CD=src.RPRTD_BID_RAW_CHNL_2_CD,tgt.RPRTD_MISS_OPEN_CD=src.RPRTD_MISS_OPEN_CD,tgt.RPRTD_TBOGI_CMPNT_SPEED_QTY=src.RPRTD_TBOGI_CMPNT_SPEED_QTY,tgt.RPRTD_WPD_CMPNT_SPEED_QTY=src.RPRTD_WPD_CMPNT_SPEED_QTY,tgt.RPRTD_CMPNT_SUB_CTGRY_CD=src.RPRTD_CMPNT_SUB_CTGRY_CD,tgt.RPRTD_CNFDNC_NBR=src.RPRTD_CNFDNC_NBR,tgt.RPRTD_DEVICE_RLTV_DRCTN_CD=src.RPRTD_DEVICE_RLTV_DRCTN_CD,tgt.RPRTD_CMPNT_PRMRY_SPEED_QTY=src.RPRTD_CMPNT_PRMRY_SPEED_QTY,tgt.RPRTD_HNTNG_INDEX_NBR=src.RPRTD_HNTNG_INDEX_NBR,tgt.RPRTD_CMPNT_LDNG_SPAN_QTY=src.RPRTD_CMPNT_LDNG_SPAN_QTY,tgt.RPRTD_CMPNT_LENGTH_QTY=src.RPRTD_CMPNT_LENGTH_QTY,tgt.RPRTD_DSTNC_FROM_PRVCMP_QTY=src.RPRTD_DSTNC_FROM_PRVCMP_QTY,tgt.RPRTD_CMPNT_TMPRTR_QTY=src.RPRTD_CMPNT_TMPRTR_QTY,tgt.RPRTD_DRTN_SCNDS_QTY=src.RPRTD_DRTN_SCNDS_QTY,tgt.RPRTD_TRCKNG_OFFSET_QTY=src.RPRTD_TRCKNG_OFFSET_QTY,tgt.RPRTD_TRUCK_NMNL_WEIGHT_QTY=src.RPRTD_TRUCK_NMNL_WEIGHT_QTY,tgt.RPRTD_CMPNT_WEIGHT_QTY=src.RPRTD_CMPNT_WEIGHT_QTY,tgt.WHEEL_SIGMA_CHNL_1_NBR=src.WHEEL_SIGMA_CHNL_1_NBR,tgt.WHEEL_SIGMA_CHNL_2_NBR=src.WHEEL_SIGMA_CHNL_2_NBR,tgt.BRNG_SIGMA_CHNL_1_NBR=src.BRNG_SIGMA_CHNL_1_NBR,tgt.BRNG_SIGMA_CHNL_2_NBR=src.BRNG_SIGMA_CHNL_2_NBR,tgt.RPRTD_PITCH_QTY=src.RPRTD_PITCH_QTY,tgt.RPRTD_BUILD_UP_TREAD_QTY=src.RPRTD_BUILD_UP_TREAD_QTY,tgt.RPRTD_ECNTRC_FORCE_QTY=src.RPRTD_ECNTRC_FORCE_QTY,tgt.RPRTD_ECNTRC_VRTN_FORCE_QTY=src.RPRTD_ECNTRC_VRTN_FORCE_QTY,tgt.RPRTD_FLANGE_ANGLE_QTY=src.RPRTD_FLANGE_ANGLE_QTY,tgt.RPRTD_FLANGE_GRDNT_QTY=src.RPRTD_FLANGE_GRDNT_QTY,tgt.RPRTD_FLANGE_HEIGHT_QTY=src.RPRTD_FLANGE_HEIGHT_QTY,tgt.RPRTD_FLANGE_THCKNS_QTY=src.RPRTD_FLANGE_THCKNS_QTY,tgt.RPRTD_GRVD_TREAD_LENGTH_QTY=src.RPRTD_GRVD_TREAD_LENGTH_QTY,tgt.RPRTD_LOAD_QTY=src.RPRTD_LOAD_QTY,tgt.RPRTD_LTRL_AVRG_LOAD_QTY=src.RPRTD_LTRL_AVRG_LOAD_QTY,tgt.RPRTD_LTRL_PEAK_LOAD_QTY=src.RPRTD_LTRL_PEAK_LOAD_QTY,tgt.RPRTD_NEW_AVRG_QTY=src.RPRTD_NEW_AVRG_QTY,tgt.RPRTD_PEAK_FORCE_QTY=src.RPRTD_PEAK_FORCE_QTY,tgt.RPRTD_RIM_THCKNS_QTY=src.RPRTD_RIM_THCKNS_QTY,tgt.RPRTD_THIN_FLANGE_LENGTH_QTY=src.RPRTD_THIN_FLANGE_LENGTH_QTY,tgt.RPRTD_TREAD_HOLLOW_LENGTH_QTY=src.RPRTD_TREAD_HOLLOW_LENGTH_QTY,tgt.RPRTD_TREAD_TAPER_LENGTH_QTY=src.RPRTD_TREAD_TAPER_LENGTH_QTY,tgt.RPRTD_VRTCL_FLANGE_QTY=src.RPRTD_VRTCL_FLANGE_QTY,tgt.RPRTD_GAUGE_QTY=src.RPRTD_GAUGE_QTY,tgt.RPRTD_TIME_FROM_FIRST_AXLE_QTY=src.RPRTD_TIME_FROM_FIRST_AXLE_QTY,tgt.RPRTD_LRWHL_DELTA_DMTR_QTY=src.RPRTD_LRWHL_DELTA_DMTR_QTY,tgt.RPRTD_WHEEL_BKTOBK_DSTNC_QTY=src.RPRTD_WHEEL_BKTOBK_DSTNC_QTY,tgt.RPRTD_LRWHL_DELTA_DMTR_CD=src.RPRTD_LRWHL_DELTA_DMTR_CD,tgt.RPRTD_WHEEL_BKTOBK_DSTNC_CD=src.RPRTD_WHEEL_BKTOBK_DSTNC_CD,tgt.RPRTD_ANGLE_OF_ATTACK_CD=src.RPRTD_ANGLE_OF_ATTACK_CD,tgt.RPRTD_WHEEL_PSTN_ON_RAIL_QTY=src.RPRTD_WHEEL_PSTN_ON_RAIL_QTY,tgt.RPRTD_BRKSHO_UPR_THCKNS_QTY=src.RPRTD_BRKSHO_UPR_THCKNS_QTY,tgt.RPRTD_BRKSHO_LWR_THCKNS_QTY=src.RPRTD_BRKSHO_LWR_THCKNS_QTY,tgt.RPRTD_FLANGE_HEIGHT_CD=src.RPRTD_FLANGE_HEIGHT_CD,tgt.RPRTD_FLANGE_THCKNS_CD=src.RPRTD_FLANGE_THCKNS_CD,tgt.RPRTD_RIM_THCKNS_CD=src.RPRTD_RIM_THCKNS_CD,tgt.RPRTD_CMPNT_LENGTH_CD=src.RPRTD_CMPNT_LENGTH_CD,tgt.RPRTD_TREAD_HOLLOW_LENGTH_CD=src.RPRTD_TREAD_HOLLOW_LENGTH_CD,tgt.RPRTD_FLANGE_ANGLE_CD=src.RPRTD_FLANGE_ANGLE_CD,tgt.RPRTD_WHEEL_PSTN_ON_RAIL_CD=src.RPRTD_WHEEL_PSTN_ON_RAIL_CD,tgt.RPRTD_BRKSHO_UPR_THCKNS_CD=src.RPRTD_BRKSHO_UPR_THCKNS_CD,tgt.RPRTD_BRKSHO_LWR_THCKNS_CD=src.RPRTD_BRKSHO_LWR_THCKNS_CD,tgt.BRNG_SIZE_CLASS_CD=src.BRNG_SIZE_CLASS_CD,tgt.BRNG_DEFECT_CODE_TXT=src.BRNG_DEFECT_CODE_TXT,tgt.BRNG_DEFECT_RNKNG_CD=src.BRNG_DEFECT_RNKNG_CD,tgt.BRNG_NOISE_PRCSR_QTY=src.BRNG_NOISE_PRCSR_QTY,tgt.BRNG_NOISE_CLSFR_VALUE_QTY=src.BRNG_NOISE_CLSFR_VALUE_QTY,tgt.BRNG_NON_BRNG_NOISE_CD=src.BRNG_NON_BRNG_NOISE_CD,tgt.RPRTD_BRNG_ALARM_RAIL_1_CD=src.RPRTD_BRNG_ALARM_RAIL_1_CD,tgt.RPRTD_BRNG_ALARM_RAIL_2_CD=src.RPRTD_BRNG_ALARM_RAIL_2_CD,tgt.RPRTD_WHEEL_ALARM_RAIL_1_CD=src.RPRTD_WHEEL_ALARM_RAIL_1_CD,tgt.RPRTD_WHEEL_ALARM_RAIL_2_CD=src.RPRTD_WHEEL_ALARM_RAIL_2_CD,tgt.RPRTD_TIME_SCNR_OFF_SCNDS_QTY=src.RPRTD_TIME_SCNR_OFF_SCNDS_QTY,tgt.RPRTD_TIME_SCNR_ON_SCNDS_QTY=src.RPRTD_TIME_SCNR_ON_SCNDS_QTY,tgt.KVALUE_TRN_CH1=src.KVALUE_TRN_CH1,tgt.KVALUE_TRN_CH2=src.KVALUE_TRN_CH2,tgt.KVALUE_EQP_CH1=src.KVALUE_EQP_CH1,tgt.KVALUE_EQP_CH2=src.KVALUE_EQP_CH2,tgt.TRUCK_OVERLOAD=src.TRUCK_OVERLOAD,tgt.RPRTD_TAPINGPTY_COORD=src.RPRTD_TAPINGPTY_COORD,tgt.RPRTD_CMPNT_WIDTH_QTY=src.RPRTD_CMPNT_WIDTH_QTY,tgt.RPRTD_DATA_QUALITY_FLAG=src.RPRTD_DATA_QUALITY_FLAG,tgt.RPRTD_LV_RATIO_CRIB1=src.RPRTD_LV_RATIO_CRIB1,tgt.RPRTD_LV_RATIO_CRIB2=src.RPRTD_LV_RATIO_CRIB2,tgt.RPRTD_HUNTING_P=src.RPRTD_HUNTING_P,tgt.RPRTD_HUNTING_A=src.RPRTD_HUNTING_A,tgt.RPRTD_HUNTING_F=src.RPRTD_HUNTING_F,tgt.RPRTD_HUNTING_W=src.RPRTD_HUNTING_W,tgt.RPRTD_IAM=src.RPRTD_IAM,tgt.RPRTD_ROT=src.RPRTD_ROT,tgt.RPRTD_TE=src.RPRTD_TE,tgt.RPRTD_SHIFT=src.RPRTD_SHIFT,tgt.RPRTD_AOA=src.RPRTD_AOA,tgt.RPRTD_TP=src.RPRTD_TP,tgt.RPRTD_TRUCKSPACING=src.RPRTD_TRUCKSPACING,tgt.SNW_OPERATION_TYPE=src.SNW_OPERATION_TYPE,tgt.SNW_OPERATION_OWNER=src.SNW_OPERATION_OWNER,tgt.SNW_LAST_REPLICATED=src.SNW_LAST_REPLICATED,
        tgt.CDC_OPERATION='INSERT',tgt.CDC_TIMESTAMP=CURRENT_TIMESTAMP(),tgt.IS_DELETED=FALSE,tgt.RECORD_UPDATED_AT=CURRENT_TIMESTAMP(),tgt.SOURCE_LOAD_BATCH_ID=src.BATCH_ID
    
    WHEN NOT MATCHED AND src.CDC_ACTION='INSERT' THEN INSERT (DTCTD_EQPMNT_CMPNT_ID,CREATE_USER_ID,RECORD_CREATE_TMS,RECORD_UPDATE_TMS,UPDATE_USER_ID,DTCTD_EQPMNT_ID,SOURCE_CREATE_TMS,SOURCE_UPDATE_TMS,RPRTD_EQPMNT_CMPNT_NM,RPRTD_CMPNT_ON_TRAIN_SQNC_NBR,RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR,RPRTD_CMPNT_ON_PARENT_SQNC_NBR,PARENT_DTCTD_EQPMNT_CMPNT_ID,RPRTD_AAR_TRUCK_ID,RPRTD_CMPNT_AXLE_FILE_NM,RPRTD_CMPNT_SIDE_CD,RPRTD_WHEEL_TMPRTR_CHNL_1_QTY,RPRTD_WHEEL_TMPRTR_CHNL_2_QTY,RPRTD_BRNG_HEAT_CHNL_1_QTY,RPRTD_BRNG_HEAT_CHNL_2_QTY,RPRTD_INVLD_DATA_DSCRPT_TXT,VRFD_RAIL_SIDE_CD,VRFD_EQPMNT_CMPNT_LCTN_CD,RPRTD_ANGLE_OF_ATTACK_QTY,RPRTD_BRNG_ALARM_RAIL_1_CD_OLD,RPRTD_BRNG_ALARM_RAIL_2_CD_OLD,RPRTD_WHL_ALARM_RAIL_1_CD_OLD,RPRTD_WHL_ALARM_RAIL_2_CD_OLD,RPRTD_DRGNG_EQPMNT_ALARM_CD,RPRTD_HIGH_LOAD_ALARM_CD,RPRTD_WIDE_LOAD_ALARM_CD,RPRTD_BID_DCLRD_CD,RPRTD_BID_RAW_CHNL_1_CD,RPRTD_BID_RAW_CHNL_2_CD,RPRTD_MISS_OPEN_CD,RPRTD_TBOGI_CMPNT_SPEED_QTY,RPRTD_WPD_CMPNT_SPEED_QTY,RPRTD_CMPNT_SUB_CTGRY_CD,RPRTD_CNFDNC_NBR,RPRTD_DEVICE_RLTV_DRCTN_CD,RPRTD_CMPNT_PRMRY_SPEED_QTY,RPRTD_HNTNG_INDEX_NBR,RPRTD_CMPNT_LDNG_SPAN_QTY,RPRTD_CMPNT_LENGTH_QTY,RPRTD_DSTNC_FROM_PRVCMP_QTY,RPRTD_CMPNT_TMPRTR_QTY,RPRTD_DRTN_SCNDS_QTY,RPRTD_TRCKNG_OFFSET_QTY,RPRTD_TRUCK_NMNL_WEIGHT_QTY,RPRTD_CMPNT_WEIGHT_QTY,WHEEL_SIGMA_CHNL_1_NBR,WHEEL_SIGMA_CHNL_2_NBR,BRNG_SIGMA_CHNL_1_NBR,BRNG_SIGMA_CHNL_2_NBR,RPRTD_PITCH_QTY,RPRTD_BUILD_UP_TREAD_QTY,RPRTD_ECNTRC_FORCE_QTY,RPRTD_ECNTRC_VRTN_FORCE_QTY,RPRTD_FLANGE_ANGLE_QTY,RPRTD_FLANGE_GRDNT_QTY,RPRTD_FLANGE_HEIGHT_QTY,RPRTD_FLANGE_THCKNS_QTY,RPRTD_GRVD_TREAD_LENGTH_QTY,RPRTD_LOAD_QTY,RPRTD_LTRL_AVRG_LOAD_QTY,RPRTD_LTRL_PEAK_LOAD_QTY,RPRTD_NEW_AVRG_QTY,RPRTD_PEAK_FORCE_QTY,RPRTD_RIM_THCKNS_QTY,RPRTD_THIN_FLANGE_LENGTH_QTY,RPRTD_TREAD_HOLLOW_LENGTH_QTY,RPRTD_TREAD_TAPER_LENGTH_QTY,RPRTD_VRTCL_FLANGE_QTY,RPRTD_GAUGE_QTY,RPRTD_TIME_FROM_FIRST_AXLE_QTY,RPRTD_LRWHL_DELTA_DMTR_QTY,RPRTD_WHEEL_BKTOBK_DSTNC_QTY,RPRTD_LRWHL_DELTA_DMTR_CD,RPRTD_WHEEL_BKTOBK_DSTNC_CD,RPRTD_ANGLE_OF_ATTACK_CD,RPRTD_WHEEL_PSTN_ON_RAIL_QTY,RPRTD_BRKSHO_UPR_THCKNS_QTY,RPRTD_BRKSHO_LWR_THCKNS_QTY,RPRTD_FLANGE_HEIGHT_CD,RPRTD_FLANGE_THCKNS_CD,RPRTD_RIM_THCKNS_CD,RPRTD_CMPNT_LENGTH_CD,RPRTD_TREAD_HOLLOW_LENGTH_CD,RPRTD_FLANGE_ANGLE_CD,RPRTD_WHEEL_PSTN_ON_RAIL_CD,RPRTD_BRKSHO_UPR_THCKNS_CD,RPRTD_BRKSHO_LWR_THCKNS_CD,BRNG_SIZE_CLASS_CD,BRNG_DEFECT_CODE_TXT,BRNG_DEFECT_RNKNG_CD,BRNG_NOISE_PRCSR_QTY,BRNG_NOISE_CLSFR_VALUE_QTY,BRNG_NON_BRNG_NOISE_CD,RPRTD_BRNG_ALARM_RAIL_1_CD,RPRTD_BRNG_ALARM_RAIL_2_CD,RPRTD_WHEEL_ALARM_RAIL_1_CD,RPRTD_WHEEL_ALARM_RAIL_2_CD,RPRTD_TIME_SCNR_OFF_SCNDS_QTY,RPRTD_TIME_SCNR_ON_SCNDS_QTY,KVALUE_TRN_CH1,KVALUE_TRN_CH2,KVALUE_EQP_CH1,KVALUE_EQP_CH2,TRUCK_OVERLOAD,RPRTD_TAPINGPTY_COORD,RPRTD_CMPNT_WIDTH_QTY,RPRTD_DATA_QUALITY_FLAG,RPRTD_LV_RATIO_CRIB1,RPRTD_LV_RATIO_CRIB2,RPRTD_HUNTING_P,RPRTD_HUNTING_A,RPRTD_HUNTING_F,RPRTD_HUNTING_W,RPRTD_IAM,RPRTD_ROT,RPRTD_TE,RPRTD_SHIFT,RPRTD_AOA,RPRTD_TP,RPRTD_TRUCKSPACING,SNW_OPERATION_TYPE,SNW_OPERATION_OWNER,SNW_LAST_REPLICATED,CDC_OPERATION,CDC_TIMESTAMP,IS_DELETED,RECORD_CREATED_AT,RECORD_UPDATED_AT,SOURCE_LOAD_BATCH_ID)
    VALUES (src.DTCTD_EQPMNT_CMPNT_ID,src.CREATE_USER_ID,src.RECORD_CREATE_TMS,src.RECORD_UPDATE_TMS,src.UPDATE_USER_ID,src.DTCTD_EQPMNT_ID,src.SOURCE_CREATE_TMS,src.SOURCE_UPDATE_TMS,src.RPRTD_EQPMNT_CMPNT_NM,src.RPRTD_CMPNT_ON_TRAIN_SQNC_NBR,src.RPRTD_CMPNT_ON_EQPMNT_SQNC_NBR,src.RPRTD_CMPNT_ON_PARENT_SQNC_NBR,src.PARENT_DTCTD_EQPMNT_CMPNT_ID,src.RPRTD_AAR_TRUCK_ID,src.RPRTD_CMPNT_AXLE_FILE_NM,src.RPRTD_CMPNT_SIDE_CD,src.RPRTD_WHEEL_TMPRTR_CHNL_1_QTY,src.RPRTD_WHEEL_TMPRTR_CHNL_2_QTY,src.RPRTD_BRNG_HEAT_CHNL_1_QTY,src.RPRTD_BRNG_HEAT_CHNL_2_QTY,src.RPRTD_INVLD_DATA_DSCRPT_TXT,src.VRFD_RAIL_SIDE_CD,src.VRFD_EQPMNT_CMPNT_LCTN_CD,src.RPRTD_ANGLE_OF_ATTACK_QTY,src.RPRTD_BRNG_ALARM_RAIL_1_CD_OLD,src.RPRTD_BRNG_ALARM_RAIL_2_CD_OLD,src.RPRTD_WHL_ALARM_RAIL_1_CD_OLD,src.RPRTD_WHL_ALARM_RAIL_2_CD_OLD,src.RPRTD_DRGNG_EQPMNT_ALARM_CD,src.RPRTD_HIGH_LOAD_ALARM_CD,src.RPRTD_WIDE_LOAD_ALARM_CD,src.RPRTD_BID_DCLRD_CD,src.RPRTD_BID_RAW_CHNL_1_CD,src.RPRTD_BID_RAW_CHNL_2_CD,src.RPRTD_MISS_OPEN_CD,src.RPRTD_TBOGI_CMPNT_SPEED_QTY,src.RPRTD_WPD_CMPNT_SPEED_QTY,src.RPRTD_CMPNT_SUB_CTGRY_CD,src.RPRTD_CNFDNC_NBR,src.RPRTD_DEVICE_RLTV_DRCTN_CD,src.RPRTD_CMPNT_PRMRY_SPEED_QTY,src.RPRTD_HNTNG_INDEX_NBR,src.RPRTD_CMPNT_LDNG_SPAN_QTY,src.RPRTD_CMPNT_LENGTH_QTY,src.RPRTD_DSTNC_FROM_PRVCMP_QTY,src.RPRTD_CMPNT_TMPRTR_QTY,src.RPRTD_DRTN_SCNDS_QTY,src.RPRTD_TRCKNG_OFFSET_QTY,src.RPRTD_TRUCK_NMNL_WEIGHT_QTY,src.RPRTD_CMPNT_WEIGHT_QTY,src.WHEEL_SIGMA_CHNL_1_NBR,src.WHEEL_SIGMA_CHNL_2_NBR,src.BRNG_SIGMA_CHNL_1_NBR,src.BRNG_SIGMA_CHNL_2_NBR,src.RPRTD_PITCH_QTY,src.RPRTD_BUILD_UP_TREAD_QTY,src.RPRTD_ECNTRC_FORCE_QTY,src.RPRTD_ECNTRC_VRTN_FORCE_QTY,src.RPRTD_FLANGE_ANGLE_QTY,src.RPRTD_FLANGE_GRDNT_QTY,src.RPRTD_FLANGE_HEIGHT_QTY,src.RPRTD_FLANGE_THCKNS_QTY,src.RPRTD_GRVD_TREAD_LENGTH_QTY,src.RPRTD_LOAD_QTY,src.RPRTD_LTRL_AVRG_LOAD_QTY,src.RPRTD_LTRL_PEAK_LOAD_QTY,src.RPRTD_NEW_AVRG_QTY,src.RPRTD_PEAK_FORCE_QTY,src.RPRTD_RIM_THCKNS_QTY,src.RPRTD_THIN_FLANGE_LENGTH_QTY,src.RPRTD_TREAD_HOLLOW_LENGTH_QTY,src.RPRTD_TREAD_TAPER_LENGTH_QTY,src.RPRTD_VRTCL_FLANGE_QTY,src.RPRTD_GAUGE_QTY,src.RPRTD_TIME_FROM_FIRST_AXLE_QTY,src.RPRTD_LRWHL_DELTA_DMTR_QTY,src.RPRTD_WHEEL_BKTOBK_DSTNC_QTY,src.RPRTD_LRWHL_DELTA_DMTR_CD,src.RPRTD_WHEEL_BKTOBK_DSTNC_CD,src.RPRTD_ANGLE_OF_ATTACK_CD,src.RPRTD_WHEEL_PSTN_ON_RAIL_QTY,src.RPRTD_BRKSHO_UPR_THCKNS_QTY,src.RPRTD_BRKSHO_LWR_THCKNS_QTY,src.RPRTD_FLANGE_HEIGHT_CD,src.RPRTD_FLANGE_THCKNS_CD,src.RPRTD_RIM_THCKNS_CD,src.RPRTD_CMPNT_LENGTH_CD,src.RPRTD_TREAD_HOLLOW_LENGTH_CD,src.RPRTD_FLANGE_ANGLE_CD,src.RPRTD_WHEEL_PSTN_ON_RAIL_CD,src.RPRTD_BRKSHO_UPR_THCKNS_CD,src.RPRTD_BRKSHO_LWR_THCKNS_CD,src.BRNG_SIZE_CLASS_CD,src.BRNG_DEFECT_CODE_TXT,src.BRNG_DEFECT_RNKNG_CD,src.BRNG_NOISE_PRCSR_QTY,src.BRNG_NOISE_CLSFR_VALUE_QTY,src.BRNG_NON_BRNG_NOISE_CD,src.RPRTD_BRNG_ALARM_RAIL_1_CD,src.RPRTD_BRNG_ALARM_RAIL_2_CD,src.RPRTD_WHEEL_ALARM_RAIL_1_CD,src.RPRTD_WHEEL_ALARM_RAIL_2_CD,src.RPRTD_TIME_SCNR_OFF_SCNDS_QTY,src.RPRTD_TIME_SCNR_ON_SCNDS_QTY,src.KVALUE_TRN_CH1,src.KVALUE_TRN_CH2,src.KVALUE_EQP_CH1,src.KVALUE_EQP_CH2,src.TRUCK_OVERLOAD,src.RPRTD_TAPINGPTY_COORD,src.RPRTD_CMPNT_WIDTH_QTY,src.RPRTD_DATA_QUALITY_FLAG,src.RPRTD_LV_RATIO_CRIB1,src.RPRTD_LV_RATIO_CRIB2,src.RPRTD_HUNTING_P,src.RPRTD_HUNTING_A,src.RPRTD_HUNTING_F,src.RPRTD_HUNTING_W,src.RPRTD_IAM,src.RPRTD_ROT,src.RPRTD_TE,src.RPRTD_SHIFT,src.RPRTD_AOA,src.RPRTD_TP,src.RPRTD_TRUCKSPACING,src.SNW_OPERATION_TYPE,src.SNW_OPERATION_OWNER,src.SNW_LAST_REPLICATED,'INSERT',CURRENT_TIMESTAMP(),FALSE,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),src.BATCH_ID);
    
    v_rows_merged := SQLROWCOUNT;
    v_end_time := CURRENT_TIMESTAMP();
    DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT;
    
    INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME,BATCH_ID,EXECUTION_STATUS,START_TIME,END_TIME,ROWS_PROCESSED,ROWS_INSERTED,ROWS_UPDATED,ROWS_DELETED,ERROR_MESSAGE,CREATED_AT) VALUES ('EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT',:v_batch_id,'SUCCESS',:v_start_time,:v_end_time,:v_rows_merged,:v_rows_inserted,:v_rows_updated,:v_rows_deleted,NULL,CURRENT_TIMESTAMP());
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes (I:' || v_rows_inserted || ' U:' || v_rows_updated || ' D:' || v_rows_deleted || '). Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        v_end_time := CURRENT_TIMESTAMP();
        v_error_msg := SQLERRM;
        DROP TABLE IF EXISTS _CDC_STAGING_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT;
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (TABLE_NAME,BATCH_ID,EXECUTION_STATUS,START_TIME,END_TIME,ROWS_PROCESSED,ROWS_INSERTED,ROWS_UPDATED,ROWS_DELETED,ERROR_MESSAGE,CREATED_AT) VALUES ('EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT',:v_batch_id,'ERROR',:v_start_time,:v_end_time,0,0,0,0,:v_error_msg,CURRENT_TIMESTAMP());
        RETURN 'ERROR: ' || v_error_msg || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT_BASE CDC changes into data preservation table'
AS
    CALL D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT();

ALTER TASK D_RAW.EHMS.TASK_PROCESS_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT%' IN SCHEMA D_BRONZE.EHMS;
-- SHOW STREAMS LIKE 'EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT%' IN SCHEMA D_RAW.EHMS;
-- SHOW TASKS LIKE 'TASK_PROCESS_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT%' IN SCHEMA D_RAW.EHMS;
-- CALL D_RAW.EHMS.SP_PROCESS_EHMSAPP_DTQ_DTCTD_EQPMNT_CMPNT();
