/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE
================================================================================
Source Table : D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE
Target Table : D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT
Stream       : D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_EQPMV_RFEQP_MVMNT_EVENT()
Task         : D_RAW.SADB.TASK_PROCESS_EQPMV_RFEQP_MVMNT_EVENT
Primary Key  : EVENT_ID (Single)
Total Columns: 90 source + 6 CDC metadata = 96
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT (
    EVENT_ID NUMBER(18,0) NOT NULL,
    EQPMT_EVENT_TYPE_ID NUMBER(18,0),
    SCAC_CD VARCHAR(16),
    FSAC_CD VARCHAR(20),
    TRSTN_VRSN_NBR NUMBER(5,0),
    RPT_SCAC_CD VARCHAR(16),
    RPT_FSAC_CD VARCHAR(20),
    RPT_TRSTN_VRSN_NBR NUMBER(5,0),
    AAR_CAR_TYPE_CD VARCHAR(16),
    AAR_CAR_TYPE_VRSN_NBR NUMBER(5,0),
    LGLNT_SLCTN_ID NUMBER(5,0),
    SLCTN_VRSN_NBR NUMBER(5,0),
    SLCTN_DATA_BASE_CN VARCHAR(8),
    LCTN_DATA_BASE_CN VARCHAR(8),
    LGLNT_LCTN_ID NUMBER(10,0),
    SPLC_CD VARCHAR(24),
    NTWRK_NODE_ID NUMBER(18,0),
    REPORT_TMS TIMESTAMP_NTZ(0),
    SQNC_NBR NUMBER(5,0),
    LOAD_EMPTY_IND VARCHAR(4),
    DRCTN_CD VARCHAR(4),
    SOURCE_SYSTEM_NM VARCHAR(40),
    LSOP_PRFL_NBR VARCHAR(32),
    TITAN_NBR VARCHAR(24),
    MARK_CD VARCHAR(16),
    EQPUN_NBR VARCHAR(40),
    OPTRN_LEG_ID NUMBER(18,0),
    OPTRN_TMS TIMESTAMP_NTZ(0),
    TRAIN_PLAN_LEG_ID NUMBER(18,0),
    TRAIN_PLAN_EVENT_ID NUMBER(18,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    REPORT_TIME_ZONE VARCHAR(8),
    ESTRN_STND_REPORT_TMS TIMESTAMP_NTZ(0),
    CONSIST_ORIGIN_NBR NUMBER(6,0),
    CONSIST_NBR VARCHAR(16),
    COMMON_YARDS_SITE_CD VARCHAR(4),
    COMMON_YARDS_TRACK_NM VARCHAR(20),
    MILE_NBR NUMBER(8,3),
    SHRT_DSTR_NM VARCHAR(40),
    RUN_NBR_CD VARCHAR(12),
    CYCLE_SERIAL_NBR NUMBER(10,0),
    EQPUN_ORNTN_CD VARCHAR(4),
    INTRCH_MOVE_ATHRTY_CD VARCHAR(8),
    COMMON_YARDS_TAG_ID VARCHAR(24),
    LGLNT_ID NUMBER(10,0),
    LGLNT_DATA_BASE_CN VARCHAR(8),
    LGLNT_VRSN_NBR NUMBER(5,0),
    CSTMR_ENTITY_IDNTFR_CD VARCHAR(12),
    DMRG_TYPE_CD VARCHAR(4),
    EVENT_STATUS_CD VARCHAR(4),
    DMRG_RPRTNG_EXCPTN_CD VARCHAR(4),
    TRAIN_TYPE_CD VARCHAR(16),
    AAR_LBLTY_CNTNTY_MSG_CD VARCHAR(4),
    TRNSFR_OF_LBLTY_CD VARCHAR(8),
    CNST_DSTNTN_FSAC_CD VARCHAR(20),
    MTP_ROUTE_POINT_SQNC_NBR NUMBER(3,0),
    EQPMT_EVENT_REASON_CD VARCHAR(32),
    AEIRD_NBR VARCHAR(16),
    OPTRN_EVENT_ID NUMBER(18,0),
    TRAVEL_DRCTN_CD VARCHAR(20),
    SWITCH_LIST_NBR NUMBER(5,0),
    TYES_TRAIN_ID NUMBER(18,0),
    LGLNT_LCTN_STN_RFRNC_ID NUMBER(18,0),
    INDSTR_RLTV_SQNC_NBR NUMBER(2,0),
    TRACK_FSAC_CD VARCHAR(20),
    TRACK_RFRNC_LCTN_ID NUMBER(18,0),
    TRACK_SHORT_ENGL_NM VARCHAR(40),
    LGLNT_VRSN_ID NUMBER(18,0),
    AAR_SHPR_RJCTN_CD VARCHAR(8),
    TRIP_END_IND VARCHAR(4),
    EQPMT_ID NUMBER(18,0),
    BLOCK_NM VARCHAR(140),
    CLASS_CD VARCHAR(28),
    CLASS_CODE_CTGRY_CD VARCHAR(12),
    INTRNL_OPRTNL_HNDLNG_CD VARCHAR(16),
    OPRTNL_HNDLNG_CD VARCHAR(16),
    INDSTR_NM VARCHAR(12),
    EXCTN_BLOCK_ID NUMBER(18,0),
    EXCTN_BLOCK_CTGRY_CD VARCHAR(40),
    EXCTN_BLOCK_ORIGIN_SCAC_CD VARCHAR(16),
    EXCTN_BLOCK_ORIGIN_FSAC_CD VARCHAR(20),
    EXCTN_BLOCK_DSTNTN_SCAC_CD VARCHAR(16),
    EXCTN_BLOCK_DSTNTN_FSAC_CD VARCHAR(20),
    EXCTN_PLND_BLOCK_NM VARCHAR(140),
    EXCTN_RPRTD_BLOCK_NM VARCHAR(140),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    -- CDC Metadata columns for data preservation
    CDC_OPERATION VARCHAR(10),  
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,    -- Soft delete flag
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100), 

    PRIMARY KEY (EVENT_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for EQPMV_RFEQP_MVMNT_EVENT_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.SADB.SP_PROCESS_EQPMV_RFEQP_MVMNT_EVENT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    
    -- =========================================================================
    -- CHECK 1: Detect if stream is stale (happens after IDMC truncate/reload)
    -- =========================================================================
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        
        CREATE OR REPLACE STREAM D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
        ON TABLE D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE src
            LEFT JOIN D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT tgt 
                ON src.EVENT_ID = tgt.EVENT_ID
            WHERE tgt.EVENT_ID IS NULL
               OR tgt.IS_DELETED = TRUE
        ) AS src
        ON tgt.EVENT_ID = src.EVENT_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.EQPMT_EVENT_TYPE_ID = src.EQPMT_EVENT_TYPE_ID,
            tgt.SCAC_CD = src.SCAC_CD,
            tgt.FSAC_CD = src.FSAC_CD,
            tgt.TRSTN_VRSN_NBR = src.TRSTN_VRSN_NBR,
            tgt.RPT_SCAC_CD = src.RPT_SCAC_CD,
            tgt.RPT_FSAC_CD = src.RPT_FSAC_CD,
            tgt.RPT_TRSTN_VRSN_NBR = src.RPT_TRSTN_VRSN_NBR,
            tgt.AAR_CAR_TYPE_CD = src.AAR_CAR_TYPE_CD,
            tgt.AAR_CAR_TYPE_VRSN_NBR = src.AAR_CAR_TYPE_VRSN_NBR,
            tgt.LGLNT_SLCTN_ID = src.LGLNT_SLCTN_ID,
            tgt.SLCTN_VRSN_NBR = src.SLCTN_VRSN_NBR,
            tgt.SLCTN_DATA_BASE_CN = src.SLCTN_DATA_BASE_CN,
            tgt.LCTN_DATA_BASE_CN = src.LCTN_DATA_BASE_CN,
            tgt.LGLNT_LCTN_ID = src.LGLNT_LCTN_ID,
            tgt.SPLC_CD = src.SPLC_CD,
            tgt.NTWRK_NODE_ID = src.NTWRK_NODE_ID,
            tgt.REPORT_TMS = src.REPORT_TMS,
            tgt.SQNC_NBR = src.SQNC_NBR,
            tgt.LOAD_EMPTY_IND = src.LOAD_EMPTY_IND,
            tgt.DRCTN_CD = src.DRCTN_CD,
            tgt.SOURCE_SYSTEM_NM = src.SOURCE_SYSTEM_NM,
            tgt.LSOP_PRFL_NBR = src.LSOP_PRFL_NBR,
            tgt.TITAN_NBR = src.TITAN_NBR,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.OPTRN_LEG_ID = src.OPTRN_LEG_ID,
            tgt.OPTRN_TMS = src.OPTRN_TMS,
            tgt.TRAIN_PLAN_LEG_ID = src.TRAIN_PLAN_LEG_ID,
            tgt.TRAIN_PLAN_EVENT_ID = src.TRAIN_PLAN_EVENT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.REPORT_TIME_ZONE = src.REPORT_TIME_ZONE,
            tgt.ESTRN_STND_REPORT_TMS = src.ESTRN_STND_REPORT_TMS,
            tgt.CONSIST_ORIGIN_NBR = src.CONSIST_ORIGIN_NBR,
            tgt.CONSIST_NBR = src.CONSIST_NBR,
            tgt.COMMON_YARDS_SITE_CD = src.COMMON_YARDS_SITE_CD,
            tgt.COMMON_YARDS_TRACK_NM = src.COMMON_YARDS_TRACK_NM,
            tgt.MILE_NBR = src.MILE_NBR,
            tgt.SHRT_DSTR_NM = src.SHRT_DSTR_NM,
            tgt.RUN_NBR_CD = src.RUN_NBR_CD,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.EQPUN_ORNTN_CD = src.EQPUN_ORNTN_CD,
            tgt.INTRCH_MOVE_ATHRTY_CD = src.INTRCH_MOVE_ATHRTY_CD,
            tgt.COMMON_YARDS_TAG_ID = src.COMMON_YARDS_TAG_ID,
            tgt.LGLNT_ID = src.LGLNT_ID,
            tgt.LGLNT_DATA_BASE_CN = src.LGLNT_DATA_BASE_CN,
            tgt.LGLNT_VRSN_NBR = src.LGLNT_VRSN_NBR,
            tgt.CSTMR_ENTITY_IDNTFR_CD = src.CSTMR_ENTITY_IDNTFR_CD,
            tgt.DMRG_TYPE_CD = src.DMRG_TYPE_CD,
            tgt.EVENT_STATUS_CD = src.EVENT_STATUS_CD,
            tgt.DMRG_RPRTNG_EXCPTN_CD = src.DMRG_RPRTNG_EXCPTN_CD,
            tgt.TRAIN_TYPE_CD = src.TRAIN_TYPE_CD,
            tgt.AAR_LBLTY_CNTNTY_MSG_CD = src.AAR_LBLTY_CNTNTY_MSG_CD,
            tgt.TRNSFR_OF_LBLTY_CD = src.TRNSFR_OF_LBLTY_CD,
            tgt.CNST_DSTNTN_FSAC_CD = src.CNST_DSTNTN_FSAC_CD,
            tgt.MTP_ROUTE_POINT_SQNC_NBR = src.MTP_ROUTE_POINT_SQNC_NBR,
            tgt.EQPMT_EVENT_REASON_CD = src.EQPMT_EVENT_REASON_CD,
            tgt.AEIRD_NBR = src.AEIRD_NBR,
            tgt.OPTRN_EVENT_ID = src.OPTRN_EVENT_ID,
            tgt.TRAVEL_DRCTN_CD = src.TRAVEL_DRCTN_CD,
            tgt.SWITCH_LIST_NBR = src.SWITCH_LIST_NBR,
            tgt.TYES_TRAIN_ID = src.TYES_TRAIN_ID,
            tgt.LGLNT_LCTN_STN_RFRNC_ID = src.LGLNT_LCTN_STN_RFRNC_ID,
            tgt.INDSTR_RLTV_SQNC_NBR = src.INDSTR_RLTV_SQNC_NBR,
            tgt.TRACK_FSAC_CD = src.TRACK_FSAC_CD,
            tgt.TRACK_RFRNC_LCTN_ID = src.TRACK_RFRNC_LCTN_ID,
            tgt.TRACK_SHORT_ENGL_NM = src.TRACK_SHORT_ENGL_NM,
            tgt.LGLNT_VRSN_ID = src.LGLNT_VRSN_ID,
            tgt.AAR_SHPR_RJCTN_CD = src.AAR_SHPR_RJCTN_CD,
            tgt.TRIP_END_IND = src.TRIP_END_IND,
            tgt.EQPMT_ID = src.EQPMT_ID,
            tgt.BLOCK_NM = src.BLOCK_NM,
            tgt.CLASS_CD = src.CLASS_CD,
            tgt.CLASS_CODE_CTGRY_CD = src.CLASS_CODE_CTGRY_CD,
            tgt.INTRNL_OPRTNL_HNDLNG_CD = src.INTRNL_OPRTNL_HNDLNG_CD,
            tgt.OPRTNL_HNDLNG_CD = src.OPRTNL_HNDLNG_CD,
            tgt.INDSTR_NM = src.INDSTR_NM,
            tgt.EXCTN_BLOCK_ID = src.EXCTN_BLOCK_ID,
            tgt.EXCTN_BLOCK_CTGRY_CD = src.EXCTN_BLOCK_CTGRY_CD,
            tgt.EXCTN_BLOCK_ORIGIN_SCAC_CD = src.EXCTN_BLOCK_ORIGIN_SCAC_CD,
            tgt.EXCTN_BLOCK_ORIGIN_FSAC_CD = src.EXCTN_BLOCK_ORIGIN_FSAC_CD,
            tgt.EXCTN_BLOCK_DSTNTN_SCAC_CD = src.EXCTN_BLOCK_DSTNTN_SCAC_CD,
            tgt.EXCTN_BLOCK_DSTNTN_FSAC_CD = src.EXCTN_BLOCK_DSTNTN_FSAC_CD,
            tgt.EXCTN_PLND_BLOCK_NM = src.EXCTN_PLND_BLOCK_NM,
            tgt.EXCTN_RPRTD_BLOCK_NM = src.EXCTN_RPRTD_BLOCK_NM,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            EVENT_ID, EQPMT_EVENT_TYPE_ID, SCAC_CD, FSAC_CD, TRSTN_VRSN_NBR,
            RPT_SCAC_CD, RPT_FSAC_CD, RPT_TRSTN_VRSN_NBR, AAR_CAR_TYPE_CD, AAR_CAR_TYPE_VRSN_NBR,
            LGLNT_SLCTN_ID, SLCTN_VRSN_NBR, SLCTN_DATA_BASE_CN, LCTN_DATA_BASE_CN, LGLNT_LCTN_ID,
            SPLC_CD, NTWRK_NODE_ID, REPORT_TMS, SQNC_NBR, LOAD_EMPTY_IND,
            DRCTN_CD, SOURCE_SYSTEM_NM, LSOP_PRFL_NBR, TITAN_NBR, MARK_CD,
            EQPUN_NBR, OPTRN_LEG_ID, OPTRN_TMS, TRAIN_PLAN_LEG_ID, TRAIN_PLAN_EVENT_ID,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, REPORT_TIME_ZONE,
            ESTRN_STND_REPORT_TMS, CONSIST_ORIGIN_NBR, CONSIST_NBR, COMMON_YARDS_SITE_CD, COMMON_YARDS_TRACK_NM,
            MILE_NBR, SHRT_DSTR_NM, RUN_NBR_CD, CYCLE_SERIAL_NBR, EQPUN_ORNTN_CD,
            INTRCH_MOVE_ATHRTY_CD, COMMON_YARDS_TAG_ID, LGLNT_ID, LGLNT_DATA_BASE_CN, LGLNT_VRSN_NBR,
            CSTMR_ENTITY_IDNTFR_CD, DMRG_TYPE_CD, EVENT_STATUS_CD, DMRG_RPRTNG_EXCPTN_CD, TRAIN_TYPE_CD,
            AAR_LBLTY_CNTNTY_MSG_CD, TRNSFR_OF_LBLTY_CD, CNST_DSTNTN_FSAC_CD, MTP_ROUTE_POINT_SQNC_NBR, EQPMT_EVENT_REASON_CD,
            AEIRD_NBR, OPTRN_EVENT_ID, TRAVEL_DRCTN_CD, SWITCH_LIST_NBR, TYES_TRAIN_ID,
            LGLNT_LCTN_STN_RFRNC_ID, INDSTR_RLTV_SQNC_NBR, TRACK_FSAC_CD, TRACK_RFRNC_LCTN_ID, TRACK_SHORT_ENGL_NM,
            LGLNT_VRSN_ID, AAR_SHPR_RJCTN_CD, TRIP_END_IND, EQPMT_ID, BLOCK_NM,
            CLASS_CD, CLASS_CODE_CTGRY_CD, INTRNL_OPRTNL_HNDLNG_CD, OPRTNL_HNDLNG_CD, INDSTR_NM,
            EXCTN_BLOCK_ID, EXCTN_BLOCK_CTGRY_CD, EXCTN_BLOCK_ORIGIN_SCAC_CD, EXCTN_BLOCK_ORIGIN_FSAC_CD, EXCTN_BLOCK_DSTNTN_SCAC_CD,
            EXCTN_BLOCK_DSTNTN_FSAC_CD, EXCTN_PLND_BLOCK_NM, EXCTN_RPRTD_BLOCK_NM, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.EVENT_ID, src.EQPMT_EVENT_TYPE_ID, src.SCAC_CD, src.FSAC_CD, src.TRSTN_VRSN_NBR,
            src.RPT_SCAC_CD, src.RPT_FSAC_CD, src.RPT_TRSTN_VRSN_NBR, src.AAR_CAR_TYPE_CD, src.AAR_CAR_TYPE_VRSN_NBR,
            src.LGLNT_SLCTN_ID, src.SLCTN_VRSN_NBR, src.SLCTN_DATA_BASE_CN, src.LCTN_DATA_BASE_CN, src.LGLNT_LCTN_ID,
            src.SPLC_CD, src.NTWRK_NODE_ID, src.REPORT_TMS, src.SQNC_NBR, src.LOAD_EMPTY_IND,
            src.DRCTN_CD, src.SOURCE_SYSTEM_NM, src.LSOP_PRFL_NBR, src.TITAN_NBR, src.MARK_CD,
            src.EQPUN_NBR, src.OPTRN_LEG_ID, src.OPTRN_TMS, src.TRAIN_PLAN_LEG_ID, src.TRAIN_PLAN_EVENT_ID,
            src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID, src.REPORT_TIME_ZONE,
            src.ESTRN_STND_REPORT_TMS, src.CONSIST_ORIGIN_NBR, src.CONSIST_NBR, src.COMMON_YARDS_SITE_CD, src.COMMON_YARDS_TRACK_NM,
            src.MILE_NBR, src.SHRT_DSTR_NM, src.RUN_NBR_CD, src.CYCLE_SERIAL_NBR, src.EQPUN_ORNTN_CD,
            src.INTRCH_MOVE_ATHRTY_CD, src.COMMON_YARDS_TAG_ID, src.LGLNT_ID, src.LGLNT_DATA_BASE_CN, src.LGLNT_VRSN_NBR,
            src.CSTMR_ENTITY_IDNTFR_CD, src.DMRG_TYPE_CD, src.EVENT_STATUS_CD, src.DMRG_RPRTNG_EXCPTN_CD, src.TRAIN_TYPE_CD,
            src.AAR_LBLTY_CNTNTY_MSG_CD, src.TRNSFR_OF_LBLTY_CD, src.CNST_DSTNTN_FSAC_CD, src.MTP_ROUTE_POINT_SQNC_NBR, src.EQPMT_EVENT_REASON_CD,
            src.AEIRD_NBR, src.OPTRN_EVENT_ID, src.TRAVEL_DRCTN_CD, src.SWITCH_LIST_NBR, src.TYES_TRAIN_ID,
            src.LGLNT_LCTN_STN_RFRNC_ID, src.INDSTR_RLTV_SQNC_NBR, src.TRACK_FSAC_CD, src.TRACK_RFRNC_LCTN_ID, src.TRACK_SHORT_ENGL_NM,
            src.LGLNT_VRSN_ID, src.AAR_SHPR_RJCTN_CD, src.TRIP_END_IND, src.EQPMT_ID, src.BLOCK_NM,
            src.CLASS_CD, src.CLASS_CODE_CTGRY_CD, src.INTRNL_OPRTNL_HNDLNG_CD, src.OPRTNL_HNDLNG_CD, src.INDSTR_NM,
            src.EXCTN_BLOCK_ID, src.EXCTN_BLOCK_CTGRY_CD, src.EXCTN_BLOCK_ORIGIN_SCAC_CD, src.EXCTN_BLOCK_ORIGIN_FSAC_CD, src.EXCTN_BLOCK_DSTNTN_SCAC_CD,
            src.EXCTN_BLOCK_DSTNTN_FSAC_CD, src.EXCTN_PLND_BLOCK_NM, src.EXCTN_RPRTD_BLOCK_NM, src.SNW_OPERATION_TYPE, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_EQPMV_RFEQP_MVMNT_EVENT AS
    SELECT 
        EVENT_ID, EQPMT_EVENT_TYPE_ID, SCAC_CD, FSAC_CD, TRSTN_VRSN_NBR,
        RPT_SCAC_CD, RPT_FSAC_CD, RPT_TRSTN_VRSN_NBR, AAR_CAR_TYPE_CD, AAR_CAR_TYPE_VRSN_NBR,
        LGLNT_SLCTN_ID, SLCTN_VRSN_NBR, SLCTN_DATA_BASE_CN, LCTN_DATA_BASE_CN, LGLNT_LCTN_ID,
        SPLC_CD, NTWRK_NODE_ID, REPORT_TMS, SQNC_NBR, LOAD_EMPTY_IND,
        DRCTN_CD, SOURCE_SYSTEM_NM, LSOP_PRFL_NBR, TITAN_NBR, MARK_CD,
        EQPUN_NBR, OPTRN_LEG_ID, OPTRN_TMS, TRAIN_PLAN_LEG_ID, TRAIN_PLAN_EVENT_ID,
        RECORD_CREATE_TMS, RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, REPORT_TIME_ZONE,
        ESTRN_STND_REPORT_TMS, CONSIST_ORIGIN_NBR, CONSIST_NBR, COMMON_YARDS_SITE_CD, COMMON_YARDS_TRACK_NM,
        MILE_NBR, SHRT_DSTR_NM, RUN_NBR_CD, CYCLE_SERIAL_NBR, EQPUN_ORNTN_CD,
        INTRCH_MOVE_ATHRTY_CD, COMMON_YARDS_TAG_ID, LGLNT_ID, LGLNT_DATA_BASE_CN, LGLNT_VRSN_NBR,
        CSTMR_ENTITY_IDNTFR_CD, DMRG_TYPE_CD, EVENT_STATUS_CD, DMRG_RPRTNG_EXCPTN_CD, TRAIN_TYPE_CD,
        AAR_LBLTY_CNTNTY_MSG_CD, TRNSFR_OF_LBLTY_CD, CNST_DSTNTN_FSAC_CD, MTP_ROUTE_POINT_SQNC_NBR, EQPMT_EVENT_REASON_CD,
        AEIRD_NBR, OPTRN_EVENT_ID, TRAVEL_DRCTN_CD, SWITCH_LIST_NBR, TYES_TRAIN_ID,
        LGLNT_LCTN_STN_RFRNC_ID, INDSTR_RLTV_SQNC_NBR, TRACK_FSAC_CD, TRACK_RFRNC_LCTN_ID, TRACK_SHORT_ENGL_NM,
        LGLNT_VRSN_ID, AAR_SHPR_RJCTN_CD, TRIP_END_IND, EQPMT_ID, BLOCK_NM,
        CLASS_CD, CLASS_CODE_CTGRY_CD, INTRNL_OPRTNL_HNDLNG_CD, OPRTNL_HNDLNG_CD, INDSTR_NM,
        EXCTN_BLOCK_ID, EXCTN_BLOCK_CTGRY_CD, EXCTN_BLOCK_ORIGIN_SCAC_CD, EXCTN_BLOCK_ORIGIN_FSAC_CD, EXCTN_BLOCK_DSTNTN_SCAC_CD,
        EXCTN_BLOCK_DSTNTN_FSAC_CD, EXCTN_PLND_BLOCK_NM, EXCTN_RPRTD_BLOCK_NM, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_EQPMV_RFEQP_MVMNT_EVENT;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_EQPMV_RFEQP_MVMNT_EVENT;
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT AS tgt
    USING (
        SELECT 
            EVENT_ID, EQPMT_EVENT_TYPE_ID, SCAC_CD, FSAC_CD, TRSTN_VRSN_NBR,
            RPT_SCAC_CD, RPT_FSAC_CD, RPT_TRSTN_VRSN_NBR, AAR_CAR_TYPE_CD, AAR_CAR_TYPE_VRSN_NBR,
            LGLNT_SLCTN_ID, SLCTN_VRSN_NBR, SLCTN_DATA_BASE_CN, LCTN_DATA_BASE_CN, LGLNT_LCTN_ID,
            SPLC_CD, NTWRK_NODE_ID, REPORT_TMS, SQNC_NBR, LOAD_EMPTY_IND,
            DRCTN_CD, SOURCE_SYSTEM_NM, LSOP_PRFL_NBR, TITAN_NBR, MARK_CD,
            EQPUN_NBR, OPTRN_LEG_ID, OPTRN_TMS, TRAIN_PLAN_LEG_ID, TRAIN_PLAN_EVENT_ID,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, REPORT_TIME_ZONE,
            ESTRN_STND_REPORT_TMS, CONSIST_ORIGIN_NBR, CONSIST_NBR, COMMON_YARDS_SITE_CD, COMMON_YARDS_TRACK_NM,
            MILE_NBR, SHRT_DSTR_NM, RUN_NBR_CD, CYCLE_SERIAL_NBR, EQPUN_ORNTN_CD,
            INTRCH_MOVE_ATHRTY_CD, COMMON_YARDS_TAG_ID, LGLNT_ID, LGLNT_DATA_BASE_CN, LGLNT_VRSN_NBR,
            CSTMR_ENTITY_IDNTFR_CD, DMRG_TYPE_CD, EVENT_STATUS_CD, DMRG_RPRTNG_EXCPTN_CD, TRAIN_TYPE_CD,
            AAR_LBLTY_CNTNTY_MSG_CD, TRNSFR_OF_LBLTY_CD, CNST_DSTNTN_FSAC_CD, MTP_ROUTE_POINT_SQNC_NBR, EQPMT_EVENT_REASON_CD,
            AEIRD_NBR, OPTRN_EVENT_ID, TRAVEL_DRCTN_CD, SWITCH_LIST_NBR, TYES_TRAIN_ID,
            LGLNT_LCTN_STN_RFRNC_ID, INDSTR_RLTV_SQNC_NBR, TRACK_FSAC_CD, TRACK_RFRNC_LCTN_ID, TRACK_SHORT_ENGL_NM,
            LGLNT_VRSN_ID, AAR_SHPR_RJCTN_CD, TRIP_END_IND, EQPMT_ID, BLOCK_NM,
            CLASS_CD, CLASS_CODE_CTGRY_CD, INTRNL_OPRTNL_HNDLNG_CD, OPRTNL_HNDLNG_CD, INDSTR_NM,
            EXCTN_BLOCK_ID, EXCTN_BLOCK_CTGRY_CD, EXCTN_BLOCK_ORIGIN_SCAC_CD, EXCTN_BLOCK_ORIGIN_FSAC_CD, EXCTN_BLOCK_DSTNTN_SCAC_CD,
            EXCTN_BLOCK_DSTNTN_FSAC_CD, EXCTN_PLND_BLOCK_NM, EXCTN_RPRTD_BLOCK_NM, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_ACTION,
            CDC_IS_UPDATE,
            ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_EQPMV_RFEQP_MVMNT_EVENT
    ) AS src
    ON tgt.EVENT_ID = src.EVENT_ID
    
    -- UPDATE scenario (METADATA$ACTION='INSERT' AND METADATA$ISUPDATE=TRUE)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.EQPMT_EVENT_TYPE_ID = src.EQPMT_EVENT_TYPE_ID,
            tgt.SCAC_CD = src.SCAC_CD,
            tgt.FSAC_CD = src.FSAC_CD,
            tgt.TRSTN_VRSN_NBR = src.TRSTN_VRSN_NBR,
            tgt.RPT_SCAC_CD = src.RPT_SCAC_CD,
            tgt.RPT_FSAC_CD = src.RPT_FSAC_CD,
            tgt.RPT_TRSTN_VRSN_NBR = src.RPT_TRSTN_VRSN_NBR,
            tgt.AAR_CAR_TYPE_CD = src.AAR_CAR_TYPE_CD,
            tgt.AAR_CAR_TYPE_VRSN_NBR = src.AAR_CAR_TYPE_VRSN_NBR,
            tgt.LGLNT_SLCTN_ID = src.LGLNT_SLCTN_ID,
            tgt.SLCTN_VRSN_NBR = src.SLCTN_VRSN_NBR,
            tgt.SLCTN_DATA_BASE_CN = src.SLCTN_DATA_BASE_CN,
            tgt.LCTN_DATA_BASE_CN = src.LCTN_DATA_BASE_CN,
            tgt.LGLNT_LCTN_ID = src.LGLNT_LCTN_ID,
            tgt.SPLC_CD = src.SPLC_CD,
            tgt.NTWRK_NODE_ID = src.NTWRK_NODE_ID,
            tgt.REPORT_TMS = src.REPORT_TMS,
            tgt.SQNC_NBR = src.SQNC_NBR,
            tgt.LOAD_EMPTY_IND = src.LOAD_EMPTY_IND,
            tgt.DRCTN_CD = src.DRCTN_CD,
            tgt.SOURCE_SYSTEM_NM = src.SOURCE_SYSTEM_NM,
            tgt.LSOP_PRFL_NBR = src.LSOP_PRFL_NBR,
            tgt.TITAN_NBR = src.TITAN_NBR,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.OPTRN_LEG_ID = src.OPTRN_LEG_ID,
            tgt.OPTRN_TMS = src.OPTRN_TMS,
            tgt.TRAIN_PLAN_LEG_ID = src.TRAIN_PLAN_LEG_ID,
            tgt.TRAIN_PLAN_EVENT_ID = src.TRAIN_PLAN_EVENT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.REPORT_TIME_ZONE = src.REPORT_TIME_ZONE,
            tgt.ESTRN_STND_REPORT_TMS = src.ESTRN_STND_REPORT_TMS,
            tgt.CONSIST_ORIGIN_NBR = src.CONSIST_ORIGIN_NBR,
            tgt.CONSIST_NBR = src.CONSIST_NBR,
            tgt.COMMON_YARDS_SITE_CD = src.COMMON_YARDS_SITE_CD,
            tgt.COMMON_YARDS_TRACK_NM = src.COMMON_YARDS_TRACK_NM,
            tgt.MILE_NBR = src.MILE_NBR,
            tgt.SHRT_DSTR_NM = src.SHRT_DSTR_NM,
            tgt.RUN_NBR_CD = src.RUN_NBR_CD,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.EQPUN_ORNTN_CD = src.EQPUN_ORNTN_CD,
            tgt.INTRCH_MOVE_ATHRTY_CD = src.INTRCH_MOVE_ATHRTY_CD,
            tgt.COMMON_YARDS_TAG_ID = src.COMMON_YARDS_TAG_ID,
            tgt.LGLNT_ID = src.LGLNT_ID,
            tgt.LGLNT_DATA_BASE_CN = src.LGLNT_DATA_BASE_CN,
            tgt.LGLNT_VRSN_NBR = src.LGLNT_VRSN_NBR,
            tgt.CSTMR_ENTITY_IDNTFR_CD = src.CSTMR_ENTITY_IDNTFR_CD,
            tgt.DMRG_TYPE_CD = src.DMRG_TYPE_CD,
            tgt.EVENT_STATUS_CD = src.EVENT_STATUS_CD,
            tgt.DMRG_RPRTNG_EXCPTN_CD = src.DMRG_RPRTNG_EXCPTN_CD,
            tgt.TRAIN_TYPE_CD = src.TRAIN_TYPE_CD,
            tgt.AAR_LBLTY_CNTNTY_MSG_CD = src.AAR_LBLTY_CNTNTY_MSG_CD,
            tgt.TRNSFR_OF_LBLTY_CD = src.TRNSFR_OF_LBLTY_CD,
            tgt.CNST_DSTNTN_FSAC_CD = src.CNST_DSTNTN_FSAC_CD,
            tgt.MTP_ROUTE_POINT_SQNC_NBR = src.MTP_ROUTE_POINT_SQNC_NBR,
            tgt.EQPMT_EVENT_REASON_CD = src.EQPMT_EVENT_REASON_CD,
            tgt.AEIRD_NBR = src.AEIRD_NBR,
            tgt.OPTRN_EVENT_ID = src.OPTRN_EVENT_ID,
            tgt.TRAVEL_DRCTN_CD = src.TRAVEL_DRCTN_CD,
            tgt.SWITCH_LIST_NBR = src.SWITCH_LIST_NBR,
            tgt.TYES_TRAIN_ID = src.TYES_TRAIN_ID,
            tgt.LGLNT_LCTN_STN_RFRNC_ID = src.LGLNT_LCTN_STN_RFRNC_ID,
            tgt.INDSTR_RLTV_SQNC_NBR = src.INDSTR_RLTV_SQNC_NBR,
            tgt.TRACK_FSAC_CD = src.TRACK_FSAC_CD,
            tgt.TRACK_RFRNC_LCTN_ID = src.TRACK_RFRNC_LCTN_ID,
            tgt.TRACK_SHORT_ENGL_NM = src.TRACK_SHORT_ENGL_NM,
            tgt.LGLNT_VRSN_ID = src.LGLNT_VRSN_ID,
            tgt.AAR_SHPR_RJCTN_CD = src.AAR_SHPR_RJCTN_CD,
            tgt.TRIP_END_IND = src.TRIP_END_IND,
            tgt.EQPMT_ID = src.EQPMT_ID,
            tgt.BLOCK_NM = src.BLOCK_NM,
            tgt.CLASS_CD = src.CLASS_CD,
            tgt.CLASS_CODE_CTGRY_CD = src.CLASS_CODE_CTGRY_CD,
            tgt.INTRNL_OPRTNL_HNDLNG_CD = src.INTRNL_OPRTNL_HNDLNG_CD,
            tgt.OPRTNL_HNDLNG_CD = src.OPRTNL_HNDLNG_CD,
            tgt.INDSTR_NM = src.INDSTR_NM,
            tgt.EXCTN_BLOCK_ID = src.EXCTN_BLOCK_ID,
            tgt.EXCTN_BLOCK_CTGRY_CD = src.EXCTN_BLOCK_CTGRY_CD,
            tgt.EXCTN_BLOCK_ORIGIN_SCAC_CD = src.EXCTN_BLOCK_ORIGIN_SCAC_CD,
            tgt.EXCTN_BLOCK_ORIGIN_FSAC_CD = src.EXCTN_BLOCK_ORIGIN_FSAC_CD,
            tgt.EXCTN_BLOCK_DSTNTN_SCAC_CD = src.EXCTN_BLOCK_DSTNTN_SCAC_CD,
            tgt.EXCTN_BLOCK_DSTNTN_FSAC_CD = src.EXCTN_BLOCK_DSTNTN_FSAC_CD,
            tgt.EXCTN_PLND_BLOCK_NM = src.EXCTN_PLND_BLOCK_NM,
            tgt.EXCTN_RPRTD_BLOCK_NM = src.EXCTN_RPRTD_BLOCK_NM,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- DELETE scenario (METADATA$ACTION='DELETE' AND METADATA$ISUPDATE=FALSE)
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- RE-INSERT scenario (record exists but being re-inserted)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.EQPMT_EVENT_TYPE_ID = src.EQPMT_EVENT_TYPE_ID,
            tgt.SCAC_CD = src.SCAC_CD,
            tgt.FSAC_CD = src.FSAC_CD,
            tgt.TRSTN_VRSN_NBR = src.TRSTN_VRSN_NBR,
            tgt.RPT_SCAC_CD = src.RPT_SCAC_CD,
            tgt.RPT_FSAC_CD = src.RPT_FSAC_CD,
            tgt.RPT_TRSTN_VRSN_NBR = src.RPT_TRSTN_VRSN_NBR,
            tgt.AAR_CAR_TYPE_CD = src.AAR_CAR_TYPE_CD,
            tgt.AAR_CAR_TYPE_VRSN_NBR = src.AAR_CAR_TYPE_VRSN_NBR,
            tgt.LGLNT_SLCTN_ID = src.LGLNT_SLCTN_ID,
            tgt.SLCTN_VRSN_NBR = src.SLCTN_VRSN_NBR,
            tgt.SLCTN_DATA_BASE_CN = src.SLCTN_DATA_BASE_CN,
            tgt.LCTN_DATA_BASE_CN = src.LCTN_DATA_BASE_CN,
            tgt.LGLNT_LCTN_ID = src.LGLNT_LCTN_ID,
            tgt.SPLC_CD = src.SPLC_CD,
            tgt.NTWRK_NODE_ID = src.NTWRK_NODE_ID,
            tgt.REPORT_TMS = src.REPORT_TMS,
            tgt.SQNC_NBR = src.SQNC_NBR,
            tgt.LOAD_EMPTY_IND = src.LOAD_EMPTY_IND,
            tgt.DRCTN_CD = src.DRCTN_CD,
            tgt.SOURCE_SYSTEM_NM = src.SOURCE_SYSTEM_NM,
            tgt.LSOP_PRFL_NBR = src.LSOP_PRFL_NBR,
            tgt.TITAN_NBR = src.TITAN_NBR,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.OPTRN_LEG_ID = src.OPTRN_LEG_ID,
            tgt.OPTRN_TMS = src.OPTRN_TMS,
            tgt.TRAIN_PLAN_LEG_ID = src.TRAIN_PLAN_LEG_ID,
            tgt.TRAIN_PLAN_EVENT_ID = src.TRAIN_PLAN_EVENT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.REPORT_TIME_ZONE = src.REPORT_TIME_ZONE,
            tgt.ESTRN_STND_REPORT_TMS = src.ESTRN_STND_REPORT_TMS,
            tgt.CONSIST_ORIGIN_NBR = src.CONSIST_ORIGIN_NBR,
            tgt.CONSIST_NBR = src.CONSIST_NBR,
            tgt.COMMON_YARDS_SITE_CD = src.COMMON_YARDS_SITE_CD,
            tgt.COMMON_YARDS_TRACK_NM = src.COMMON_YARDS_TRACK_NM,
            tgt.MILE_NBR = src.MILE_NBR,
            tgt.SHRT_DSTR_NM = src.SHRT_DSTR_NM,
            tgt.RUN_NBR_CD = src.RUN_NBR_CD,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.EQPUN_ORNTN_CD = src.EQPUN_ORNTN_CD,
            tgt.INTRCH_MOVE_ATHRTY_CD = src.INTRCH_MOVE_ATHRTY_CD,
            tgt.COMMON_YARDS_TAG_ID = src.COMMON_YARDS_TAG_ID,
            tgt.LGLNT_ID = src.LGLNT_ID,
            tgt.LGLNT_DATA_BASE_CN = src.LGLNT_DATA_BASE_CN,
            tgt.LGLNT_VRSN_NBR = src.LGLNT_VRSN_NBR,
            tgt.CSTMR_ENTITY_IDNTFR_CD = src.CSTMR_ENTITY_IDNTFR_CD,
            tgt.DMRG_TYPE_CD = src.DMRG_TYPE_CD,
            tgt.EVENT_STATUS_CD = src.EVENT_STATUS_CD,
            tgt.DMRG_RPRTNG_EXCPTN_CD = src.DMRG_RPRTNG_EXCPTN_CD,
            tgt.TRAIN_TYPE_CD = src.TRAIN_TYPE_CD,
            tgt.AAR_LBLTY_CNTNTY_MSG_CD = src.AAR_LBLTY_CNTNTY_MSG_CD,
            tgt.TRNSFR_OF_LBLTY_CD = src.TRNSFR_OF_LBLTY_CD,
            tgt.CNST_DSTNTN_FSAC_CD = src.CNST_DSTNTN_FSAC_CD,
            tgt.MTP_ROUTE_POINT_SQNC_NBR = src.MTP_ROUTE_POINT_SQNC_NBR,
            tgt.EQPMT_EVENT_REASON_CD = src.EQPMT_EVENT_REASON_CD,
            tgt.AEIRD_NBR = src.AEIRD_NBR,
            tgt.OPTRN_EVENT_ID = src.OPTRN_EVENT_ID,
            tgt.TRAVEL_DRCTN_CD = src.TRAVEL_DRCTN_CD,
            tgt.SWITCH_LIST_NBR = src.SWITCH_LIST_NBR,
            tgt.TYES_TRAIN_ID = src.TYES_TRAIN_ID,
            tgt.LGLNT_LCTN_STN_RFRNC_ID = src.LGLNT_LCTN_STN_RFRNC_ID,
            tgt.INDSTR_RLTV_SQNC_NBR = src.INDSTR_RLTV_SQNC_NBR,
            tgt.TRACK_FSAC_CD = src.TRACK_FSAC_CD,
            tgt.TRACK_RFRNC_LCTN_ID = src.TRACK_RFRNC_LCTN_ID,
            tgt.TRACK_SHORT_ENGL_NM = src.TRACK_SHORT_ENGL_NM,
            tgt.LGLNT_VRSN_ID = src.LGLNT_VRSN_ID,
            tgt.AAR_SHPR_RJCTN_CD = src.AAR_SHPR_RJCTN_CD,
            tgt.TRIP_END_IND = src.TRIP_END_IND,
            tgt.EQPMT_ID = src.EQPMT_ID,
            tgt.BLOCK_NM = src.BLOCK_NM,
            tgt.CLASS_CD = src.CLASS_CD,
            tgt.CLASS_CODE_CTGRY_CD = src.CLASS_CODE_CTGRY_CD,
            tgt.INTRNL_OPRTNL_HNDLNG_CD = src.INTRNL_OPRTNL_HNDLNG_CD,
            tgt.OPRTNL_HNDLNG_CD = src.OPRTNL_HNDLNG_CD,
            tgt.INDSTR_NM = src.INDSTR_NM,
            tgt.EXCTN_BLOCK_ID = src.EXCTN_BLOCK_ID,
            tgt.EXCTN_BLOCK_CTGRY_CD = src.EXCTN_BLOCK_CTGRY_CD,
            tgt.EXCTN_BLOCK_ORIGIN_SCAC_CD = src.EXCTN_BLOCK_ORIGIN_SCAC_CD,
            tgt.EXCTN_BLOCK_ORIGIN_FSAC_CD = src.EXCTN_BLOCK_ORIGIN_FSAC_CD,
            tgt.EXCTN_BLOCK_DSTNTN_SCAC_CD = src.EXCTN_BLOCK_DSTNTN_SCAC_CD,
            tgt.EXCTN_BLOCK_DSTNTN_FSAC_CD = src.EXCTN_BLOCK_DSTNTN_FSAC_CD,
            tgt.EXCTN_PLND_BLOCK_NM = src.EXCTN_PLND_BLOCK_NM,
            tgt.EXCTN_RPRTD_BLOCK_NM = src.EXCTN_RPRTD_BLOCK_NM,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- NEW INSERT scenario
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            EVENT_ID, EQPMT_EVENT_TYPE_ID, SCAC_CD, FSAC_CD, TRSTN_VRSN_NBR,
            RPT_SCAC_CD, RPT_FSAC_CD, RPT_TRSTN_VRSN_NBR, AAR_CAR_TYPE_CD, AAR_CAR_TYPE_VRSN_NBR,
            LGLNT_SLCTN_ID, SLCTN_VRSN_NBR, SLCTN_DATA_BASE_CN, LCTN_DATA_BASE_CN, LGLNT_LCTN_ID,
            SPLC_CD, NTWRK_NODE_ID, REPORT_TMS, SQNC_NBR, LOAD_EMPTY_IND,
            DRCTN_CD, SOURCE_SYSTEM_NM, LSOP_PRFL_NBR, TITAN_NBR, MARK_CD,
            EQPUN_NBR, OPTRN_LEG_ID, OPTRN_TMS, TRAIN_PLAN_LEG_ID, TRAIN_PLAN_EVENT_ID,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, REPORT_TIME_ZONE,
            ESTRN_STND_REPORT_TMS, CONSIST_ORIGIN_NBR, CONSIST_NBR, COMMON_YARDS_SITE_CD, COMMON_YARDS_TRACK_NM,
            MILE_NBR, SHRT_DSTR_NM, RUN_NBR_CD, CYCLE_SERIAL_NBR, EQPUN_ORNTN_CD,
            INTRCH_MOVE_ATHRTY_CD, COMMON_YARDS_TAG_ID, LGLNT_ID, LGLNT_DATA_BASE_CN, LGLNT_VRSN_NBR,
            CSTMR_ENTITY_IDNTFR_CD, DMRG_TYPE_CD, EVENT_STATUS_CD, DMRG_RPRTNG_EXCPTN_CD, TRAIN_TYPE_CD,
            AAR_LBLTY_CNTNTY_MSG_CD, TRNSFR_OF_LBLTY_CD, CNST_DSTNTN_FSAC_CD, MTP_ROUTE_POINT_SQNC_NBR, EQPMT_EVENT_REASON_CD,
            AEIRD_NBR, OPTRN_EVENT_ID, TRAVEL_DRCTN_CD, SWITCH_LIST_NBR, TYES_TRAIN_ID,
            LGLNT_LCTN_STN_RFRNC_ID, INDSTR_RLTV_SQNC_NBR, TRACK_FSAC_CD, TRACK_RFRNC_LCTN_ID, TRACK_SHORT_ENGL_NM,
            LGLNT_VRSN_ID, AAR_SHPR_RJCTN_CD, TRIP_END_IND, EQPMT_ID, BLOCK_NM,
            CLASS_CD, CLASS_CODE_CTGRY_CD, INTRNL_OPRTNL_HNDLNG_CD, OPRTNL_HNDLNG_CD, INDSTR_NM,
            EXCTN_BLOCK_ID, EXCTN_BLOCK_CTGRY_CD, EXCTN_BLOCK_ORIGIN_SCAC_CD, EXCTN_BLOCK_ORIGIN_FSAC_CD, EXCTN_BLOCK_DSTNTN_SCAC_CD,
            EXCTN_BLOCK_DSTNTN_FSAC_CD, EXCTN_PLND_BLOCK_NM, EXCTN_RPRTD_BLOCK_NM, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.EVENT_ID, src.EQPMT_EVENT_TYPE_ID, src.SCAC_CD, src.FSAC_CD, src.TRSTN_VRSN_NBR,
            src.RPT_SCAC_CD, src.RPT_FSAC_CD, src.RPT_TRSTN_VRSN_NBR, src.AAR_CAR_TYPE_CD, src.AAR_CAR_TYPE_VRSN_NBR,
            src.LGLNT_SLCTN_ID, src.SLCTN_VRSN_NBR, src.SLCTN_DATA_BASE_CN, src.LCTN_DATA_BASE_CN, src.LGLNT_LCTN_ID,
            src.SPLC_CD, src.NTWRK_NODE_ID, src.REPORT_TMS, src.SQNC_NBR, src.LOAD_EMPTY_IND,
            src.DRCTN_CD, src.SOURCE_SYSTEM_NM, src.LSOP_PRFL_NBR, src.TITAN_NBR, src.MARK_CD,
            src.EQPUN_NBR, src.OPTRN_LEG_ID, src.OPTRN_TMS, src.TRAIN_PLAN_LEG_ID, src.TRAIN_PLAN_EVENT_ID,
            src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID, src.REPORT_TIME_ZONE,
            src.ESTRN_STND_REPORT_TMS, src.CONSIST_ORIGIN_NBR, src.CONSIST_NBR, src.COMMON_YARDS_SITE_CD, src.COMMON_YARDS_TRACK_NM,
            src.MILE_NBR, src.SHRT_DSTR_NM, src.RUN_NBR_CD, src.CYCLE_SERIAL_NBR, src.EQPUN_ORNTN_CD,
            src.INTRCH_MOVE_ATHRTY_CD, src.COMMON_YARDS_TAG_ID, src.LGLNT_ID, src.LGLNT_DATA_BASE_CN, src.LGLNT_VRSN_NBR,
            src.CSTMR_ENTITY_IDNTFR_CD, src.DMRG_TYPE_CD, src.EVENT_STATUS_CD, src.DMRG_RPRTNG_EXCPTN_CD, src.TRAIN_TYPE_CD,
            src.AAR_LBLTY_CNTNTY_MSG_CD, src.TRNSFR_OF_LBLTY_CD, src.CNST_DSTNTN_FSAC_CD, src.MTP_ROUTE_POINT_SQNC_NBR, src.EQPMT_EVENT_REASON_CD,
            src.AEIRD_NBR, src.OPTRN_EVENT_ID, src.TRAVEL_DRCTN_CD, src.SWITCH_LIST_NBR, src.TYES_TRAIN_ID,
            src.LGLNT_LCTN_STN_RFRNC_ID, src.INDSTR_RLTV_SQNC_NBR, src.TRACK_FSAC_CD, src.TRACK_RFRNC_LCTN_ID, src.TRACK_SHORT_ENGL_NM,
            src.LGLNT_VRSN_ID, src.AAR_SHPR_RJCTN_CD, src.TRIP_END_IND, src.EQPMT_ID, src.BLOCK_NM,
            src.CLASS_CD, src.CLASS_CODE_CTGRY_CD, src.INTRNL_OPRTNL_HNDLNG_CD, src.OPRTNL_HNDLNG_CD, src.INDSTR_NM,
            src.EXCTN_BLOCK_ID, src.EXCTN_BLOCK_CTGRY_CD, src.EXCTN_BLOCK_ORIGIN_SCAC_CD, src.EXCTN_BLOCK_ORIGIN_FSAC_CD, src.EXCTN_BLOCK_DSTNTN_SCAC_CD,
            src.EXCTN_BLOCK_DSTNTN_FSAC_CD, src.EXCTN_PLND_BLOCK_NM, src.EXCTN_RPRTD_BLOCK_NM, src.SNW_OPERATION_TYPE, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    DROP TABLE IF EXISTS _CDC_STAGING_EQPMV_RFEQP_MVMNT_EVENT;
    
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes. Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        DROP TABLE IF EXISTS _CDC_STAGING_EQPMV_RFEQP_MVMNT_EVENT;
        RETURN 'ERROR: ' || SQLERRM || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.SADB.TASK_PROCESS_EQPMV_RFEQP_MVMNT_EVENT
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process EQPMV_RFEQP_MVMNT_EVENT_BASE CDC changes into data preservation table'
WHEN
    SYSTEM$STREAM_HAS_DATA('D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM')
AS
    CALL D_RAW.SADB.SP_PROCESS_EQPMV_RFEQP_MVMNT_EVENT();

ALTER TASK D_RAW.SADB.TASK_PROCESS_EQPMV_RFEQP_MVMNT_EVENT RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'EQPMV_RFEQP_MVMNT_EVENT%' IN SCHEMA D_BRONZE.SADB;
-- SHOW STREAMS LIKE 'EQPMV_RFEQP_MVMNT_EVENT%' IN SCHEMA D_RAW.SADB;
-- SHOW TASKS LIKE 'TASK_PROCESS_EQPMV_RFEQP%' IN SCHEMA D_RAW.SADB;
-- CALL D_RAW.SADB.SP_PROCESS_EQPMV_RFEQP_MVMNT_EVENT();
