/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.TRAIN_CNST_SMRY_BASE
================================================================================
Source Table : D_RAW.SADB.TRAIN_CNST_SMRY_BASE
Target Table : D_BRONZE.SADB.TRAIN_CNST_SMRY
Stream       : D_RAW.SADB.TRAIN_CNST_SMRY_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_TRAIN_CNST_SMRY()
Task         : D_RAW.SADB.TASK_PROCESS_TRAIN_CNST_SMRY
Primary Key  : COMPOSITE (TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR)
Total Columns: 87 source + 6 CDC metadata = 93
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.TRAIN_CNST_SMRY (
    TRAIN_CNST_SMRY_ID NUMBER(18,0) NOT NULL,
    TRAIN_CNST_SMRY_VRSN_NBR NUMBER(4,0) NOT NULL,
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    SOURCE_SYSTEM_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    SOURCE_SYSTEM_UPDATE_USER_ID VARCHAR(32),
    TRAIN_NM VARCHAR(32),
    CNST_PRTY_NBR NUMBER(1,0),
    LOADED_CARS_QTY NUMBER(3,0),
    EMPTY_CARS_QTY NUMBER(3,0),
    TOTAL_LENGTH_FEET_QTY NUMBER(10,0),
    ESTMTD_GROSS_TONS_QTY NUMBER(10,0),
    RQRD_LCMTV_QTY NUMBER(2,0),
    RQRD_TOTAL_HRSPWR_QTY NUMBER(5,0),
    RQRD_HRSPWR_PER_TON_QTY NUMBER(3,2),
    ACTUAL_LCMTV_QTY NUMBER(2,0),
    ACTUAL_TOTAL_HRSPWR_QTY NUMBER(5,0),
    ACTUAL_HRSPWR_PER_TON_QTY NUMBER(3,2),
    CNTNT_WEIGHT_TONS_QTY NUMBER(10,0),
    TRAIN_SPEED_RSTRCN_MPH_QTY NUMBER(3,0),
    TARE_WEIGHT_TONS_QTY NUMBER(10,0),
    SOURCE_SYSTEM_TRAIN_CNST_NBR VARCHAR(16),
    TITAN_NBR NUMBER(6,0),
    DATA_SOURCE_CD VARCHAR(40),
    TRAIN_DMNSNL_LOAD_RSTRCN_CD VARCHAR(12),
    DNGRS_CARS_STATUS_CD VARCHAR(68),
    CHNG_CNST_SMRY_STATUS_CD VARCHAR(60),
    LAST_RPRTD_CNST_SMRY_STATUS_CD VARCHAR(60),
    CNST_ORIGIN_TRN_PLN_EVENT_ID NUMBER(18,0),
    CNST_ORIGIN_SCAC_CD VARCHAR(16),
    CNST_ORIGIN_FSAC_CD VARCHAR(20),
    CNST_ORIGIN_TRSTN_VRSN_NBR NUMBER(5,0),
    CNST_ORIGIN_RTPT_SQNC_NBR NUMBER(3,0),
    CNST_DSTNTN_TRN_PLN_EVENT_ID NUMBER(18,0),
    CNST_DSTNTN_SCAC_CD VARCHAR(16),
    CNST_DSTNTN_FSAC_CD VARCHAR(20),
    CNST_DSTNTN_TRSTN_VRSN_NBR NUMBER(5,0),
    CNST_DSTNTN_RTPT_SQNC_NBR NUMBER(3,0),
    CNST_CHNG_PT_TRN_PLN_EVENT_ID NUMBER(18,0),
    CNST_CHNG_PT_OPTRN_EVENT_ID NUMBER(18,0),
    CNST_CHNG_PT_MVMNT_EVENT_ID NUMBER(18,0),
    CNST_CHNG_PT_SCAC_CD VARCHAR(16),
    CNST_CHNG_PT_FSAC_CD VARCHAR(20),
    CNST_CHNG_PT_TRSTN_VRSN_NBR NUMBER(5,0),
    CNST_CHNG_PT_RTPT_SQNC_NBR NUMBER(3,0),
    CNST_CHNG_PT_EVENT_TMS TIMESTAMP_NTZ(0),
    CNST_CHNG_RPRTNG_TM_ZN_CD VARCHAR(8),
    CNST_CHNG_RPRTNG_TM_ZN_YR_NBR NUMBER(4,0),
    LAST_RPRTD_OPTRN_EVENT_ID NUMBER(18,0),
    LAST_RPRTD_MVMNT_EVENT_ID NUMBER(18,0),
    LAST_RPRTD_SCAC_CD VARCHAR(16),
    LAST_RPRTD_FSAC_CD VARCHAR(20),
    LAST_RPRTD_TRSTN_VRSN_NBR NUMBER(5,0),
    LAST_RPRTD_RTPT_SQNC_NBR NUMBER(3,0),
    LAST_RPRTD_EVENT_TMS TIMESTAMP_NTZ(0),
    LAST_RPRTD_RPRTNG_TM_ZN_CD VARCHAR(8),
    LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR NUMBER(4,0),
    LEAD_LCMTV_MARK_CD VARCHAR(16),
    LEAD_LCMTV_EQPUN_NBR VARCHAR(40),
    SBU_MARK_CD VARCHAR(16),
    SBU_EQPUN_NBR VARCHAR(40),
    TYES_TRAIN_ID NUMBER(18,0),
    TRMNTD_TRAIN_IND VARCHAR(4),
    CNST_CHNG_DYLGHT_SVNGS_IND VARCHAR(4),
    CNST_CHNG_LOCAL_TMS TIMESTAMP_NTZ(0),
    CNST_CHNG_INTRMD_RTPNT_NBR NUMBER(5,0),
    TYES_FUNCTION_CD VARCHAR(32),
    EGT_WHLG_FACTOR_QTY NUMBER(2,0),
    CDN_MRSHL_VLTN_CD VARCHAR(4),
    USA_MRSHL_VLTN_CD VARCHAR(4),
    CLV_REJECT_IND VARCHAR(4),
    RCVRD_TRAIN_IND VARCHAR(4),
    SENT_TO_CLV_TMS TIMESTAMP_NTZ(0),
    MTCHD_DPRTR_ARVL_VRSN_NBR NUMBER(4,0),
    LAST_RPRTD_DYLGHT_SVNGS_IND VARCHAR(4),
    LAST_RPRTD_LOCAL_TMS TIMESTAMP_NTZ(0),
    LAST_RPRTD_INTRMD_RTPNT_NBR NUMBER(5,0),
    RUN_NBR VARCHAR(12),
    TRNSFR_RUN_NUMBER_TXT VARCHAR(16),
    TRAIN_CNST_ID NUMBER(18,0),
    AEIRD_NBR VARCHAR(16),
    OCS_UPDATE_CD VARCHAR(4),
    CNST_RAIL_EQPMNT_QTY NUMBER(3,0),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    -- CDC Metadata columns for data preservation
    CDC_OPERATION VARCHAR(10),  
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,    -- Soft delete flag
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100), 

    PRIMARY KEY (TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.SADB.TRAIN_CNST_SMRY_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.SADB.TRAIN_CNST_SMRY_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.TRAIN_CNST_SMRY_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for TRAIN_CNST_SMRY_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.SADB.SP_PROCESS_TRAIN_CNST_SMRY()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    
    -- =========================================================================
    -- CHECK 1: Detect if stream is stale (happens after IDMC truncate/reload)
    -- =========================================================================
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.SADB.TRAIN_CNST_SMRY_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        
        CREATE OR REPLACE STREAM D_RAW.SADB.TRAIN_CNST_SMRY_BASE_HIST_STREAM
        ON TABLE D_RAW.SADB.TRAIN_CNST_SMRY_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.SADB.TRAIN_CNST_SMRY AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.SADB.TRAIN_CNST_SMRY_BASE src
            LEFT JOIN D_BRONZE.SADB.TRAIN_CNST_SMRY tgt 
                ON src.TRAIN_CNST_SMRY_ID = tgt.TRAIN_CNST_SMRY_ID
                AND src.TRAIN_CNST_SMRY_VRSN_NBR = tgt.TRAIN_CNST_SMRY_VRSN_NBR
            WHERE tgt.TRAIN_CNST_SMRY_ID IS NULL
               OR tgt.IS_DELETED = TRUE
        ) AS src
        ON tgt.TRAIN_CNST_SMRY_ID = src.TRAIN_CNST_SMRY_ID
            AND tgt.TRAIN_CNST_SMRY_VRSN_NBR = src.TRAIN_CNST_SMRY_VRSN_NBR
        WHEN MATCHED THEN UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.SOURCE_SYSTEM_UPDATE_TMS = src.SOURCE_SYSTEM_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.SOURCE_SYSTEM_UPDATE_USER_ID = src.SOURCE_SYSTEM_UPDATE_USER_ID,
            tgt.TRAIN_NM = src.TRAIN_NM,
            tgt.CNST_PRTY_NBR = src.CNST_PRTY_NBR,
            tgt.LOADED_CARS_QTY = src.LOADED_CARS_QTY,
            tgt.EMPTY_CARS_QTY = src.EMPTY_CARS_QTY,
            tgt.TOTAL_LENGTH_FEET_QTY = src.TOTAL_LENGTH_FEET_QTY,
            tgt.ESTMTD_GROSS_TONS_QTY = src.ESTMTD_GROSS_TONS_QTY,
            tgt.RQRD_LCMTV_QTY = src.RQRD_LCMTV_QTY,
            tgt.RQRD_TOTAL_HRSPWR_QTY = src.RQRD_TOTAL_HRSPWR_QTY,
            tgt.RQRD_HRSPWR_PER_TON_QTY = src.RQRD_HRSPWR_PER_TON_QTY,
            tgt.ACTUAL_LCMTV_QTY = src.ACTUAL_LCMTV_QTY,
            tgt.ACTUAL_TOTAL_HRSPWR_QTY = src.ACTUAL_TOTAL_HRSPWR_QTY,
            tgt.ACTUAL_HRSPWR_PER_TON_QTY = src.ACTUAL_HRSPWR_PER_TON_QTY,
            tgt.CNTNT_WEIGHT_TONS_QTY = src.CNTNT_WEIGHT_TONS_QTY,
            tgt.TRAIN_SPEED_RSTRCN_MPH_QTY = src.TRAIN_SPEED_RSTRCN_MPH_QTY,
            tgt.TARE_WEIGHT_TONS_QTY = src.TARE_WEIGHT_TONS_QTY,
            tgt.SOURCE_SYSTEM_TRAIN_CNST_NBR = src.SOURCE_SYSTEM_TRAIN_CNST_NBR,
            tgt.TITAN_NBR = src.TITAN_NBR,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.TRAIN_DMNSNL_LOAD_RSTRCN_CD = src.TRAIN_DMNSNL_LOAD_RSTRCN_CD,
            tgt.DNGRS_CARS_STATUS_CD = src.DNGRS_CARS_STATUS_CD,
            tgt.CHNG_CNST_SMRY_STATUS_CD = src.CHNG_CNST_SMRY_STATUS_CD,
            tgt.LAST_RPRTD_CNST_SMRY_STATUS_CD = src.LAST_RPRTD_CNST_SMRY_STATUS_CD,
            tgt.CNST_ORIGIN_TRN_PLN_EVENT_ID = src.CNST_ORIGIN_TRN_PLN_EVENT_ID,
            tgt.CNST_ORIGIN_SCAC_CD = src.CNST_ORIGIN_SCAC_CD,
            tgt.CNST_ORIGIN_FSAC_CD = src.CNST_ORIGIN_FSAC_CD,
            tgt.CNST_ORIGIN_TRSTN_VRSN_NBR = src.CNST_ORIGIN_TRSTN_VRSN_NBR,
            tgt.CNST_ORIGIN_RTPT_SQNC_NBR = src.CNST_ORIGIN_RTPT_SQNC_NBR,
            tgt.CNST_DSTNTN_TRN_PLN_EVENT_ID = src.CNST_DSTNTN_TRN_PLN_EVENT_ID,
            tgt.CNST_DSTNTN_SCAC_CD = src.CNST_DSTNTN_SCAC_CD,
            tgt.CNST_DSTNTN_FSAC_CD = src.CNST_DSTNTN_FSAC_CD,
            tgt.CNST_DSTNTN_TRSTN_VRSN_NBR = src.CNST_DSTNTN_TRSTN_VRSN_NBR,
            tgt.CNST_DSTNTN_RTPT_SQNC_NBR = src.CNST_DSTNTN_RTPT_SQNC_NBR,
            tgt.CNST_CHNG_PT_TRN_PLN_EVENT_ID = src.CNST_CHNG_PT_TRN_PLN_EVENT_ID,
            tgt.CNST_CHNG_PT_OPTRN_EVENT_ID = src.CNST_CHNG_PT_OPTRN_EVENT_ID,
            tgt.CNST_CHNG_PT_MVMNT_EVENT_ID = src.CNST_CHNG_PT_MVMNT_EVENT_ID,
            tgt.CNST_CHNG_PT_SCAC_CD = src.CNST_CHNG_PT_SCAC_CD,
            tgt.CNST_CHNG_PT_FSAC_CD = src.CNST_CHNG_PT_FSAC_CD,
            tgt.CNST_CHNG_PT_TRSTN_VRSN_NBR = src.CNST_CHNG_PT_TRSTN_VRSN_NBR,
            tgt.CNST_CHNG_PT_RTPT_SQNC_NBR = src.CNST_CHNG_PT_RTPT_SQNC_NBR,
            tgt.CNST_CHNG_PT_EVENT_TMS = src.CNST_CHNG_PT_EVENT_TMS,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_CD = src.CNST_CHNG_RPRTNG_TM_ZN_CD,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR = src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            tgt.LAST_RPRTD_OPTRN_EVENT_ID = src.LAST_RPRTD_OPTRN_EVENT_ID,
            tgt.LAST_RPRTD_MVMNT_EVENT_ID = src.LAST_RPRTD_MVMNT_EVENT_ID,
            tgt.LAST_RPRTD_SCAC_CD = src.LAST_RPRTD_SCAC_CD,
            tgt.LAST_RPRTD_FSAC_CD = src.LAST_RPRTD_FSAC_CD,
            tgt.LAST_RPRTD_TRSTN_VRSN_NBR = src.LAST_RPRTD_TRSTN_VRSN_NBR,
            tgt.LAST_RPRTD_RTPT_SQNC_NBR = src.LAST_RPRTD_RTPT_SQNC_NBR,
            tgt.LAST_RPRTD_EVENT_TMS = src.LAST_RPRTD_EVENT_TMS,
            tgt.LAST_RPRTD_RPRTNG_TM_ZN_CD = src.LAST_RPRTD_RPRTNG_TM_ZN_CD,
            tgt.LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR = src.LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
            tgt.LEAD_LCMTV_MARK_CD = src.LEAD_LCMTV_MARK_CD,
            tgt.LEAD_LCMTV_EQPUN_NBR = src.LEAD_LCMTV_EQPUN_NBR,
            tgt.SBU_MARK_CD = src.SBU_MARK_CD,
            tgt.SBU_EQPUN_NBR = src.SBU_EQPUN_NBR,
            tgt.TYES_TRAIN_ID = src.TYES_TRAIN_ID,
            tgt.TRMNTD_TRAIN_IND = src.TRMNTD_TRAIN_IND,
            tgt.CNST_CHNG_DYLGHT_SVNGS_IND = src.CNST_CHNG_DYLGHT_SVNGS_IND,
            tgt.CNST_CHNG_LOCAL_TMS = src.CNST_CHNG_LOCAL_TMS,
            tgt.CNST_CHNG_INTRMD_RTPNT_NBR = src.CNST_CHNG_INTRMD_RTPNT_NBR,
            tgt.TYES_FUNCTION_CD = src.TYES_FUNCTION_CD,
            tgt.EGT_WHLG_FACTOR_QTY = src.EGT_WHLG_FACTOR_QTY,
            tgt.CDN_MRSHL_VLTN_CD = src.CDN_MRSHL_VLTN_CD,
            tgt.USA_MRSHL_VLTN_CD = src.USA_MRSHL_VLTN_CD,
            tgt.CLV_REJECT_IND = src.CLV_REJECT_IND,
            tgt.RCVRD_TRAIN_IND = src.RCVRD_TRAIN_IND,
            tgt.SENT_TO_CLV_TMS = src.SENT_TO_CLV_TMS,
            tgt.MTCHD_DPRTR_ARVL_VRSN_NBR = src.MTCHD_DPRTR_ARVL_VRSN_NBR,
            tgt.LAST_RPRTD_DYLGHT_SVNGS_IND = src.LAST_RPRTD_DYLGHT_SVNGS_IND,
            tgt.LAST_RPRTD_LOCAL_TMS = src.LAST_RPRTD_LOCAL_TMS,
            tgt.LAST_RPRTD_INTRMD_RTPNT_NBR = src.LAST_RPRTD_INTRMD_RTPNT_NBR,
            tgt.RUN_NBR = src.RUN_NBR,
            tgt.TRNSFR_RUN_NUMBER_TXT = src.TRNSFR_RUN_NUMBER_TXT,
            tgt.TRAIN_CNST_ID = src.TRAIN_CNST_ID,
            tgt.AEIRD_NBR = src.AEIRD_NBR,
            tgt.OCS_UPDATE_CD = src.OCS_UPDATE_CD,
            tgt.CNST_RAIL_EQPMNT_QTY = src.CNST_RAIL_EQPMNT_QTY,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, SOURCE_SYSTEM_UPDATE_TMS,
            CREATE_USER_ID, UPDATE_USER_ID, SOURCE_SYSTEM_UPDATE_USER_ID,
            TRAIN_NM, CNST_PRTY_NBR, LOADED_CARS_QTY, EMPTY_CARS_QTY,
            TOTAL_LENGTH_FEET_QTY, ESTMTD_GROSS_TONS_QTY, RQRD_LCMTV_QTY,
            RQRD_TOTAL_HRSPWR_QTY, RQRD_HRSPWR_PER_TON_QTY, ACTUAL_LCMTV_QTY,
            ACTUAL_TOTAL_HRSPWR_QTY, ACTUAL_HRSPWR_PER_TON_QTY, CNTNT_WEIGHT_TONS_QTY,
            TRAIN_SPEED_RSTRCN_MPH_QTY, TARE_WEIGHT_TONS_QTY, SOURCE_SYSTEM_TRAIN_CNST_NBR,
            TITAN_NBR, DATA_SOURCE_CD, TRAIN_DMNSNL_LOAD_RSTRCN_CD, DNGRS_CARS_STATUS_CD,
            CHNG_CNST_SMRY_STATUS_CD, LAST_RPRTD_CNST_SMRY_STATUS_CD,
            CNST_ORIGIN_TRN_PLN_EVENT_ID, CNST_ORIGIN_SCAC_CD, CNST_ORIGIN_FSAC_CD,
            CNST_ORIGIN_TRSTN_VRSN_NBR, CNST_ORIGIN_RTPT_SQNC_NBR,
            CNST_DSTNTN_TRN_PLN_EVENT_ID, CNST_DSTNTN_SCAC_CD, CNST_DSTNTN_FSAC_CD,
            CNST_DSTNTN_TRSTN_VRSN_NBR, CNST_DSTNTN_RTPT_SQNC_NBR,
            CNST_CHNG_PT_TRN_PLN_EVENT_ID, CNST_CHNG_PT_OPTRN_EVENT_ID, CNST_CHNG_PT_MVMNT_EVENT_ID,
            CNST_CHNG_PT_SCAC_CD, CNST_CHNG_PT_FSAC_CD, CNST_CHNG_PT_TRSTN_VRSN_NBR,
            CNST_CHNG_PT_RTPT_SQNC_NBR, CNST_CHNG_PT_EVENT_TMS,
            CNST_CHNG_RPRTNG_TM_ZN_CD, CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            LAST_RPRTD_OPTRN_EVENT_ID, LAST_RPRTD_MVMNT_EVENT_ID,
            LAST_RPRTD_SCAC_CD, LAST_RPRTD_FSAC_CD, LAST_RPRTD_TRSTN_VRSN_NBR,
            LAST_RPRTD_RTPT_SQNC_NBR, LAST_RPRTD_EVENT_TMS,
            LAST_RPRTD_RPRTNG_TM_ZN_CD, LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
            LEAD_LCMTV_MARK_CD, LEAD_LCMTV_EQPUN_NBR, SBU_MARK_CD, SBU_EQPUN_NBR,
            TYES_TRAIN_ID, TRMNTD_TRAIN_IND, CNST_CHNG_DYLGHT_SVNGS_IND,
            CNST_CHNG_LOCAL_TMS, CNST_CHNG_INTRMD_RTPNT_NBR, TYES_FUNCTION_CD,
            EGT_WHLG_FACTOR_QTY, CDN_MRSHL_VLTN_CD, USA_MRSHL_VLTN_CD, CLV_REJECT_IND,
            RCVRD_TRAIN_IND, SENT_TO_CLV_TMS, MTCHD_DPRTR_ARVL_VRSN_NBR,
            LAST_RPRTD_DYLGHT_SVNGS_IND, LAST_RPRTD_LOCAL_TMS, LAST_RPRTD_INTRMD_RTPNT_NBR,
            RUN_NBR, TRNSFR_RUN_NUMBER_TXT, TRAIN_CNST_ID, AEIRD_NBR, OCS_UPDATE_CD,
            CNST_RAIL_EQPMNT_QTY, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.TRAIN_CNST_SMRY_ID, src.TRAIN_CNST_SMRY_VRSN_NBR,
            src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.SOURCE_SYSTEM_UPDATE_TMS,
            src.CREATE_USER_ID, src.UPDATE_USER_ID, src.SOURCE_SYSTEM_UPDATE_USER_ID,
            src.TRAIN_NM, src.CNST_PRTY_NBR, src.LOADED_CARS_QTY, src.EMPTY_CARS_QTY,
            src.TOTAL_LENGTH_FEET_QTY, src.ESTMTD_GROSS_TONS_QTY, src.RQRD_LCMTV_QTY,
            src.RQRD_TOTAL_HRSPWR_QTY, src.RQRD_HRSPWR_PER_TON_QTY, src.ACTUAL_LCMTV_QTY,
            src.ACTUAL_TOTAL_HRSPWR_QTY, src.ACTUAL_HRSPWR_PER_TON_QTY, src.CNTNT_WEIGHT_TONS_QTY,
            src.TRAIN_SPEED_RSTRCN_MPH_QTY, src.TARE_WEIGHT_TONS_QTY, src.SOURCE_SYSTEM_TRAIN_CNST_NBR,
            src.TITAN_NBR, src.DATA_SOURCE_CD, src.TRAIN_DMNSNL_LOAD_RSTRCN_CD, src.DNGRS_CARS_STATUS_CD,
            src.CHNG_CNST_SMRY_STATUS_CD, src.LAST_RPRTD_CNST_SMRY_STATUS_CD,
            src.CNST_ORIGIN_TRN_PLN_EVENT_ID, src.CNST_ORIGIN_SCAC_CD, src.CNST_ORIGIN_FSAC_CD,
            src.CNST_ORIGIN_TRSTN_VRSN_NBR, src.CNST_ORIGIN_RTPT_SQNC_NBR,
            src.CNST_DSTNTN_TRN_PLN_EVENT_ID, src.CNST_DSTNTN_SCAC_CD, src.CNST_DSTNTN_FSAC_CD,
            src.CNST_DSTNTN_TRSTN_VRSN_NBR, src.CNST_DSTNTN_RTPT_SQNC_NBR,
            src.CNST_CHNG_PT_TRN_PLN_EVENT_ID, src.CNST_CHNG_PT_OPTRN_EVENT_ID, src.CNST_CHNG_PT_MVMNT_EVENT_ID,
            src.CNST_CHNG_PT_SCAC_CD, src.CNST_CHNG_PT_FSAC_CD, src.CNST_CHNG_PT_TRSTN_VRSN_NBR,
            src.CNST_CHNG_PT_RTPT_SQNC_NBR, src.CNST_CHNG_PT_EVENT_TMS,
            src.CNST_CHNG_RPRTNG_TM_ZN_CD, src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            src.LAST_RPRTD_OPTRN_EVENT_ID, src.LAST_RPRTD_MVMNT_EVENT_ID,
            src.LAST_RPRTD_SCAC_CD, src.LAST_RPRTD_FSAC_CD, src.LAST_RPRTD_TRSTN_VRSN_NBR,
            src.LAST_RPRTD_RTPT_SQNC_NBR, src.LAST_RPRTD_EVENT_TMS,
            src.LAST_RPRTD_RPRTNG_TM_ZN_CD, src.LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
            src.LEAD_LCMTV_MARK_CD, src.LEAD_LCMTV_EQPUN_NBR, src.SBU_MARK_CD, src.SBU_EQPUN_NBR,
            src.TYES_TRAIN_ID, src.TRMNTD_TRAIN_IND, src.CNST_CHNG_DYLGHT_SVNGS_IND,
            src.CNST_CHNG_LOCAL_TMS, src.CNST_CHNG_INTRMD_RTPNT_NBR, src.TYES_FUNCTION_CD,
            src.EGT_WHLG_FACTOR_QTY, src.CDN_MRSHL_VLTN_CD, src.USA_MRSHL_VLTN_CD, src.CLV_REJECT_IND,
            src.RCVRD_TRAIN_IND, src.SENT_TO_CLV_TMS, src.MTCHD_DPRTR_ARVL_VRSN_NBR,
            src.LAST_RPRTD_DYLGHT_SVNGS_IND, src.LAST_RPRTD_LOCAL_TMS, src.LAST_RPRTD_INTRMD_RTPNT_NBR,
            src.RUN_NBR, src.TRNSFR_RUN_NUMBER_TXT, src.TRAIN_CNST_ID, src.AEIRD_NBR, src.OCS_UPDATE_CD,
            src.CNST_RAIL_EQPMNT_QTY, src.SNW_OPERATION_TYPE, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_TRAIN_CNST_SMRY AS
    SELECT 
        TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR,
        RECORD_CREATE_TMS, RECORD_UPDATE_TMS, SOURCE_SYSTEM_UPDATE_TMS,
        CREATE_USER_ID, UPDATE_USER_ID, SOURCE_SYSTEM_UPDATE_USER_ID,
        TRAIN_NM, CNST_PRTY_NBR, LOADED_CARS_QTY, EMPTY_CARS_QTY,
        TOTAL_LENGTH_FEET_QTY, ESTMTD_GROSS_TONS_QTY, RQRD_LCMTV_QTY,
        RQRD_TOTAL_HRSPWR_QTY, RQRD_HRSPWR_PER_TON_QTY, ACTUAL_LCMTV_QTY,
        ACTUAL_TOTAL_HRSPWR_QTY, ACTUAL_HRSPWR_PER_TON_QTY, CNTNT_WEIGHT_TONS_QTY,
        TRAIN_SPEED_RSTRCN_MPH_QTY, TARE_WEIGHT_TONS_QTY, SOURCE_SYSTEM_TRAIN_CNST_NBR,
        TITAN_NBR, DATA_SOURCE_CD, TRAIN_DMNSNL_LOAD_RSTRCN_CD, DNGRS_CARS_STATUS_CD,
        CHNG_CNST_SMRY_STATUS_CD, LAST_RPRTD_CNST_SMRY_STATUS_CD,
        CNST_ORIGIN_TRN_PLN_EVENT_ID, CNST_ORIGIN_SCAC_CD, CNST_ORIGIN_FSAC_CD,
        CNST_ORIGIN_TRSTN_VRSN_NBR, CNST_ORIGIN_RTPT_SQNC_NBR,
        CNST_DSTNTN_TRN_PLN_EVENT_ID, CNST_DSTNTN_SCAC_CD, CNST_DSTNTN_FSAC_CD,
        CNST_DSTNTN_TRSTN_VRSN_NBR, CNST_DSTNTN_RTPT_SQNC_NBR,
        CNST_CHNG_PT_TRN_PLN_EVENT_ID, CNST_CHNG_PT_OPTRN_EVENT_ID, CNST_CHNG_PT_MVMNT_EVENT_ID,
        CNST_CHNG_PT_SCAC_CD, CNST_CHNG_PT_FSAC_CD, CNST_CHNG_PT_TRSTN_VRSN_NBR,
        CNST_CHNG_PT_RTPT_SQNC_NBR, CNST_CHNG_PT_EVENT_TMS,
        CNST_CHNG_RPRTNG_TM_ZN_CD, CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
        LAST_RPRTD_OPTRN_EVENT_ID, LAST_RPRTD_MVMNT_EVENT_ID,
        LAST_RPRTD_SCAC_CD, LAST_RPRTD_FSAC_CD, LAST_RPRTD_TRSTN_VRSN_NBR,
        LAST_RPRTD_RTPT_SQNC_NBR, LAST_RPRTD_EVENT_TMS,
        LAST_RPRTD_RPRTNG_TM_ZN_CD, LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
        LEAD_LCMTV_MARK_CD, LEAD_LCMTV_EQPUN_NBR, SBU_MARK_CD, SBU_EQPUN_NBR,
        TYES_TRAIN_ID, TRMNTD_TRAIN_IND, CNST_CHNG_DYLGHT_SVNGS_IND,
        CNST_CHNG_LOCAL_TMS, CNST_CHNG_INTRMD_RTPNT_NBR, TYES_FUNCTION_CD,
        EGT_WHLG_FACTOR_QTY, CDN_MRSHL_VLTN_CD, USA_MRSHL_VLTN_CD, CLV_REJECT_IND,
        RCVRD_TRAIN_IND, SENT_TO_CLV_TMS, MTCHD_DPRTR_ARVL_VRSN_NBR,
        LAST_RPRTD_DYLGHT_SVNGS_IND, LAST_RPRTD_LOCAL_TMS, LAST_RPRTD_INTRMD_RTPNT_NBR,
        RUN_NBR, TRNSFR_RUN_NUMBER_TXT, TRAIN_CNST_ID, AEIRD_NBR, OCS_UPDATE_CD,
        CNST_RAIL_EQPMNT_QTY, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.SADB.TRAIN_CNST_SMRY_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_TRAIN_CNST_SMRY;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_TRAIN_CNST_SMRY;
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.SADB.TRAIN_CNST_SMRY AS tgt
    USING (
        SELECT 
            TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, SOURCE_SYSTEM_UPDATE_TMS,
            CREATE_USER_ID, UPDATE_USER_ID, SOURCE_SYSTEM_UPDATE_USER_ID,
            TRAIN_NM, CNST_PRTY_NBR, LOADED_CARS_QTY, EMPTY_CARS_QTY,
            TOTAL_LENGTH_FEET_QTY, ESTMTD_GROSS_TONS_QTY, RQRD_LCMTV_QTY,
            RQRD_TOTAL_HRSPWR_QTY, RQRD_HRSPWR_PER_TON_QTY, ACTUAL_LCMTV_QTY,
            ACTUAL_TOTAL_HRSPWR_QTY, ACTUAL_HRSPWR_PER_TON_QTY, CNTNT_WEIGHT_TONS_QTY,
            TRAIN_SPEED_RSTRCN_MPH_QTY, TARE_WEIGHT_TONS_QTY, SOURCE_SYSTEM_TRAIN_CNST_NBR,
            TITAN_NBR, DATA_SOURCE_CD, TRAIN_DMNSNL_LOAD_RSTRCN_CD, DNGRS_CARS_STATUS_CD,
            CHNG_CNST_SMRY_STATUS_CD, LAST_RPRTD_CNST_SMRY_STATUS_CD,
            CNST_ORIGIN_TRN_PLN_EVENT_ID, CNST_ORIGIN_SCAC_CD, CNST_ORIGIN_FSAC_CD,
            CNST_ORIGIN_TRSTN_VRSN_NBR, CNST_ORIGIN_RTPT_SQNC_NBR,
            CNST_DSTNTN_TRN_PLN_EVENT_ID, CNST_DSTNTN_SCAC_CD, CNST_DSTNTN_FSAC_CD,
            CNST_DSTNTN_TRSTN_VRSN_NBR, CNST_DSTNTN_RTPT_SQNC_NBR,
            CNST_CHNG_PT_TRN_PLN_EVENT_ID, CNST_CHNG_PT_OPTRN_EVENT_ID, CNST_CHNG_PT_MVMNT_EVENT_ID,
            CNST_CHNG_PT_SCAC_CD, CNST_CHNG_PT_FSAC_CD, CNST_CHNG_PT_TRSTN_VRSN_NBR,
            CNST_CHNG_PT_RTPT_SQNC_NBR, CNST_CHNG_PT_EVENT_TMS,
            CNST_CHNG_RPRTNG_TM_ZN_CD, CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            LAST_RPRTD_OPTRN_EVENT_ID, LAST_RPRTD_MVMNT_EVENT_ID,
            LAST_RPRTD_SCAC_CD, LAST_RPRTD_FSAC_CD, LAST_RPRTD_TRSTN_VRSN_NBR,
            LAST_RPRTD_RTPT_SQNC_NBR, LAST_RPRTD_EVENT_TMS,
            LAST_RPRTD_RPRTNG_TM_ZN_CD, LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
            LEAD_LCMTV_MARK_CD, LEAD_LCMTV_EQPUN_NBR, SBU_MARK_CD, SBU_EQPUN_NBR,
            TYES_TRAIN_ID, TRMNTD_TRAIN_IND, CNST_CHNG_DYLGHT_SVNGS_IND,
            CNST_CHNG_LOCAL_TMS, CNST_CHNG_INTRMD_RTPNT_NBR, TYES_FUNCTION_CD,
            EGT_WHLG_FACTOR_QTY, CDN_MRSHL_VLTN_CD, USA_MRSHL_VLTN_CD, CLV_REJECT_IND,
            RCVRD_TRAIN_IND, SENT_TO_CLV_TMS, MTCHD_DPRTR_ARVL_VRSN_NBR,
            LAST_RPRTD_DYLGHT_SVNGS_IND, LAST_RPRTD_LOCAL_TMS, LAST_RPRTD_INTRMD_RTPNT_NBR,
            RUN_NBR, TRNSFR_RUN_NUMBER_TXT, TRAIN_CNST_ID, AEIRD_NBR, OCS_UPDATE_CD,
            CNST_RAIL_EQPMNT_QTY, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_ACTION,
            CDC_IS_UPDATE,
            ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_TRAIN_CNST_SMRY
    ) AS src
    ON tgt.TRAIN_CNST_SMRY_ID = src.TRAIN_CNST_SMRY_ID
        AND tgt.TRAIN_CNST_SMRY_VRSN_NBR = src.TRAIN_CNST_SMRY_VRSN_NBR
    
    -- UPDATE scenario (METADATA$ACTION='INSERT' AND METADATA$ISUPDATE=TRUE)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.SOURCE_SYSTEM_UPDATE_TMS = src.SOURCE_SYSTEM_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.SOURCE_SYSTEM_UPDATE_USER_ID = src.SOURCE_SYSTEM_UPDATE_USER_ID,
            tgt.TRAIN_NM = src.TRAIN_NM,
            tgt.CNST_PRTY_NBR = src.CNST_PRTY_NBR,
            tgt.LOADED_CARS_QTY = src.LOADED_CARS_QTY,
            tgt.EMPTY_CARS_QTY = src.EMPTY_CARS_QTY,
            tgt.TOTAL_LENGTH_FEET_QTY = src.TOTAL_LENGTH_FEET_QTY,
            tgt.ESTMTD_GROSS_TONS_QTY = src.ESTMTD_GROSS_TONS_QTY,
            tgt.RQRD_LCMTV_QTY = src.RQRD_LCMTV_QTY,
            tgt.RQRD_TOTAL_HRSPWR_QTY = src.RQRD_TOTAL_HRSPWR_QTY,
            tgt.RQRD_HRSPWR_PER_TON_QTY = src.RQRD_HRSPWR_PER_TON_QTY,
            tgt.ACTUAL_LCMTV_QTY = src.ACTUAL_LCMTV_QTY,
            tgt.ACTUAL_TOTAL_HRSPWR_QTY = src.ACTUAL_TOTAL_HRSPWR_QTY,
            tgt.ACTUAL_HRSPWR_PER_TON_QTY = src.ACTUAL_HRSPWR_PER_TON_QTY,
            tgt.CNTNT_WEIGHT_TONS_QTY = src.CNTNT_WEIGHT_TONS_QTY,
            tgt.TRAIN_SPEED_RSTRCN_MPH_QTY = src.TRAIN_SPEED_RSTRCN_MPH_QTY,
            tgt.TARE_WEIGHT_TONS_QTY = src.TARE_WEIGHT_TONS_QTY,
            tgt.SOURCE_SYSTEM_TRAIN_CNST_NBR = src.SOURCE_SYSTEM_TRAIN_CNST_NBR,
            tgt.TITAN_NBR = src.TITAN_NBR,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.TRAIN_DMNSNL_LOAD_RSTRCN_CD = src.TRAIN_DMNSNL_LOAD_RSTRCN_CD,
            tgt.DNGRS_CARS_STATUS_CD = src.DNGRS_CARS_STATUS_CD,
            tgt.CHNG_CNST_SMRY_STATUS_CD = src.CHNG_CNST_SMRY_STATUS_CD,
            tgt.LAST_RPRTD_CNST_SMRY_STATUS_CD = src.LAST_RPRTD_CNST_SMRY_STATUS_CD,
            tgt.CNST_ORIGIN_TRN_PLN_EVENT_ID = src.CNST_ORIGIN_TRN_PLN_EVENT_ID,
            tgt.CNST_ORIGIN_SCAC_CD = src.CNST_ORIGIN_SCAC_CD,
            tgt.CNST_ORIGIN_FSAC_CD = src.CNST_ORIGIN_FSAC_CD,
            tgt.CNST_ORIGIN_TRSTN_VRSN_NBR = src.CNST_ORIGIN_TRSTN_VRSN_NBR,
            tgt.CNST_ORIGIN_RTPT_SQNC_NBR = src.CNST_ORIGIN_RTPT_SQNC_NBR,
            tgt.CNST_DSTNTN_TRN_PLN_EVENT_ID = src.CNST_DSTNTN_TRN_PLN_EVENT_ID,
            tgt.CNST_DSTNTN_SCAC_CD = src.CNST_DSTNTN_SCAC_CD,
            tgt.CNST_DSTNTN_FSAC_CD = src.CNST_DSTNTN_FSAC_CD,
            tgt.CNST_DSTNTN_TRSTN_VRSN_NBR = src.CNST_DSTNTN_TRSTN_VRSN_NBR,
            tgt.CNST_DSTNTN_RTPT_SQNC_NBR = src.CNST_DSTNTN_RTPT_SQNC_NBR,
            tgt.CNST_CHNG_PT_TRN_PLN_EVENT_ID = src.CNST_CHNG_PT_TRN_PLN_EVENT_ID,
            tgt.CNST_CHNG_PT_OPTRN_EVENT_ID = src.CNST_CHNG_PT_OPTRN_EVENT_ID,
            tgt.CNST_CHNG_PT_MVMNT_EVENT_ID = src.CNST_CHNG_PT_MVMNT_EVENT_ID,
            tgt.CNST_CHNG_PT_SCAC_CD = src.CNST_CHNG_PT_SCAC_CD,
            tgt.CNST_CHNG_PT_FSAC_CD = src.CNST_CHNG_PT_FSAC_CD,
            tgt.CNST_CHNG_PT_TRSTN_VRSN_NBR = src.CNST_CHNG_PT_TRSTN_VRSN_NBR,
            tgt.CNST_CHNG_PT_RTPT_SQNC_NBR = src.CNST_CHNG_PT_RTPT_SQNC_NBR,
            tgt.CNST_CHNG_PT_EVENT_TMS = src.CNST_CHNG_PT_EVENT_TMS,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_CD = src.CNST_CHNG_RPRTNG_TM_ZN_CD,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR = src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            tgt.LAST_RPRTD_OPTRN_EVENT_ID = src.LAST_RPRTD_OPTRN_EVENT_ID,
            tgt.LAST_RPRTD_MVMNT_EVENT_ID = src.LAST_RPRTD_MVMNT_EVENT_ID,
            tgt.LAST_RPRTD_SCAC_CD = src.LAST_RPRTD_SCAC_CD,
            tgt.LAST_RPRTD_FSAC_CD = src.LAST_RPRTD_FSAC_CD,
            tgt.LAST_RPRTD_TRSTN_VRSN_NBR = src.LAST_RPRTD_TRSTN_VRSN_NBR,
            tgt.LAST_RPRTD_RTPT_SQNC_NBR = src.LAST_RPRTD_RTPT_SQNC_NBR,
            tgt.LAST_RPRTD_EVENT_TMS = src.LAST_RPRTD_EVENT_TMS,
            tgt.LAST_RPRTD_RPRTNG_TM_ZN_CD = src.LAST_RPRTD_RPRTNG_TM_ZN_CD,
            tgt.LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR = src.LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
            tgt.LEAD_LCMTV_MARK_CD = src.LEAD_LCMTV_MARK_CD,
            tgt.LEAD_LCMTV_EQPUN_NBR = src.LEAD_LCMTV_EQPUN_NBR,
            tgt.SBU_MARK_CD = src.SBU_MARK_CD,
            tgt.SBU_EQPUN_NBR = src.SBU_EQPUN_NBR,
            tgt.TYES_TRAIN_ID = src.TYES_TRAIN_ID,
            tgt.TRMNTD_TRAIN_IND = src.TRMNTD_TRAIN_IND,
            tgt.CNST_CHNG_DYLGHT_SVNGS_IND = src.CNST_CHNG_DYLGHT_SVNGS_IND,
            tgt.CNST_CHNG_LOCAL_TMS = src.CNST_CHNG_LOCAL_TMS,
            tgt.CNST_CHNG_INTRMD_RTPNT_NBR = src.CNST_CHNG_INTRMD_RTPNT_NBR,
            tgt.TYES_FUNCTION_CD = src.TYES_FUNCTION_CD,
            tgt.EGT_WHLG_FACTOR_QTY = src.EGT_WHLG_FACTOR_QTY,
            tgt.CDN_MRSHL_VLTN_CD = src.CDN_MRSHL_VLTN_CD,
            tgt.USA_MRSHL_VLTN_CD = src.USA_MRSHL_VLTN_CD,
            tgt.CLV_REJECT_IND = src.CLV_REJECT_IND,
            tgt.RCVRD_TRAIN_IND = src.RCVRD_TRAIN_IND,
            tgt.SENT_TO_CLV_TMS = src.SENT_TO_CLV_TMS,
            tgt.MTCHD_DPRTR_ARVL_VRSN_NBR = src.MTCHD_DPRTR_ARVL_VRSN_NBR,
            tgt.LAST_RPRTD_DYLGHT_SVNGS_IND = src.LAST_RPRTD_DYLGHT_SVNGS_IND,
            tgt.LAST_RPRTD_LOCAL_TMS = src.LAST_RPRTD_LOCAL_TMS,
            tgt.LAST_RPRTD_INTRMD_RTPNT_NBR = src.LAST_RPRTD_INTRMD_RTPNT_NBR,
            tgt.RUN_NBR = src.RUN_NBR,
            tgt.TRNSFR_RUN_NUMBER_TXT = src.TRNSFR_RUN_NUMBER_TXT,
            tgt.TRAIN_CNST_ID = src.TRAIN_CNST_ID,
            tgt.AEIRD_NBR = src.AEIRD_NBR,
            tgt.OCS_UPDATE_CD = src.OCS_UPDATE_CD,
            tgt.CNST_RAIL_EQPMNT_QTY = src.CNST_RAIL_EQPMNT_QTY,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- DELETE scenario (METADATA$ACTION='DELETE' AND METADATA$ISUPDATE=FALSE)
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- RE-INSERT scenario (record exists but being re-inserted)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.SOURCE_SYSTEM_UPDATE_TMS = src.SOURCE_SYSTEM_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.SOURCE_SYSTEM_UPDATE_USER_ID = src.SOURCE_SYSTEM_UPDATE_USER_ID,
            tgt.TRAIN_NM = src.TRAIN_NM,
            tgt.CNST_PRTY_NBR = src.CNST_PRTY_NBR,
            tgt.LOADED_CARS_QTY = src.LOADED_CARS_QTY,
            tgt.EMPTY_CARS_QTY = src.EMPTY_CARS_QTY,
            tgt.TOTAL_LENGTH_FEET_QTY = src.TOTAL_LENGTH_FEET_QTY,
            tgt.ESTMTD_GROSS_TONS_QTY = src.ESTMTD_GROSS_TONS_QTY,
            tgt.RQRD_LCMTV_QTY = src.RQRD_LCMTV_QTY,
            tgt.RQRD_TOTAL_HRSPWR_QTY = src.RQRD_TOTAL_HRSPWR_QTY,
            tgt.RQRD_HRSPWR_PER_TON_QTY = src.RQRD_HRSPWR_PER_TON_QTY,
            tgt.ACTUAL_LCMTV_QTY = src.ACTUAL_LCMTV_QTY,
            tgt.ACTUAL_TOTAL_HRSPWR_QTY = src.ACTUAL_TOTAL_HRSPWR_QTY,
            tgt.ACTUAL_HRSPWR_PER_TON_QTY = src.ACTUAL_HRSPWR_PER_TON_QTY,
            tgt.CNTNT_WEIGHT_TONS_QTY = src.CNTNT_WEIGHT_TONS_QTY,
            tgt.TRAIN_SPEED_RSTRCN_MPH_QTY = src.TRAIN_SPEED_RSTRCN_MPH_QTY,
            tgt.TARE_WEIGHT_TONS_QTY = src.TARE_WEIGHT_TONS_QTY,
            tgt.SOURCE_SYSTEM_TRAIN_CNST_NBR = src.SOURCE_SYSTEM_TRAIN_CNST_NBR,
            tgt.TITAN_NBR = src.TITAN_NBR,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.TRAIN_DMNSNL_LOAD_RSTRCN_CD = src.TRAIN_DMNSNL_LOAD_RSTRCN_CD,
            tgt.DNGRS_CARS_STATUS_CD = src.DNGRS_CARS_STATUS_CD,
            tgt.CHNG_CNST_SMRY_STATUS_CD = src.CHNG_CNST_SMRY_STATUS_CD,
            tgt.LAST_RPRTD_CNST_SMRY_STATUS_CD = src.LAST_RPRTD_CNST_SMRY_STATUS_CD,
            tgt.CNST_ORIGIN_TRN_PLN_EVENT_ID = src.CNST_ORIGIN_TRN_PLN_EVENT_ID,
            tgt.CNST_ORIGIN_SCAC_CD = src.CNST_ORIGIN_SCAC_CD,
            tgt.CNST_ORIGIN_FSAC_CD = src.CNST_ORIGIN_FSAC_CD,
            tgt.CNST_ORIGIN_TRSTN_VRSN_NBR = src.CNST_ORIGIN_TRSTN_VRSN_NBR,
            tgt.CNST_ORIGIN_RTPT_SQNC_NBR = src.CNST_ORIGIN_RTPT_SQNC_NBR,
            tgt.CNST_DSTNTN_TRN_PLN_EVENT_ID = src.CNST_DSTNTN_TRN_PLN_EVENT_ID,
            tgt.CNST_DSTNTN_SCAC_CD = src.CNST_DSTNTN_SCAC_CD,
            tgt.CNST_DSTNTN_FSAC_CD = src.CNST_DSTNTN_FSAC_CD,
            tgt.CNST_DSTNTN_TRSTN_VRSN_NBR = src.CNST_DSTNTN_TRSTN_VRSN_NBR,
            tgt.CNST_DSTNTN_RTPT_SQNC_NBR = src.CNST_DSTNTN_RTPT_SQNC_NBR,
            tgt.CNST_CHNG_PT_TRN_PLN_EVENT_ID = src.CNST_CHNG_PT_TRN_PLN_EVENT_ID,
            tgt.CNST_CHNG_PT_OPTRN_EVENT_ID = src.CNST_CHNG_PT_OPTRN_EVENT_ID,
            tgt.CNST_CHNG_PT_MVMNT_EVENT_ID = src.CNST_CHNG_PT_MVMNT_EVENT_ID,
            tgt.CNST_CHNG_PT_SCAC_CD = src.CNST_CHNG_PT_SCAC_CD,
            tgt.CNST_CHNG_PT_FSAC_CD = src.CNST_CHNG_PT_FSAC_CD,
            tgt.CNST_CHNG_PT_TRSTN_VRSN_NBR = src.CNST_CHNG_PT_TRSTN_VRSN_NBR,
            tgt.CNST_CHNG_PT_RTPT_SQNC_NBR = src.CNST_CHNG_PT_RTPT_SQNC_NBR,
            tgt.CNST_CHNG_PT_EVENT_TMS = src.CNST_CHNG_PT_EVENT_TMS,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_CD = src.CNST_CHNG_RPRTNG_TM_ZN_CD,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR = src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            tgt.LAST_RPRTD_OPTRN_EVENT_ID = src.LAST_RPRTD_OPTRN_EVENT_ID,
            tgt.LAST_RPRTD_MVMNT_EVENT_ID = src.LAST_RPRTD_MVMNT_EVENT_ID,
            tgt.LAST_RPRTD_SCAC_CD = src.LAST_RPRTD_SCAC_CD,
            tgt.LAST_RPRTD_FSAC_CD = src.LAST_RPRTD_FSAC_CD,
            tgt.LAST_RPRTD_TRSTN_VRSN_NBR = src.LAST_RPRTD_TRSTN_VRSN_NBR,
            tgt.LAST_RPRTD_RTPT_SQNC_NBR = src.LAST_RPRTD_RTPT_SQNC_NBR,
            tgt.LAST_RPRTD_EVENT_TMS = src.LAST_RPRTD_EVENT_TMS,
            tgt.LAST_RPRTD_RPRTNG_TM_ZN_CD = src.LAST_RPRTD_RPRTNG_TM_ZN_CD,
            tgt.LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR = src.LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
            tgt.LEAD_LCMTV_MARK_CD = src.LEAD_LCMTV_MARK_CD,
            tgt.LEAD_LCMTV_EQPUN_NBR = src.LEAD_LCMTV_EQPUN_NBR,
            tgt.SBU_MARK_CD = src.SBU_MARK_CD,
            tgt.SBU_EQPUN_NBR = src.SBU_EQPUN_NBR,
            tgt.TYES_TRAIN_ID = src.TYES_TRAIN_ID,
            tgt.TRMNTD_TRAIN_IND = src.TRMNTD_TRAIN_IND,
            tgt.CNST_CHNG_DYLGHT_SVNGS_IND = src.CNST_CHNG_DYLGHT_SVNGS_IND,
            tgt.CNST_CHNG_LOCAL_TMS = src.CNST_CHNG_LOCAL_TMS,
            tgt.CNST_CHNG_INTRMD_RTPNT_NBR = src.CNST_CHNG_INTRMD_RTPNT_NBR,
            tgt.TYES_FUNCTION_CD = src.TYES_FUNCTION_CD,
            tgt.EGT_WHLG_FACTOR_QTY = src.EGT_WHLG_FACTOR_QTY,
            tgt.CDN_MRSHL_VLTN_CD = src.CDN_MRSHL_VLTN_CD,
            tgt.USA_MRSHL_VLTN_CD = src.USA_MRSHL_VLTN_CD,
            tgt.CLV_REJECT_IND = src.CLV_REJECT_IND,
            tgt.RCVRD_TRAIN_IND = src.RCVRD_TRAIN_IND,
            tgt.SENT_TO_CLV_TMS = src.SENT_TO_CLV_TMS,
            tgt.MTCHD_DPRTR_ARVL_VRSN_NBR = src.MTCHD_DPRTR_ARVL_VRSN_NBR,
            tgt.LAST_RPRTD_DYLGHT_SVNGS_IND = src.LAST_RPRTD_DYLGHT_SVNGS_IND,
            tgt.LAST_RPRTD_LOCAL_TMS = src.LAST_RPRTD_LOCAL_TMS,
            tgt.LAST_RPRTD_INTRMD_RTPNT_NBR = src.LAST_RPRTD_INTRMD_RTPNT_NBR,
            tgt.RUN_NBR = src.RUN_NBR,
            tgt.TRNSFR_RUN_NUMBER_TXT = src.TRNSFR_RUN_NUMBER_TXT,
            tgt.TRAIN_CNST_ID = src.TRAIN_CNST_ID,
            tgt.AEIRD_NBR = src.AEIRD_NBR,
            tgt.OCS_UPDATE_CD = src.OCS_UPDATE_CD,
            tgt.CNST_RAIL_EQPMNT_QTY = src.CNST_RAIL_EQPMNT_QTY,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- NEW INSERT scenario
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, SOURCE_SYSTEM_UPDATE_TMS,
            CREATE_USER_ID, UPDATE_USER_ID, SOURCE_SYSTEM_UPDATE_USER_ID,
            TRAIN_NM, CNST_PRTY_NBR, LOADED_CARS_QTY, EMPTY_CARS_QTY,
            TOTAL_LENGTH_FEET_QTY, ESTMTD_GROSS_TONS_QTY, RQRD_LCMTV_QTY,
            RQRD_TOTAL_HRSPWR_QTY, RQRD_HRSPWR_PER_TON_QTY, ACTUAL_LCMTV_QTY,
            ACTUAL_TOTAL_HRSPWR_QTY, ACTUAL_HRSPWR_PER_TON_QTY, CNTNT_WEIGHT_TONS_QTY,
            TRAIN_SPEED_RSTRCN_MPH_QTY, TARE_WEIGHT_TONS_QTY, SOURCE_SYSTEM_TRAIN_CNST_NBR,
            TITAN_NBR, DATA_SOURCE_CD, TRAIN_DMNSNL_LOAD_RSTRCN_CD, DNGRS_CARS_STATUS_CD,
            CHNG_CNST_SMRY_STATUS_CD, LAST_RPRTD_CNST_SMRY_STATUS_CD,
            CNST_ORIGIN_TRN_PLN_EVENT_ID, CNST_ORIGIN_SCAC_CD, CNST_ORIGIN_FSAC_CD,
            CNST_ORIGIN_TRSTN_VRSN_NBR, CNST_ORIGIN_RTPT_SQNC_NBR,
            CNST_DSTNTN_TRN_PLN_EVENT_ID, CNST_DSTNTN_SCAC_CD, CNST_DSTNTN_FSAC_CD,
            CNST_DSTNTN_TRSTN_VRSN_NBR, CNST_DSTNTN_RTPT_SQNC_NBR,
            CNST_CHNG_PT_TRN_PLN_EVENT_ID, CNST_CHNG_PT_OPTRN_EVENT_ID, CNST_CHNG_PT_MVMNT_EVENT_ID,
            CNST_CHNG_PT_SCAC_CD, CNST_CHNG_PT_FSAC_CD, CNST_CHNG_PT_TRSTN_VRSN_NBR,
            CNST_CHNG_PT_RTPT_SQNC_NBR, CNST_CHNG_PT_EVENT_TMS,
            CNST_CHNG_RPRTNG_TM_ZN_CD, CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            LAST_RPRTD_OPTRN_EVENT_ID, LAST_RPRTD_MVMNT_EVENT_ID,
            LAST_RPRTD_SCAC_CD, LAST_RPRTD_FSAC_CD, LAST_RPRTD_TRSTN_VRSN_NBR,
            LAST_RPRTD_RTPT_SQNC_NBR, LAST_RPRTD_EVENT_TMS,
            LAST_RPRTD_RPRTNG_TM_ZN_CD, LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
            LEAD_LCMTV_MARK_CD, LEAD_LCMTV_EQPUN_NBR, SBU_MARK_CD, SBU_EQPUN_NBR,
            TYES_TRAIN_ID, TRMNTD_TRAIN_IND, CNST_CHNG_DYLGHT_SVNGS_IND,
            CNST_CHNG_LOCAL_TMS, CNST_CHNG_INTRMD_RTPNT_NBR, TYES_FUNCTION_CD,
            EGT_WHLG_FACTOR_QTY, CDN_MRSHL_VLTN_CD, USA_MRSHL_VLTN_CD, CLV_REJECT_IND,
            RCVRD_TRAIN_IND, SENT_TO_CLV_TMS, MTCHD_DPRTR_ARVL_VRSN_NBR,
            LAST_RPRTD_DYLGHT_SVNGS_IND, LAST_RPRTD_LOCAL_TMS, LAST_RPRTD_INTRMD_RTPNT_NBR,
            RUN_NBR, TRNSFR_RUN_NUMBER_TXT, TRAIN_CNST_ID, AEIRD_NBR, OCS_UPDATE_CD,
            CNST_RAIL_EQPMNT_QTY, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.TRAIN_CNST_SMRY_ID, src.TRAIN_CNST_SMRY_VRSN_NBR,
            src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.SOURCE_SYSTEM_UPDATE_TMS,
            src.CREATE_USER_ID, src.UPDATE_USER_ID, src.SOURCE_SYSTEM_UPDATE_USER_ID,
            src.TRAIN_NM, src.CNST_PRTY_NBR, src.LOADED_CARS_QTY, src.EMPTY_CARS_QTY,
            src.TOTAL_LENGTH_FEET_QTY, src.ESTMTD_GROSS_TONS_QTY, src.RQRD_LCMTV_QTY,
            src.RQRD_TOTAL_HRSPWR_QTY, src.RQRD_HRSPWR_PER_TON_QTY, src.ACTUAL_LCMTV_QTY,
            src.ACTUAL_TOTAL_HRSPWR_QTY, src.ACTUAL_HRSPWR_PER_TON_QTY, src.CNTNT_WEIGHT_TONS_QTY,
            src.TRAIN_SPEED_RSTRCN_MPH_QTY, src.TARE_WEIGHT_TONS_QTY, src.SOURCE_SYSTEM_TRAIN_CNST_NBR,
            src.TITAN_NBR, src.DATA_SOURCE_CD, src.TRAIN_DMNSNL_LOAD_RSTRCN_CD, src.DNGRS_CARS_STATUS_CD,
            src.CHNG_CNST_SMRY_STATUS_CD, src.LAST_RPRTD_CNST_SMRY_STATUS_CD,
            src.CNST_ORIGIN_TRN_PLN_EVENT_ID, src.CNST_ORIGIN_SCAC_CD, src.CNST_ORIGIN_FSAC_CD,
            src.CNST_ORIGIN_TRSTN_VRSN_NBR, src.CNST_ORIGIN_RTPT_SQNC_NBR,
            src.CNST_DSTNTN_TRN_PLN_EVENT_ID, src.CNST_DSTNTN_SCAC_CD, src.CNST_DSTNTN_FSAC_CD,
            src.CNST_DSTNTN_TRSTN_VRSN_NBR, src.CNST_DSTNTN_RTPT_SQNC_NBR,
            src.CNST_CHNG_PT_TRN_PLN_EVENT_ID, src.CNST_CHNG_PT_OPTRN_EVENT_ID, src.CNST_CHNG_PT_MVMNT_EVENT_ID,
            src.CNST_CHNG_PT_SCAC_CD, src.CNST_CHNG_PT_FSAC_CD, src.CNST_CHNG_PT_TRSTN_VRSN_NBR,
            src.CNST_CHNG_PT_RTPT_SQNC_NBR, src.CNST_CHNG_PT_EVENT_TMS,
            src.CNST_CHNG_RPRTNG_TM_ZN_CD, src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            src.LAST_RPRTD_OPTRN_EVENT_ID, src.LAST_RPRTD_MVMNT_EVENT_ID,
            src.LAST_RPRTD_SCAC_CD, src.LAST_RPRTD_FSAC_CD, src.LAST_RPRTD_TRSTN_VRSN_NBR,
            src.LAST_RPRTD_RTPT_SQNC_NBR, src.LAST_RPRTD_EVENT_TMS,
            src.LAST_RPRTD_RPRTNG_TM_ZN_CD, src.LAST_RPRTD_RPRTNG_TM_ZN_YR_NBR,
            src.LEAD_LCMTV_MARK_CD, src.LEAD_LCMTV_EQPUN_NBR, src.SBU_MARK_CD, src.SBU_EQPUN_NBR,
            src.TYES_TRAIN_ID, src.TRMNTD_TRAIN_IND, src.CNST_CHNG_DYLGHT_SVNGS_IND,
            src.CNST_CHNG_LOCAL_TMS, src.CNST_CHNG_INTRMD_RTPNT_NBR, src.TYES_FUNCTION_CD,
            src.EGT_WHLG_FACTOR_QTY, src.CDN_MRSHL_VLTN_CD, src.USA_MRSHL_VLTN_CD, src.CLV_REJECT_IND,
            src.RCVRD_TRAIN_IND, src.SENT_TO_CLV_TMS, src.MTCHD_DPRTR_ARVL_VRSN_NBR,
            src.LAST_RPRTD_DYLGHT_SVNGS_IND, src.LAST_RPRTD_LOCAL_TMS, src.LAST_RPRTD_INTRMD_RTPNT_NBR,
            src.RUN_NBR, src.TRNSFR_RUN_NUMBER_TXT, src.TRAIN_CNST_ID, src.AEIRD_NBR, src.OCS_UPDATE_CD,
            src.CNST_RAIL_EQPMNT_QTY, src.SNW_OPERATION_TYPE, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    DROP TABLE IF EXISTS _CDC_STAGING_TRAIN_CNST_SMRY;
    
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes. Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        DROP TABLE IF EXISTS _CDC_STAGING_TRAIN_CNST_SMRY;
        RETURN 'ERROR: ' || SQLERRM || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.SADB.TASK_PROCESS_TRAIN_CNST_SMRY
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process TRAIN_CNST_SMRY_BASE CDC changes into data preservation table'
WHEN
    SYSTEM$STREAM_HAS_DATA('D_RAW.SADB.TRAIN_CNST_SMRY_BASE_HIST_STREAM')
AS
    CALL D_RAW.SADB.SP_PROCESS_TRAIN_CNST_SMRY();

ALTER TASK D_RAW.SADB.TASK_PROCESS_TRAIN_CNST_SMRY RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'TRAIN_CNST_SMRY%' IN SCHEMA D_BRONZE.SADB;
-- SHOW STREAMS LIKE 'TRAIN_CNST_SMRY%' IN SCHEMA D_RAW.SADB;
-- SHOW TASKS LIKE 'TASK_PROCESS_TRAIN_CNST_SMRY%' IN SCHEMA D_RAW.SADB;
-- CALL D_RAW.SADB.SP_PROCESS_TRAIN_CNST_SMRY();
