/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE
================================================================================
Source Table : D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE
Target Table : D_BRONZE.SADB.TRAIN_CNST_DTL_RAIL_EQPT
Stream       : D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT()
Task         : D_RAW.SADB.TASK_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT
Primary Key  : COMPOSITE (TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR, SQNC_NBR)
Total Columns: 77 source + 6 CDC metadata = 83
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.TRAIN_CNST_DTL_RAIL_EQPT (
    TRAIN_CNST_SMRY_ID NUMBER(18,0) NOT NULL,
    TRAIN_CNST_SMRY_VRSN_NBR NUMBER(4,0) NOT NULL,
    SQNC_NBR NUMBER(4,0) NOT NULL,
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    MARK_CD VARCHAR(16),
    EQPUN_NBR VARCHAR(40),
    AAR_CAR_TYPE_CD VARCHAR(16),
    OTSD_LENGTH_FEET_QTY NUMBER(10,0),
    OTSD_LENGTH_INCHES_QTY NUMBER(10,0),
    TARE_WEIGHT_TONS_QTY NUMBER(10,2),
    ORIGIN_SCAC_CD VARCHAR(16),
    ORIGIN_FSAC_CD VARCHAR(20),
    ORIGIN_TRSTN_VRSN_NBR NUMBER(5,0),
    DSTNTN_SCAC_CD VARCHAR(16),
    DSTNTN_FSAC_CD VARCHAR(20),
    DSTNTN_TRSTN_VRSN_NBR NUMBER(5,0),
    CYCLE_SERIAL_NBR NUMBER(10,0),
    LOAD_EMPTY_IND VARCHAR(4),
    NET_WEIGHT_TONS_QTY NUMBER(10,0),
    CLRNC_PLATE_CD VARCHAR(4),
    BAD_ORDER_CAR_GRADE_CD VARCHAR(4),
    BAD_ORDER_REASON_CD VARCHAR(16),
    SHPPR_CPRS_CSTMR_ID VARCHAR(32),
    CNSGN_CPRS_CSTMR_ID VARCHAR(32),
    FSTWY_WYBL_NBR NUMBER(6,0),
    WYBL_TMS TIMESTAMP_NTZ(0),
    STCC_CD VARCHAR(28),
    HZCMD_MTRL_RSPNS_CD NUMBER(7,0),
    ON_JNCTN_SCAC_CD VARCHAR(16),
    ON_JNCTN_FSAC_CD VARCHAR(20),
    ON_JNCTN_TRSTN_VRSN_NBR NUMBER(5,0),
    RCVD_FROM_SCAC_CD VARCHAR(16),
    OFF_JNCTN_SCAC_CD VARCHAR(16),
    OFF_JNCTN_FSAC_CD VARCHAR(20),
    OFF_JNCTN_TRSTN_VRSN_NBR NUMBER(5,0),
    DLVR_TO_SCAC_CD VARCHAR(16),
    RFEQP_ASGN_NBR NUMBER(18,0),
    RFEQP_DATA_BASE_CN VARCHAR(8),
    SHPMT_NBR NUMBER(18,0),
    SHPMT_DATA_BASE_CN VARCHAR(8),
    ORNTN_CD VARCHAR(4),
    LEAD_LCMTV_IND VARCHAR(4),
    LCMTV_CNST_STATUS_CD VARCHAR(40),
    LCMTV_MCHNCL_STATUS_CD VARCHAR(40),
    BRNG_TYPE_CD VARCHAR(4),
    LIFT_MVMNT_EVENT_ID NUMBER(18,0),
    LIFT_EVENT_TMS TIMESTAMP_NTZ(0),
    LIFT_SCAC_CD VARCHAR(16),
    LIFT_FSAC_CD VARCHAR(20),
    LIFT_TRSTN_VRSN_NBR NUMBER(5,0),
    SET_MVMNT_EVENT_ID NUMBER(18,0),
    SET_EVENT_TMS TIMESTAMP_NTZ(0),
    SET_SCAC_CD VARCHAR(16),
    SET_FSAC_CD VARCHAR(20),
    SET_TRSTN_VRSN_NBR NUMBER(5,0),
    CNST_CHNG_EVENT_TMS TIMESTAMP_NTZ(0),
    CNST_CHNG_MVMNT_EVENT_ID NUMBER(18,0),
    CNST_CHNG_SCAC_CD VARCHAR(16),
    CNST_CHNG_FSAC_CD VARCHAR(20),
    CNST_CHNG_TRSTN_VRSN_NBR NUMBER(5,0),
    CARE_OF_PARTY_CPRS_CSTMR_ID VARCHAR(32),
    LIFT_RPRTNG_TM_ZN_CD VARCHAR(8),
    LIFT_RPRTNG_TM_ZN_YR_NBR NUMBER(4,0),
    SET_RPRTNG_TM_ZN_CD VARCHAR(8),
    SET_RPRTNG_TM_ZN_YR_NBR NUMBER(4,0),
    CNST_CHNG_RPRTNG_TM_ZN_CD VARCHAR(8),
    CNST_CHNG_RPRTNG_TM_ZN_YR_NBR NUMBER(4,0),
    INTRCH_MVMNT_ATHRTY_CD VARCHAR(8),
    OCS_UPDATE_CD VARCHAR(4),
    EQPMT_ASGNMN_ID NUMBER(18,0),
    SHPMT_ID NUMBER(18,0),
    CNST_LCM_OPRSTS_ID NUMBER(18,0),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    -- CDC Metadata columns for data preservation
    CDC_OPERATION VARCHAR(10),  
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,    -- Soft delete flag
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100), 

    PRIMARY KEY (TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR, SQNC_NBR)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for TRAIN_CNST_DTL_RAIL_EQPT_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.SADB.SP_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    
    -- =========================================================================
    -- CHECK 1: Detect if stream is stale (happens after IDMC truncate/reload)
    -- =========================================================================
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        
        CREATE OR REPLACE STREAM D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE_HIST_STREAM
        ON TABLE D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.SADB.TRAIN_CNST_DTL_RAIL_EQPT AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE src
            LEFT JOIN D_BRONZE.SADB.TRAIN_CNST_DTL_RAIL_EQPT tgt 
                ON src.TRAIN_CNST_SMRY_ID = tgt.TRAIN_CNST_SMRY_ID
                AND src.TRAIN_CNST_SMRY_VRSN_NBR = tgt.TRAIN_CNST_SMRY_VRSN_NBR
                AND src.SQNC_NBR = tgt.SQNC_NBR
            WHERE tgt.TRAIN_CNST_SMRY_ID IS NULL
               OR tgt.IS_DELETED = TRUE
        ) AS src
        ON tgt.TRAIN_CNST_SMRY_ID = src.TRAIN_CNST_SMRY_ID
            AND tgt.TRAIN_CNST_SMRY_VRSN_NBR = src.TRAIN_CNST_SMRY_VRSN_NBR
            AND tgt.SQNC_NBR = src.SQNC_NBR
        WHEN MATCHED THEN UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.AAR_CAR_TYPE_CD = src.AAR_CAR_TYPE_CD,
            tgt.OTSD_LENGTH_FEET_QTY = src.OTSD_LENGTH_FEET_QTY,
            tgt.OTSD_LENGTH_INCHES_QTY = src.OTSD_LENGTH_INCHES_QTY,
            tgt.TARE_WEIGHT_TONS_QTY = src.TARE_WEIGHT_TONS_QTY,
            tgt.ORIGIN_SCAC_CD = src.ORIGIN_SCAC_CD,
            tgt.ORIGIN_FSAC_CD = src.ORIGIN_FSAC_CD,
            tgt.ORIGIN_TRSTN_VRSN_NBR = src.ORIGIN_TRSTN_VRSN_NBR,
            tgt.DSTNTN_SCAC_CD = src.DSTNTN_SCAC_CD,
            tgt.DSTNTN_FSAC_CD = src.DSTNTN_FSAC_CD,
            tgt.DSTNTN_TRSTN_VRSN_NBR = src.DSTNTN_TRSTN_VRSN_NBR,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.LOAD_EMPTY_IND = src.LOAD_EMPTY_IND,
            tgt.NET_WEIGHT_TONS_QTY = src.NET_WEIGHT_TONS_QTY,
            tgt.CLRNC_PLATE_CD = src.CLRNC_PLATE_CD,
            tgt.BAD_ORDER_CAR_GRADE_CD = src.BAD_ORDER_CAR_GRADE_CD,
            tgt.BAD_ORDER_REASON_CD = src.BAD_ORDER_REASON_CD,
            tgt.SHPPR_CPRS_CSTMR_ID = src.SHPPR_CPRS_CSTMR_ID,
            tgt.CNSGN_CPRS_CSTMR_ID = src.CNSGN_CPRS_CSTMR_ID,
            tgt.FSTWY_WYBL_NBR = src.FSTWY_WYBL_NBR,
            tgt.WYBL_TMS = src.WYBL_TMS,
            tgt.STCC_CD = src.STCC_CD,
            tgt.HZCMD_MTRL_RSPNS_CD = src.HZCMD_MTRL_RSPNS_CD,
            tgt.ON_JNCTN_SCAC_CD = src.ON_JNCTN_SCAC_CD,
            tgt.ON_JNCTN_FSAC_CD = src.ON_JNCTN_FSAC_CD,
            tgt.ON_JNCTN_TRSTN_VRSN_NBR = src.ON_JNCTN_TRSTN_VRSN_NBR,
            tgt.RCVD_FROM_SCAC_CD = src.RCVD_FROM_SCAC_CD,
            tgt.OFF_JNCTN_SCAC_CD = src.OFF_JNCTN_SCAC_CD,
            tgt.OFF_JNCTN_FSAC_CD = src.OFF_JNCTN_FSAC_CD,
            tgt.OFF_JNCTN_TRSTN_VRSN_NBR = src.OFF_JNCTN_TRSTN_VRSN_NBR,
            tgt.DLVR_TO_SCAC_CD = src.DLVR_TO_SCAC_CD,
            tgt.RFEQP_ASGN_NBR = src.RFEQP_ASGN_NBR,
            tgt.RFEQP_DATA_BASE_CN = src.RFEQP_DATA_BASE_CN,
            tgt.SHPMT_NBR = src.SHPMT_NBR,
            tgt.SHPMT_DATA_BASE_CN = src.SHPMT_DATA_BASE_CN,
            tgt.ORNTN_CD = src.ORNTN_CD,
            tgt.LEAD_LCMTV_IND = src.LEAD_LCMTV_IND,
            tgt.LCMTV_CNST_STATUS_CD = src.LCMTV_CNST_STATUS_CD,
            tgt.LCMTV_MCHNCL_STATUS_CD = src.LCMTV_MCHNCL_STATUS_CD,
            tgt.BRNG_TYPE_CD = src.BRNG_TYPE_CD,
            tgt.LIFT_MVMNT_EVENT_ID = src.LIFT_MVMNT_EVENT_ID,
            tgt.LIFT_EVENT_TMS = src.LIFT_EVENT_TMS,
            tgt.LIFT_SCAC_CD = src.LIFT_SCAC_CD,
            tgt.LIFT_FSAC_CD = src.LIFT_FSAC_CD,
            tgt.LIFT_TRSTN_VRSN_NBR = src.LIFT_TRSTN_VRSN_NBR,
            tgt.SET_MVMNT_EVENT_ID = src.SET_MVMNT_EVENT_ID,
            tgt.SET_EVENT_TMS = src.SET_EVENT_TMS,
            tgt.SET_SCAC_CD = src.SET_SCAC_CD,
            tgt.SET_FSAC_CD = src.SET_FSAC_CD,
            tgt.SET_TRSTN_VRSN_NBR = src.SET_TRSTN_VRSN_NBR,
            tgt.CNST_CHNG_EVENT_TMS = src.CNST_CHNG_EVENT_TMS,
            tgt.CNST_CHNG_MVMNT_EVENT_ID = src.CNST_CHNG_MVMNT_EVENT_ID,
            tgt.CNST_CHNG_SCAC_CD = src.CNST_CHNG_SCAC_CD,
            tgt.CNST_CHNG_FSAC_CD = src.CNST_CHNG_FSAC_CD,
            tgt.CNST_CHNG_TRSTN_VRSN_NBR = src.CNST_CHNG_TRSTN_VRSN_NBR,
            tgt.CARE_OF_PARTY_CPRS_CSTMR_ID = src.CARE_OF_PARTY_CPRS_CSTMR_ID,
            tgt.LIFT_RPRTNG_TM_ZN_CD = src.LIFT_RPRTNG_TM_ZN_CD,
            tgt.LIFT_RPRTNG_TM_ZN_YR_NBR = src.LIFT_RPRTNG_TM_ZN_YR_NBR,
            tgt.SET_RPRTNG_TM_ZN_CD = src.SET_RPRTNG_TM_ZN_CD,
            tgt.SET_RPRTNG_TM_ZN_YR_NBR = src.SET_RPRTNG_TM_ZN_YR_NBR,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_CD = src.CNST_CHNG_RPRTNG_TM_ZN_CD,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR = src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            tgt.INTRCH_MVMNT_ATHRTY_CD = src.INTRCH_MVMNT_ATHRTY_CD,
            tgt.OCS_UPDATE_CD = src.OCS_UPDATE_CD,
            tgt.EQPMT_ASGNMN_ID = src.EQPMT_ASGNMN_ID,
            tgt.SHPMT_ID = src.SHPMT_ID,
            tgt.CNST_LCM_OPRSTS_ID = src.CNST_LCM_OPRSTS_ID,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR, SQNC_NBR,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID,
            MARK_CD, EQPUN_NBR, AAR_CAR_TYPE_CD, OTSD_LENGTH_FEET_QTY, OTSD_LENGTH_INCHES_QTY,
            TARE_WEIGHT_TONS_QTY, ORIGIN_SCAC_CD, ORIGIN_FSAC_CD, ORIGIN_TRSTN_VRSN_NBR,
            DSTNTN_SCAC_CD, DSTNTN_FSAC_CD, DSTNTN_TRSTN_VRSN_NBR, CYCLE_SERIAL_NBR,
            LOAD_EMPTY_IND, NET_WEIGHT_TONS_QTY, CLRNC_PLATE_CD, BAD_ORDER_CAR_GRADE_CD,
            BAD_ORDER_REASON_CD, SHPPR_CPRS_CSTMR_ID, CNSGN_CPRS_CSTMR_ID, FSTWY_WYBL_NBR,
            WYBL_TMS, STCC_CD, HZCMD_MTRL_RSPNS_CD, ON_JNCTN_SCAC_CD, ON_JNCTN_FSAC_CD,
            ON_JNCTN_TRSTN_VRSN_NBR, RCVD_FROM_SCAC_CD, OFF_JNCTN_SCAC_CD, OFF_JNCTN_FSAC_CD,
            OFF_JNCTN_TRSTN_VRSN_NBR, DLVR_TO_SCAC_CD, RFEQP_ASGN_NBR, RFEQP_DATA_BASE_CN,
            SHPMT_NBR, SHPMT_DATA_BASE_CN, ORNTN_CD, LEAD_LCMTV_IND, LCMTV_CNST_STATUS_CD,
            LCMTV_MCHNCL_STATUS_CD, BRNG_TYPE_CD, LIFT_MVMNT_EVENT_ID, LIFT_EVENT_TMS,
            LIFT_SCAC_CD, LIFT_FSAC_CD, LIFT_TRSTN_VRSN_NBR, SET_MVMNT_EVENT_ID, SET_EVENT_TMS,
            SET_SCAC_CD, SET_FSAC_CD, SET_TRSTN_VRSN_NBR, CNST_CHNG_EVENT_TMS,
            CNST_CHNG_MVMNT_EVENT_ID, CNST_CHNG_SCAC_CD, CNST_CHNG_FSAC_CD, CNST_CHNG_TRSTN_VRSN_NBR,
            CARE_OF_PARTY_CPRS_CSTMR_ID, LIFT_RPRTNG_TM_ZN_CD, LIFT_RPRTNG_TM_ZN_YR_NBR,
            SET_RPRTNG_TM_ZN_CD, SET_RPRTNG_TM_ZN_YR_NBR, CNST_CHNG_RPRTNG_TM_ZN_CD,
            CNST_CHNG_RPRTNG_TM_ZN_YR_NBR, INTRCH_MVMNT_ATHRTY_CD, OCS_UPDATE_CD,
            EQPMT_ASGNMN_ID, SHPMT_ID, CNST_LCM_OPRSTS_ID, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.TRAIN_CNST_SMRY_ID, src.TRAIN_CNST_SMRY_VRSN_NBR, src.SQNC_NBR,
            src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID,
            src.MARK_CD, src.EQPUN_NBR, src.AAR_CAR_TYPE_CD, src.OTSD_LENGTH_FEET_QTY, src.OTSD_LENGTH_INCHES_QTY,
            src.TARE_WEIGHT_TONS_QTY, src.ORIGIN_SCAC_CD, src.ORIGIN_FSAC_CD, src.ORIGIN_TRSTN_VRSN_NBR,
            src.DSTNTN_SCAC_CD, src.DSTNTN_FSAC_CD, src.DSTNTN_TRSTN_VRSN_NBR, src.CYCLE_SERIAL_NBR,
            src.LOAD_EMPTY_IND, src.NET_WEIGHT_TONS_QTY, src.CLRNC_PLATE_CD, src.BAD_ORDER_CAR_GRADE_CD,
            src.BAD_ORDER_REASON_CD, src.SHPPR_CPRS_CSTMR_ID, src.CNSGN_CPRS_CSTMR_ID, src.FSTWY_WYBL_NBR,
            src.WYBL_TMS, src.STCC_CD, src.HZCMD_MTRL_RSPNS_CD, src.ON_JNCTN_SCAC_CD, src.ON_JNCTN_FSAC_CD,
            src.ON_JNCTN_TRSTN_VRSN_NBR, src.RCVD_FROM_SCAC_CD, src.OFF_JNCTN_SCAC_CD, src.OFF_JNCTN_FSAC_CD,
            src.OFF_JNCTN_TRSTN_VRSN_NBR, src.DLVR_TO_SCAC_CD, src.RFEQP_ASGN_NBR, src.RFEQP_DATA_BASE_CN,
            src.SHPMT_NBR, src.SHPMT_DATA_BASE_CN, src.ORNTN_CD, src.LEAD_LCMTV_IND, src.LCMTV_CNST_STATUS_CD,
            src.LCMTV_MCHNCL_STATUS_CD, src.BRNG_TYPE_CD, src.LIFT_MVMNT_EVENT_ID, src.LIFT_EVENT_TMS,
            src.LIFT_SCAC_CD, src.LIFT_FSAC_CD, src.LIFT_TRSTN_VRSN_NBR, src.SET_MVMNT_EVENT_ID, src.SET_EVENT_TMS,
            src.SET_SCAC_CD, src.SET_FSAC_CD, src.SET_TRSTN_VRSN_NBR, src.CNST_CHNG_EVENT_TMS,
            src.CNST_CHNG_MVMNT_EVENT_ID, src.CNST_CHNG_SCAC_CD, src.CNST_CHNG_FSAC_CD, src.CNST_CHNG_TRSTN_VRSN_NBR,
            src.CARE_OF_PARTY_CPRS_CSTMR_ID, src.LIFT_RPRTNG_TM_ZN_CD, src.LIFT_RPRTNG_TM_ZN_YR_NBR,
            src.SET_RPRTNG_TM_ZN_CD, src.SET_RPRTNG_TM_ZN_YR_NBR, src.CNST_CHNG_RPRTNG_TM_ZN_CD,
            src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR, src.INTRCH_MVMNT_ATHRTY_CD, src.OCS_UPDATE_CD,
            src.EQPMT_ASGNMN_ID, src.SHPMT_ID, src.CNST_LCM_OPRSTS_ID, src.SNW_OPERATION_TYPE, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_TRAIN_CNST_DTL_RAIL_EQPT AS
    SELECT 
        TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR, SQNC_NBR,
        RECORD_CREATE_TMS, RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID,
        MARK_CD, EQPUN_NBR, AAR_CAR_TYPE_CD, OTSD_LENGTH_FEET_QTY, OTSD_LENGTH_INCHES_QTY,
        TARE_WEIGHT_TONS_QTY, ORIGIN_SCAC_CD, ORIGIN_FSAC_CD, ORIGIN_TRSTN_VRSN_NBR,
        DSTNTN_SCAC_CD, DSTNTN_FSAC_CD, DSTNTN_TRSTN_VRSN_NBR, CYCLE_SERIAL_NBR,
        LOAD_EMPTY_IND, NET_WEIGHT_TONS_QTY, CLRNC_PLATE_CD, BAD_ORDER_CAR_GRADE_CD,
        BAD_ORDER_REASON_CD, SHPPR_CPRS_CSTMR_ID, CNSGN_CPRS_CSTMR_ID, FSTWY_WYBL_NBR,
        WYBL_TMS, STCC_CD, HZCMD_MTRL_RSPNS_CD, ON_JNCTN_SCAC_CD, ON_JNCTN_FSAC_CD,
        ON_JNCTN_TRSTN_VRSN_NBR, RCVD_FROM_SCAC_CD, OFF_JNCTN_SCAC_CD, OFF_JNCTN_FSAC_CD,
        OFF_JNCTN_TRSTN_VRSN_NBR, DLVR_TO_SCAC_CD, RFEQP_ASGN_NBR, RFEQP_DATA_BASE_CN,
        SHPMT_NBR, SHPMT_DATA_BASE_CN, ORNTN_CD, LEAD_LCMTV_IND, LCMTV_CNST_STATUS_CD,
        LCMTV_MCHNCL_STATUS_CD, BRNG_TYPE_CD, LIFT_MVMNT_EVENT_ID, LIFT_EVENT_TMS,
        LIFT_SCAC_CD, LIFT_FSAC_CD, LIFT_TRSTN_VRSN_NBR, SET_MVMNT_EVENT_ID, SET_EVENT_TMS,
        SET_SCAC_CD, SET_FSAC_CD, SET_TRSTN_VRSN_NBR, CNST_CHNG_EVENT_TMS,
        CNST_CHNG_MVMNT_EVENT_ID, CNST_CHNG_SCAC_CD, CNST_CHNG_FSAC_CD, CNST_CHNG_TRSTN_VRSN_NBR,
        CARE_OF_PARTY_CPRS_CSTMR_ID, LIFT_RPRTNG_TM_ZN_CD, LIFT_RPRTNG_TM_ZN_YR_NBR,
        SET_RPRTNG_TM_ZN_CD, SET_RPRTNG_TM_ZN_YR_NBR, CNST_CHNG_RPRTNG_TM_ZN_CD,
        CNST_CHNG_RPRTNG_TM_ZN_YR_NBR, INTRCH_MVMNT_ATHRTY_CD, OCS_UPDATE_CD,
        EQPMT_ASGNMN_ID, SHPMT_ID, CNST_LCM_OPRSTS_ID, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_TRAIN_CNST_DTL_RAIL_EQPT;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_TRAIN_CNST_DTL_RAIL_EQPT;
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.SADB.TRAIN_CNST_DTL_RAIL_EQPT AS tgt
    USING (
        SELECT 
            TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR, SQNC_NBR,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID,
            MARK_CD, EQPUN_NBR, AAR_CAR_TYPE_CD, OTSD_LENGTH_FEET_QTY, OTSD_LENGTH_INCHES_QTY,
            TARE_WEIGHT_TONS_QTY, ORIGIN_SCAC_CD, ORIGIN_FSAC_CD, ORIGIN_TRSTN_VRSN_NBR,
            DSTNTN_SCAC_CD, DSTNTN_FSAC_CD, DSTNTN_TRSTN_VRSN_NBR, CYCLE_SERIAL_NBR,
            LOAD_EMPTY_IND, NET_WEIGHT_TONS_QTY, CLRNC_PLATE_CD, BAD_ORDER_CAR_GRADE_CD,
            BAD_ORDER_REASON_CD, SHPPR_CPRS_CSTMR_ID, CNSGN_CPRS_CSTMR_ID, FSTWY_WYBL_NBR,
            WYBL_TMS, STCC_CD, HZCMD_MTRL_RSPNS_CD, ON_JNCTN_SCAC_CD, ON_JNCTN_FSAC_CD,
            ON_JNCTN_TRSTN_VRSN_NBR, RCVD_FROM_SCAC_CD, OFF_JNCTN_SCAC_CD, OFF_JNCTN_FSAC_CD,
            OFF_JNCTN_TRSTN_VRSN_NBR, DLVR_TO_SCAC_CD, RFEQP_ASGN_NBR, RFEQP_DATA_BASE_CN,
            SHPMT_NBR, SHPMT_DATA_BASE_CN, ORNTN_CD, LEAD_LCMTV_IND, LCMTV_CNST_STATUS_CD,
            LCMTV_MCHNCL_STATUS_CD, BRNG_TYPE_CD, LIFT_MVMNT_EVENT_ID, LIFT_EVENT_TMS,
            LIFT_SCAC_CD, LIFT_FSAC_CD, LIFT_TRSTN_VRSN_NBR, SET_MVMNT_EVENT_ID, SET_EVENT_TMS,
            SET_SCAC_CD, SET_FSAC_CD, SET_TRSTN_VRSN_NBR, CNST_CHNG_EVENT_TMS,
            CNST_CHNG_MVMNT_EVENT_ID, CNST_CHNG_SCAC_CD, CNST_CHNG_FSAC_CD, CNST_CHNG_TRSTN_VRSN_NBR,
            CARE_OF_PARTY_CPRS_CSTMR_ID, LIFT_RPRTNG_TM_ZN_CD, LIFT_RPRTNG_TM_ZN_YR_NBR,
            SET_RPRTNG_TM_ZN_CD, SET_RPRTNG_TM_ZN_YR_NBR, CNST_CHNG_RPRTNG_TM_ZN_CD,
            CNST_CHNG_RPRTNG_TM_ZN_YR_NBR, INTRCH_MVMNT_ATHRTY_CD, OCS_UPDATE_CD,
            EQPMT_ASGNMN_ID, SHPMT_ID, CNST_LCM_OPRSTS_ID, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_ACTION,
            CDC_IS_UPDATE,
            ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_TRAIN_CNST_DTL_RAIL_EQPT
    ) AS src
    ON tgt.TRAIN_CNST_SMRY_ID = src.TRAIN_CNST_SMRY_ID
        AND tgt.TRAIN_CNST_SMRY_VRSN_NBR = src.TRAIN_CNST_SMRY_VRSN_NBR
        AND tgt.SQNC_NBR = src.SQNC_NBR
    
    -- UPDATE scenario (METADATA$ACTION='INSERT' AND METADATA$ISUPDATE=TRUE)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.AAR_CAR_TYPE_CD = src.AAR_CAR_TYPE_CD,
            tgt.OTSD_LENGTH_FEET_QTY = src.OTSD_LENGTH_FEET_QTY,
            tgt.OTSD_LENGTH_INCHES_QTY = src.OTSD_LENGTH_INCHES_QTY,
            tgt.TARE_WEIGHT_TONS_QTY = src.TARE_WEIGHT_TONS_QTY,
            tgt.ORIGIN_SCAC_CD = src.ORIGIN_SCAC_CD,
            tgt.ORIGIN_FSAC_CD = src.ORIGIN_FSAC_CD,
            tgt.ORIGIN_TRSTN_VRSN_NBR = src.ORIGIN_TRSTN_VRSN_NBR,
            tgt.DSTNTN_SCAC_CD = src.DSTNTN_SCAC_CD,
            tgt.DSTNTN_FSAC_CD = src.DSTNTN_FSAC_CD,
            tgt.DSTNTN_TRSTN_VRSN_NBR = src.DSTNTN_TRSTN_VRSN_NBR,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.LOAD_EMPTY_IND = src.LOAD_EMPTY_IND,
            tgt.NET_WEIGHT_TONS_QTY = src.NET_WEIGHT_TONS_QTY,
            tgt.CLRNC_PLATE_CD = src.CLRNC_PLATE_CD,
            tgt.BAD_ORDER_CAR_GRADE_CD = src.BAD_ORDER_CAR_GRADE_CD,
            tgt.BAD_ORDER_REASON_CD = src.BAD_ORDER_REASON_CD,
            tgt.SHPPR_CPRS_CSTMR_ID = src.SHPPR_CPRS_CSTMR_ID,
            tgt.CNSGN_CPRS_CSTMR_ID = src.CNSGN_CPRS_CSTMR_ID,
            tgt.FSTWY_WYBL_NBR = src.FSTWY_WYBL_NBR,
            tgt.WYBL_TMS = src.WYBL_TMS,
            tgt.STCC_CD = src.STCC_CD,
            tgt.HZCMD_MTRL_RSPNS_CD = src.HZCMD_MTRL_RSPNS_CD,
            tgt.ON_JNCTN_SCAC_CD = src.ON_JNCTN_SCAC_CD,
            tgt.ON_JNCTN_FSAC_CD = src.ON_JNCTN_FSAC_CD,
            tgt.ON_JNCTN_TRSTN_VRSN_NBR = src.ON_JNCTN_TRSTN_VRSN_NBR,
            tgt.RCVD_FROM_SCAC_CD = src.RCVD_FROM_SCAC_CD,
            tgt.OFF_JNCTN_SCAC_CD = src.OFF_JNCTN_SCAC_CD,
            tgt.OFF_JNCTN_FSAC_CD = src.OFF_JNCTN_FSAC_CD,
            tgt.OFF_JNCTN_TRSTN_VRSN_NBR = src.OFF_JNCTN_TRSTN_VRSN_NBR,
            tgt.DLVR_TO_SCAC_CD = src.DLVR_TO_SCAC_CD,
            tgt.RFEQP_ASGN_NBR = src.RFEQP_ASGN_NBR,
            tgt.RFEQP_DATA_BASE_CN = src.RFEQP_DATA_BASE_CN,
            tgt.SHPMT_NBR = src.SHPMT_NBR,
            tgt.SHPMT_DATA_BASE_CN = src.SHPMT_DATA_BASE_CN,
            tgt.ORNTN_CD = src.ORNTN_CD,
            tgt.LEAD_LCMTV_IND = src.LEAD_LCMTV_IND,
            tgt.LCMTV_CNST_STATUS_CD = src.LCMTV_CNST_STATUS_CD,
            tgt.LCMTV_MCHNCL_STATUS_CD = src.LCMTV_MCHNCL_STATUS_CD,
            tgt.BRNG_TYPE_CD = src.BRNG_TYPE_CD,
            tgt.LIFT_MVMNT_EVENT_ID = src.LIFT_MVMNT_EVENT_ID,
            tgt.LIFT_EVENT_TMS = src.LIFT_EVENT_TMS,
            tgt.LIFT_SCAC_CD = src.LIFT_SCAC_CD,
            tgt.LIFT_FSAC_CD = src.LIFT_FSAC_CD,
            tgt.LIFT_TRSTN_VRSN_NBR = src.LIFT_TRSTN_VRSN_NBR,
            tgt.SET_MVMNT_EVENT_ID = src.SET_MVMNT_EVENT_ID,
            tgt.SET_EVENT_TMS = src.SET_EVENT_TMS,
            tgt.SET_SCAC_CD = src.SET_SCAC_CD,
            tgt.SET_FSAC_CD = src.SET_FSAC_CD,
            tgt.SET_TRSTN_VRSN_NBR = src.SET_TRSTN_VRSN_NBR,
            tgt.CNST_CHNG_EVENT_TMS = src.CNST_CHNG_EVENT_TMS,
            tgt.CNST_CHNG_MVMNT_EVENT_ID = src.CNST_CHNG_MVMNT_EVENT_ID,
            tgt.CNST_CHNG_SCAC_CD = src.CNST_CHNG_SCAC_CD,
            tgt.CNST_CHNG_FSAC_CD = src.CNST_CHNG_FSAC_CD,
            tgt.CNST_CHNG_TRSTN_VRSN_NBR = src.CNST_CHNG_TRSTN_VRSN_NBR,
            tgt.CARE_OF_PARTY_CPRS_CSTMR_ID = src.CARE_OF_PARTY_CPRS_CSTMR_ID,
            tgt.LIFT_RPRTNG_TM_ZN_CD = src.LIFT_RPRTNG_TM_ZN_CD,
            tgt.LIFT_RPRTNG_TM_ZN_YR_NBR = src.LIFT_RPRTNG_TM_ZN_YR_NBR,
            tgt.SET_RPRTNG_TM_ZN_CD = src.SET_RPRTNG_TM_ZN_CD,
            tgt.SET_RPRTNG_TM_ZN_YR_NBR = src.SET_RPRTNG_TM_ZN_YR_NBR,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_CD = src.CNST_CHNG_RPRTNG_TM_ZN_CD,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR = src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            tgt.INTRCH_MVMNT_ATHRTY_CD = src.INTRCH_MVMNT_ATHRTY_CD,
            tgt.OCS_UPDATE_CD = src.OCS_UPDATE_CD,
            tgt.EQPMT_ASGNMN_ID = src.EQPMT_ASGNMN_ID,
            tgt.SHPMT_ID = src.SHPMT_ID,
            tgt.CNST_LCM_OPRSTS_ID = src.CNST_LCM_OPRSTS_ID,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- DELETE scenario (METADATA$ACTION='DELETE' AND METADATA$ISUPDATE=FALSE)
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- RE-INSERT scenario (record exists but being re-inserted)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.MARK_CD = src.MARK_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.AAR_CAR_TYPE_CD = src.AAR_CAR_TYPE_CD,
            tgt.OTSD_LENGTH_FEET_QTY = src.OTSD_LENGTH_FEET_QTY,
            tgt.OTSD_LENGTH_INCHES_QTY = src.OTSD_LENGTH_INCHES_QTY,
            tgt.TARE_WEIGHT_TONS_QTY = src.TARE_WEIGHT_TONS_QTY,
            tgt.ORIGIN_SCAC_CD = src.ORIGIN_SCAC_CD,
            tgt.ORIGIN_FSAC_CD = src.ORIGIN_FSAC_CD,
            tgt.ORIGIN_TRSTN_VRSN_NBR = src.ORIGIN_TRSTN_VRSN_NBR,
            tgt.DSTNTN_SCAC_CD = src.DSTNTN_SCAC_CD,
            tgt.DSTNTN_FSAC_CD = src.DSTNTN_FSAC_CD,
            tgt.DSTNTN_TRSTN_VRSN_NBR = src.DSTNTN_TRSTN_VRSN_NBR,
            tgt.CYCLE_SERIAL_NBR = src.CYCLE_SERIAL_NBR,
            tgt.LOAD_EMPTY_IND = src.LOAD_EMPTY_IND,
            tgt.NET_WEIGHT_TONS_QTY = src.NET_WEIGHT_TONS_QTY,
            tgt.CLRNC_PLATE_CD = src.CLRNC_PLATE_CD,
            tgt.BAD_ORDER_CAR_GRADE_CD = src.BAD_ORDER_CAR_GRADE_CD,
            tgt.BAD_ORDER_REASON_CD = src.BAD_ORDER_REASON_CD,
            tgt.SHPPR_CPRS_CSTMR_ID = src.SHPPR_CPRS_CSTMR_ID,
            tgt.CNSGN_CPRS_CSTMR_ID = src.CNSGN_CPRS_CSTMR_ID,
            tgt.FSTWY_WYBL_NBR = src.FSTWY_WYBL_NBR,
            tgt.WYBL_TMS = src.WYBL_TMS,
            tgt.STCC_CD = src.STCC_CD,
            tgt.HZCMD_MTRL_RSPNS_CD = src.HZCMD_MTRL_RSPNS_CD,
            tgt.ON_JNCTN_SCAC_CD = src.ON_JNCTN_SCAC_CD,
            tgt.ON_JNCTN_FSAC_CD = src.ON_JNCTN_FSAC_CD,
            tgt.ON_JNCTN_TRSTN_VRSN_NBR = src.ON_JNCTN_TRSTN_VRSN_NBR,
            tgt.RCVD_FROM_SCAC_CD = src.RCVD_FROM_SCAC_CD,
            tgt.OFF_JNCTN_SCAC_CD = src.OFF_JNCTN_SCAC_CD,
            tgt.OFF_JNCTN_FSAC_CD = src.OFF_JNCTN_FSAC_CD,
            tgt.OFF_JNCTN_TRSTN_VRSN_NBR = src.OFF_JNCTN_TRSTN_VRSN_NBR,
            tgt.DLVR_TO_SCAC_CD = src.DLVR_TO_SCAC_CD,
            tgt.RFEQP_ASGN_NBR = src.RFEQP_ASGN_NBR,
            tgt.RFEQP_DATA_BASE_CN = src.RFEQP_DATA_BASE_CN,
            tgt.SHPMT_NBR = src.SHPMT_NBR,
            tgt.SHPMT_DATA_BASE_CN = src.SHPMT_DATA_BASE_CN,
            tgt.ORNTN_CD = src.ORNTN_CD,
            tgt.LEAD_LCMTV_IND = src.LEAD_LCMTV_IND,
            tgt.LCMTV_CNST_STATUS_CD = src.LCMTV_CNST_STATUS_CD,
            tgt.LCMTV_MCHNCL_STATUS_CD = src.LCMTV_MCHNCL_STATUS_CD,
            tgt.BRNG_TYPE_CD = src.BRNG_TYPE_CD,
            tgt.LIFT_MVMNT_EVENT_ID = src.LIFT_MVMNT_EVENT_ID,
            tgt.LIFT_EVENT_TMS = src.LIFT_EVENT_TMS,
            tgt.LIFT_SCAC_CD = src.LIFT_SCAC_CD,
            tgt.LIFT_FSAC_CD = src.LIFT_FSAC_CD,
            tgt.LIFT_TRSTN_VRSN_NBR = src.LIFT_TRSTN_VRSN_NBR,
            tgt.SET_MVMNT_EVENT_ID = src.SET_MVMNT_EVENT_ID,
            tgt.SET_EVENT_TMS = src.SET_EVENT_TMS,
            tgt.SET_SCAC_CD = src.SET_SCAC_CD,
            tgt.SET_FSAC_CD = src.SET_FSAC_CD,
            tgt.SET_TRSTN_VRSN_NBR = src.SET_TRSTN_VRSN_NBR,
            tgt.CNST_CHNG_EVENT_TMS = src.CNST_CHNG_EVENT_TMS,
            tgt.CNST_CHNG_MVMNT_EVENT_ID = src.CNST_CHNG_MVMNT_EVENT_ID,
            tgt.CNST_CHNG_SCAC_CD = src.CNST_CHNG_SCAC_CD,
            tgt.CNST_CHNG_FSAC_CD = src.CNST_CHNG_FSAC_CD,
            tgt.CNST_CHNG_TRSTN_VRSN_NBR = src.CNST_CHNG_TRSTN_VRSN_NBR,
            tgt.CARE_OF_PARTY_CPRS_CSTMR_ID = src.CARE_OF_PARTY_CPRS_CSTMR_ID,
            tgt.LIFT_RPRTNG_TM_ZN_CD = src.LIFT_RPRTNG_TM_ZN_CD,
            tgt.LIFT_RPRTNG_TM_ZN_YR_NBR = src.LIFT_RPRTNG_TM_ZN_YR_NBR,
            tgt.SET_RPRTNG_TM_ZN_CD = src.SET_RPRTNG_TM_ZN_CD,
            tgt.SET_RPRTNG_TM_ZN_YR_NBR = src.SET_RPRTNG_TM_ZN_YR_NBR,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_CD = src.CNST_CHNG_RPRTNG_TM_ZN_CD,
            tgt.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR = src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR,
            tgt.INTRCH_MVMNT_ATHRTY_CD = src.INTRCH_MVMNT_ATHRTY_CD,
            tgt.OCS_UPDATE_CD = src.OCS_UPDATE_CD,
            tgt.EQPMT_ASGNMN_ID = src.EQPMT_ASGNMN_ID,
            tgt.SHPMT_ID = src.SHPMT_ID,
            tgt.CNST_LCM_OPRSTS_ID = src.CNST_LCM_OPRSTS_ID,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- NEW INSERT scenario
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            TRAIN_CNST_SMRY_ID, TRAIN_CNST_SMRY_VRSN_NBR, SQNC_NBR,
            RECORD_CREATE_TMS, RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID,
            MARK_CD, EQPUN_NBR, AAR_CAR_TYPE_CD, OTSD_LENGTH_FEET_QTY, OTSD_LENGTH_INCHES_QTY,
            TARE_WEIGHT_TONS_QTY, ORIGIN_SCAC_CD, ORIGIN_FSAC_CD, ORIGIN_TRSTN_VRSN_NBR,
            DSTNTN_SCAC_CD, DSTNTN_FSAC_CD, DSTNTN_TRSTN_VRSN_NBR, CYCLE_SERIAL_NBR,
            LOAD_EMPTY_IND, NET_WEIGHT_TONS_QTY, CLRNC_PLATE_CD, BAD_ORDER_CAR_GRADE_CD,
            BAD_ORDER_REASON_CD, SHPPR_CPRS_CSTMR_ID, CNSGN_CPRS_CSTMR_ID, FSTWY_WYBL_NBR,
            WYBL_TMS, STCC_CD, HZCMD_MTRL_RSPNS_CD, ON_JNCTN_SCAC_CD, ON_JNCTN_FSAC_CD,
            ON_JNCTN_TRSTN_VRSN_NBR, RCVD_FROM_SCAC_CD, OFF_JNCTN_SCAC_CD, OFF_JNCTN_FSAC_CD,
            OFF_JNCTN_TRSTN_VRSN_NBR, DLVR_TO_SCAC_CD, RFEQP_ASGN_NBR, RFEQP_DATA_BASE_CN,
            SHPMT_NBR, SHPMT_DATA_BASE_CN, ORNTN_CD, LEAD_LCMTV_IND, LCMTV_CNST_STATUS_CD,
            LCMTV_MCHNCL_STATUS_CD, BRNG_TYPE_CD, LIFT_MVMNT_EVENT_ID, LIFT_EVENT_TMS,
            LIFT_SCAC_CD, LIFT_FSAC_CD, LIFT_TRSTN_VRSN_NBR, SET_MVMNT_EVENT_ID, SET_EVENT_TMS,
            SET_SCAC_CD, SET_FSAC_CD, SET_TRSTN_VRSN_NBR, CNST_CHNG_EVENT_TMS,
            CNST_CHNG_MVMNT_EVENT_ID, CNST_CHNG_SCAC_CD, CNST_CHNG_FSAC_CD, CNST_CHNG_TRSTN_VRSN_NBR,
            CARE_OF_PARTY_CPRS_CSTMR_ID, LIFT_RPRTNG_TM_ZN_CD, LIFT_RPRTNG_TM_ZN_YR_NBR,
            SET_RPRTNG_TM_ZN_CD, SET_RPRTNG_TM_ZN_YR_NBR, CNST_CHNG_RPRTNG_TM_ZN_CD,
            CNST_CHNG_RPRTNG_TM_ZN_YR_NBR, INTRCH_MVMNT_ATHRTY_CD, OCS_UPDATE_CD,
            EQPMT_ASGNMN_ID, SHPMT_ID, CNST_LCM_OPRSTS_ID, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.TRAIN_CNST_SMRY_ID, src.TRAIN_CNST_SMRY_VRSN_NBR, src.SQNC_NBR,
            src.RECORD_CREATE_TMS, src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID,
            src.MARK_CD, src.EQPUN_NBR, src.AAR_CAR_TYPE_CD, src.OTSD_LENGTH_FEET_QTY, src.OTSD_LENGTH_INCHES_QTY,
            src.TARE_WEIGHT_TONS_QTY, src.ORIGIN_SCAC_CD, src.ORIGIN_FSAC_CD, src.ORIGIN_TRSTN_VRSN_NBR,
            src.DSTNTN_SCAC_CD, src.DSTNTN_FSAC_CD, src.DSTNTN_TRSTN_VRSN_NBR, src.CYCLE_SERIAL_NBR,
            src.LOAD_EMPTY_IND, src.NET_WEIGHT_TONS_QTY, src.CLRNC_PLATE_CD, src.BAD_ORDER_CAR_GRADE_CD,
            src.BAD_ORDER_REASON_CD, src.SHPPR_CPRS_CSTMR_ID, src.CNSGN_CPRS_CSTMR_ID, src.FSTWY_WYBL_NBR,
            src.WYBL_TMS, src.STCC_CD, src.HZCMD_MTRL_RSPNS_CD, src.ON_JNCTN_SCAC_CD, src.ON_JNCTN_FSAC_CD,
            src.ON_JNCTN_TRSTN_VRSN_NBR, src.RCVD_FROM_SCAC_CD, src.OFF_JNCTN_SCAC_CD, src.OFF_JNCTN_FSAC_CD,
            src.OFF_JNCTN_TRSTN_VRSN_NBR, src.DLVR_TO_SCAC_CD, src.RFEQP_ASGN_NBR, src.RFEQP_DATA_BASE_CN,
            src.SHPMT_NBR, src.SHPMT_DATA_BASE_CN, src.ORNTN_CD, src.LEAD_LCMTV_IND, src.LCMTV_CNST_STATUS_CD,
            src.LCMTV_MCHNCL_STATUS_CD, src.BRNG_TYPE_CD, src.LIFT_MVMNT_EVENT_ID, src.LIFT_EVENT_TMS,
            src.LIFT_SCAC_CD, src.LIFT_FSAC_CD, src.LIFT_TRSTN_VRSN_NBR, src.SET_MVMNT_EVENT_ID, src.SET_EVENT_TMS,
            src.SET_SCAC_CD, src.SET_FSAC_CD, src.SET_TRSTN_VRSN_NBR, src.CNST_CHNG_EVENT_TMS,
            src.CNST_CHNG_MVMNT_EVENT_ID, src.CNST_CHNG_SCAC_CD, src.CNST_CHNG_FSAC_CD, src.CNST_CHNG_TRSTN_VRSN_NBR,
            src.CARE_OF_PARTY_CPRS_CSTMR_ID, src.LIFT_RPRTNG_TM_ZN_CD, src.LIFT_RPRTNG_TM_ZN_YR_NBR,
            src.SET_RPRTNG_TM_ZN_CD, src.SET_RPRTNG_TM_ZN_YR_NBR, src.CNST_CHNG_RPRTNG_TM_ZN_CD,
            src.CNST_CHNG_RPRTNG_TM_ZN_YR_NBR, src.INTRCH_MVMNT_ATHRTY_CD, src.OCS_UPDATE_CD,
            src.EQPMT_ASGNMN_ID, src.SHPMT_ID, src.CNST_LCM_OPRSTS_ID, src.SNW_OPERATION_TYPE, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    DROP TABLE IF EXISTS _CDC_STAGING_TRAIN_CNST_DTL_RAIL_EQPT;
    
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes. Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        DROP TABLE IF EXISTS _CDC_STAGING_TRAIN_CNST_DTL_RAIL_EQPT;
        RETURN 'ERROR: ' || SQLERRM || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.SADB.TASK_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process TRAIN_CNST_DTL_RAIL_EQPT_BASE CDC changes into data preservation table'
WHEN
    SYSTEM$STREAM_HAS_DATA('D_RAW.SADB.TRAIN_CNST_DTL_RAIL_EQPT_BASE_HIST_STREAM')
AS
    CALL D_RAW.SADB.SP_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT();

ALTER TASK D_RAW.SADB.TASK_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'TRAIN_CNST_DTL_RAIL_EQPT%' IN SCHEMA D_BRONZE.SADB;
-- SHOW STREAMS LIKE 'TRAIN_CNST_DTL_RAIL_EQPT%' IN SCHEMA D_RAW.SADB;
-- SHOW TASKS LIKE 'TASK_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT%' IN SCHEMA D_RAW.SADB;
-- CALL D_RAW.SADB.SP_PROCESS_TRAIN_CNST_DTL_RAIL_EQPT();
