/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE
================================================================================
Source Table : D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE
Target Table : D_BRONZE.SADB.TRKFCG_TRACK_SGMNT_DN
Stream       : D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_TRKFCG_TRACK_SGMNT_DN()
Task         : D_RAW.SADB.TASK_PROCESS_TRKFCG_TRACK_SGMNT_DN
Primary Key  : GRPHC_OBJECT_VRSN_ID (Single)
Total Columns: 58 source + 6 CDC metadata = 64
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.TRKFCG_TRACK_SGMNT_DN (
    GRPHC_OBJECT_VRSN_ID NUMBER(18,0) NOT NULL,
    VRSN_CREATE_TMS TIMESTAMP_NTZ(0),
    VRSN_USER_ID VARCHAR(32),
    FIRST_GRPHC_OBJECT_VRSN_ID NUMBER(18,0),
    PRVS_GRPHC_OBJECT_VRSN_ID NUMBER(18,0),
    GRPHC_OBJECT_MDFCTN_CD VARCHAR(36),
    GRPHC_OBJECT_STATUS_CD VARCHAR(32),
    GRPHC_TRNSCT_ID NUMBER(18,0),
    TRACK_SGMNT_ID NUMBER(18,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    TRACK_AREA_BNDRY_ST VARCHAR(160),
    EFCTV_TMS TIMESTAMP_NTZ(0),
    ENGLSH_BASE_NM VARCHAR(320),
    LONG_ENGLSH_NM VARCHAR(320),
    PRMRY_RFRNC_IND VARCHAR(4),
    SHORT_ENGLSH_NM VARCHAR(40),
    DATA_SOURCE_CD VARCHAR(40),
    NAME_GNRTN_RULE_ID NUMBER(18,0),
    ORGNL_DATA_SOURCE_CD VARCHAR(40),
    PHYSCL_TRACK_ID NUMBER(18,0),
    TRACK_CD VARCHAR(40),
    AMAP_TRACK_RFRNC_NM VARCHAR(64),
    AMAP_MAIN_TRACK_RFRNC_NM VARCHAR(64),
    AMAP_TRACK_SIDE_CD VARCHAR(20),
    AMAP_RFRNC_HIGH_MILES_QTY NUMBER(8,3),
    AMAP_TRACK_SQNC_NBR NUMBER(3,1),
    EXPIRY_TMS TIMESTAMP_NTZ(0),
    FRENCH_BASE_NM VARCHAR(320),
    LONG_FRENCH_NM VARCHAR(320),
    ORGNL_SHORT_ENGLSH_NM VARCHAR(40),
    RFRNC_HIGH_MILES_QTY NUMBER(8,3),
    RFRNC_LOW_MILES_QTY NUMBER(8,3),
    SBDVSN_RFRNC_LOW_MILES_QTY NUMBER(8,3),
    SHORT_FRENCH_NM VARCHAR(40),
    STRG_FEET_QTY NUMBER(5,0),
    YARD_TRACK_NM VARCHAR(24),
    YARD_SUB_TRACK_NM VARCHAR(8),
    REGION_ID NUMBER(18,0),
    TRACK_MLG_CD VARCHAR(4),
    TRACK_USAGE_CD VARCHAR(40),
    UMBRL_STN_ID NUMBER(18,0),
    OCS_DSPTCH_CD VARCHAR(4),
    TRFC_DRCTN_CD VARCHAR(20),
    SUB_YARD_NM VARCHAR(8),
    INSPCT_FRQNCY_CD VARCHAR(40),
    POST_START_NM VARCHAR(64),
    POST_START_DSTNC_MILES_QTY NUMBER(8,3),
    POST_END_NM VARCHAR(64),
    POST_END_DSTNC_MILES_QTY NUMBER(8,3),
    NTWRK_SNAP_CD NUMBER(1,0),
    PSTN_MODE_CD NUMBER(1,0),
    OPRTNG_CPCTY_FEET_QTY VARCHAR(255),
    OPRTNG_CPCTY_CARS_QTY VARCHAR(255),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    CDC_OPERATION VARCHAR(10),  
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100), 

    PRIMARY KEY (GRPHC_OBJECT_VRSN_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for TRKFCG_TRACK_SGMNT_DN_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.SADB.SP_PROCESS_TRKFCG_TRACK_SGMNT_DN()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    
    -- =========================================================================
    -- CHECK 1: Detect if stream is stale (happens after IDMC truncate/reload)
    -- =========================================================================
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        
        CREATE OR REPLACE STREAM D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE_HIST_STREAM
        ON TABLE D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.SADB.TRKFCG_TRACK_SGMNT_DN AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE src
            LEFT JOIN D_BRONZE.SADB.TRKFCG_TRACK_SGMNT_DN tgt 
                ON src.GRPHC_OBJECT_VRSN_ID = tgt.GRPHC_OBJECT_VRSN_ID
            WHERE tgt.GRPHC_OBJECT_VRSN_ID IS NULL
               OR tgt.IS_DELETED = TRUE
        ) AS src
        ON tgt.GRPHC_OBJECT_VRSN_ID = src.GRPHC_OBJECT_VRSN_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.TRACK_AREA_BNDRY_ST = src.TRACK_AREA_BNDRY_ST,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.ENGLSH_BASE_NM = src.ENGLSH_BASE_NM,
            tgt.LONG_ENGLSH_NM = src.LONG_ENGLSH_NM,
            tgt.PRMRY_RFRNC_IND = src.PRMRY_RFRNC_IND,
            tgt.SHORT_ENGLSH_NM = src.SHORT_ENGLSH_NM,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.NAME_GNRTN_RULE_ID = src.NAME_GNRTN_RULE_ID,
            tgt.ORGNL_DATA_SOURCE_CD = src.ORGNL_DATA_SOURCE_CD,
            tgt.PHYSCL_TRACK_ID = src.PHYSCL_TRACK_ID,
            tgt.TRACK_CD = src.TRACK_CD,
            tgt.AMAP_TRACK_RFRNC_NM = src.AMAP_TRACK_RFRNC_NM,
            tgt.AMAP_MAIN_TRACK_RFRNC_NM = src.AMAP_MAIN_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SIDE_CD = src.AMAP_TRACK_SIDE_CD,
            tgt.AMAP_RFRNC_HIGH_MILES_QTY = src.AMAP_RFRNC_HIGH_MILES_QTY,
            tgt.AMAP_TRACK_SQNC_NBR = src.AMAP_TRACK_SQNC_NBR,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.FRENCH_BASE_NM = src.FRENCH_BASE_NM,
            tgt.LONG_FRENCH_NM = src.LONG_FRENCH_NM,
            tgt.ORGNL_SHORT_ENGLSH_NM = src.ORGNL_SHORT_ENGLSH_NM,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.SBDVSN_RFRNC_LOW_MILES_QTY = src.SBDVSN_RFRNC_LOW_MILES_QTY,
            tgt.SHORT_FRENCH_NM = src.SHORT_FRENCH_NM,
            tgt.STRG_FEET_QTY = src.STRG_FEET_QTY,
            tgt.YARD_TRACK_NM = src.YARD_TRACK_NM,
            tgt.YARD_SUB_TRACK_NM = src.YARD_SUB_TRACK_NM,
            tgt.REGION_ID = src.REGION_ID,
            tgt.TRACK_MLG_CD = src.TRACK_MLG_CD,
            tgt.TRACK_USAGE_CD = src.TRACK_USAGE_CD,
            tgt.UMBRL_STN_ID = src.UMBRL_STN_ID,
            tgt.OCS_DSPTCH_CD = src.OCS_DSPTCH_CD,
            tgt.TRFC_DRCTN_CD = src.TRFC_DRCTN_CD,
            tgt.SUB_YARD_NM = src.SUB_YARD_NM,
            tgt.INSPCT_FRQNCY_CD = src.INSPCT_FRQNCY_CD,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.POST_END_NM = src.POST_END_NM,
            tgt.POST_END_DSTNC_MILES_QTY = src.POST_END_DSTNC_MILES_QTY,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.OPRTNG_CPCTY_FEET_QTY = src.OPRTNG_CPCTY_FEET_QTY,
            tgt.OPRTNG_CPCTY_CARS_QTY = src.OPRTNG_CPCTY_CARS_QTY,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, TRACK_SGMNT_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, TRACK_AREA_BNDRY_ST, EFCTV_TMS,
            ENGLSH_BASE_NM, LONG_ENGLSH_NM, PRMRY_RFRNC_IND, SHORT_ENGLSH_NM, DATA_SOURCE_CD,
            NAME_GNRTN_RULE_ID, ORGNL_DATA_SOURCE_CD, PHYSCL_TRACK_ID, TRACK_CD, AMAP_TRACK_RFRNC_NM,
            AMAP_MAIN_TRACK_RFRNC_NM, AMAP_TRACK_SIDE_CD, AMAP_RFRNC_HIGH_MILES_QTY, AMAP_TRACK_SQNC_NBR, EXPIRY_TMS,
            FRENCH_BASE_NM, LONG_FRENCH_NM, ORGNL_SHORT_ENGLSH_NM, RFRNC_HIGH_MILES_QTY, RFRNC_LOW_MILES_QTY,
            SBDVSN_RFRNC_LOW_MILES_QTY, SHORT_FRENCH_NM, STRG_FEET_QTY, YARD_TRACK_NM, YARD_SUB_TRACK_NM,
            REGION_ID, TRACK_MLG_CD, TRACK_USAGE_CD, UMBRL_STN_ID, OCS_DSPTCH_CD,
            TRFC_DRCTN_CD, SUB_YARD_NM, INSPCT_FRQNCY_CD, POST_START_NM, POST_START_DSTNC_MILES_QTY,
            POST_END_NM, POST_END_DSTNC_MILES_QTY, NTWRK_SNAP_CD, PSTN_MODE_CD, OPRTNG_CPCTY_FEET_QTY,
            OPRTNG_CPCTY_CARS_QTY, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.GRPHC_OBJECT_VRSN_ID, src.VRSN_CREATE_TMS, src.VRSN_USER_ID, src.FIRST_GRPHC_OBJECT_VRSN_ID, src.PRVS_GRPHC_OBJECT_VRSN_ID,
            src.GRPHC_OBJECT_MDFCTN_CD, src.GRPHC_OBJECT_STATUS_CD, src.GRPHC_TRNSCT_ID, src.TRACK_SGMNT_ID, src.RECORD_CREATE_TMS,
            src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID, src.TRACK_AREA_BNDRY_ST, src.EFCTV_TMS,
            src.ENGLSH_BASE_NM, src.LONG_ENGLSH_NM, src.PRMRY_RFRNC_IND, src.SHORT_ENGLSH_NM, src.DATA_SOURCE_CD,
            src.NAME_GNRTN_RULE_ID, src.ORGNL_DATA_SOURCE_CD, src.PHYSCL_TRACK_ID, src.TRACK_CD, src.AMAP_TRACK_RFRNC_NM,
            src.AMAP_MAIN_TRACK_RFRNC_NM, src.AMAP_TRACK_SIDE_CD, src.AMAP_RFRNC_HIGH_MILES_QTY, src.AMAP_TRACK_SQNC_NBR, src.EXPIRY_TMS,
            src.FRENCH_BASE_NM, src.LONG_FRENCH_NM, src.ORGNL_SHORT_ENGLSH_NM, src.RFRNC_HIGH_MILES_QTY, src.RFRNC_LOW_MILES_QTY,
            src.SBDVSN_RFRNC_LOW_MILES_QTY, src.SHORT_FRENCH_NM, src.STRG_FEET_QTY, src.YARD_TRACK_NM, src.YARD_SUB_TRACK_NM,
            src.REGION_ID, src.TRACK_MLG_CD, src.TRACK_USAGE_CD, src.UMBRL_STN_ID, src.OCS_DSPTCH_CD,
            src.TRFC_DRCTN_CD, src.SUB_YARD_NM, src.INSPCT_FRQNCY_CD, src.POST_START_NM, src.POST_START_DSTNC_MILES_QTY,
            src.POST_END_NM, src.POST_END_DSTNC_MILES_QTY, src.NTWRK_SNAP_CD, src.PSTN_MODE_CD, src.OPRTNG_CPCTY_FEET_QTY,
            src.OPRTNG_CPCTY_CARS_QTY, src.SNW_OPERATION_TYPE, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_TRKFCG_TRACK_SGMNT_DN AS
    SELECT 
        GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
        GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, TRACK_SGMNT_ID, RECORD_CREATE_TMS,
        RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, TRACK_AREA_BNDRY_ST, EFCTV_TMS,
        ENGLSH_BASE_NM, LONG_ENGLSH_NM, PRMRY_RFRNC_IND, SHORT_ENGLSH_NM, DATA_SOURCE_CD,
        NAME_GNRTN_RULE_ID, ORGNL_DATA_SOURCE_CD, PHYSCL_TRACK_ID, TRACK_CD, AMAP_TRACK_RFRNC_NM,
        AMAP_MAIN_TRACK_RFRNC_NM, AMAP_TRACK_SIDE_CD, AMAP_RFRNC_HIGH_MILES_QTY, AMAP_TRACK_SQNC_NBR, EXPIRY_TMS,
        FRENCH_BASE_NM, LONG_FRENCH_NM, ORGNL_SHORT_ENGLSH_NM, RFRNC_HIGH_MILES_QTY, RFRNC_LOW_MILES_QTY,
        SBDVSN_RFRNC_LOW_MILES_QTY, SHORT_FRENCH_NM, STRG_FEET_QTY, YARD_TRACK_NM, YARD_SUB_TRACK_NM,
        REGION_ID, TRACK_MLG_CD, TRACK_USAGE_CD, UMBRL_STN_ID, OCS_DSPTCH_CD,
        TRFC_DRCTN_CD, SUB_YARD_NM, INSPCT_FRQNCY_CD, POST_START_NM, POST_START_DSTNC_MILES_QTY,
        POST_END_NM, POST_END_DSTNC_MILES_QTY, NTWRK_SNAP_CD, PSTN_MODE_CD, OPRTNG_CPCTY_FEET_QTY,
        OPRTNG_CPCTY_CARS_QTY, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_TRKFCG_TRACK_SGMNT_DN;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_TRKFCG_TRACK_SGMNT_DN;
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.SADB.TRKFCG_TRACK_SGMNT_DN AS tgt
    USING (
        SELECT 
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, TRACK_SGMNT_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, TRACK_AREA_BNDRY_ST, EFCTV_TMS,
            ENGLSH_BASE_NM, LONG_ENGLSH_NM, PRMRY_RFRNC_IND, SHORT_ENGLSH_NM, DATA_SOURCE_CD,
            NAME_GNRTN_RULE_ID, ORGNL_DATA_SOURCE_CD, PHYSCL_TRACK_ID, TRACK_CD, AMAP_TRACK_RFRNC_NM,
            AMAP_MAIN_TRACK_RFRNC_NM, AMAP_TRACK_SIDE_CD, AMAP_RFRNC_HIGH_MILES_QTY, AMAP_TRACK_SQNC_NBR, EXPIRY_TMS,
            FRENCH_BASE_NM, LONG_FRENCH_NM, ORGNL_SHORT_ENGLSH_NM, RFRNC_HIGH_MILES_QTY, RFRNC_LOW_MILES_QTY,
            SBDVSN_RFRNC_LOW_MILES_QTY, SHORT_FRENCH_NM, STRG_FEET_QTY, YARD_TRACK_NM, YARD_SUB_TRACK_NM,
            REGION_ID, TRACK_MLG_CD, TRACK_USAGE_CD, UMBRL_STN_ID, OCS_DSPTCH_CD,
            TRFC_DRCTN_CD, SUB_YARD_NM, INSPCT_FRQNCY_CD, POST_START_NM, POST_START_DSTNC_MILES_QTY,
            POST_END_NM, POST_END_DSTNC_MILES_QTY, NTWRK_SNAP_CD, PSTN_MODE_CD, OPRTNG_CPCTY_FEET_QTY,
            OPRTNG_CPCTY_CARS_QTY, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_ACTION,
            CDC_IS_UPDATE,
            ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_TRKFCG_TRACK_SGMNT_DN
    ) AS src
    ON tgt.GRPHC_OBJECT_VRSN_ID = src.GRPHC_OBJECT_VRSN_ID
    
    -- UPDATE scenario (METADATA$ACTION='INSERT' AND METADATA$ISUPDATE=TRUE)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.TRACK_AREA_BNDRY_ST = src.TRACK_AREA_BNDRY_ST,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.ENGLSH_BASE_NM = src.ENGLSH_BASE_NM,
            tgt.LONG_ENGLSH_NM = src.LONG_ENGLSH_NM,
            tgt.PRMRY_RFRNC_IND = src.PRMRY_RFRNC_IND,
            tgt.SHORT_ENGLSH_NM = src.SHORT_ENGLSH_NM,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.NAME_GNRTN_RULE_ID = src.NAME_GNRTN_RULE_ID,
            tgt.ORGNL_DATA_SOURCE_CD = src.ORGNL_DATA_SOURCE_CD,
            tgt.PHYSCL_TRACK_ID = src.PHYSCL_TRACK_ID,
            tgt.TRACK_CD = src.TRACK_CD,
            tgt.AMAP_TRACK_RFRNC_NM = src.AMAP_TRACK_RFRNC_NM,
            tgt.AMAP_MAIN_TRACK_RFRNC_NM = src.AMAP_MAIN_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SIDE_CD = src.AMAP_TRACK_SIDE_CD,
            tgt.AMAP_RFRNC_HIGH_MILES_QTY = src.AMAP_RFRNC_HIGH_MILES_QTY,
            tgt.AMAP_TRACK_SQNC_NBR = src.AMAP_TRACK_SQNC_NBR,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.FRENCH_BASE_NM = src.FRENCH_BASE_NM,
            tgt.LONG_FRENCH_NM = src.LONG_FRENCH_NM,
            tgt.ORGNL_SHORT_ENGLSH_NM = src.ORGNL_SHORT_ENGLSH_NM,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.SBDVSN_RFRNC_LOW_MILES_QTY = src.SBDVSN_RFRNC_LOW_MILES_QTY,
            tgt.SHORT_FRENCH_NM = src.SHORT_FRENCH_NM,
            tgt.STRG_FEET_QTY = src.STRG_FEET_QTY,
            tgt.YARD_TRACK_NM = src.YARD_TRACK_NM,
            tgt.YARD_SUB_TRACK_NM = src.YARD_SUB_TRACK_NM,
            tgt.REGION_ID = src.REGION_ID,
            tgt.TRACK_MLG_CD = src.TRACK_MLG_CD,
            tgt.TRACK_USAGE_CD = src.TRACK_USAGE_CD,
            tgt.UMBRL_STN_ID = src.UMBRL_STN_ID,
            tgt.OCS_DSPTCH_CD = src.OCS_DSPTCH_CD,
            tgt.TRFC_DRCTN_CD = src.TRFC_DRCTN_CD,
            tgt.SUB_YARD_NM = src.SUB_YARD_NM,
            tgt.INSPCT_FRQNCY_CD = src.INSPCT_FRQNCY_CD,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.POST_END_NM = src.POST_END_NM,
            tgt.POST_END_DSTNC_MILES_QTY = src.POST_END_DSTNC_MILES_QTY,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.OPRTNG_CPCTY_FEET_QTY = src.OPRTNG_CPCTY_FEET_QTY,
            tgt.OPRTNG_CPCTY_CARS_QTY = src.OPRTNG_CPCTY_CARS_QTY,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- DELETE scenario (METADATA$ACTION='DELETE' AND METADATA$ISUPDATE=FALSE)
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- RE-INSERT scenario (record exists but being re-inserted)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.TRACK_AREA_BNDRY_ST = src.TRACK_AREA_BNDRY_ST,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.ENGLSH_BASE_NM = src.ENGLSH_BASE_NM,
            tgt.LONG_ENGLSH_NM = src.LONG_ENGLSH_NM,
            tgt.PRMRY_RFRNC_IND = src.PRMRY_RFRNC_IND,
            tgt.SHORT_ENGLSH_NM = src.SHORT_ENGLSH_NM,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.NAME_GNRTN_RULE_ID = src.NAME_GNRTN_RULE_ID,
            tgt.ORGNL_DATA_SOURCE_CD = src.ORGNL_DATA_SOURCE_CD,
            tgt.PHYSCL_TRACK_ID = src.PHYSCL_TRACK_ID,
            tgt.TRACK_CD = src.TRACK_CD,
            tgt.AMAP_TRACK_RFRNC_NM = src.AMAP_TRACK_RFRNC_NM,
            tgt.AMAP_MAIN_TRACK_RFRNC_NM = src.AMAP_MAIN_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SIDE_CD = src.AMAP_TRACK_SIDE_CD,
            tgt.AMAP_RFRNC_HIGH_MILES_QTY = src.AMAP_RFRNC_HIGH_MILES_QTY,
            tgt.AMAP_TRACK_SQNC_NBR = src.AMAP_TRACK_SQNC_NBR,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.FRENCH_BASE_NM = src.FRENCH_BASE_NM,
            tgt.LONG_FRENCH_NM = src.LONG_FRENCH_NM,
            tgt.ORGNL_SHORT_ENGLSH_NM = src.ORGNL_SHORT_ENGLSH_NM,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.SBDVSN_RFRNC_LOW_MILES_QTY = src.SBDVSN_RFRNC_LOW_MILES_QTY,
            tgt.SHORT_FRENCH_NM = src.SHORT_FRENCH_NM,
            tgt.STRG_FEET_QTY = src.STRG_FEET_QTY,
            tgt.YARD_TRACK_NM = src.YARD_TRACK_NM,
            tgt.YARD_SUB_TRACK_NM = src.YARD_SUB_TRACK_NM,
            tgt.REGION_ID = src.REGION_ID,
            tgt.TRACK_MLG_CD = src.TRACK_MLG_CD,
            tgt.TRACK_USAGE_CD = src.TRACK_USAGE_CD,
            tgt.UMBRL_STN_ID = src.UMBRL_STN_ID,
            tgt.OCS_DSPTCH_CD = src.OCS_DSPTCH_CD,
            tgt.TRFC_DRCTN_CD = src.TRFC_DRCTN_CD,
            tgt.SUB_YARD_NM = src.SUB_YARD_NM,
            tgt.INSPCT_FRQNCY_CD = src.INSPCT_FRQNCY_CD,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.POST_END_NM = src.POST_END_NM,
            tgt.POST_END_DSTNC_MILES_QTY = src.POST_END_DSTNC_MILES_QTY,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.OPRTNG_CPCTY_FEET_QTY = src.OPRTNG_CPCTY_FEET_QTY,
            tgt.OPRTNG_CPCTY_CARS_QTY = src.OPRTNG_CPCTY_CARS_QTY,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- NEW INSERT scenario
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, TRACK_SGMNT_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, TRACK_AREA_BNDRY_ST, EFCTV_TMS,
            ENGLSH_BASE_NM, LONG_ENGLSH_NM, PRMRY_RFRNC_IND, SHORT_ENGLSH_NM, DATA_SOURCE_CD,
            NAME_GNRTN_RULE_ID, ORGNL_DATA_SOURCE_CD, PHYSCL_TRACK_ID, TRACK_CD, AMAP_TRACK_RFRNC_NM,
            AMAP_MAIN_TRACK_RFRNC_NM, AMAP_TRACK_SIDE_CD, AMAP_RFRNC_HIGH_MILES_QTY, AMAP_TRACK_SQNC_NBR, EXPIRY_TMS,
            FRENCH_BASE_NM, LONG_FRENCH_NM, ORGNL_SHORT_ENGLSH_NM, RFRNC_HIGH_MILES_QTY, RFRNC_LOW_MILES_QTY,
            SBDVSN_RFRNC_LOW_MILES_QTY, SHORT_FRENCH_NM, STRG_FEET_QTY, YARD_TRACK_NM, YARD_SUB_TRACK_NM,
            REGION_ID, TRACK_MLG_CD, TRACK_USAGE_CD, UMBRL_STN_ID, OCS_DSPTCH_CD,
            TRFC_DRCTN_CD, SUB_YARD_NM, INSPCT_FRQNCY_CD, POST_START_NM, POST_START_DSTNC_MILES_QTY,
            POST_END_NM, POST_END_DSTNC_MILES_QTY, NTWRK_SNAP_CD, PSTN_MODE_CD, OPRTNG_CPCTY_FEET_QTY,
            OPRTNG_CPCTY_CARS_QTY, SNW_OPERATION_TYPE, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.GRPHC_OBJECT_VRSN_ID, src.VRSN_CREATE_TMS, src.VRSN_USER_ID, src.FIRST_GRPHC_OBJECT_VRSN_ID, src.PRVS_GRPHC_OBJECT_VRSN_ID,
            src.GRPHC_OBJECT_MDFCTN_CD, src.GRPHC_OBJECT_STATUS_CD, src.GRPHC_TRNSCT_ID, src.TRACK_SGMNT_ID, src.RECORD_CREATE_TMS,
            src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID, src.TRACK_AREA_BNDRY_ST, src.EFCTV_TMS,
            src.ENGLSH_BASE_NM, src.LONG_ENGLSH_NM, src.PRMRY_RFRNC_IND, src.SHORT_ENGLSH_NM, src.DATA_SOURCE_CD,
            src.NAME_GNRTN_RULE_ID, src.ORGNL_DATA_SOURCE_CD, src.PHYSCL_TRACK_ID, src.TRACK_CD, src.AMAP_TRACK_RFRNC_NM,
            src.AMAP_MAIN_TRACK_RFRNC_NM, src.AMAP_TRACK_SIDE_CD, src.AMAP_RFRNC_HIGH_MILES_QTY, src.AMAP_TRACK_SQNC_NBR, src.EXPIRY_TMS,
            src.FRENCH_BASE_NM, src.LONG_FRENCH_NM, src.ORGNL_SHORT_ENGLSH_NM, src.RFRNC_HIGH_MILES_QTY, src.RFRNC_LOW_MILES_QTY,
            src.SBDVSN_RFRNC_LOW_MILES_QTY, src.SHORT_FRENCH_NM, src.STRG_FEET_QTY, src.YARD_TRACK_NM, src.YARD_SUB_TRACK_NM,
            src.REGION_ID, src.TRACK_MLG_CD, src.TRACK_USAGE_CD, src.UMBRL_STN_ID, src.OCS_DSPTCH_CD,
            src.TRFC_DRCTN_CD, src.SUB_YARD_NM, src.INSPCT_FRQNCY_CD, src.POST_START_NM, src.POST_START_DSTNC_MILES_QTY,
            src.POST_END_NM, src.POST_END_DSTNC_MILES_QTY, src.NTWRK_SNAP_CD, src.PSTN_MODE_CD, src.OPRTNG_CPCTY_FEET_QTY,
            src.OPRTNG_CPCTY_CARS_QTY, src.SNW_OPERATION_TYPE, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    DROP TABLE IF EXISTS _CDC_STAGING_TRKFCG_TRACK_SGMNT_DN;
    
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes. Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        DROP TABLE IF EXISTS _CDC_STAGING_TRKFCG_TRACK_SGMNT_DN;
        RETURN 'ERROR: ' || SQLERRM || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.SADB.TASK_PROCESS_TRKFCG_TRACK_SGMNT_DN
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process TRKFCG_TRACK_SGMNT_DN_BASE CDC changes into data preservation table'
WHEN
    SYSTEM$STREAM_HAS_DATA('D_RAW.SADB.TRKFCG_TRACK_SGMNT_DN_BASE_HIST_STREAM')
AS
    CALL D_RAW.SADB.SP_PROCESS_TRKFCG_TRACK_SGMNT_DN();

ALTER TASK D_RAW.SADB.TASK_PROCESS_TRKFCG_TRACK_SGMNT_DN RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'TRKFCG_TRACK_SGMNT_DN%' IN SCHEMA D_BRONZE.SADB;
-- SHOW STREAMS LIKE 'TRKFCG_TRACK_SGMNT_DN%' IN SCHEMA D_RAW.SADB;
-- SHOW TASKS LIKE 'TASK_PROCESS_TRKFCG_TRACK_SGMNT_DN%' IN SCHEMA D_RAW.SADB;
-- CALL D_RAW.SADB.SP_PROCESS_TRKFCG_TRACK_SGMNT_DN();
