/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE
================================================================================
Source Table : D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE
Target Table : D_BRONZE.SADB.CTNAPP_CTNG_LINE_DN
Stream       : D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_CTNAPP_CTNG_LINE_DN()
Task         : D_RAW.SADB.TASK_PROCESS_CTNAPP_CTNG_LINE_DN
Primary Key  : GRPHC_OBJECT_VRSN_ID (Single)
Total Columns: 65 source + 6 CDC metadata = 71
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.CTNAPP_CTNG_LINE_DN (
    GRPHC_OBJECT_VRSN_ID NUMBER(18,0) NOT NULL,
    VRSN_CREATE_TMS TIMESTAMP_NTZ(0),
    VRSN_USER_ID VARCHAR(32),
    FIRST_GRPHC_OBJECT_VRSN_ID NUMBER(18,0),
    PRVS_GRPHC_OBJECT_VRSN_ID NUMBER(18,0),
    GRPHC_OBJECT_MDFCTN_CD VARCHAR(36),
    GRPHC_OBJECT_STATUS_CD VARCHAR(32),
    GRPHC_TRNSCT_ID NUMBER(18,0),
    LINE_ID NUMBER(18,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    AMAP_TRACK_RFRNC_NM VARCHAR(64),
    AMAP_TRACK_SQNC_NBR NUMBER(3,1),
    CMPLX_ARC_IND VARCHAR(4),
    RFRNC_HIGH_MILES_QTY NUMBER(8,3),
    RFRNC_LOW_MILES_QTY NUMBER(8,3),
    TRACK_SGMNT_ID NUMBER(18,0),
    ACTUAL_HIGH_MILES_QTY NUMBER(8,3),
    ACTUAL_LINE_FEET_QTY NUMBER(8,0),
    ACTUAL_LOW_MILES_QTY NUMBER(8,3),
    ACTUAL_GRADE_PCT NUMBER(4,2),
    AMAP_MAIN_TRACK_RFRNC_NM VARCHAR(64),
    AMAP_TRACK_SIDE_CD VARCHAR(20),
    CRCLR_SPIRAL_CURVE_CD VARCHAR(4),
    CRVTR_DGRS_QTY NUMBER(2,0),
    HIGH_ANGLE_DGRS_QTY NUMBER(5,2),
    HIGH_MILE_DSPLY_OFFSET_NBR NUMBER(8,3),
    HIGH_SWITCH_DSPLY_DGRS_QTY NUMBER(3,0),
    HIGH_SWITCH_OFFSET_MLTPLR_NBR NUMBER(3,1),
    HIGH_SWITCH_SYMBOL_NM VARCHAR(40),
    LOW_ANGLE_DGRS_QTY NUMBER(5,2),
    LOW_MILE_DSPLY_OFFSET_NBR NUMBER(8,3),
    LOW_SWITCH_DSPLY_DGRS_QTY NUMBER(3,0),
    LOW_SWITCH_OFFSET_MLTPLR_NBR NUMBER(3,1),
    LOW_SWITCH_SYMBOL_NM VARCHAR(40),
    RFRNC_LINE_FEET_QTY NUMBER(8,0),
    RFRNC_GRADE_PCT NUMBER(4,2),
    SBDVSN_LONG_ENGLSH_NM VARCHAR(320),
    SBDVSN_TRACK_SHORT_ENGLSH_NM VARCHAR(40),
    YARD_TRSTN_NM VARCHAR(120),
    YARD_TRACK_SHORT_ENGLSH_NM VARCHAR(40),
    RFRNC_GRADE_SOURCE_CD VARCHAR(40),
    RFRNC_LINE_FEET_SOURCE_CD VARCHAR(40),
    RFRNC_MILE_SOURCE_CD VARCHAR(40),
    SCAC_CD VARCHAR(16),
    FSAC_CD VARCHAR(20),
    YARD_TRACK_LONG_ENGLSH_NM VARCHAR(320),
    SBDVSN_TRACK_LONG_ENGLSH_NM VARCHAR(320),
    TRACK_CD VARCHAR(40),
    STRG_FEET_QTY NUMBER(5,0),
    REGION_ID NUMBER(18,0),
    SBDVSN_ID NUMBER(4,0),
    START_POINT_ID VARCHAR(72),
    END_POINT_ID VARCHAR(72),
    LINE_SRCNG_METHOD_CD VARCHAR(80),
    POST_START_DSTNC_MILES_QTY NUMBER(8,3),
    POST_END_DSTNC_MILES_QTY NUMBER(8,3),
    POST_START_NM VARCHAR(64),
    POST_END_NM VARCHAR(64),
    ERROR_CD NUMBER(1,0),
    NTWRK_SNAP_CD NUMBER(1,0),
    PSTN_MODE_CD NUMBER(1,0),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),

    PRIMARY KEY (GRPHC_OBJECT_VRSN_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for CTNAPP_CTNG_LINE_DN_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.SADB.SP_PROCESS_CTNAPP_CTNG_LINE_DN()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    
    -- =========================================================================
    -- CHECK 1: Detect if stream is stale (happens after IDMC truncate/reload)
    -- =========================================================================
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        
        CREATE OR REPLACE STREAM D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE_HIST_STREAM
        ON TABLE D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.SADB.CTNAPP_CTNG_LINE_DN AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE src
            LEFT JOIN D_BRONZE.SADB.CTNAPP_CTNG_LINE_DN tgt 
                ON src.GRPHC_OBJECT_VRSN_ID = tgt.GRPHC_OBJECT_VRSN_ID
            WHERE tgt.GRPHC_OBJECT_VRSN_ID IS NULL
               OR tgt.IS_DELETED = TRUE
        ) AS src
        ON tgt.GRPHC_OBJECT_VRSN_ID = src.GRPHC_OBJECT_VRSN_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.LINE_ID = src.LINE_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.AMAP_TRACK_RFRNC_NM = src.AMAP_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SQNC_NBR = src.AMAP_TRACK_SQNC_NBR,
            tgt.CMPLX_ARC_IND = src.CMPLX_ARC_IND,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.ACTUAL_HIGH_MILES_QTY = src.ACTUAL_HIGH_MILES_QTY,
            tgt.ACTUAL_LINE_FEET_QTY = src.ACTUAL_LINE_FEET_QTY,
            tgt.ACTUAL_LOW_MILES_QTY = src.ACTUAL_LOW_MILES_QTY,
            tgt.ACTUAL_GRADE_PCT = src.ACTUAL_GRADE_PCT,
            tgt.AMAP_MAIN_TRACK_RFRNC_NM = src.AMAP_MAIN_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SIDE_CD = src.AMAP_TRACK_SIDE_CD,
            tgt.CRCLR_SPIRAL_CURVE_CD = src.CRCLR_SPIRAL_CURVE_CD,
            tgt.CRVTR_DGRS_QTY = src.CRVTR_DGRS_QTY,
            tgt.HIGH_ANGLE_DGRS_QTY = src.HIGH_ANGLE_DGRS_QTY,
            tgt.HIGH_MILE_DSPLY_OFFSET_NBR = src.HIGH_MILE_DSPLY_OFFSET_NBR,
            tgt.HIGH_SWITCH_DSPLY_DGRS_QTY = src.HIGH_SWITCH_DSPLY_DGRS_QTY,
            tgt.HIGH_SWITCH_OFFSET_MLTPLR_NBR = src.HIGH_SWITCH_OFFSET_MLTPLR_NBR,
            tgt.HIGH_SWITCH_SYMBOL_NM = src.HIGH_SWITCH_SYMBOL_NM,
            tgt.LOW_ANGLE_DGRS_QTY = src.LOW_ANGLE_DGRS_QTY,
            tgt.LOW_MILE_DSPLY_OFFSET_NBR = src.LOW_MILE_DSPLY_OFFSET_NBR,
            tgt.LOW_SWITCH_DSPLY_DGRS_QTY = src.LOW_SWITCH_DSPLY_DGRS_QTY,
            tgt.LOW_SWITCH_OFFSET_MLTPLR_NBR = src.LOW_SWITCH_OFFSET_MLTPLR_NBR,
            tgt.LOW_SWITCH_SYMBOL_NM = src.LOW_SWITCH_SYMBOL_NM,
            tgt.RFRNC_LINE_FEET_QTY = src.RFRNC_LINE_FEET_QTY,
            tgt.RFRNC_GRADE_PCT = src.RFRNC_GRADE_PCT,
            tgt.SBDVSN_LONG_ENGLSH_NM = src.SBDVSN_LONG_ENGLSH_NM,
            tgt.SBDVSN_TRACK_SHORT_ENGLSH_NM = src.SBDVSN_TRACK_SHORT_ENGLSH_NM,
            tgt.YARD_TRSTN_NM = src.YARD_TRSTN_NM,
            tgt.YARD_TRACK_SHORT_ENGLSH_NM = src.YARD_TRACK_SHORT_ENGLSH_NM,
            tgt.RFRNC_GRADE_SOURCE_CD = src.RFRNC_GRADE_SOURCE_CD,
            tgt.RFRNC_LINE_FEET_SOURCE_CD = src.RFRNC_LINE_FEET_SOURCE_CD,
            tgt.RFRNC_MILE_SOURCE_CD = src.RFRNC_MILE_SOURCE_CD,
            tgt.SCAC_CD = src.SCAC_CD,
            tgt.FSAC_CD = src.FSAC_CD,
            tgt.YARD_TRACK_LONG_ENGLSH_NM = src.YARD_TRACK_LONG_ENGLSH_NM,
            tgt.SBDVSN_TRACK_LONG_ENGLSH_NM = src.SBDVSN_TRACK_LONG_ENGLSH_NM,
            tgt.TRACK_CD = src.TRACK_CD,
            tgt.STRG_FEET_QTY = src.STRG_FEET_QTY,
            tgt.REGION_ID = src.REGION_ID,
            tgt.SBDVSN_ID = src.SBDVSN_ID,
            tgt.START_POINT_ID = src.START_POINT_ID,
            tgt.END_POINT_ID = src.END_POINT_ID,
            tgt.LINE_SRCNG_METHOD_CD = src.LINE_SRCNG_METHOD_CD,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.POST_END_DSTNC_MILES_QTY = src.POST_END_DSTNC_MILES_QTY,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_END_NM = src.POST_END_NM,
            tgt.ERROR_CD = src.ERROR_CD,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, LINE_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, AMAP_TRACK_RFRNC_NM, AMAP_TRACK_SQNC_NBR,
            CMPLX_ARC_IND, RFRNC_HIGH_MILES_QTY, RFRNC_LOW_MILES_QTY, TRACK_SGMNT_ID, ACTUAL_HIGH_MILES_QTY,
            ACTUAL_LINE_FEET_QTY, ACTUAL_LOW_MILES_QTY, ACTUAL_GRADE_PCT, AMAP_MAIN_TRACK_RFRNC_NM, AMAP_TRACK_SIDE_CD,
            CRCLR_SPIRAL_CURVE_CD, CRVTR_DGRS_QTY, HIGH_ANGLE_DGRS_QTY, HIGH_MILE_DSPLY_OFFSET_NBR, HIGH_SWITCH_DSPLY_DGRS_QTY,
            HIGH_SWITCH_OFFSET_MLTPLR_NBR, HIGH_SWITCH_SYMBOL_NM, LOW_ANGLE_DGRS_QTY, LOW_MILE_DSPLY_OFFSET_NBR, LOW_SWITCH_DSPLY_DGRS_QTY,
            LOW_SWITCH_OFFSET_MLTPLR_NBR, LOW_SWITCH_SYMBOL_NM, RFRNC_LINE_FEET_QTY, RFRNC_GRADE_PCT, SBDVSN_LONG_ENGLSH_NM,
            SBDVSN_TRACK_SHORT_ENGLSH_NM, YARD_TRSTN_NM, YARD_TRACK_SHORT_ENGLSH_NM, RFRNC_GRADE_SOURCE_CD, RFRNC_LINE_FEET_SOURCE_CD,
            RFRNC_MILE_SOURCE_CD, SCAC_CD, FSAC_CD, YARD_TRACK_LONG_ENGLSH_NM, SBDVSN_TRACK_LONG_ENGLSH_NM,
            TRACK_CD, STRG_FEET_QTY, REGION_ID, SBDVSN_ID, START_POINT_ID,
            END_POINT_ID, LINE_SRCNG_METHOD_CD, POST_START_DSTNC_MILES_QTY, POST_END_DSTNC_MILES_QTY, POST_START_NM,
            POST_END_NM, ERROR_CD, NTWRK_SNAP_CD, PSTN_MODE_CD, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.GRPHC_OBJECT_VRSN_ID, src.VRSN_CREATE_TMS, src.VRSN_USER_ID, src.FIRST_GRPHC_OBJECT_VRSN_ID, src.PRVS_GRPHC_OBJECT_VRSN_ID,
            src.GRPHC_OBJECT_MDFCTN_CD, src.GRPHC_OBJECT_STATUS_CD, src.GRPHC_TRNSCT_ID, src.LINE_ID, src.RECORD_CREATE_TMS,
            src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID, src.AMAP_TRACK_RFRNC_NM, src.AMAP_TRACK_SQNC_NBR,
            src.CMPLX_ARC_IND, src.RFRNC_HIGH_MILES_QTY, src.RFRNC_LOW_MILES_QTY, src.TRACK_SGMNT_ID, src.ACTUAL_HIGH_MILES_QTY,
            src.ACTUAL_LINE_FEET_QTY, src.ACTUAL_LOW_MILES_QTY, src.ACTUAL_GRADE_PCT, src.AMAP_MAIN_TRACK_RFRNC_NM, src.AMAP_TRACK_SIDE_CD,
            src.CRCLR_SPIRAL_CURVE_CD, src.CRVTR_DGRS_QTY, src.HIGH_ANGLE_DGRS_QTY, src.HIGH_MILE_DSPLY_OFFSET_NBR, src.HIGH_SWITCH_DSPLY_DGRS_QTY,
            src.HIGH_SWITCH_OFFSET_MLTPLR_NBR, src.HIGH_SWITCH_SYMBOL_NM, src.LOW_ANGLE_DGRS_QTY, src.LOW_MILE_DSPLY_OFFSET_NBR, src.LOW_SWITCH_DSPLY_DGRS_QTY,
            src.LOW_SWITCH_OFFSET_MLTPLR_NBR, src.LOW_SWITCH_SYMBOL_NM, src.RFRNC_LINE_FEET_QTY, src.RFRNC_GRADE_PCT, src.SBDVSN_LONG_ENGLSH_NM,
            src.SBDVSN_TRACK_SHORT_ENGLSH_NM, src.YARD_TRSTN_NM, src.YARD_TRACK_SHORT_ENGLSH_NM, src.RFRNC_GRADE_SOURCE_CD, src.RFRNC_LINE_FEET_SOURCE_CD,
            src.RFRNC_MILE_SOURCE_CD, src.SCAC_CD, src.FSAC_CD, src.YARD_TRACK_LONG_ENGLSH_NM, src.SBDVSN_TRACK_LONG_ENGLSH_NM,
            src.TRACK_CD, src.STRG_FEET_QTY, src.REGION_ID, src.SBDVSN_ID, src.START_POINT_ID,
            src.END_POINT_ID, src.LINE_SRCNG_METHOD_CD, src.POST_START_DSTNC_MILES_QTY, src.POST_END_DSTNC_MILES_QTY, src.POST_START_NM,
            src.POST_END_NM, src.ERROR_CD, src.NTWRK_SNAP_CD, src.PSTN_MODE_CD, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_CTNAPP_CTNG_LINE_DN AS
    SELECT 
        GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
        GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, LINE_ID, RECORD_CREATE_TMS,
        RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, AMAP_TRACK_RFRNC_NM, AMAP_TRACK_SQNC_NBR,
        CMPLX_ARC_IND, RFRNC_HIGH_MILES_QTY, RFRNC_LOW_MILES_QTY, TRACK_SGMNT_ID, ACTUAL_HIGH_MILES_QTY,
        ACTUAL_LINE_FEET_QTY, ACTUAL_LOW_MILES_QTY, ACTUAL_GRADE_PCT, AMAP_MAIN_TRACK_RFRNC_NM, AMAP_TRACK_SIDE_CD,
        CRCLR_SPIRAL_CURVE_CD, CRVTR_DGRS_QTY, HIGH_ANGLE_DGRS_QTY, HIGH_MILE_DSPLY_OFFSET_NBR, HIGH_SWITCH_DSPLY_DGRS_QTY,
        HIGH_SWITCH_OFFSET_MLTPLR_NBR, HIGH_SWITCH_SYMBOL_NM, LOW_ANGLE_DGRS_QTY, LOW_MILE_DSPLY_OFFSET_NBR, LOW_SWITCH_DSPLY_DGRS_QTY,
        LOW_SWITCH_OFFSET_MLTPLR_NBR, LOW_SWITCH_SYMBOL_NM, RFRNC_LINE_FEET_QTY, RFRNC_GRADE_PCT, SBDVSN_LONG_ENGLSH_NM,
        SBDVSN_TRACK_SHORT_ENGLSH_NM, YARD_TRSTN_NM, YARD_TRACK_SHORT_ENGLSH_NM, RFRNC_GRADE_SOURCE_CD, RFRNC_LINE_FEET_SOURCE_CD,
        RFRNC_MILE_SOURCE_CD, SCAC_CD, FSAC_CD, YARD_TRACK_LONG_ENGLSH_NM, SBDVSN_TRACK_LONG_ENGLSH_NM,
        TRACK_CD, STRG_FEET_QTY, REGION_ID, SBDVSN_ID, START_POINT_ID,
        END_POINT_ID, LINE_SRCNG_METHOD_CD, POST_START_DSTNC_MILES_QTY, POST_END_DSTNC_MILES_QTY, POST_START_NM,
        POST_END_NM, ERROR_CD, NTWRK_SNAP_CD, PSTN_MODE_CD, SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_CTNAPP_CTNG_LINE_DN;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_CTNAPP_CTNG_LINE_DN;
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.SADB.CTNAPP_CTNG_LINE_DN AS tgt
    USING (
        SELECT 
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, LINE_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, AMAP_TRACK_RFRNC_NM, AMAP_TRACK_SQNC_NBR,
            CMPLX_ARC_IND, RFRNC_HIGH_MILES_QTY, RFRNC_LOW_MILES_QTY, TRACK_SGMNT_ID, ACTUAL_HIGH_MILES_QTY,
            ACTUAL_LINE_FEET_QTY, ACTUAL_LOW_MILES_QTY, ACTUAL_GRADE_PCT, AMAP_MAIN_TRACK_RFRNC_NM, AMAP_TRACK_SIDE_CD,
            CRCLR_SPIRAL_CURVE_CD, CRVTR_DGRS_QTY, HIGH_ANGLE_DGRS_QTY, HIGH_MILE_DSPLY_OFFSET_NBR, HIGH_SWITCH_DSPLY_DGRS_QTY,
            HIGH_SWITCH_OFFSET_MLTPLR_NBR, HIGH_SWITCH_SYMBOL_NM, LOW_ANGLE_DGRS_QTY, LOW_MILE_DSPLY_OFFSET_NBR, LOW_SWITCH_DSPLY_DGRS_QTY,
            LOW_SWITCH_OFFSET_MLTPLR_NBR, LOW_SWITCH_SYMBOL_NM, RFRNC_LINE_FEET_QTY, RFRNC_GRADE_PCT, SBDVSN_LONG_ENGLSH_NM,
            SBDVSN_TRACK_SHORT_ENGLSH_NM, YARD_TRSTN_NM, YARD_TRACK_SHORT_ENGLSH_NM, RFRNC_GRADE_SOURCE_CD, RFRNC_LINE_FEET_SOURCE_CD,
            RFRNC_MILE_SOURCE_CD, SCAC_CD, FSAC_CD, YARD_TRACK_LONG_ENGLSH_NM, SBDVSN_TRACK_LONG_ENGLSH_NM,
            TRACK_CD, STRG_FEET_QTY, REGION_ID, SBDVSN_ID, START_POINT_ID,
            END_POINT_ID, LINE_SRCNG_METHOD_CD, POST_START_DSTNC_MILES_QTY, POST_END_DSTNC_MILES_QTY, POST_START_NM,
            POST_END_NM, ERROR_CD, NTWRK_SNAP_CD, PSTN_MODE_CD, SNW_LAST_REPLICATED,
            CDC_ACTION,
            CDC_IS_UPDATE,
            ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_CTNAPP_CTNG_LINE_DN
    ) AS src
    ON tgt.GRPHC_OBJECT_VRSN_ID = src.GRPHC_OBJECT_VRSN_ID
    
    -- UPDATE scenario (METADATA$ACTION='INSERT' AND METADATA$ISUPDATE=TRUE)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.LINE_ID = src.LINE_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.AMAP_TRACK_RFRNC_NM = src.AMAP_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SQNC_NBR = src.AMAP_TRACK_SQNC_NBR,
            tgt.CMPLX_ARC_IND = src.CMPLX_ARC_IND,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.ACTUAL_HIGH_MILES_QTY = src.ACTUAL_HIGH_MILES_QTY,
            tgt.ACTUAL_LINE_FEET_QTY = src.ACTUAL_LINE_FEET_QTY,
            tgt.ACTUAL_LOW_MILES_QTY = src.ACTUAL_LOW_MILES_QTY,
            tgt.ACTUAL_GRADE_PCT = src.ACTUAL_GRADE_PCT,
            tgt.AMAP_MAIN_TRACK_RFRNC_NM = src.AMAP_MAIN_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SIDE_CD = src.AMAP_TRACK_SIDE_CD,
            tgt.CRCLR_SPIRAL_CURVE_CD = src.CRCLR_SPIRAL_CURVE_CD,
            tgt.CRVTR_DGRS_QTY = src.CRVTR_DGRS_QTY,
            tgt.HIGH_ANGLE_DGRS_QTY = src.HIGH_ANGLE_DGRS_QTY,
            tgt.HIGH_MILE_DSPLY_OFFSET_NBR = src.HIGH_MILE_DSPLY_OFFSET_NBR,
            tgt.HIGH_SWITCH_DSPLY_DGRS_QTY = src.HIGH_SWITCH_DSPLY_DGRS_QTY,
            tgt.HIGH_SWITCH_OFFSET_MLTPLR_NBR = src.HIGH_SWITCH_OFFSET_MLTPLR_NBR,
            tgt.HIGH_SWITCH_SYMBOL_NM = src.HIGH_SWITCH_SYMBOL_NM,
            tgt.LOW_ANGLE_DGRS_QTY = src.LOW_ANGLE_DGRS_QTY,
            tgt.LOW_MILE_DSPLY_OFFSET_NBR = src.LOW_MILE_DSPLY_OFFSET_NBR,
            tgt.LOW_SWITCH_DSPLY_DGRS_QTY = src.LOW_SWITCH_DSPLY_DGRS_QTY,
            tgt.LOW_SWITCH_OFFSET_MLTPLR_NBR = src.LOW_SWITCH_OFFSET_MLTPLR_NBR,
            tgt.LOW_SWITCH_SYMBOL_NM = src.LOW_SWITCH_SYMBOL_NM,
            tgt.RFRNC_LINE_FEET_QTY = src.RFRNC_LINE_FEET_QTY,
            tgt.RFRNC_GRADE_PCT = src.RFRNC_GRADE_PCT,
            tgt.SBDVSN_LONG_ENGLSH_NM = src.SBDVSN_LONG_ENGLSH_NM,
            tgt.SBDVSN_TRACK_SHORT_ENGLSH_NM = src.SBDVSN_TRACK_SHORT_ENGLSH_NM,
            tgt.YARD_TRSTN_NM = src.YARD_TRSTN_NM,
            tgt.YARD_TRACK_SHORT_ENGLSH_NM = src.YARD_TRACK_SHORT_ENGLSH_NM,
            tgt.RFRNC_GRADE_SOURCE_CD = src.RFRNC_GRADE_SOURCE_CD,
            tgt.RFRNC_LINE_FEET_SOURCE_CD = src.RFRNC_LINE_FEET_SOURCE_CD,
            tgt.RFRNC_MILE_SOURCE_CD = src.RFRNC_MILE_SOURCE_CD,
            tgt.SCAC_CD = src.SCAC_CD,
            tgt.FSAC_CD = src.FSAC_CD,
            tgt.YARD_TRACK_LONG_ENGLSH_NM = src.YARD_TRACK_LONG_ENGLSH_NM,
            tgt.SBDVSN_TRACK_LONG_ENGLSH_NM = src.SBDVSN_TRACK_LONG_ENGLSH_NM,
            tgt.TRACK_CD = src.TRACK_CD,
            tgt.STRG_FEET_QTY = src.STRG_FEET_QTY,
            tgt.REGION_ID = src.REGION_ID,
            tgt.SBDVSN_ID = src.SBDVSN_ID,
            tgt.START_POINT_ID = src.START_POINT_ID,
            tgt.END_POINT_ID = src.END_POINT_ID,
            tgt.LINE_SRCNG_METHOD_CD = src.LINE_SRCNG_METHOD_CD,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.POST_END_DSTNC_MILES_QTY = src.POST_END_DSTNC_MILES_QTY,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_END_NM = src.POST_END_NM,
            tgt.ERROR_CD = src.ERROR_CD,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- DELETE scenario (METADATA$ACTION='DELETE' AND METADATA$ISUPDATE=FALSE)
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- RE-INSERT scenario (record exists but being re-inserted)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.LINE_ID = src.LINE_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.AMAP_TRACK_RFRNC_NM = src.AMAP_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SQNC_NBR = src.AMAP_TRACK_SQNC_NBR,
            tgt.CMPLX_ARC_IND = src.CMPLX_ARC_IND,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.ACTUAL_HIGH_MILES_QTY = src.ACTUAL_HIGH_MILES_QTY,
            tgt.ACTUAL_LINE_FEET_QTY = src.ACTUAL_LINE_FEET_QTY,
            tgt.ACTUAL_LOW_MILES_QTY = src.ACTUAL_LOW_MILES_QTY,
            tgt.ACTUAL_GRADE_PCT = src.ACTUAL_GRADE_PCT,
            tgt.AMAP_MAIN_TRACK_RFRNC_NM = src.AMAP_MAIN_TRACK_RFRNC_NM,
            tgt.AMAP_TRACK_SIDE_CD = src.AMAP_TRACK_SIDE_CD,
            tgt.CRCLR_SPIRAL_CURVE_CD = src.CRCLR_SPIRAL_CURVE_CD,
            tgt.CRVTR_DGRS_QTY = src.CRVTR_DGRS_QTY,
            tgt.HIGH_ANGLE_DGRS_QTY = src.HIGH_ANGLE_DGRS_QTY,
            tgt.HIGH_MILE_DSPLY_OFFSET_NBR = src.HIGH_MILE_DSPLY_OFFSET_NBR,
            tgt.HIGH_SWITCH_DSPLY_DGRS_QTY = src.HIGH_SWITCH_DSPLY_DGRS_QTY,
            tgt.HIGH_SWITCH_OFFSET_MLTPLR_NBR = src.HIGH_SWITCH_OFFSET_MLTPLR_NBR,
            tgt.HIGH_SWITCH_SYMBOL_NM = src.HIGH_SWITCH_SYMBOL_NM,
            tgt.LOW_ANGLE_DGRS_QTY = src.LOW_ANGLE_DGRS_QTY,
            tgt.LOW_MILE_DSPLY_OFFSET_NBR = src.LOW_MILE_DSPLY_OFFSET_NBR,
            tgt.LOW_SWITCH_DSPLY_DGRS_QTY = src.LOW_SWITCH_DSPLY_DGRS_QTY,
            tgt.LOW_SWITCH_OFFSET_MLTPLR_NBR = src.LOW_SWITCH_OFFSET_MLTPLR_NBR,
            tgt.LOW_SWITCH_SYMBOL_NM = src.LOW_SWITCH_SYMBOL_NM,
            tgt.RFRNC_LINE_FEET_QTY = src.RFRNC_LINE_FEET_QTY,
            tgt.RFRNC_GRADE_PCT = src.RFRNC_GRADE_PCT,
            tgt.SBDVSN_LONG_ENGLSH_NM = src.SBDVSN_LONG_ENGLSH_NM,
            tgt.SBDVSN_TRACK_SHORT_ENGLSH_NM = src.SBDVSN_TRACK_SHORT_ENGLSH_NM,
            tgt.YARD_TRSTN_NM = src.YARD_TRSTN_NM,
            tgt.YARD_TRACK_SHORT_ENGLSH_NM = src.YARD_TRACK_SHORT_ENGLSH_NM,
            tgt.RFRNC_GRADE_SOURCE_CD = src.RFRNC_GRADE_SOURCE_CD,
            tgt.RFRNC_LINE_FEET_SOURCE_CD = src.RFRNC_LINE_FEET_SOURCE_CD,
            tgt.RFRNC_MILE_SOURCE_CD = src.RFRNC_MILE_SOURCE_CD,
            tgt.SCAC_CD = src.SCAC_CD,
            tgt.FSAC_CD = src.FSAC_CD,
            tgt.YARD_TRACK_LONG_ENGLSH_NM = src.YARD_TRACK_LONG_ENGLSH_NM,
            tgt.SBDVSN_TRACK_LONG_ENGLSH_NM = src.SBDVSN_TRACK_LONG_ENGLSH_NM,
            tgt.TRACK_CD = src.TRACK_CD,
            tgt.STRG_FEET_QTY = src.STRG_FEET_QTY,
            tgt.REGION_ID = src.REGION_ID,
            tgt.SBDVSN_ID = src.SBDVSN_ID,
            tgt.START_POINT_ID = src.START_POINT_ID,
            tgt.END_POINT_ID = src.END_POINT_ID,
            tgt.LINE_SRCNG_METHOD_CD = src.LINE_SRCNG_METHOD_CD,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.POST_END_DSTNC_MILES_QTY = src.POST_END_DSTNC_MILES_QTY,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_END_NM = src.POST_END_NM,
            tgt.ERROR_CD = src.ERROR_CD,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- NEW INSERT scenario
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, LINE_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, AMAP_TRACK_RFRNC_NM, AMAP_TRACK_SQNC_NBR,
            CMPLX_ARC_IND, RFRNC_HIGH_MILES_QTY, RFRNC_LOW_MILES_QTY, TRACK_SGMNT_ID, ACTUAL_HIGH_MILES_QTY,
            ACTUAL_LINE_FEET_QTY, ACTUAL_LOW_MILES_QTY, ACTUAL_GRADE_PCT, AMAP_MAIN_TRACK_RFRNC_NM, AMAP_TRACK_SIDE_CD,
            CRCLR_SPIRAL_CURVE_CD, CRVTR_DGRS_QTY, HIGH_ANGLE_DGRS_QTY, HIGH_MILE_DSPLY_OFFSET_NBR, HIGH_SWITCH_DSPLY_DGRS_QTY,
            HIGH_SWITCH_OFFSET_MLTPLR_NBR, HIGH_SWITCH_SYMBOL_NM, LOW_ANGLE_DGRS_QTY, LOW_MILE_DSPLY_OFFSET_NBR, LOW_SWITCH_DSPLY_DGRS_QTY,
            LOW_SWITCH_OFFSET_MLTPLR_NBR, LOW_SWITCH_SYMBOL_NM, RFRNC_LINE_FEET_QTY, RFRNC_GRADE_PCT, SBDVSN_LONG_ENGLSH_NM,
            SBDVSN_TRACK_SHORT_ENGLSH_NM, YARD_TRSTN_NM, YARD_TRACK_SHORT_ENGLSH_NM, RFRNC_GRADE_SOURCE_CD, RFRNC_LINE_FEET_SOURCE_CD,
            RFRNC_MILE_SOURCE_CD, SCAC_CD, FSAC_CD, YARD_TRACK_LONG_ENGLSH_NM, SBDVSN_TRACK_LONG_ENGLSH_NM,
            TRACK_CD, STRG_FEET_QTY, REGION_ID, SBDVSN_ID, START_POINT_ID,
            END_POINT_ID, LINE_SRCNG_METHOD_CD, POST_START_DSTNC_MILES_QTY, POST_END_DSTNC_MILES_QTY, POST_START_NM,
            POST_END_NM, ERROR_CD, NTWRK_SNAP_CD, PSTN_MODE_CD, SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.GRPHC_OBJECT_VRSN_ID, src.VRSN_CREATE_TMS, src.VRSN_USER_ID, src.FIRST_GRPHC_OBJECT_VRSN_ID, src.PRVS_GRPHC_OBJECT_VRSN_ID,
            src.GRPHC_OBJECT_MDFCTN_CD, src.GRPHC_OBJECT_STATUS_CD, src.GRPHC_TRNSCT_ID, src.LINE_ID, src.RECORD_CREATE_TMS,
            src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID, src.AMAP_TRACK_RFRNC_NM, src.AMAP_TRACK_SQNC_NBR,
            src.CMPLX_ARC_IND, src.RFRNC_HIGH_MILES_QTY, src.RFRNC_LOW_MILES_QTY, src.TRACK_SGMNT_ID, src.ACTUAL_HIGH_MILES_QTY,
            src.ACTUAL_LINE_FEET_QTY, src.ACTUAL_LOW_MILES_QTY, src.ACTUAL_GRADE_PCT, src.AMAP_MAIN_TRACK_RFRNC_NM, src.AMAP_TRACK_SIDE_CD,
            src.CRCLR_SPIRAL_CURVE_CD, src.CRVTR_DGRS_QTY, src.HIGH_ANGLE_DGRS_QTY, src.HIGH_MILE_DSPLY_OFFSET_NBR, src.HIGH_SWITCH_DSPLY_DGRS_QTY,
            src.HIGH_SWITCH_OFFSET_MLTPLR_NBR, src.HIGH_SWITCH_SYMBOL_NM, src.LOW_ANGLE_DGRS_QTY, src.LOW_MILE_DSPLY_OFFSET_NBR, src.LOW_SWITCH_DSPLY_DGRS_QTY,
            src.LOW_SWITCH_OFFSET_MLTPLR_NBR, src.LOW_SWITCH_SYMBOL_NM, src.RFRNC_LINE_FEET_QTY, src.RFRNC_GRADE_PCT, src.SBDVSN_LONG_ENGLSH_NM,
            src.SBDVSN_TRACK_SHORT_ENGLSH_NM, src.YARD_TRSTN_NM, src.YARD_TRACK_SHORT_ENGLSH_NM, src.RFRNC_GRADE_SOURCE_CD, src.RFRNC_LINE_FEET_SOURCE_CD,
            src.RFRNC_MILE_SOURCE_CD, src.SCAC_CD, src.FSAC_CD, src.YARD_TRACK_LONG_ENGLSH_NM, src.SBDVSN_TRACK_LONG_ENGLSH_NM,
            src.TRACK_CD, src.STRG_FEET_QTY, src.REGION_ID, src.SBDVSN_ID, src.START_POINT_ID,
            src.END_POINT_ID, src.LINE_SRCNG_METHOD_CD, src.POST_START_DSTNC_MILES_QTY, src.POST_END_DSTNC_MILES_QTY, src.POST_START_NM,
            src.POST_END_NM, src.ERROR_CD, src.NTWRK_SNAP_CD, src.PSTN_MODE_CD, src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    DROP TABLE IF EXISTS _CDC_STAGING_CTNAPP_CTNG_LINE_DN;
    
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes. Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        DROP TABLE IF EXISTS _CDC_STAGING_CTNAPP_CTNG_LINE_DN;
        RETURN 'ERROR: ' || SQLERRM || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.SADB.TASK_PROCESS_CTNAPP_CTNG_LINE_DN
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process CTNAPP_CTNG_LINE_DN_BASE CDC changes into data preservation table'
WHEN
    SYSTEM$STREAM_HAS_DATA('D_RAW.SADB.CTNAPP_CTNG_LINE_DN_BASE_HIST_STREAM')
AS
    CALL D_RAW.SADB.SP_PROCESS_CTNAPP_CTNG_LINE_DN();

ALTER TASK D_RAW.SADB.TASK_PROCESS_CTNAPP_CTNG_LINE_DN RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'CTNAPP_CTNG_LINE_DN%' IN SCHEMA D_BRONZE.SADB;
-- SHOW STREAMS LIKE 'CTNAPP_CTNG_LINE_DN%' IN SCHEMA D_RAW.SADB;
-- SHOW TASKS LIKE 'TASK_PROCESS_CTNAPP_CTNG_LINE_DN%' IN SCHEMA D_RAW.SADB;
-- CALL D_RAW.SADB.SP_PROCESS_CTNAPP_CTNG_LINE_DN();
