/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.EQPMNT_AAR_BASE_BASE
================================================================================
Source Table : D_RAW.SADB.EQPMNT_AAR_BASE_BASE
Target Table : D_BRONZE.SADB.EQPMNT_AAR_BASE
Stream       : D_RAW.SADB.EQPMNT_AAR_BASE_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_EQPMNT_AAR_BASE()
Task         : D_RAW.SADB.TASK_PROCESS_EQPMNT_AAR_BASE
Primary Key  : EQPMNT_ID (Single)
Total Columns: 80 source + 6 CDC metadata = 86
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.EQPMNT_AAR_BASE (
    EQPMNT_ID NUMBER(18,0) NOT NULL,
    MASTER_EQPMNT_ID NUMBER(18,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    UPDATE_USER_ID VARCHAR(32),
    CREATE_DATA_SOURCE_CD VARCHAR(40),
    SOURCE_CREATE_USER_ID VARCHAR(32),
    SOURCE_UPDATE_USER_ID VARCHAR(32),
    UPDATE_DATA_SOURCE_CD VARCHAR(40),
    AAR_ADD_TMS TIMESTAMP_NTZ(0),
    AAR_CAR_CD VARCHAR(16),
    AAR_CAR_CODE_ID NUMBER(18,0),
    AAR_UPDATE_TMS TIMESTAMP_NTZ(0),
    EQPMNT_GROUP_CD VARCHAR(16),
    EQPUN_NBR VARCHAR(40),
    MARK_CD VARCHAR(16),
    MCHNCL_DSGNTN_CD VARCHAR(16),
    ALTRNT_CAR_CD_ID NUMBER(18,0),
    ALTRNT_CAR_CD VARCHAR(16),
    AXLE_QTY NUMBER(4,0),
    BLDR_CD VARCHAR(16),
    DLTD_TMS TIMESTAMP_NTZ(0),
    BUILT_DT TIMESTAMP_NTZ(0),
    DMTR_UOM_BASIS_CD VARCHAR(8),
    EFCTV_TMS TIMESTAMP_NTZ(0),
    EIN_NBR VARCHAR(40),
    EQPMNT_MNGMNT_CODE_ASCTN_ID NUMBER(18,0),
    EQPMNT_POOL_ID NUMBER(18,0),
    EXPIRY_TMS TIMESTAMP_NTZ(0),
    GROSS_WEIGHT_QTY NUMBER(7,0),
    GROSS_WEIGHT_UOM_BASIS_CD VARCHAR(8),
    LINEAL_FRCTNL_UOM_BASIS_CD VARCHAR(8),
    LINEAL_UOM_BASIS_CD VARCHAR(8),
    LIQUID_UOM_BASIS_CD VARCHAR(8),
    OPRTNG_BRAKE_QTY NUMBER(2,0),
    OTSD_EXTRM_HEIGHT_QTY NUMBER(4,0),
    OTSD_EXTRM_WIDTH_QTY NUMBER(4,0),
    OTSD_HEIGHT_EXTRM_WIDTH_QTY NUMBER(4,0),
    OTSD_LENGTH_QTY NUMBER(5,0),
    OWNER_MARK_CD VARCHAR(16),
    PLATE_CLRNC_CD VARCHAR(8),
    PRIOR_EQPUN_NBR VARCHAR(40),
    PRIOR_MARK_CD VARCHAR(16),
    RBLT_CD VARCHAR(4),
    RBLT_DT TIMESTAMP_NTZ(0),
    SOURCE_CREATE_PARTY_RLTNSH_ID NUMBER(18,0),
    SOURCE_UPDATE_PARTY_RLTNSH_ID NUMBER(18,0),
    SPEED_UOM_BASIS_CD VARCHAR(8),
    SRVC_LIFE_CD VARCHAR(8),
    STATUS_CD VARCHAR(8),
    STNCL_MARK_OWNER_CLASS_CD VARCHAR(8),
    TARE_WEIGHT_QTY NUMBER(7,0),
    TRUCK_CENTER_LENGTH_QTY NUMBER(4,0),
    VOLUME_UOM_BASIS_CD VARCHAR(8),
    WEIGHT_UOM_BASIS_CD VARCHAR(8),
    EQPMNT_DSGNTN_CD VARCHAR(20),
    WHEEL_BRNG_CD VARCHAR(12),
    FIRST_MVMNT_TMS TIMESTAMP_NTZ(0),
    STATUS_CHANGE_REASON_CD VARCHAR(8),
    STATUS_CHANGE_TMS TIMESTAMP_NTZ(0),
    DELETE_REASON_CD VARCHAR(8),
    BLDR_LOT_TXT VARCHAR(100),
    CMRCL_LESSEE_CIF_TXT VARCHAR(60),
    CMRCL_OWNER_CIF_TXT VARCHAR(60),
    CNFLCT_STATUS_CD VARCHAR(8),
    CRNT_CNFLCT_STATUS_DT TIMESTAMP_NTZ(0),
    ECP_BRAKE_BLDR_CD VARCHAR(20),
    ECP_BRAKE_TYPE_CD VARCHAR(8),
    EIN_DPLCTN_CD VARCHAR(4),
    EQPMNT_ADD_RPRTR_CMPNY_MARK_CD VARCHAR(20),
    MNFCTR_CNTRY_CD VARCHAR(8),
    NEXT_CNFLCT_STATUS_CD VARCHAR(8),
    NEXT_CNFLCT_STATUS_DT TIMESTAMP_NTZ(0),
    NOTICE_MGMNT_INDCTR_CD VARCHAR(4),
    RGSTRN_REASON_CD VARCHAR(8),
    RSTNCL_PRGRM_CD VARCHAR(4),
    TRUCK_QTY NUMBER(3,0),
    RATE_CD VARCHAR(8),
    SNW__OPERATION_TYPE VARCHAR(1),
    SNW__LAST_REPLICATED TIMESTAMP_NTZ(9),

    CDC_OPERATION VARCHAR(10),  
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100), 

    PRIMARY KEY (EQPMNT_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.SADB.EQPMNT_AAR_BASE_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.SADB.EQPMNT_AAR_BASE_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.EQPMNT_AAR_BASE_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for EQPMNT_AAR_BASE_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing
-- ============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.SADB.SP_PROCESS_EQPMNT_AAR_BASE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    
    -- =========================================================================
    -- CHECK 1: Detect if stream is stale (happens after IDMC truncate/reload)
    -- =========================================================================
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.SADB.EQPMNT_AAR_BASE_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        
        CREATE OR REPLACE STREAM D_RAW.SADB.EQPMNT_AAR_BASE_BASE_HIST_STREAM
        ON TABLE D_RAW.SADB.EQPMNT_AAR_BASE_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.SADB.EQPMNT_AAR_BASE AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.SADB.EQPMNT_AAR_BASE_BASE src
            LEFT JOIN D_BRONZE.SADB.EQPMNT_AAR_BASE tgt 
                ON src.EQPMNT_ID = tgt.EQPMNT_ID
            WHERE tgt.EQPMNT_ID IS NULL
               OR tgt.IS_DELETED = TRUE
        ) AS src
        ON tgt.EQPMNT_ID = src.EQPMNT_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.MASTER_EQPMNT_ID = src.MASTER_EQPMNT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.CREATE_DATA_SOURCE_CD = src.CREATE_DATA_SOURCE_CD,
            tgt.SOURCE_CREATE_USER_ID = src.SOURCE_CREATE_USER_ID,
            tgt.SOURCE_UPDATE_USER_ID = src.SOURCE_UPDATE_USER_ID,
            tgt.UPDATE_DATA_SOURCE_CD = src.UPDATE_DATA_SOURCE_CD,
            tgt.AAR_ADD_TMS = src.AAR_ADD_TMS,
            tgt.AAR_CAR_CD = src.AAR_CAR_CD,
            tgt.AAR_CAR_CODE_ID = src.AAR_CAR_CODE_ID,
            tgt.AAR_UPDATE_TMS = src.AAR_UPDATE_TMS,
            tgt.EQPMNT_GROUP_CD = src.EQPMNT_GROUP_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.MARK_CD = src.MARK_CD,
            tgt.MCHNCL_DSGNTN_CD = src.MCHNCL_DSGNTN_CD,
            tgt.ALTRNT_CAR_CD_ID = src.ALTRNT_CAR_CD_ID,
            tgt.ALTRNT_CAR_CD = src.ALTRNT_CAR_CD,
            tgt.AXLE_QTY = src.AXLE_QTY,
            tgt.BLDR_CD = src.BLDR_CD,
            tgt.DLTD_TMS = src.DLTD_TMS,
            tgt.BUILT_DT = src.BUILT_DT,
            tgt.DMTR_UOM_BASIS_CD = src.DMTR_UOM_BASIS_CD,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.EIN_NBR = src.EIN_NBR,
            tgt.EQPMNT_MNGMNT_CODE_ASCTN_ID = src.EQPMNT_MNGMNT_CODE_ASCTN_ID,
            tgt.EQPMNT_POOL_ID = src.EQPMNT_POOL_ID,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.GROSS_WEIGHT_QTY = src.GROSS_WEIGHT_QTY,
            tgt.GROSS_WEIGHT_UOM_BASIS_CD = src.GROSS_WEIGHT_UOM_BASIS_CD,
            tgt.LINEAL_FRCTNL_UOM_BASIS_CD = src.LINEAL_FRCTNL_UOM_BASIS_CD,
            tgt.LINEAL_UOM_BASIS_CD = src.LINEAL_UOM_BASIS_CD,
            tgt.LIQUID_UOM_BASIS_CD = src.LIQUID_UOM_BASIS_CD,
            tgt.OPRTNG_BRAKE_QTY = src.OPRTNG_BRAKE_QTY,
            tgt.OTSD_EXTRM_HEIGHT_QTY = src.OTSD_EXTRM_HEIGHT_QTY,
            tgt.OTSD_EXTRM_WIDTH_QTY = src.OTSD_EXTRM_WIDTH_QTY,
            tgt.OTSD_HEIGHT_EXTRM_WIDTH_QTY = src.OTSD_HEIGHT_EXTRM_WIDTH_QTY,
            tgt.OTSD_LENGTH_QTY = src.OTSD_LENGTH_QTY,
            tgt.OWNER_MARK_CD = src.OWNER_MARK_CD,
            tgt.PLATE_CLRNC_CD = src.PLATE_CLRNC_CD,
            tgt.PRIOR_EQPUN_NBR = src.PRIOR_EQPUN_NBR,
            tgt.PRIOR_MARK_CD = src.PRIOR_MARK_CD,
            tgt.RBLT_CD = src.RBLT_CD,
            tgt.RBLT_DT = src.RBLT_DT,
            tgt.SOURCE_CREATE_PARTY_RLTNSH_ID = src.SOURCE_CREATE_PARTY_RLTNSH_ID,
            tgt.SOURCE_UPDATE_PARTY_RLTNSH_ID = src.SOURCE_UPDATE_PARTY_RLTNSH_ID,
            tgt.SPEED_UOM_BASIS_CD = src.SPEED_UOM_BASIS_CD,
            tgt.SRVC_LIFE_CD = src.SRVC_LIFE_CD,
            tgt.STATUS_CD = src.STATUS_CD,
            tgt.STNCL_MARK_OWNER_CLASS_CD = src.STNCL_MARK_OWNER_CLASS_CD,
            tgt.TARE_WEIGHT_QTY = src.TARE_WEIGHT_QTY,
            tgt.TRUCK_CENTER_LENGTH_QTY = src.TRUCK_CENTER_LENGTH_QTY,
            tgt.VOLUME_UOM_BASIS_CD = src.VOLUME_UOM_BASIS_CD,
            tgt.WEIGHT_UOM_BASIS_CD = src.WEIGHT_UOM_BASIS_CD,
            tgt.EQPMNT_DSGNTN_CD = src.EQPMNT_DSGNTN_CD,
            tgt.WHEEL_BRNG_CD = src.WHEEL_BRNG_CD,
            tgt.FIRST_MVMNT_TMS = src.FIRST_MVMNT_TMS,
            tgt.STATUS_CHANGE_REASON_CD = src.STATUS_CHANGE_REASON_CD,
            tgt.STATUS_CHANGE_TMS = src.STATUS_CHANGE_TMS,
            tgt.DELETE_REASON_CD = src.DELETE_REASON_CD,
            tgt.BLDR_LOT_TXT = src.BLDR_LOT_TXT,
            tgt.CMRCL_LESSEE_CIF_TXT = src.CMRCL_LESSEE_CIF_TXT,
            tgt.CMRCL_OWNER_CIF_TXT = src.CMRCL_OWNER_CIF_TXT,
            tgt.CNFLCT_STATUS_CD = src.CNFLCT_STATUS_CD,
            tgt.CRNT_CNFLCT_STATUS_DT = src.CRNT_CNFLCT_STATUS_DT,
            tgt.ECP_BRAKE_BLDR_CD = src.ECP_BRAKE_BLDR_CD,
            tgt.ECP_BRAKE_TYPE_CD = src.ECP_BRAKE_TYPE_CD,
            tgt.EIN_DPLCTN_CD = src.EIN_DPLCTN_CD,
            tgt.EQPMNT_ADD_RPRTR_CMPNY_MARK_CD = src.EQPMNT_ADD_RPRTR_CMPNY_MARK_CD,
            tgt.MNFCTR_CNTRY_CD = src.MNFCTR_CNTRY_CD,
            tgt.NEXT_CNFLCT_STATUS_CD = src.NEXT_CNFLCT_STATUS_CD,
            tgt.NEXT_CNFLCT_STATUS_DT = src.NEXT_CNFLCT_STATUS_DT,
            tgt.NOTICE_MGMNT_INDCTR_CD = src.NOTICE_MGMNT_INDCTR_CD,
            tgt.RGSTRN_REASON_CD = src.RGSTRN_REASON_CD,
            tgt.RSTNCL_PRGRM_CD = src.RSTNCL_PRGRM_CD,
            tgt.TRUCK_QTY = src.TRUCK_QTY,
            tgt.RATE_CD = src.RATE_CD,
            tgt.SNW__OPERATION_TYPE = src.SNW__OPERATION_TYPE,
            tgt.SNW__LAST_REPLICATED = src.SNW__LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            EQPMNT_ID, MASTER_EQPMNT_ID, RECORD_CREATE_TMS, CREATE_USER_ID, RECORD_UPDATE_TMS,
            UPDATE_USER_ID, CREATE_DATA_SOURCE_CD, SOURCE_CREATE_USER_ID, SOURCE_UPDATE_USER_ID, UPDATE_DATA_SOURCE_CD,
            AAR_ADD_TMS, AAR_CAR_CD, AAR_CAR_CODE_ID, AAR_UPDATE_TMS, EQPMNT_GROUP_CD,
            EQPUN_NBR, MARK_CD, MCHNCL_DSGNTN_CD, ALTRNT_CAR_CD_ID, ALTRNT_CAR_CD,
            AXLE_QTY, BLDR_CD, DLTD_TMS, BUILT_DT, DMTR_UOM_BASIS_CD,
            EFCTV_TMS, EIN_NBR, EQPMNT_MNGMNT_CODE_ASCTN_ID, EQPMNT_POOL_ID, EXPIRY_TMS,
            GROSS_WEIGHT_QTY, GROSS_WEIGHT_UOM_BASIS_CD, LINEAL_FRCTNL_UOM_BASIS_CD, LINEAL_UOM_BASIS_CD, LIQUID_UOM_BASIS_CD,
            OPRTNG_BRAKE_QTY, OTSD_EXTRM_HEIGHT_QTY, OTSD_EXTRM_WIDTH_QTY, OTSD_HEIGHT_EXTRM_WIDTH_QTY, OTSD_LENGTH_QTY,
            OWNER_MARK_CD, PLATE_CLRNC_CD, PRIOR_EQPUN_NBR, PRIOR_MARK_CD, RBLT_CD,
            RBLT_DT, SOURCE_CREATE_PARTY_RLTNSH_ID, SOURCE_UPDATE_PARTY_RLTNSH_ID, SPEED_UOM_BASIS_CD, SRVC_LIFE_CD,
            STATUS_CD, STNCL_MARK_OWNER_CLASS_CD, TARE_WEIGHT_QTY, TRUCK_CENTER_LENGTH_QTY, VOLUME_UOM_BASIS_CD,
            WEIGHT_UOM_BASIS_CD, EQPMNT_DSGNTN_CD, WHEEL_BRNG_CD, FIRST_MVMNT_TMS, STATUS_CHANGE_REASON_CD,
            STATUS_CHANGE_TMS, DELETE_REASON_CD, BLDR_LOT_TXT, CMRCL_LESSEE_CIF_TXT, CMRCL_OWNER_CIF_TXT,
            CNFLCT_STATUS_CD, CRNT_CNFLCT_STATUS_DT, ECP_BRAKE_BLDR_CD, ECP_BRAKE_TYPE_CD, EIN_DPLCTN_CD,
            EQPMNT_ADD_RPRTR_CMPNY_MARK_CD, MNFCTR_CNTRY_CD, NEXT_CNFLCT_STATUS_CD, NEXT_CNFLCT_STATUS_DT, NOTICE_MGMNT_INDCTR_CD,
            RGSTRN_REASON_CD, RSTNCL_PRGRM_CD, TRUCK_QTY, RATE_CD, SNW__OPERATION_TYPE,
            SNW__LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.EQPMNT_ID, src.MASTER_EQPMNT_ID, src.RECORD_CREATE_TMS, src.CREATE_USER_ID, src.RECORD_UPDATE_TMS,
            src.UPDATE_USER_ID, src.CREATE_DATA_SOURCE_CD, src.SOURCE_CREATE_USER_ID, src.SOURCE_UPDATE_USER_ID, src.UPDATE_DATA_SOURCE_CD,
            src.AAR_ADD_TMS, src.AAR_CAR_CD, src.AAR_CAR_CODE_ID, src.AAR_UPDATE_TMS, src.EQPMNT_GROUP_CD,
            src.EQPUN_NBR, src.MARK_CD, src.MCHNCL_DSGNTN_CD, src.ALTRNT_CAR_CD_ID, src.ALTRNT_CAR_CD,
            src.AXLE_QTY, src.BLDR_CD, src.DLTD_TMS, src.BUILT_DT, src.DMTR_UOM_BASIS_CD,
            src.EFCTV_TMS, src.EIN_NBR, src.EQPMNT_MNGMNT_CODE_ASCTN_ID, src.EQPMNT_POOL_ID, src.EXPIRY_TMS,
            src.GROSS_WEIGHT_QTY, src.GROSS_WEIGHT_UOM_BASIS_CD, src.LINEAL_FRCTNL_UOM_BASIS_CD, src.LINEAL_UOM_BASIS_CD, src.LIQUID_UOM_BASIS_CD,
            src.OPRTNG_BRAKE_QTY, src.OTSD_EXTRM_HEIGHT_QTY, src.OTSD_EXTRM_WIDTH_QTY, src.OTSD_HEIGHT_EXTRM_WIDTH_QTY, src.OTSD_LENGTH_QTY,
            src.OWNER_MARK_CD, src.PLATE_CLRNC_CD, src.PRIOR_EQPUN_NBR, src.PRIOR_MARK_CD, src.RBLT_CD,
            src.RBLT_DT, src.SOURCE_CREATE_PARTY_RLTNSH_ID, src.SOURCE_UPDATE_PARTY_RLTNSH_ID, src.SPEED_UOM_BASIS_CD, src.SRVC_LIFE_CD,
            src.STATUS_CD, src.STNCL_MARK_OWNER_CLASS_CD, src.TARE_WEIGHT_QTY, src.TRUCK_CENTER_LENGTH_QTY, src.VOLUME_UOM_BASIS_CD,
            src.WEIGHT_UOM_BASIS_CD, src.EQPMNT_DSGNTN_CD, src.WHEEL_BRNG_CD, src.FIRST_MVMNT_TMS, src.STATUS_CHANGE_REASON_CD,
            src.STATUS_CHANGE_TMS, src.DELETE_REASON_CD, src.BLDR_LOT_TXT, src.CMRCL_LESSEE_CIF_TXT, src.CMRCL_OWNER_CIF_TXT,
            src.CNFLCT_STATUS_CD, src.CRNT_CNFLCT_STATUS_DT, src.ECP_BRAKE_BLDR_CD, src.ECP_BRAKE_TYPE_CD, src.EIN_DPLCTN_CD,
            src.EQPMNT_ADD_RPRTR_CMPNY_MARK_CD, src.MNFCTR_CNTRY_CD, src.NEXT_CNFLCT_STATUS_CD, src.NEXT_CNFLCT_STATUS_DT, src.NOTICE_MGMNT_INDCTR_CD,
            src.RGSTRN_REASON_CD, src.RSTNCL_PRGRM_CD, src.TRUCK_QTY, src.RATE_CD, src.SNW__OPERATION_TYPE,
            src.SNW__LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_EQPMNT_AAR_BASE AS
    SELECT 
        EQPMNT_ID, MASTER_EQPMNT_ID, RECORD_CREATE_TMS, CREATE_USER_ID, RECORD_UPDATE_TMS,
        UPDATE_USER_ID, CREATE_DATA_SOURCE_CD, SOURCE_CREATE_USER_ID, SOURCE_UPDATE_USER_ID, UPDATE_DATA_SOURCE_CD,
        AAR_ADD_TMS, AAR_CAR_CD, AAR_CAR_CODE_ID, AAR_UPDATE_TMS, EQPMNT_GROUP_CD,
        EQPUN_NBR, MARK_CD, MCHNCL_DSGNTN_CD, ALTRNT_CAR_CD_ID, ALTRNT_CAR_CD,
        AXLE_QTY, BLDR_CD, DLTD_TMS, BUILT_DT, DMTR_UOM_BASIS_CD,
        EFCTV_TMS, EIN_NBR, EQPMNT_MNGMNT_CODE_ASCTN_ID, EQPMNT_POOL_ID, EXPIRY_TMS,
        GROSS_WEIGHT_QTY, GROSS_WEIGHT_UOM_BASIS_CD, LINEAL_FRCTNL_UOM_BASIS_CD, LINEAL_UOM_BASIS_CD, LIQUID_UOM_BASIS_CD,
        OPRTNG_BRAKE_QTY, OTSD_EXTRM_HEIGHT_QTY, OTSD_EXTRM_WIDTH_QTY, OTSD_HEIGHT_EXTRM_WIDTH_QTY, OTSD_LENGTH_QTY,
        OWNER_MARK_CD, PLATE_CLRNC_CD, PRIOR_EQPUN_NBR, PRIOR_MARK_CD, RBLT_CD,
        RBLT_DT, SOURCE_CREATE_PARTY_RLTNSH_ID, SOURCE_UPDATE_PARTY_RLTNSH_ID, SPEED_UOM_BASIS_CD, SRVC_LIFE_CD,
        STATUS_CD, STNCL_MARK_OWNER_CLASS_CD, TARE_WEIGHT_QTY, TRUCK_CENTER_LENGTH_QTY, VOLUME_UOM_BASIS_CD,
        WEIGHT_UOM_BASIS_CD, EQPMNT_DSGNTN_CD, WHEEL_BRNG_CD, FIRST_MVMNT_TMS, STATUS_CHANGE_REASON_CD,
        STATUS_CHANGE_TMS, DELETE_REASON_CD, BLDR_LOT_TXT, CMRCL_LESSEE_CIF_TXT, CMRCL_OWNER_CIF_TXT,
        CNFLCT_STATUS_CD, CRNT_CNFLCT_STATUS_DT, ECP_BRAKE_BLDR_CD, ECP_BRAKE_TYPE_CD, EIN_DPLCTN_CD,
        EQPMNT_ADD_RPRTR_CMPNY_MARK_CD, MNFCTR_CNTRY_CD, NEXT_CNFLCT_STATUS_CD, NEXT_CNFLCT_STATUS_DT, NOTICE_MGMNT_INDCTR_CD,
        RGSTRN_REASON_CD, RSTNCL_PRGRM_CD, TRUCK_QTY, RATE_CD, SNW__OPERATION_TYPE,
        SNW__LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.SADB.EQPMNT_AAR_BASE_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_EQPMNT_AAR_BASE;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_EQPMNT_AAR_BASE;
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.SADB.EQPMNT_AAR_BASE AS tgt
    USING (
        SELECT 
            EQPMNT_ID, MASTER_EQPMNT_ID, RECORD_CREATE_TMS, CREATE_USER_ID, RECORD_UPDATE_TMS,
            UPDATE_USER_ID, CREATE_DATA_SOURCE_CD, SOURCE_CREATE_USER_ID, SOURCE_UPDATE_USER_ID, UPDATE_DATA_SOURCE_CD,
            AAR_ADD_TMS, AAR_CAR_CD, AAR_CAR_CODE_ID, AAR_UPDATE_TMS, EQPMNT_GROUP_CD,
            EQPUN_NBR, MARK_CD, MCHNCL_DSGNTN_CD, ALTRNT_CAR_CD_ID, ALTRNT_CAR_CD,
            AXLE_QTY, BLDR_CD, DLTD_TMS, BUILT_DT, DMTR_UOM_BASIS_CD,
            EFCTV_TMS, EIN_NBR, EQPMNT_MNGMNT_CODE_ASCTN_ID, EQPMNT_POOL_ID, EXPIRY_TMS,
            GROSS_WEIGHT_QTY, GROSS_WEIGHT_UOM_BASIS_CD, LINEAL_FRCTNL_UOM_BASIS_CD, LINEAL_UOM_BASIS_CD, LIQUID_UOM_BASIS_CD,
            OPRTNG_BRAKE_QTY, OTSD_EXTRM_HEIGHT_QTY, OTSD_EXTRM_WIDTH_QTY, OTSD_HEIGHT_EXTRM_WIDTH_QTY, OTSD_LENGTH_QTY,
            OWNER_MARK_CD, PLATE_CLRNC_CD, PRIOR_EQPUN_NBR, PRIOR_MARK_CD, RBLT_CD,
            RBLT_DT, SOURCE_CREATE_PARTY_RLTNSH_ID, SOURCE_UPDATE_PARTY_RLTNSH_ID, SPEED_UOM_BASIS_CD, SRVC_LIFE_CD,
            STATUS_CD, STNCL_MARK_OWNER_CLASS_CD, TARE_WEIGHT_QTY, TRUCK_CENTER_LENGTH_QTY, VOLUME_UOM_BASIS_CD,
            WEIGHT_UOM_BASIS_CD, EQPMNT_DSGNTN_CD, WHEEL_BRNG_CD, FIRST_MVMNT_TMS, STATUS_CHANGE_REASON_CD,
            STATUS_CHANGE_TMS, DELETE_REASON_CD, BLDR_LOT_TXT, CMRCL_LESSEE_CIF_TXT, CMRCL_OWNER_CIF_TXT,
            CNFLCT_STATUS_CD, CRNT_CNFLCT_STATUS_DT, ECP_BRAKE_BLDR_CD, ECP_BRAKE_TYPE_CD, EIN_DPLCTN_CD,
            EQPMNT_ADD_RPRTR_CMPNY_MARK_CD, MNFCTR_CNTRY_CD, NEXT_CNFLCT_STATUS_CD, NEXT_CNFLCT_STATUS_DT, NOTICE_MGMNT_INDCTR_CD,
            RGSTRN_REASON_CD, RSTNCL_PRGRM_CD, TRUCK_QTY, RATE_CD, SNW__OPERATION_TYPE,
            SNW__LAST_REPLICATED,
            CDC_ACTION,
            CDC_IS_UPDATE,
            ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_EQPMNT_AAR_BASE
    ) AS src
    ON tgt.EQPMNT_ID = src.EQPMNT_ID
    
    -- UPDATE scenario (METADATA$ACTION='INSERT' AND METADATA$ISUPDATE=TRUE)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.MASTER_EQPMNT_ID = src.MASTER_EQPMNT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.CREATE_DATA_SOURCE_CD = src.CREATE_DATA_SOURCE_CD,
            tgt.SOURCE_CREATE_USER_ID = src.SOURCE_CREATE_USER_ID,
            tgt.SOURCE_UPDATE_USER_ID = src.SOURCE_UPDATE_USER_ID,
            tgt.UPDATE_DATA_SOURCE_CD = src.UPDATE_DATA_SOURCE_CD,
            tgt.AAR_ADD_TMS = src.AAR_ADD_TMS,
            tgt.AAR_CAR_CD = src.AAR_CAR_CD,
            tgt.AAR_CAR_CODE_ID = src.AAR_CAR_CODE_ID,
            tgt.AAR_UPDATE_TMS = src.AAR_UPDATE_TMS,
            tgt.EQPMNT_GROUP_CD = src.EQPMNT_GROUP_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.MARK_CD = src.MARK_CD,
            tgt.MCHNCL_DSGNTN_CD = src.MCHNCL_DSGNTN_CD,
            tgt.ALTRNT_CAR_CD_ID = src.ALTRNT_CAR_CD_ID,
            tgt.ALTRNT_CAR_CD = src.ALTRNT_CAR_CD,
            tgt.AXLE_QTY = src.AXLE_QTY,
            tgt.BLDR_CD = src.BLDR_CD,
            tgt.DLTD_TMS = src.DLTD_TMS,
            tgt.BUILT_DT = src.BUILT_DT,
            tgt.DMTR_UOM_BASIS_CD = src.DMTR_UOM_BASIS_CD,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.EIN_NBR = src.EIN_NBR,
            tgt.EQPMNT_MNGMNT_CODE_ASCTN_ID = src.EQPMNT_MNGMNT_CODE_ASCTN_ID,
            tgt.EQPMNT_POOL_ID = src.EQPMNT_POOL_ID,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.GROSS_WEIGHT_QTY = src.GROSS_WEIGHT_QTY,
            tgt.GROSS_WEIGHT_UOM_BASIS_CD = src.GROSS_WEIGHT_UOM_BASIS_CD,
            tgt.LINEAL_FRCTNL_UOM_BASIS_CD = src.LINEAL_FRCTNL_UOM_BASIS_CD,
            tgt.LINEAL_UOM_BASIS_CD = src.LINEAL_UOM_BASIS_CD,
            tgt.LIQUID_UOM_BASIS_CD = src.LIQUID_UOM_BASIS_CD,
            tgt.OPRTNG_BRAKE_QTY = src.OPRTNG_BRAKE_QTY,
            tgt.OTSD_EXTRM_HEIGHT_QTY = src.OTSD_EXTRM_HEIGHT_QTY,
            tgt.OTSD_EXTRM_WIDTH_QTY = src.OTSD_EXTRM_WIDTH_QTY,
            tgt.OTSD_HEIGHT_EXTRM_WIDTH_QTY = src.OTSD_HEIGHT_EXTRM_WIDTH_QTY,
            tgt.OTSD_LENGTH_QTY = src.OTSD_LENGTH_QTY,
            tgt.OWNER_MARK_CD = src.OWNER_MARK_CD,
            tgt.PLATE_CLRNC_CD = src.PLATE_CLRNC_CD,
            tgt.PRIOR_EQPUN_NBR = src.PRIOR_EQPUN_NBR,
            tgt.PRIOR_MARK_CD = src.PRIOR_MARK_CD,
            tgt.RBLT_CD = src.RBLT_CD,
            tgt.RBLT_DT = src.RBLT_DT,
            tgt.SOURCE_CREATE_PARTY_RLTNSH_ID = src.SOURCE_CREATE_PARTY_RLTNSH_ID,
            tgt.SOURCE_UPDATE_PARTY_RLTNSH_ID = src.SOURCE_UPDATE_PARTY_RLTNSH_ID,
            tgt.SPEED_UOM_BASIS_CD = src.SPEED_UOM_BASIS_CD,
            tgt.SRVC_LIFE_CD = src.SRVC_LIFE_CD,
            tgt.STATUS_CD = src.STATUS_CD,
            tgt.STNCL_MARK_OWNER_CLASS_CD = src.STNCL_MARK_OWNER_CLASS_CD,
            tgt.TARE_WEIGHT_QTY = src.TARE_WEIGHT_QTY,
            tgt.TRUCK_CENTER_LENGTH_QTY = src.TRUCK_CENTER_LENGTH_QTY,
            tgt.VOLUME_UOM_BASIS_CD = src.VOLUME_UOM_BASIS_CD,
            tgt.WEIGHT_UOM_BASIS_CD = src.WEIGHT_UOM_BASIS_CD,
            tgt.EQPMNT_DSGNTN_CD = src.EQPMNT_DSGNTN_CD,
            tgt.WHEEL_BRNG_CD = src.WHEEL_BRNG_CD,
            tgt.FIRST_MVMNT_TMS = src.FIRST_MVMNT_TMS,
            tgt.STATUS_CHANGE_REASON_CD = src.STATUS_CHANGE_REASON_CD,
            tgt.STATUS_CHANGE_TMS = src.STATUS_CHANGE_TMS,
            tgt.DELETE_REASON_CD = src.DELETE_REASON_CD,
            tgt.BLDR_LOT_TXT = src.BLDR_LOT_TXT,
            tgt.CMRCL_LESSEE_CIF_TXT = src.CMRCL_LESSEE_CIF_TXT,
            tgt.CMRCL_OWNER_CIF_TXT = src.CMRCL_OWNER_CIF_TXT,
            tgt.CNFLCT_STATUS_CD = src.CNFLCT_STATUS_CD,
            tgt.CRNT_CNFLCT_STATUS_DT = src.CRNT_CNFLCT_STATUS_DT,
            tgt.ECP_BRAKE_BLDR_CD = src.ECP_BRAKE_BLDR_CD,
            tgt.ECP_BRAKE_TYPE_CD = src.ECP_BRAKE_TYPE_CD,
            tgt.EIN_DPLCTN_CD = src.EIN_DPLCTN_CD,
            tgt.EQPMNT_ADD_RPRTR_CMPNY_MARK_CD = src.EQPMNT_ADD_RPRTR_CMPNY_MARK_CD,
            tgt.MNFCTR_CNTRY_CD = src.MNFCTR_CNTRY_CD,
            tgt.NEXT_CNFLCT_STATUS_CD = src.NEXT_CNFLCT_STATUS_CD,
            tgt.NEXT_CNFLCT_STATUS_DT = src.NEXT_CNFLCT_STATUS_DT,
            tgt.NOTICE_MGMNT_INDCTR_CD = src.NOTICE_MGMNT_INDCTR_CD,
            tgt.RGSTRN_REASON_CD = src.RGSTRN_REASON_CD,
            tgt.RSTNCL_PRGRM_CD = src.RSTNCL_PRGRM_CD,
            tgt.TRUCK_QTY = src.TRUCK_QTY,
            tgt.RATE_CD = src.RATE_CD,
            tgt.SNW__OPERATION_TYPE = src.SNW__OPERATION_TYPE,
            tgt.SNW__LAST_REPLICATED = src.SNW__LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- DELETE scenario (METADATA$ACTION='DELETE' AND METADATA$ISUPDATE=FALSE)
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- RE-INSERT scenario (record exists but being re-inserted)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.MASTER_EQPMNT_ID = src.MASTER_EQPMNT_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.CREATE_DATA_SOURCE_CD = src.CREATE_DATA_SOURCE_CD,
            tgt.SOURCE_CREATE_USER_ID = src.SOURCE_CREATE_USER_ID,
            tgt.SOURCE_UPDATE_USER_ID = src.SOURCE_UPDATE_USER_ID,
            tgt.UPDATE_DATA_SOURCE_CD = src.UPDATE_DATA_SOURCE_CD,
            tgt.AAR_ADD_TMS = src.AAR_ADD_TMS,
            tgt.AAR_CAR_CD = src.AAR_CAR_CD,
            tgt.AAR_CAR_CODE_ID = src.AAR_CAR_CODE_ID,
            tgt.AAR_UPDATE_TMS = src.AAR_UPDATE_TMS,
            tgt.EQPMNT_GROUP_CD = src.EQPMNT_GROUP_CD,
            tgt.EQPUN_NBR = src.EQPUN_NBR,
            tgt.MARK_CD = src.MARK_CD,
            tgt.MCHNCL_DSGNTN_CD = src.MCHNCL_DSGNTN_CD,
            tgt.ALTRNT_CAR_CD_ID = src.ALTRNT_CAR_CD_ID,
            tgt.ALTRNT_CAR_CD = src.ALTRNT_CAR_CD,
            tgt.AXLE_QTY = src.AXLE_QTY,
            tgt.BLDR_CD = src.BLDR_CD,
            tgt.DLTD_TMS = src.DLTD_TMS,
            tgt.BUILT_DT = src.BUILT_DT,
            tgt.DMTR_UOM_BASIS_CD = src.DMTR_UOM_BASIS_CD,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.EIN_NBR = src.EIN_NBR,
            tgt.EQPMNT_MNGMNT_CODE_ASCTN_ID = src.EQPMNT_MNGMNT_CODE_ASCTN_ID,
            tgt.EQPMNT_POOL_ID = src.EQPMNT_POOL_ID,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.GROSS_WEIGHT_QTY = src.GROSS_WEIGHT_QTY,
            tgt.GROSS_WEIGHT_UOM_BASIS_CD = src.GROSS_WEIGHT_UOM_BASIS_CD,
            tgt.LINEAL_FRCTNL_UOM_BASIS_CD = src.LINEAL_FRCTNL_UOM_BASIS_CD,
            tgt.LINEAL_UOM_BASIS_CD = src.LINEAL_UOM_BASIS_CD,
            tgt.LIQUID_UOM_BASIS_CD = src.LIQUID_UOM_BASIS_CD,
            tgt.OPRTNG_BRAKE_QTY = src.OPRTNG_BRAKE_QTY,
            tgt.OTSD_EXTRM_HEIGHT_QTY = src.OTSD_EXTRM_HEIGHT_QTY,
            tgt.OTSD_EXTRM_WIDTH_QTY = src.OTSD_EXTRM_WIDTH_QTY,
            tgt.OTSD_HEIGHT_EXTRM_WIDTH_QTY = src.OTSD_HEIGHT_EXTRM_WIDTH_QTY,
            tgt.OTSD_LENGTH_QTY = src.OTSD_LENGTH_QTY,
            tgt.OWNER_MARK_CD = src.OWNER_MARK_CD,
            tgt.PLATE_CLRNC_CD = src.PLATE_CLRNC_CD,
            tgt.PRIOR_EQPUN_NBR = src.PRIOR_EQPUN_NBR,
            tgt.PRIOR_MARK_CD = src.PRIOR_MARK_CD,
            tgt.RBLT_CD = src.RBLT_CD,
            tgt.RBLT_DT = src.RBLT_DT,
            tgt.SOURCE_CREATE_PARTY_RLTNSH_ID = src.SOURCE_CREATE_PARTY_RLTNSH_ID,
            tgt.SOURCE_UPDATE_PARTY_RLTNSH_ID = src.SOURCE_UPDATE_PARTY_RLTNSH_ID,
            tgt.SPEED_UOM_BASIS_CD = src.SPEED_UOM_BASIS_CD,
            tgt.SRVC_LIFE_CD = src.SRVC_LIFE_CD,
            tgt.STATUS_CD = src.STATUS_CD,
            tgt.STNCL_MARK_OWNER_CLASS_CD = src.STNCL_MARK_OWNER_CLASS_CD,
            tgt.TARE_WEIGHT_QTY = src.TARE_WEIGHT_QTY,
            tgt.TRUCK_CENTER_LENGTH_QTY = src.TRUCK_CENTER_LENGTH_QTY,
            tgt.VOLUME_UOM_BASIS_CD = src.VOLUME_UOM_BASIS_CD,
            tgt.WEIGHT_UOM_BASIS_CD = src.WEIGHT_UOM_BASIS_CD,
            tgt.EQPMNT_DSGNTN_CD = src.EQPMNT_DSGNTN_CD,
            tgt.WHEEL_BRNG_CD = src.WHEEL_BRNG_CD,
            tgt.FIRST_MVMNT_TMS = src.FIRST_MVMNT_TMS,
            tgt.STATUS_CHANGE_REASON_CD = src.STATUS_CHANGE_REASON_CD,
            tgt.STATUS_CHANGE_TMS = src.STATUS_CHANGE_TMS,
            tgt.DELETE_REASON_CD = src.DELETE_REASON_CD,
            tgt.BLDR_LOT_TXT = src.BLDR_LOT_TXT,
            tgt.CMRCL_LESSEE_CIF_TXT = src.CMRCL_LESSEE_CIF_TXT,
            tgt.CMRCL_OWNER_CIF_TXT = src.CMRCL_OWNER_CIF_TXT,
            tgt.CNFLCT_STATUS_CD = src.CNFLCT_STATUS_CD,
            tgt.CRNT_CNFLCT_STATUS_DT = src.CRNT_CNFLCT_STATUS_DT,
            tgt.ECP_BRAKE_BLDR_CD = src.ECP_BRAKE_BLDR_CD,
            tgt.ECP_BRAKE_TYPE_CD = src.ECP_BRAKE_TYPE_CD,
            tgt.EIN_DPLCTN_CD = src.EIN_DPLCTN_CD,
            tgt.EQPMNT_ADD_RPRTR_CMPNY_MARK_CD = src.EQPMNT_ADD_RPRTR_CMPNY_MARK_CD,
            tgt.MNFCTR_CNTRY_CD = src.MNFCTR_CNTRY_CD,
            tgt.NEXT_CNFLCT_STATUS_CD = src.NEXT_CNFLCT_STATUS_CD,
            tgt.NEXT_CNFLCT_STATUS_DT = src.NEXT_CNFLCT_STATUS_DT,
            tgt.NOTICE_MGMNT_INDCTR_CD = src.NOTICE_MGMNT_INDCTR_CD,
            tgt.RGSTRN_REASON_CD = src.RGSTRN_REASON_CD,
            tgt.RSTNCL_PRGRM_CD = src.RSTNCL_PRGRM_CD,
            tgt.TRUCK_QTY = src.TRUCK_QTY,
            tgt.RATE_CD = src.RATE_CD,
            tgt.SNW__OPERATION_TYPE = src.SNW__OPERATION_TYPE,
            tgt.SNW__LAST_REPLICATED = src.SNW__LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- NEW INSERT scenario
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            EQPMNT_ID, MASTER_EQPMNT_ID, RECORD_CREATE_TMS, CREATE_USER_ID, RECORD_UPDATE_TMS,
            UPDATE_USER_ID, CREATE_DATA_SOURCE_CD, SOURCE_CREATE_USER_ID, SOURCE_UPDATE_USER_ID, UPDATE_DATA_SOURCE_CD,
            AAR_ADD_TMS, AAR_CAR_CD, AAR_CAR_CODE_ID, AAR_UPDATE_TMS, EQPMNT_GROUP_CD,
            EQPUN_NBR, MARK_CD, MCHNCL_DSGNTN_CD, ALTRNT_CAR_CD_ID, ALTRNT_CAR_CD,
            AXLE_QTY, BLDR_CD, DLTD_TMS, BUILT_DT, DMTR_UOM_BASIS_CD,
            EFCTV_TMS, EIN_NBR, EQPMNT_MNGMNT_CODE_ASCTN_ID, EQPMNT_POOL_ID, EXPIRY_TMS,
            GROSS_WEIGHT_QTY, GROSS_WEIGHT_UOM_BASIS_CD, LINEAL_FRCTNL_UOM_BASIS_CD, LINEAL_UOM_BASIS_CD, LIQUID_UOM_BASIS_CD,
            OPRTNG_BRAKE_QTY, OTSD_EXTRM_HEIGHT_QTY, OTSD_EXTRM_WIDTH_QTY, OTSD_HEIGHT_EXTRM_WIDTH_QTY, OTSD_LENGTH_QTY,
            OWNER_MARK_CD, PLATE_CLRNC_CD, PRIOR_EQPUN_NBR, PRIOR_MARK_CD, RBLT_CD,
            RBLT_DT, SOURCE_CREATE_PARTY_RLTNSH_ID, SOURCE_UPDATE_PARTY_RLTNSH_ID, SPEED_UOM_BASIS_CD, SRVC_LIFE_CD,
            STATUS_CD, STNCL_MARK_OWNER_CLASS_CD, TARE_WEIGHT_QTY, TRUCK_CENTER_LENGTH_QTY, VOLUME_UOM_BASIS_CD,
            WEIGHT_UOM_BASIS_CD, EQPMNT_DSGNTN_CD, WHEEL_BRNG_CD, FIRST_MVMNT_TMS, STATUS_CHANGE_REASON_CD,
            STATUS_CHANGE_TMS, DELETE_REASON_CD, BLDR_LOT_TXT, CMRCL_LESSEE_CIF_TXT, CMRCL_OWNER_CIF_TXT,
            CNFLCT_STATUS_CD, CRNT_CNFLCT_STATUS_DT, ECP_BRAKE_BLDR_CD, ECP_BRAKE_TYPE_CD, EIN_DPLCTN_CD,
            EQPMNT_ADD_RPRTR_CMPNY_MARK_CD, MNFCTR_CNTRY_CD, NEXT_CNFLCT_STATUS_CD, NEXT_CNFLCT_STATUS_DT, NOTICE_MGMNT_INDCTR_CD,
            RGSTRN_REASON_CD, RSTNCL_PRGRM_CD, TRUCK_QTY, RATE_CD, SNW__OPERATION_TYPE,
            SNW__LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.EQPMNT_ID, src.MASTER_EQPMNT_ID, src.RECORD_CREATE_TMS, src.CREATE_USER_ID, src.RECORD_UPDATE_TMS,
            src.UPDATE_USER_ID, src.CREATE_DATA_SOURCE_CD, src.SOURCE_CREATE_USER_ID, src.SOURCE_UPDATE_USER_ID, src.UPDATE_DATA_SOURCE_CD,
            src.AAR_ADD_TMS, src.AAR_CAR_CD, src.AAR_CAR_CODE_ID, src.AAR_UPDATE_TMS, src.EQPMNT_GROUP_CD,
            src.EQPUN_NBR, src.MARK_CD, src.MCHNCL_DSGNTN_CD, src.ALTRNT_CAR_CD_ID, src.ALTRNT_CAR_CD,
            src.AXLE_QTY, src.BLDR_CD, src.DLTD_TMS, src.BUILT_DT, src.DMTR_UOM_BASIS_CD,
            src.EFCTV_TMS, src.EIN_NBR, src.EQPMNT_MNGMNT_CODE_ASCTN_ID, src.EQPMNT_POOL_ID, src.EXPIRY_TMS,
            src.GROSS_WEIGHT_QTY, src.GROSS_WEIGHT_UOM_BASIS_CD, src.LINEAL_FRCTNL_UOM_BASIS_CD, src.LINEAL_UOM_BASIS_CD, src.LIQUID_UOM_BASIS_CD,
            src.OPRTNG_BRAKE_QTY, src.OTSD_EXTRM_HEIGHT_QTY, src.OTSD_EXTRM_WIDTH_QTY, src.OTSD_HEIGHT_EXTRM_WIDTH_QTY, src.OTSD_LENGTH_QTY,
            src.OWNER_MARK_CD, src.PLATE_CLRNC_CD, src.PRIOR_EQPUN_NBR, src.PRIOR_MARK_CD, src.RBLT_CD,
            src.RBLT_DT, src.SOURCE_CREATE_PARTY_RLTNSH_ID, src.SOURCE_UPDATE_PARTY_RLTNSH_ID, src.SPEED_UOM_BASIS_CD, src.SRVC_LIFE_CD,
            src.STATUS_CD, src.STNCL_MARK_OWNER_CLASS_CD, src.TARE_WEIGHT_QTY, src.TRUCK_CENTER_LENGTH_QTY, src.VOLUME_UOM_BASIS_CD,
            src.WEIGHT_UOM_BASIS_CD, src.EQPMNT_DSGNTN_CD, src.WHEEL_BRNG_CD, src.FIRST_MVMNT_TMS, src.STATUS_CHANGE_REASON_CD,
            src.STATUS_CHANGE_TMS, src.DELETE_REASON_CD, src.BLDR_LOT_TXT, src.CMRCL_LESSEE_CIF_TXT, src.CMRCL_OWNER_CIF_TXT,
            src.CNFLCT_STATUS_CD, src.CRNT_CNFLCT_STATUS_DT, src.ECP_BRAKE_BLDR_CD, src.ECP_BRAKE_TYPE_CD, src.EIN_DPLCTN_CD,
            src.EQPMNT_ADD_RPRTR_CMPNY_MARK_CD, src.MNFCTR_CNTRY_CD, src.NEXT_CNFLCT_STATUS_CD, src.NEXT_CNFLCT_STATUS_DT, src.NOTICE_MGMNT_INDCTR_CD,
            src.RGSTRN_REASON_CD, src.RSTNCL_PRGRM_CD, src.TRUCK_QTY, src.RATE_CD, src.SNW__OPERATION_TYPE,
            src.SNW__LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    DROP TABLE IF EXISTS _CDC_STAGING_EQPMNT_AAR_BASE;
    
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes. Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        DROP TABLE IF EXISTS _CDC_STAGING_EQPMNT_AAR_BASE;
        RETURN 'ERROR: ' || SQLERRM || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.SADB.TASK_PROCESS_EQPMNT_AAR_BASE
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process EQPMNT_AAR_BASE_BASE CDC changes into data preservation table'
WHEN
    SYSTEM$STREAM_HAS_DATA('D_RAW.SADB.EQPMNT_AAR_BASE_BASE_HIST_STREAM')
AS
    CALL D_RAW.SADB.SP_PROCESS_EQPMNT_AAR_BASE();

ALTER TASK D_RAW.SADB.TASK_PROCESS_EQPMNT_AAR_BASE RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'EQPMNT_AAR_BASE%' IN SCHEMA D_RAW.SADB;
-- SHOW STREAMS LIKE 'EQPMNT_AAR_BASE%' IN SCHEMA D_RAW.SADB;
-- SHOW TASKS LIKE 'TASK_PROCESS_EQPMNT_AAR_BASE%' IN SCHEMA D_RAW.SADB;
-- CALL D_RAW.SADB.SP_PROCESS_EQPMNT_AAR_BASE();
