/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE
================================================================================
Source Table : D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE
Target Table : D_BRONZE.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN
Stream       : D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN()
Task         : D_RAW.SADB.TASK_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN
Primary Key  : GRPHC_OBJECT_VRSN_ID (Single)
Total Columns: 56 source + 6 CDC metadata = 62
================================================================================
*/

-- =============================================================================
-- STEP 1: Create Target Data Preservation Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN (
    GRPHC_OBJECT_VRSN_ID NUMBER(18,0) NOT NULL,
    VRSN_CREATE_TMS TIMESTAMP_NTZ(0),
    VRSN_USER_ID VARCHAR(32),
    FIRST_GRPHC_OBJECT_VRSN_ID NUMBER(18,0),
    PRVS_GRPHC_OBJECT_VRSN_ID NUMBER(18,0),
    GRPHC_OBJECT_MDFCTN_CD VARCHAR(36),
    GRPHC_OBJECT_STATUS_CD VARCHAR(32),
    GRPHC_TRNSCT_ID NUMBER(18,0),
    FXPLA_TRACK_LCTN_ID NUMBER(18,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(0),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(0),
    CREATE_USER_ID VARCHAR(32),
    UPDATE_USER_ID VARCHAR(32),
    EFCTV_TMS TIMESTAMP_NTZ(0),
    DSPTCH_IND VARCHAR(4),
    PHYSCL_LCTN_IND VARCHAR(4),
    RFRNC_LOW_MILES_QTY NUMBER(8,3),
    RPRTNG_POINT_IND VARCHAR(4),
    DATA_SOURCE_CD VARCHAR(40),
    FIXED_PLANT_ASSET_ID NUMBER(18,0),
    ORGNL_DATA_SOURCE_CD VARCHAR(40),
    TRACK_SGMNT_ID NUMBER(18,0),
    ACTUAL_HIGH_MILES_QTY NUMBER(8,3),
    ACTUAL_LOW_MILES_QTY NUMBER(8,3),
    ASSET_SQNC_CD VARCHAR(4),
    EXPIRY_TMS TIMESTAMP_NTZ(0),
    DRCTN_FROM_TRACK_CD VARCHAR(20),
    DSPLY_HIGH_MILES_QTY NUMBER(8,3),
    DSPLY_LOW_MILES_QTY NUMBER(8,3),
    RFRNC_HIGH_MILES_QTY NUMBER(8,3),
    ALTD_FEET_QTY NUMBER(8,4),
    DSPLY_RTN_DGRS_QTY NUMBER(3,0),
    LNGTD_NBR NUMBER(11,8),
    LTD_NBR NUMBER(10,8),
    LTD_LNGTD_DATA_SOURCE_CD VARCHAR(40),
    PSTN_METHOD_CD VARCHAR(44),
    OVRD_DSPLY_RTN_DGRS_QTY NUMBER(3,0),
    ALTD_2_FEET_QTY NUMBER(8,4),
    DSPLY_RTN_2_DGRS_QTY NUMBER(3,0),
    LNGTD_2_NBR NUMBER(11,8),
    LTD_2_NBR NUMBER(10,8),
    LTD_LNGTD_2_DATA_SOURCE_CD VARCHAR(40),
    PSTN_METHOD_2_CD VARCHAR(44),
    OVRD_DSPLY_RTN_2_DGRS_QTY NUMBER(3,0),
    ATHRZD_MVMNT_DRCTN_CD VARCHAR(20),
    CNCTN_ORNTN_CD VARCHAR(20),
    DRCTN_RFRNC_MILE_CD VARCHAR(4),
    OCS_DSPTCH_CD VARCHAR(4),
    OVRD_LOW_MILES_QTY NUMBER(8,3),
    INSPCT_FRQNCY_CD VARCHAR(40),
    POST_START_NM VARCHAR(64),
    POST_START_DSTNC_MILES_QTY NUMBER(8,3),
    NTWRK_SNAP_CD NUMBER(1,0),
    PSTN_MODE_CD NUMBER(1,0),
    SNW_OPERATION_TYPE VARCHAR(1),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),

    CDC_OPERATION VARCHAR(10),  
    CDC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100), 

    PRIMARY KEY (GRPHC_OBJECT_VRSN_ID)
);

-- =============================================================================
-- STEP 2: Enable Change Tracking on Source Table
-- =============================================================================
ALTER TABLE D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE 
SET CHANGE_TRACKING = TRUE,
    DATA_RETENTION_TIME_IN_DAYS = 45,
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 15;

-- =============================================================================
-- STEP 3: Create Stream with SHOW_INITIAL_ROWS for Initial Load
-- =============================================================================
CREATE OR REPLACE STREAM D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE
SHOW_INITIAL_ROWS = TRUE
COMMENT = 'CDC Stream for TRKFCG_FXPLA_TRACK_LCTN_DN_BASE data preservation. SHOW_INITIAL_ROWS=TRUE for initial load.';

-- =============================================================================
-- STEP 4: Create Stored Procedure for CDC Processing
-- =============================================================================
CREATE OR REPLACE PROCEDURE D_RAW.SADB.SP_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    
    -- =========================================================================
    -- CHECK 1: Detect if stream is stale (happens after IDMC truncate/reload)
    -- =========================================================================
    BEGIN
        SELECT COUNT(*) INTO v_staging_count 
        FROM D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
        
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;
    
    -- =========================================================================
    -- RECOVERY: If stream is stale, recreate it and do differential load
    -- =========================================================================
    IF (v_stream_stale = TRUE) THEN
        v_result := 'STREAM_STALE_DETECTED: ' || NVL(v_error_msg, 'Unknown') || ' - Initiating recovery at ' || CURRENT_TIMESTAMP()::VARCHAR;
        
        CREATE OR REPLACE STREAM D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE_HIST_STREAM
        ON TABLE D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE
        SHOW_INITIAL_ROWS = TRUE
        COMMENT = 'CDC Stream recreated after staleness detection';
        
        MERGE INTO D_BRONZE.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN AS tgt
        USING (
            SELECT 
                src.*,
                'INSERT' AS CDC_OP,
                :v_batch_id AS BATCH_ID
            FROM D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE src
            LEFT JOIN D_BRONZE.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN tgt 
                ON src.GRPHC_OBJECT_VRSN_ID = tgt.GRPHC_OBJECT_VRSN_ID
            WHERE tgt.GRPHC_OBJECT_VRSN_ID IS NULL
               OR tgt.IS_DELETED = TRUE
        ) AS src
        ON tgt.GRPHC_OBJECT_VRSN_ID = src.GRPHC_OBJECT_VRSN_ID
        WHEN MATCHED THEN UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.FXPLA_TRACK_LCTN_ID = src.FXPLA_TRACK_LCTN_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.DSPTCH_IND = src.DSPTCH_IND,
            tgt.PHYSCL_LCTN_IND = src.PHYSCL_LCTN_IND,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.RPRTNG_POINT_IND = src.RPRTNG_POINT_IND,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.FIXED_PLANT_ASSET_ID = src.FIXED_PLANT_ASSET_ID,
            tgt.ORGNL_DATA_SOURCE_CD = src.ORGNL_DATA_SOURCE_CD,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.ACTUAL_HIGH_MILES_QTY = src.ACTUAL_HIGH_MILES_QTY,
            tgt.ACTUAL_LOW_MILES_QTY = src.ACTUAL_LOW_MILES_QTY,
            tgt.ASSET_SQNC_CD = src.ASSET_SQNC_CD,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.DRCTN_FROM_TRACK_CD = src.DRCTN_FROM_TRACK_CD,
            tgt.DSPLY_HIGH_MILES_QTY = src.DSPLY_HIGH_MILES_QTY,
            tgt.DSPLY_LOW_MILES_QTY = src.DSPLY_LOW_MILES_QTY,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.ALTD_FEET_QTY = src.ALTD_FEET_QTY,
            tgt.DSPLY_RTN_DGRS_QTY = src.DSPLY_RTN_DGRS_QTY,
            tgt.LNGTD_NBR = src.LNGTD_NBR,
            tgt.LTD_NBR = src.LTD_NBR,
            tgt.LTD_LNGTD_DATA_SOURCE_CD = src.LTD_LNGTD_DATA_SOURCE_CD,
            tgt.PSTN_METHOD_CD = src.PSTN_METHOD_CD,
            tgt.OVRD_DSPLY_RTN_DGRS_QTY = src.OVRD_DSPLY_RTN_DGRS_QTY,
            tgt.ALTD_2_FEET_QTY = src.ALTD_2_FEET_QTY,
            tgt.DSPLY_RTN_2_DGRS_QTY = src.DSPLY_RTN_2_DGRS_QTY,
            tgt.LNGTD_2_NBR = src.LNGTD_2_NBR,
            tgt.LTD_2_NBR = src.LTD_2_NBR,
            tgt.LTD_LNGTD_2_DATA_SOURCE_CD = src.LTD_LNGTD_2_DATA_SOURCE_CD,
            tgt.PSTN_METHOD_2_CD = src.PSTN_METHOD_2_CD,
            tgt.OVRD_DSPLY_RTN_2_DGRS_QTY = src.OVRD_DSPLY_RTN_2_DGRS_QTY,
            tgt.ATHRZD_MVMNT_DRCTN_CD = src.ATHRZD_MVMNT_DRCTN_CD,
            tgt.CNCTN_ORNTN_CD = src.CNCTN_ORNTN_CD,
            tgt.DRCTN_RFRNC_MILE_CD = src.DRCTN_RFRNC_MILE_CD,
            tgt.OCS_DSPTCH_CD = src.OCS_DSPTCH_CD,
            tgt.OVRD_LOW_MILES_QTY = src.OVRD_LOW_MILES_QTY,
            tgt.INSPCT_FRQNCY_CD = src.INSPCT_FRQNCY_CD,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'RELOADED',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
        WHEN NOT MATCHED THEN INSERT (
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, FXPLA_TRACK_LCTN_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, EFCTV_TMS, DSPTCH_IND,
            PHYSCL_LCTN_IND, RFRNC_LOW_MILES_QTY, RPRTNG_POINT_IND, DATA_SOURCE_CD, FIXED_PLANT_ASSET_ID,
            ORGNL_DATA_SOURCE_CD, TRACK_SGMNT_ID, ACTUAL_HIGH_MILES_QTY, ACTUAL_LOW_MILES_QTY, ASSET_SQNC_CD,
            EXPIRY_TMS, DRCTN_FROM_TRACK_CD, DSPLY_HIGH_MILES_QTY, DSPLY_LOW_MILES_QTY, RFRNC_HIGH_MILES_QTY,
            ALTD_FEET_QTY, DSPLY_RTN_DGRS_QTY, LNGTD_NBR, LTD_NBR, LTD_LNGTD_DATA_SOURCE_CD,
            PSTN_METHOD_CD, OVRD_DSPLY_RTN_DGRS_QTY, ALTD_2_FEET_QTY, DSPLY_RTN_2_DGRS_QTY, LNGTD_2_NBR,
            LTD_2_NBR, LTD_LNGTD_2_DATA_SOURCE_CD, PSTN_METHOD_2_CD, OVRD_DSPLY_RTN_2_DGRS_QTY, ATHRZD_MVMNT_DRCTN_CD,
            CNCTN_ORNTN_CD, DRCTN_RFRNC_MILE_CD, OCS_DSPTCH_CD, OVRD_LOW_MILES_QTY, INSPCT_FRQNCY_CD,
            POST_START_NM, POST_START_DSTNC_MILES_QTY, NTWRK_SNAP_CD, PSTN_MODE_CD, SNW_OPERATION_TYPE,
            SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.GRPHC_OBJECT_VRSN_ID, src.VRSN_CREATE_TMS, src.VRSN_USER_ID, src.FIRST_GRPHC_OBJECT_VRSN_ID, src.PRVS_GRPHC_OBJECT_VRSN_ID,
            src.GRPHC_OBJECT_MDFCTN_CD, src.GRPHC_OBJECT_STATUS_CD, src.GRPHC_TRNSCT_ID, src.FXPLA_TRACK_LCTN_ID, src.RECORD_CREATE_TMS,
            src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID, src.EFCTV_TMS, src.DSPTCH_IND,
            src.PHYSCL_LCTN_IND, src.RFRNC_LOW_MILES_QTY, src.RPRTNG_POINT_IND, src.DATA_SOURCE_CD, src.FIXED_PLANT_ASSET_ID,
            src.ORGNL_DATA_SOURCE_CD, src.TRACK_SGMNT_ID, src.ACTUAL_HIGH_MILES_QTY, src.ACTUAL_LOW_MILES_QTY, src.ASSET_SQNC_CD,
            src.EXPIRY_TMS, src.DRCTN_FROM_TRACK_CD, src.DSPLY_HIGH_MILES_QTY, src.DSPLY_LOW_MILES_QTY, src.RFRNC_HIGH_MILES_QTY,
            src.ALTD_FEET_QTY, src.DSPLY_RTN_DGRS_QTY, src.LNGTD_NBR, src.LTD_NBR, src.LTD_LNGTD_DATA_SOURCE_CD,
            src.PSTN_METHOD_CD, src.OVRD_DSPLY_RTN_DGRS_QTY, src.ALTD_2_FEET_QTY, src.DSPLY_RTN_2_DGRS_QTY, src.LNGTD_2_NBR,
            src.LTD_2_NBR, src.LTD_LNGTD_2_DATA_SOURCE_CD, src.PSTN_METHOD_2_CD, src.OVRD_DSPLY_RTN_2_DGRS_QTY, src.ATHRZD_MVMNT_DRCTN_CD,
            src.CNCTN_ORNTN_CD, src.DRCTN_RFRNC_MILE_CD, src.OCS_DSPTCH_CD, src.OVRD_LOW_MILES_QTY, src.INSPCT_FRQNCY_CD,
            src.POST_START_NM, src.POST_START_DSTNC_MILES_QTY, src.NTWRK_SNAP_CD, src.PSTN_MODE_CD, src.SNW_OPERATION_TYPE,
            src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
        
        v_rows_merged := SQLROWCOUNT;
        RETURN 'RECOVERY_COMPLETE: Stream recreated, ' || v_rows_merged || ' rows merged. Batch: ' || v_batch_id;
    END IF;
    
    -- =========================================================================
    -- CHECK 2: Stage stream data into temp table (BEST PRACTICE - single read)
    -- =========================================================================
    CREATE OR REPLACE TEMPORARY TABLE _CDC_STAGING_TRKFCG_FXPLA_TRACK_LCTN_DN AS
    SELECT 
        GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
        GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, FXPLA_TRACK_LCTN_ID, RECORD_CREATE_TMS,
        RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, EFCTV_TMS, DSPTCH_IND,
        PHYSCL_LCTN_IND, RFRNC_LOW_MILES_QTY, RPRTNG_POINT_IND, DATA_SOURCE_CD, FIXED_PLANT_ASSET_ID,
        ORGNL_DATA_SOURCE_CD, TRACK_SGMNT_ID, ACTUAL_HIGH_MILES_QTY, ACTUAL_LOW_MILES_QTY, ASSET_SQNC_CD,
        EXPIRY_TMS, DRCTN_FROM_TRACK_CD, DSPLY_HIGH_MILES_QTY, DSPLY_LOW_MILES_QTY, RFRNC_HIGH_MILES_QTY,
        ALTD_FEET_QTY, DSPLY_RTN_DGRS_QTY, LNGTD_NBR, LTD_NBR, LTD_LNGTD_DATA_SOURCE_CD,
        PSTN_METHOD_CD, OVRD_DSPLY_RTN_DGRS_QTY, ALTD_2_FEET_QTY, DSPLY_RTN_2_DGRS_QTY, LNGTD_2_NBR,
        LTD_2_NBR, LTD_LNGTD_2_DATA_SOURCE_CD, PSTN_METHOD_2_CD, OVRD_DSPLY_RTN_2_DGRS_QTY, ATHRZD_MVMNT_DRCTN_CD,
        CNCTN_ORNTN_CD, DRCTN_RFRNC_MILE_CD, OCS_DSPTCH_CD, OVRD_LOW_MILES_QTY, INSPCT_FRQNCY_CD,
        POST_START_NM, POST_START_DSTNC_MILES_QTY, NTWRK_SNAP_CD, PSTN_MODE_CD, SNW_OPERATION_TYPE,
        SNW_LAST_REPLICATED,
        METADATA$ACTION AS CDC_ACTION,
        METADATA$ISUPDATE AS CDC_IS_UPDATE,
        METADATA$ROW_ID AS ROW_ID
    FROM D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE_HIST_STREAM;
    
    SELECT COUNT(*) INTO v_staging_count FROM _CDC_STAGING_TRKFCG_FXPLA_TRACK_LCTN_DN;
    
    IF (v_staging_count = 0) THEN
        DROP TABLE IF EXISTS _CDC_STAGING_TRKFCG_FXPLA_TRACK_LCTN_DN;
        RETURN 'NO_DATA: Stream has no changes to process at ' || CURRENT_TIMESTAMP()::VARCHAR;
    END IF;
    
    -- =========================================================================
    -- MAIN PROCESSING: MERGE CDC changes from staging into Data Preservation table
    -- =========================================================================
    MERGE INTO D_BRONZE.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN AS tgt
    USING (
        SELECT 
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, FXPLA_TRACK_LCTN_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, EFCTV_TMS, DSPTCH_IND,
            PHYSCL_LCTN_IND, RFRNC_LOW_MILES_QTY, RPRTNG_POINT_IND, DATA_SOURCE_CD, FIXED_PLANT_ASSET_ID,
            ORGNL_DATA_SOURCE_CD, TRACK_SGMNT_ID, ACTUAL_HIGH_MILES_QTY, ACTUAL_LOW_MILES_QTY, ASSET_SQNC_CD,
            EXPIRY_TMS, DRCTN_FROM_TRACK_CD, DSPLY_HIGH_MILES_QTY, DSPLY_LOW_MILES_QTY, RFRNC_HIGH_MILES_QTY,
            ALTD_FEET_QTY, DSPLY_RTN_DGRS_QTY, LNGTD_NBR, LTD_NBR, LTD_LNGTD_DATA_SOURCE_CD,
            PSTN_METHOD_CD, OVRD_DSPLY_RTN_DGRS_QTY, ALTD_2_FEET_QTY, DSPLY_RTN_2_DGRS_QTY, LNGTD_2_NBR,
            LTD_2_NBR, LTD_LNGTD_2_DATA_SOURCE_CD, PSTN_METHOD_2_CD, OVRD_DSPLY_RTN_2_DGRS_QTY, ATHRZD_MVMNT_DRCTN_CD,
            CNCTN_ORNTN_CD, DRCTN_RFRNC_MILE_CD, OCS_DSPTCH_CD, OVRD_LOW_MILES_QTY, INSPCT_FRQNCY_CD,
            POST_START_NM, POST_START_DSTNC_MILES_QTY, NTWRK_SNAP_CD, PSTN_MODE_CD, SNW_OPERATION_TYPE,
            SNW_LAST_REPLICATED,
            CDC_ACTION,
            CDC_IS_UPDATE,
            ROW_ID,
            :v_batch_id AS BATCH_ID
        FROM _CDC_STAGING_TRKFCG_FXPLA_TRACK_LCTN_DN
    ) AS src
    ON tgt.GRPHC_OBJECT_VRSN_ID = src.GRPHC_OBJECT_VRSN_ID
    
    -- UPDATE scenario (METADATA$ACTION='INSERT' AND METADATA$ISUPDATE=TRUE)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = TRUE THEN 
        UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.FXPLA_TRACK_LCTN_ID = src.FXPLA_TRACK_LCTN_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.DSPTCH_IND = src.DSPTCH_IND,
            tgt.PHYSCL_LCTN_IND = src.PHYSCL_LCTN_IND,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.RPRTNG_POINT_IND = src.RPRTNG_POINT_IND,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.FIXED_PLANT_ASSET_ID = src.FIXED_PLANT_ASSET_ID,
            tgt.ORGNL_DATA_SOURCE_CD = src.ORGNL_DATA_SOURCE_CD,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.ACTUAL_HIGH_MILES_QTY = src.ACTUAL_HIGH_MILES_QTY,
            tgt.ACTUAL_LOW_MILES_QTY = src.ACTUAL_LOW_MILES_QTY,
            tgt.ASSET_SQNC_CD = src.ASSET_SQNC_CD,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.DRCTN_FROM_TRACK_CD = src.DRCTN_FROM_TRACK_CD,
            tgt.DSPLY_HIGH_MILES_QTY = src.DSPLY_HIGH_MILES_QTY,
            tgt.DSPLY_LOW_MILES_QTY = src.DSPLY_LOW_MILES_QTY,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.ALTD_FEET_QTY = src.ALTD_FEET_QTY,
            tgt.DSPLY_RTN_DGRS_QTY = src.DSPLY_RTN_DGRS_QTY,
            tgt.LNGTD_NBR = src.LNGTD_NBR,
            tgt.LTD_NBR = src.LTD_NBR,
            tgt.LTD_LNGTD_DATA_SOURCE_CD = src.LTD_LNGTD_DATA_SOURCE_CD,
            tgt.PSTN_METHOD_CD = src.PSTN_METHOD_CD,
            tgt.OVRD_DSPLY_RTN_DGRS_QTY = src.OVRD_DSPLY_RTN_DGRS_QTY,
            tgt.ALTD_2_FEET_QTY = src.ALTD_2_FEET_QTY,
            tgt.DSPLY_RTN_2_DGRS_QTY = src.DSPLY_RTN_2_DGRS_QTY,
            tgt.LNGTD_2_NBR = src.LNGTD_2_NBR,
            tgt.LTD_2_NBR = src.LTD_2_NBR,
            tgt.LTD_LNGTD_2_DATA_SOURCE_CD = src.LTD_LNGTD_2_DATA_SOURCE_CD,
            tgt.PSTN_METHOD_2_CD = src.PSTN_METHOD_2_CD,
            tgt.OVRD_DSPLY_RTN_2_DGRS_QTY = src.OVRD_DSPLY_RTN_2_DGRS_QTY,
            tgt.ATHRZD_MVMNT_DRCTN_CD = src.ATHRZD_MVMNT_DRCTN_CD,
            tgt.CNCTN_ORNTN_CD = src.CNCTN_ORNTN_CD,
            tgt.DRCTN_RFRNC_MILE_CD = src.DRCTN_RFRNC_MILE_CD,
            tgt.OCS_DSPTCH_CD = src.OCS_DSPTCH_CD,
            tgt.OVRD_LOW_MILES_QTY = src.OVRD_LOW_MILES_QTY,
            tgt.INSPCT_FRQNCY_CD = src.INSPCT_FRQNCY_CD,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'UPDATE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- DELETE scenario (METADATA$ACTION='DELETE' AND METADATA$ISUPDATE=FALSE)
    WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.CDC_IS_UPDATE = FALSE THEN 
        UPDATE SET
            tgt.CDC_OPERATION = 'DELETE',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = TRUE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- RE-INSERT scenario (record exists but being re-inserted)
    WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.CDC_IS_UPDATE = FALSE THEN
        UPDATE SET
            tgt.VRSN_CREATE_TMS = src.VRSN_CREATE_TMS,
            tgt.VRSN_USER_ID = src.VRSN_USER_ID,
            tgt.FIRST_GRPHC_OBJECT_VRSN_ID = src.FIRST_GRPHC_OBJECT_VRSN_ID,
            tgt.PRVS_GRPHC_OBJECT_VRSN_ID = src.PRVS_GRPHC_OBJECT_VRSN_ID,
            tgt.GRPHC_OBJECT_MDFCTN_CD = src.GRPHC_OBJECT_MDFCTN_CD,
            tgt.GRPHC_OBJECT_STATUS_CD = src.GRPHC_OBJECT_STATUS_CD,
            tgt.GRPHC_TRNSCT_ID = src.GRPHC_TRNSCT_ID,
            tgt.FXPLA_TRACK_LCTN_ID = src.FXPLA_TRACK_LCTN_ID,
            tgt.RECORD_CREATE_TMS = src.RECORD_CREATE_TMS,
            tgt.RECORD_UPDATE_TMS = src.RECORD_UPDATE_TMS,
            tgt.CREATE_USER_ID = src.CREATE_USER_ID,
            tgt.UPDATE_USER_ID = src.UPDATE_USER_ID,
            tgt.EFCTV_TMS = src.EFCTV_TMS,
            tgt.DSPTCH_IND = src.DSPTCH_IND,
            tgt.PHYSCL_LCTN_IND = src.PHYSCL_LCTN_IND,
            tgt.RFRNC_LOW_MILES_QTY = src.RFRNC_LOW_MILES_QTY,
            tgt.RPRTNG_POINT_IND = src.RPRTNG_POINT_IND,
            tgt.DATA_SOURCE_CD = src.DATA_SOURCE_CD,
            tgt.FIXED_PLANT_ASSET_ID = src.FIXED_PLANT_ASSET_ID,
            tgt.ORGNL_DATA_SOURCE_CD = src.ORGNL_DATA_SOURCE_CD,
            tgt.TRACK_SGMNT_ID = src.TRACK_SGMNT_ID,
            tgt.ACTUAL_HIGH_MILES_QTY = src.ACTUAL_HIGH_MILES_QTY,
            tgt.ACTUAL_LOW_MILES_QTY = src.ACTUAL_LOW_MILES_QTY,
            tgt.ASSET_SQNC_CD = src.ASSET_SQNC_CD,
            tgt.EXPIRY_TMS = src.EXPIRY_TMS,
            tgt.DRCTN_FROM_TRACK_CD = src.DRCTN_FROM_TRACK_CD,
            tgt.DSPLY_HIGH_MILES_QTY = src.DSPLY_HIGH_MILES_QTY,
            tgt.DSPLY_LOW_MILES_QTY = src.DSPLY_LOW_MILES_QTY,
            tgt.RFRNC_HIGH_MILES_QTY = src.RFRNC_HIGH_MILES_QTY,
            tgt.ALTD_FEET_QTY = src.ALTD_FEET_QTY,
            tgt.DSPLY_RTN_DGRS_QTY = src.DSPLY_RTN_DGRS_QTY,
            tgt.LNGTD_NBR = src.LNGTD_NBR,
            tgt.LTD_NBR = src.LTD_NBR,
            tgt.LTD_LNGTD_DATA_SOURCE_CD = src.LTD_LNGTD_DATA_SOURCE_CD,
            tgt.PSTN_METHOD_CD = src.PSTN_METHOD_CD,
            tgt.OVRD_DSPLY_RTN_DGRS_QTY = src.OVRD_DSPLY_RTN_DGRS_QTY,
            tgt.ALTD_2_FEET_QTY = src.ALTD_2_FEET_QTY,
            tgt.DSPLY_RTN_2_DGRS_QTY = src.DSPLY_RTN_2_DGRS_QTY,
            tgt.LNGTD_2_NBR = src.LNGTD_2_NBR,
            tgt.LTD_2_NBR = src.LTD_2_NBR,
            tgt.LTD_LNGTD_2_DATA_SOURCE_CD = src.LTD_LNGTD_2_DATA_SOURCE_CD,
            tgt.PSTN_METHOD_2_CD = src.PSTN_METHOD_2_CD,
            tgt.OVRD_DSPLY_RTN_2_DGRS_QTY = src.OVRD_DSPLY_RTN_2_DGRS_QTY,
            tgt.ATHRZD_MVMNT_DRCTN_CD = src.ATHRZD_MVMNT_DRCTN_CD,
            tgt.CNCTN_ORNTN_CD = src.CNCTN_ORNTN_CD,
            tgt.DRCTN_RFRNC_MILE_CD = src.DRCTN_RFRNC_MILE_CD,
            tgt.OCS_DSPTCH_CD = src.OCS_DSPTCH_CD,
            tgt.OVRD_LOW_MILES_QTY = src.OVRD_LOW_MILES_QTY,
            tgt.INSPCT_FRQNCY_CD = src.INSPCT_FRQNCY_CD,
            tgt.POST_START_NM = src.POST_START_NM,
            tgt.POST_START_DSTNC_MILES_QTY = src.POST_START_DSTNC_MILES_QTY,
            tgt.NTWRK_SNAP_CD = src.NTWRK_SNAP_CD,
            tgt.PSTN_MODE_CD = src.PSTN_MODE_CD,
            tgt.SNW_OPERATION_TYPE = src.SNW_OPERATION_TYPE,
            tgt.SNW_LAST_REPLICATED = src.SNW_LAST_REPLICATED,
            tgt.CDC_OPERATION = 'INSERT',
            tgt.CDC_TIMESTAMP = CURRENT_TIMESTAMP(),
            tgt.IS_DELETED = FALSE,
            tgt.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            tgt.SOURCE_LOAD_BATCH_ID = src.BATCH_ID
    
    -- NEW INSERT scenario
    WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN 
        INSERT (
            GRPHC_OBJECT_VRSN_ID, VRSN_CREATE_TMS, VRSN_USER_ID, FIRST_GRPHC_OBJECT_VRSN_ID, PRVS_GRPHC_OBJECT_VRSN_ID,
            GRPHC_OBJECT_MDFCTN_CD, GRPHC_OBJECT_STATUS_CD, GRPHC_TRNSCT_ID, FXPLA_TRACK_LCTN_ID, RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS, CREATE_USER_ID, UPDATE_USER_ID, EFCTV_TMS, DSPTCH_IND,
            PHYSCL_LCTN_IND, RFRNC_LOW_MILES_QTY, RPRTNG_POINT_IND, DATA_SOURCE_CD, FIXED_PLANT_ASSET_ID,
            ORGNL_DATA_SOURCE_CD, TRACK_SGMNT_ID, ACTUAL_HIGH_MILES_QTY, ACTUAL_LOW_MILES_QTY, ASSET_SQNC_CD,
            EXPIRY_TMS, DRCTN_FROM_TRACK_CD, DSPLY_HIGH_MILES_QTY, DSPLY_LOW_MILES_QTY, RFRNC_HIGH_MILES_QTY,
            ALTD_FEET_QTY, DSPLY_RTN_DGRS_QTY, LNGTD_NBR, LTD_NBR, LTD_LNGTD_DATA_SOURCE_CD,
            PSTN_METHOD_CD, OVRD_DSPLY_RTN_DGRS_QTY, ALTD_2_FEET_QTY, DSPLY_RTN_2_DGRS_QTY, LNGTD_2_NBR,
            LTD_2_NBR, LTD_LNGTD_2_DATA_SOURCE_CD, PSTN_METHOD_2_CD, OVRD_DSPLY_RTN_2_DGRS_QTY, ATHRZD_MVMNT_DRCTN_CD,
            CNCTN_ORNTN_CD, DRCTN_RFRNC_MILE_CD, OCS_DSPTCH_CD, OVRD_LOW_MILES_QTY, INSPCT_FRQNCY_CD,
            POST_START_NM, POST_START_DSTNC_MILES_QTY, NTWRK_SNAP_CD, PSTN_MODE_CD, SNW_OPERATION_TYPE,
            SNW_LAST_REPLICATED,
            CDC_OPERATION, CDC_TIMESTAMP, IS_DELETED, RECORD_CREATED_AT, RECORD_UPDATED_AT, SOURCE_LOAD_BATCH_ID
        ) VALUES (
            src.GRPHC_OBJECT_VRSN_ID, src.VRSN_CREATE_TMS, src.VRSN_USER_ID, src.FIRST_GRPHC_OBJECT_VRSN_ID, src.PRVS_GRPHC_OBJECT_VRSN_ID,
            src.GRPHC_OBJECT_MDFCTN_CD, src.GRPHC_OBJECT_STATUS_CD, src.GRPHC_TRNSCT_ID, src.FXPLA_TRACK_LCTN_ID, src.RECORD_CREATE_TMS,
            src.RECORD_UPDATE_TMS, src.CREATE_USER_ID, src.UPDATE_USER_ID, src.EFCTV_TMS, src.DSPTCH_IND,
            src.PHYSCL_LCTN_IND, src.RFRNC_LOW_MILES_QTY, src.RPRTNG_POINT_IND, src.DATA_SOURCE_CD, src.FIXED_PLANT_ASSET_ID,
            src.ORGNL_DATA_SOURCE_CD, src.TRACK_SGMNT_ID, src.ACTUAL_HIGH_MILES_QTY, src.ACTUAL_LOW_MILES_QTY, src.ASSET_SQNC_CD,
            src.EXPIRY_TMS, src.DRCTN_FROM_TRACK_CD, src.DSPLY_HIGH_MILES_QTY, src.DSPLY_LOW_MILES_QTY, src.RFRNC_HIGH_MILES_QTY,
            src.ALTD_FEET_QTY, src.DSPLY_RTN_DGRS_QTY, src.LNGTD_NBR, src.LTD_NBR, src.LTD_LNGTD_DATA_SOURCE_CD,
            src.PSTN_METHOD_CD, src.OVRD_DSPLY_RTN_DGRS_QTY, src.ALTD_2_FEET_QTY, src.DSPLY_RTN_2_DGRS_QTY, src.LNGTD_2_NBR,
            src.LTD_2_NBR, src.LTD_LNGTD_2_DATA_SOURCE_CD, src.PSTN_METHOD_2_CD, src.OVRD_DSPLY_RTN_2_DGRS_QTY, src.ATHRZD_MVMNT_DRCTN_CD,
            src.CNCTN_ORNTN_CD, src.DRCTN_RFRNC_MILE_CD, src.OCS_DSPTCH_CD, src.OVRD_LOW_MILES_QTY, src.INSPCT_FRQNCY_CD,
            src.POST_START_NM, src.POST_START_DSTNC_MILES_QTY, src.NTWRK_SNAP_CD, src.PSTN_MODE_CD, src.SNW_OPERATION_TYPE,
            src.SNW_LAST_REPLICATED,
            'INSERT', CURRENT_TIMESTAMP(), FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), src.BATCH_ID
        );
    
    v_rows_merged := SQLROWCOUNT;
    DROP TABLE IF EXISTS _CDC_STAGING_TRKFCG_FXPLA_TRACK_LCTN_DN;
    
    RETURN 'SUCCESS: Processed ' || v_rows_merged || ' CDC changes. Batch: ' || v_batch_id;
    
EXCEPTION
    WHEN OTHER THEN
        DROP TABLE IF EXISTS _CDC_STAGING_TRKFCG_FXPLA_TRACK_LCTN_DN;
        RETURN 'ERROR: ' || SQLERRM || ' at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- =============================================================================
-- STEP 5: Create Scheduled Task to Process CDC Data
-- =============================================================================
CREATE OR REPLACE TASK D_RAW.SADB.TASK_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Task to process TRKFCG_FXPLA_TRACK_LCTN_DN_BASE CDC changes into data preservation table'
WHEN
    SYSTEM$STREAM_HAS_DATA('D_RAW.SADB.TRKFCG_FXPLA_TRACK_LCTN_DN_BASE_HIST_STREAM')
AS
    CALL D_RAW.SADB.SP_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN();

ALTER TASK D_RAW.SADB.TASK_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN RESUME;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SHOW TABLES LIKE 'TRKFCG_FXPLA_TRACK_LCTN_DN%' IN SCHEMA D_BRONZE.SADB;
-- SHOW STREAMS LIKE 'TRKFCG_FXPLA_TRACK_LCTN_DN%' IN SCHEMA D_RAW.SADB;
-- SHOW TASKS LIKE 'TASK_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN%' IN SCHEMA D_RAW.SADB;
-- CALL D_RAW.SADB.SP_PROCESS_TRKFCG_FXPLA_TRACK_LCTN_DN();
