/*
================================================================================
DATA PRESERVATION SCRIPT FOR D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE
================================================================================
Source Table : D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE
Target Table : D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT
Stream       : D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
Procedure    : D_RAW.SADB.SP_PROCESS_EQPMV_RFEQP_MVMNT_EVENT()
Task         : D_RAW.SADB.TASK_PROCESS_EQPMV_RFEQP_MVMNT_EVENT
Primary Key  : EVENT_ID (Single)
Total Columns: 91 source + 6 CDC metadata = 97
Filter       : SNW_OPERATION_OWNER NOT IN ('TSDPRG','EMEPRG') (exclude purged records)
================================================================================
VERSION      : v1.0
DATE         : 2026-03-13
CHANGES      : 
  - Added execution logging to D_BRONZE.MONITORING.CDC_EXECUTION_LOG
  - Staleness detection via SELECT COUNT(*) WHERE 1=0 pattern
================================================================================
*/

--------------------------------------------------------------------------------
-- SECTION 1: DROP EXISTING OBJECTS
--------------------------------------------------------------------------------
DROP STREAM IF EXISTS D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM;
DROP TABLE IF EXISTS D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT;
DROP TABLE IF EXISTS D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT_STAGING;
DROP PROCEDURE IF EXISTS D_BRONZE.SADB.SP_CDC_EQPMV_RFEQP_MVMNT_EVENT();
DROP TASK IF EXISTS D_BRONZE.SADB.TSK_CDC_EQPMV_RFEQP_MVMNT_EVENT;

--------------------------------------------------------------------------------
-- SECTION 2: CREATE TARGET TABLE
--------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT (
    EVENT_ID NUMBER(38,0) NOT NULL,
    EQPMT_EVENT_TYPE_ID NUMBER(38,0),
    SCAC_CD VARCHAR(16777216),
    FSAC_CD VARCHAR(16777216),
    TRSTN_VRSN_NBR NUMBER(38,0),
    RPT_SCAC_CD VARCHAR(16777216),
    RPT_FSAC_CD VARCHAR(16777216),
    RPT_TRSTN_VRSN_NBR NUMBER(38,0),
    AAR_CAR_TYPE_CD VARCHAR(16777216),
    AAR_CAR_TYPE_VRSN_NBR NUMBER(38,0),
    LGLNT_SLCTN_ID NUMBER(38,0),
    SLCTN_VRSN_NBR NUMBER(38,0),
    SLCTN_DATA_BASE_CN NUMBER(38,0),
    LCTN_DATA_BASE_CN NUMBER(38,0),
    LGLNT_LCTN_ID NUMBER(38,0),
    SPLC_CD VARCHAR(16777216),
    NTWRK_NODE_ID NUMBER(38,0),
    REPORT_TMS TIMESTAMP_NTZ(9),
    SQNC_NBR NUMBER(38,0),
    LOAD_EMPTY_IND VARCHAR(16777216),
    DRCTN_CD VARCHAR(16777216),
    SOURCE_SYSTEM_NM VARCHAR(16777216),
    LSOP_PRFL_NBR NUMBER(38,0),
    TITAN_NBR NUMBER(38,0),
    MARK_CD VARCHAR(16777216),
    EQPUN_NBR NUMBER(38,0),
    OPTRN_LEG_ID NUMBER(38,0),
    OPTRN_TMS TIMESTAMP_NTZ(9),
    TRAIN_PLAN_LEG_ID NUMBER(38,0),
    TRAIN_PLAN_EVENT_ID NUMBER(38,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(9),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(9),
    CREATE_USER_ID VARCHAR(16777216),
    UPDATE_USER_ID VARCHAR(16777216),
    REPORT_TIME_ZONE VARCHAR(16777216),
    ESTRN_STND_REPORT_TMS TIMESTAMP_NTZ(9),
    CONSIST_ORIGIN_NBR NUMBER(38,0),
    CONSIST_NBR NUMBER(38,0),
    COMMON_YARDS_SITE_CD VARCHAR(16777216),
    COMMON_YARDS_TRACK_NM VARCHAR(16777216),
    MILE_NBR NUMBER(38,0),
    SHRT_DSTR_NM VARCHAR(16777216),
    RUN_NBR_CD VARCHAR(16777216),
    CYCLE_SERIAL_NBR NUMBER(38,0),
    EQPUN_ORNTN_CD VARCHAR(16777216),
    INTRCH_MOVE_ATHRTY_CD VARCHAR(16777216),
    COMMON_YARDS_TAG_ID NUMBER(38,0),
    LGLNT_ID NUMBER(38,0),
    LGLNT_DATA_BASE_CN NUMBER(38,0),
    LGLNT_VRSN_NBR NUMBER(38,0),
    CSTMR_ENTITY_IDNTFR_CD VARCHAR(16777216),
    DMRG_TYPE_CD VARCHAR(16777216),
    EVENT_STATUS_CD VARCHAR(16777216),
    DMRG_RPRTNG_EXCPTN_CD VARCHAR(16777216),
    TRAIN_TYPE_CD VARCHAR(16777216),
    AAR_LBLTY_CNTNTY_MSG_CD VARCHAR(16777216),
    TRNSFR_OF_LBLTY_CD VARCHAR(16777216),
    CNST_DSTNTN_FSAC_CD VARCHAR(16777216),
    MTP_ROUTE_POINT_SQNC_NBR NUMBER(38,0),
    EQPMT_EVENT_REASON_CD VARCHAR(16777216),
    AEIRD_NBR NUMBER(38,0),
    OPTRN_EVENT_ID NUMBER(38,0),
    TRAVEL_DRCTN_CD VARCHAR(16777216),
    SWITCH_LIST_NBR NUMBER(38,0),
    TYES_TRAIN_ID NUMBER(38,0),
    LGLNT_LCTN_STN_RFRNC_ID NUMBER(38,0),
    INDSTR_RLTV_SQNC_NBR NUMBER(38,0),
    TRACK_FSAC_CD VARCHAR(16777216),
    TRACK_RFRNC_LCTN_ID NUMBER(38,0),
    TRACK_SHORT_ENGL_NM VARCHAR(16777216),
    LGLNT_VRSN_ID NUMBER(38,0),
    AAR_SHPR_RJCTN_CD VARCHAR(16777216),
    TRIP_END_IND VARCHAR(16777216),
    EQPMT_ID NUMBER(38,0),
    BLOCK_NM VARCHAR(16777216),
    CLASS_CD VARCHAR(16777216),
    CLASS_CODE_CTGRY_CD VARCHAR(16777216),
    INTRNL_OPRTNL_HNDLNG_CD VARCHAR(16777216),
    OPRTNL_HNDLNG_CD VARCHAR(16777216),
    INDSTR_NM VARCHAR(16777216),
    EXCTN_BLOCK_ID NUMBER(38,0),
    EXCTN_BLOCK_CTGRY_CD VARCHAR(16777216),
    EXCTN_BLOCK_ORIGIN_SCAC_CD VARCHAR(16777216),
    EXCTN_BLOCK_ORIGIN_FSAC_CD VARCHAR(16777216),
    EXCTN_BLOCK_DSTNTN_SCAC_CD VARCHAR(16777216),
    EXCTN_BLOCK_DSTNTN_FSAC_CD VARCHAR(16777216),
    EXCTN_PLND_BLOCK_NM VARCHAR(16777216),
    EXCTN_RPRTD_BLOCK_NM VARCHAR(16777216),
    SNW_OPERATION_TYPE VARCHAR(16777216),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ(9),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    RECORD_CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    RECORD_UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    SNW_OPERATION_OWNER VARCHAR(16777216),
    PRIMARY KEY (EVENT_ID)
);

--------------------------------------------------------------------------------
-- SECTION 3: CREATE STAGING TABLE
--------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT_STAGING (
    EVENT_ID NUMBER(38,0) NOT NULL,
    EQPMT_EVENT_TYPE_ID NUMBER(38,0),
    SCAC_CD VARCHAR(16777216),
    FSAC_CD VARCHAR(16777216),
    TRSTN_VRSN_NBR NUMBER(38,0),
    RPT_SCAC_CD VARCHAR(16777216),
    RPT_FSAC_CD VARCHAR(16777216),
    RPT_TRSTN_VRSN_NBR NUMBER(38,0),
    AAR_CAR_TYPE_CD VARCHAR(16777216),
    AAR_CAR_TYPE_VRSN_NBR NUMBER(38,0),
    LGLNT_SLCTN_ID NUMBER(38,0),
    SLCTN_VRSN_NBR NUMBER(38,0),
    SLCTN_DATA_BASE_CN NUMBER(38,0),
    LCTN_DATA_BASE_CN NUMBER(38,0),
    LGLNT_LCTN_ID NUMBER(38,0),
    SPLC_CD VARCHAR(16777216),
    NTWRK_NODE_ID NUMBER(38,0),
    REPORT_TMS TIMESTAMP_NTZ(9),
    SQNC_NBR NUMBER(38,0),
    LOAD_EMPTY_IND VARCHAR(16777216),
    DRCTN_CD VARCHAR(16777216),
    SOURCE_SYSTEM_NM VARCHAR(16777216),
    LSOP_PRFL_NBR NUMBER(38,0),
    TITAN_NBR NUMBER(38,0),
    MARK_CD VARCHAR(16777216),
    EQPUN_NBR NUMBER(38,0),
    OPTRN_LEG_ID NUMBER(38,0),
    OPTRN_TMS TIMESTAMP_NTZ(9),
    TRAIN_PLAN_LEG_ID NUMBER(38,0),
    TRAIN_PLAN_EVENT_ID NUMBER(38,0),
    RECORD_CREATE_TMS TIMESTAMP_NTZ(9),
    RECORD_UPDATE_TMS TIMESTAMP_NTZ(9),
    CREATE_USER_ID VARCHAR(16777216),
    UPDATE_USER_ID VARCHAR(16777216),
    REPORT_TIME_ZONE VARCHAR(16777216),
    ESTRN_STND_REPORT_TMS TIMESTAMP_NTZ(9),
    CONSIST_ORIGIN_NBR NUMBER(38,0),
    CONSIST_NBR NUMBER(38,0),
    COMMON_YARDS_SITE_CD VARCHAR(16777216),
    COMMON_YARDS_TRACK_NM VARCHAR(16777216),
    MILE_NBR NUMBER(38,0),
    SHRT_DSTR_NM VARCHAR(16777216),
    RUN_NBR_CD VARCHAR(16777216),
    CYCLE_SERIAL_NBR NUMBER(38,0),
    EQPUN_ORNTN_CD VARCHAR(16777216),
    INTRCH_MOVE_ATHRTY_CD VARCHAR(16777216),
    COMMON_YARDS_TAG_ID NUMBER(38,0),
    LGLNT_ID NUMBER(38,0),
    LGLNT_DATA_BASE_CN NUMBER(38,0),
    LGLNT_VRSN_NBR NUMBER(38,0),
    CSTMR_ENTITY_IDNTFR_CD VARCHAR(16777216),
    DMRG_TYPE_CD VARCHAR(16777216),
    EVENT_STATUS_CD VARCHAR(16777216),
    DMRG_RPRTNG_EXCPTN_CD VARCHAR(16777216),
    TRAIN_TYPE_CD VARCHAR(16777216),
    AAR_LBLTY_CNTNTY_MSG_CD VARCHAR(16777216),
    TRNSFR_OF_LBLTY_CD VARCHAR(16777216),
    CNST_DSTNTN_FSAC_CD VARCHAR(16777216),
    MTP_ROUTE_POINT_SQNC_NBR NUMBER(38,0),
    EQPMT_EVENT_REASON_CD VARCHAR(16777216),
    AEIRD_NBR NUMBER(38,0),
    OPTRN_EVENT_ID NUMBER(38,0),
    TRAVEL_DRCTN_CD VARCHAR(16777216),
    SWITCH_LIST_NBR NUMBER(38,0),
    TYES_TRAIN_ID NUMBER(38,0),
    LGLNT_LCTN_STN_RFRNC_ID NUMBER(38,0),
    INDSTR_RLTV_SQNC_NBR NUMBER(38,0),
    TRACK_FSAC_CD VARCHAR(16777216),
    TRACK_RFRNC_LCTN_ID NUMBER(38,0),
    TRACK_SHORT_ENGL_NM VARCHAR(16777216),
    LGLNT_VRSN_ID NUMBER(38,0),
    AAR_SHPR_RJCTN_CD VARCHAR(16777216),
    TRIP_END_IND VARCHAR(16777216),
    EQPMT_ID NUMBER(38,0),
    BLOCK_NM VARCHAR(16777216),
    CLASS_CD VARCHAR(16777216),
    CLASS_CODE_CTGRY_CD VARCHAR(16777216),
    INTRNL_OPRTNL_HNDLNG_CD VARCHAR(16777216),
    OPRTNL_HNDLNG_CD VARCHAR(16777216),
    INDSTR_NM VARCHAR(16777216),
    EXCTN_BLOCK_ID NUMBER(38,0),
    EXCTN_BLOCK_CTGRY_CD VARCHAR(16777216),
    EXCTN_BLOCK_ORIGIN_SCAC_CD VARCHAR(16777216),
    EXCTN_BLOCK_ORIGIN_FSAC_CD VARCHAR(16777216),
    EXCTN_BLOCK_DSTNTN_SCAC_CD VARCHAR(16777216),
    EXCTN_BLOCK_DSTNTN_FSAC_CD VARCHAR(16777216),
    EXCTN_PLND_BLOCK_NM VARCHAR(16777216),
    EXCTN_RPRTD_BLOCK_NM VARCHAR(16777216),
    SNW_OPERATION_TYPE VARCHAR(16777216),
    SNW_LAST_REPLICATED TIMESTAMP_NTZ(9),
    CDC_OPERATION VARCHAR(10),
    CDC_TIMESTAMP TIMESTAMP_NTZ(9),
    IS_DELETED BOOLEAN,
    SOURCE_LOAD_BATCH_ID VARCHAR(100),
    SNW_OPERATION_OWNER VARCHAR(16777216),
    PRIMARY KEY (EVENT_ID)
);

--------------------------------------------------------------------------------
-- SECTION 4: CREATE STREAM ON SOURCE TABLE
--------------------------------------------------------------------------------
CREATE STREAM IF NOT EXISTS D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
ON TABLE D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE
APPEND_ONLY = FALSE
SHOW_INITIAL_ROWS = TRUE;

--------------------------------------------------------------------------------
-- SECTION 5: CREATE CDC STORED PROCEDURE
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE D_BRONZE.SADB.SP_CDC_EQPMV_RFEQP_MVMNT_EVENT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
DECLARE
    v_batch_id VARCHAR;
    v_stream_stale BOOLEAN DEFAULT FALSE;
    v_staging_count NUMBER DEFAULT 0;
    v_rows_merged NUMBER DEFAULT 0;
    v_rows_inserted NUMBER DEFAULT 0;
    v_rows_updated NUMBER DEFAULT 0;
    v_rows_deleted NUMBER DEFAULT 0;
    v_result VARCHAR;
    v_error_msg VARCHAR;
    v_start_time TIMESTAMP_NTZ;
    v_end_time TIMESTAMP_NTZ;
    v_execution_status VARCHAR DEFAULT 'SUCCESS';
BEGIN
    v_batch_id := 'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS');
    v_start_time := CURRENT_TIMESTAMP();

    ----------------------------------------------------------------------------
    -- STEP 1: STALENESS DETECTION (SELECT COUNT WHERE 1=0 pattern)
    ----------------------------------------------------------------------------
    BEGIN
        SELECT COUNT(*) INTO v_staging_count
        FROM D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
        WHERE 1=0;
        
        v_stream_stale := FALSE;
    EXCEPTION
        WHEN OTHER THEN
            v_stream_stale := TRUE;
            v_error_msg := SQLERRM;
    END;

    IF (v_stream_stale) THEN
        v_execution_status := 'FAILED';
        v_end_time := CURRENT_TIMESTAMP();
        
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
            BATCH_ID, TABLE_NAME, EXECUTION_STATUS, ERROR_MESSAGE,
            ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED,
            EXECUTION_START_TIME, EXECUTION_END_TIME
        ) VALUES (
            v_batch_id, 'EQPMV_RFEQP_MVMNT_EVENT', v_execution_status, v_error_msg,
            0, 0, 0,
            v_start_time, v_end_time
        );
        
        RETURN 'FAILED: ' || v_error_msg;
    END IF;

    ----------------------------------------------------------------------------
    -- STEP 2: TRUNCATE AND LOAD STAGING TABLE
    ----------------------------------------------------------------------------
    TRUNCATE TABLE D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT_STAGING;

    INSERT INTO D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT_STAGING (
        EVENT_ID,
        EQPMT_EVENT_TYPE_ID,
        SCAC_CD,
        FSAC_CD,
        TRSTN_VRSN_NBR,
        RPT_SCAC_CD,
        RPT_FSAC_CD,
        RPT_TRSTN_VRSN_NBR,
        AAR_CAR_TYPE_CD,
        AAR_CAR_TYPE_VRSN_NBR,
        LGLNT_SLCTN_ID,
        SLCTN_VRSN_NBR,
        SLCTN_DATA_BASE_CN,
        LCTN_DATA_BASE_CN,
        LGLNT_LCTN_ID,
        SPLC_CD,
        NTWRK_NODE_ID,
        REPORT_TMS,
        SQNC_NBR,
        LOAD_EMPTY_IND,
        DRCTN_CD,
        SOURCE_SYSTEM_NM,
        LSOP_PRFL_NBR,
        TITAN_NBR,
        MARK_CD,
        EQPUN_NBR,
        OPTRN_LEG_ID,
        OPTRN_TMS,
        TRAIN_PLAN_LEG_ID,
        TRAIN_PLAN_EVENT_ID,
        RECORD_CREATE_TMS,
        RECORD_UPDATE_TMS,
        CREATE_USER_ID,
        UPDATE_USER_ID,
        REPORT_TIME_ZONE,
        ESTRN_STND_REPORT_TMS,
        CONSIST_ORIGIN_NBR,
        CONSIST_NBR,
        COMMON_YARDS_SITE_CD,
        COMMON_YARDS_TRACK_NM,
        MILE_NBR,
        SHRT_DSTR_NM,
        RUN_NBR_CD,
        CYCLE_SERIAL_NBR,
        EQPUN_ORNTN_CD,
        INTRCH_MOVE_ATHRTY_CD,
        COMMON_YARDS_TAG_ID,
        LGLNT_ID,
        LGLNT_DATA_BASE_CN,
        LGLNT_VRSN_NBR,
        CSTMR_ENTITY_IDNTFR_CD,
        DMRG_TYPE_CD,
        EVENT_STATUS_CD,
        DMRG_RPRTNG_EXCPTN_CD,
        TRAIN_TYPE_CD,
        AAR_LBLTY_CNTNTY_MSG_CD,
        TRNSFR_OF_LBLTY_CD,
        CNST_DSTNTN_FSAC_CD,
        MTP_ROUTE_POINT_SQNC_NBR,
        EQPMT_EVENT_REASON_CD,
        AEIRD_NBR,
        OPTRN_EVENT_ID,
        TRAVEL_DRCTN_CD,
        SWITCH_LIST_NBR,
        TYES_TRAIN_ID,
        LGLNT_LCTN_STN_RFRNC_ID,
        INDSTR_RLTV_SQNC_NBR,
        TRACK_FSAC_CD,
        TRACK_RFRNC_LCTN_ID,
        TRACK_SHORT_ENGL_NM,
        LGLNT_VRSN_ID,
        AAR_SHPR_RJCTN_CD,
        TRIP_END_IND,
        EQPMT_ID,
        BLOCK_NM,
        CLASS_CD,
        CLASS_CODE_CTGRY_CD,
        INTRNL_OPRTNL_HNDLNG_CD,
        OPRTNL_HNDLNG_CD,
        INDSTR_NM,
        EXCTN_BLOCK_ID,
        EXCTN_BLOCK_CTGRY_CD,
        EXCTN_BLOCK_ORIGIN_SCAC_CD,
        EXCTN_BLOCK_ORIGIN_FSAC_CD,
        EXCTN_BLOCK_DSTNTN_SCAC_CD,
        EXCTN_BLOCK_DSTNTN_FSAC_CD,
        EXCTN_PLND_BLOCK_NM,
        EXCTN_RPRTD_BLOCK_NM,
        SNW_OPERATION_TYPE,
        SNW_LAST_REPLICATED,
        CDC_OPERATION,
        CDC_TIMESTAMP,
        IS_DELETED,
        SOURCE_LOAD_BATCH_ID,
        SNW_OPERATION_OWNER
    )
    SELECT
        EVENT_ID,
        EQPMT_EVENT_TYPE_ID,
        SCAC_CD,
        FSAC_CD,
        TRSTN_VRSN_NBR,
        RPT_SCAC_CD,
        RPT_FSAC_CD,
        RPT_TRSTN_VRSN_NBR,
        AAR_CAR_TYPE_CD,
        AAR_CAR_TYPE_VRSN_NBR,
        LGLNT_SLCTN_ID,
        SLCTN_VRSN_NBR,
        SLCTN_DATA_BASE_CN,
        LCTN_DATA_BASE_CN,
        LGLNT_LCTN_ID,
        SPLC_CD,
        NTWRK_NODE_ID,
        REPORT_TMS,
        SQNC_NBR,
        LOAD_EMPTY_IND,
        DRCTN_CD,
        SOURCE_SYSTEM_NM,
        LSOP_PRFL_NBR,
        TITAN_NBR,
        MARK_CD,
        EQPUN_NBR,
        OPTRN_LEG_ID,
        OPTRN_TMS,
        TRAIN_PLAN_LEG_ID,
        TRAIN_PLAN_EVENT_ID,
        RECORD_CREATE_TMS,
        RECORD_UPDATE_TMS,
        CREATE_USER_ID,
        UPDATE_USER_ID,
        REPORT_TIME_ZONE,
        ESTRN_STND_REPORT_TMS,
        CONSIST_ORIGIN_NBR,
        CONSIST_NBR,
        COMMON_YARDS_SITE_CD,
        COMMON_YARDS_TRACK_NM,
        MILE_NBR,
        SHRT_DSTR_NM,
        RUN_NBR_CD,
        CYCLE_SERIAL_NBR,
        EQPUN_ORNTN_CD,
        INTRCH_MOVE_ATHRTY_CD,
        COMMON_YARDS_TAG_ID,
        LGLNT_ID,
        LGLNT_DATA_BASE_CN,
        LGLNT_VRSN_NBR,
        CSTMR_ENTITY_IDNTFR_CD,
        DMRG_TYPE_CD,
        EVENT_STATUS_CD,
        DMRG_RPRTNG_EXCPTN_CD,
        TRAIN_TYPE_CD,
        AAR_LBLTY_CNTNTY_MSG_CD,
        TRNSFR_OF_LBLTY_CD,
        CNST_DSTNTN_FSAC_CD,
        MTP_ROUTE_POINT_SQNC_NBR,
        EQPMT_EVENT_REASON_CD,
        AEIRD_NBR,
        OPTRN_EVENT_ID,
        TRAVEL_DRCTN_CD,
        SWITCH_LIST_NBR,
        TYES_TRAIN_ID,
        LGLNT_LCTN_STN_RFRNC_ID,
        INDSTR_RLTV_SQNC_NBR,
        TRACK_FSAC_CD,
        TRACK_RFRNC_LCTN_ID,
        TRACK_SHORT_ENGL_NM,
        LGLNT_VRSN_ID,
        AAR_SHPR_RJCTN_CD,
        TRIP_END_IND,
        EQPMT_ID,
        BLOCK_NM,
        CLASS_CD,
        CLASS_CODE_CTGRY_CD,
        INTRNL_OPRTNL_HNDLNG_CD,
        OPRTNL_HNDLNG_CD,
        INDSTR_NM,
        EXCTN_BLOCK_ID,
        EXCTN_BLOCK_CTGRY_CD,
        EXCTN_BLOCK_ORIGIN_SCAC_CD,
        EXCTN_BLOCK_ORIGIN_FSAC_CD,
        EXCTN_BLOCK_DSTNTN_SCAC_CD,
        EXCTN_BLOCK_DSTNTN_FSAC_CD,
        EXCTN_PLND_BLOCK_NM,
        EXCTN_RPRTD_BLOCK_NM,
        SNW_OPERATION_TYPE,
        SNW_LAST_REPLICATED,
        CASE
            WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'INSERT'
            WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE THEN 'UPDATE'
            WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'DELETE'
            WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = TRUE THEN 'UPDATE'
            ELSE 'UNKNOWN'
        END AS CDC_OPERATION,
        CURRENT_TIMESTAMP() AS CDC_TIMESTAMP,
        CASE
            WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN TRUE
            ELSE FALSE
        END AS IS_DELETED,
        :v_batch_id AS SOURCE_LOAD_BATCH_ID,
        SNW_OPERATION_OWNER
    FROM D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
    WHERE SNW_OPERATION_OWNER NOT IN ('TSDPRG', 'EMEPRG');

    SELECT COUNT(*) INTO v_staging_count FROM D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT_STAGING;

    IF (v_staging_count = 0) THEN
        v_end_time := CURRENT_TIMESTAMP();
        
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
            BATCH_ID, TABLE_NAME, EXECUTION_STATUS, ERROR_MESSAGE,
            ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED,
            EXECUTION_START_TIME, EXECUTION_END_TIME
        ) VALUES (
            v_batch_id, 'EQPMV_RFEQP_MVMNT_EVENT', 'SUCCESS', 'No changes to process',
            0, 0, 0,
            v_start_time, v_end_time
        );
        
        RETURN 'No changes to process';
    END IF;

    ----------------------------------------------------------------------------
    -- STEP 3: MERGE STAGING INTO TARGET
    ----------------------------------------------------------------------------
    MERGE INTO D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT AS TGT
    USING (
        SELECT * FROM D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT_STAGING
        QUALIFY ROW_NUMBER() OVER (PARTITION BY EVENT_ID ORDER BY CDC_TIMESTAMP DESC) = 1
    ) AS STG
    ON TGT.EVENT_ID = STG.EVENT_ID
    WHEN MATCHED AND STG.IS_DELETED = TRUE THEN
        UPDATE SET
            TGT.IS_DELETED = TRUE,
            TGT.CDC_OPERATION = 'DELETE',
            TGT.CDC_TIMESTAMP = STG.CDC_TIMESTAMP,
            TGT.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            TGT.SOURCE_LOAD_BATCH_ID = STG.SOURCE_LOAD_BATCH_ID
    WHEN MATCHED AND STG.IS_DELETED = FALSE THEN
        UPDATE SET
            TGT.EQPMT_EVENT_TYPE_ID = STG.EQPMT_EVENT_TYPE_ID,
            TGT.SCAC_CD = STG.SCAC_CD,
            TGT.FSAC_CD = STG.FSAC_CD,
            TGT.TRSTN_VRSN_NBR = STG.TRSTN_VRSN_NBR,
            TGT.RPT_SCAC_CD = STG.RPT_SCAC_CD,
            TGT.RPT_FSAC_CD = STG.RPT_FSAC_CD,
            TGT.RPT_TRSTN_VRSN_NBR = STG.RPT_TRSTN_VRSN_NBR,
            TGT.AAR_CAR_TYPE_CD = STG.AAR_CAR_TYPE_CD,
            TGT.AAR_CAR_TYPE_VRSN_NBR = STG.AAR_CAR_TYPE_VRSN_NBR,
            TGT.LGLNT_SLCTN_ID = STG.LGLNT_SLCTN_ID,
            TGT.SLCTN_VRSN_NBR = STG.SLCTN_VRSN_NBR,
            TGT.SLCTN_DATA_BASE_CN = STG.SLCTN_DATA_BASE_CN,
            TGT.LCTN_DATA_BASE_CN = STG.LCTN_DATA_BASE_CN,
            TGT.LGLNT_LCTN_ID = STG.LGLNT_LCTN_ID,
            TGT.SPLC_CD = STG.SPLC_CD,
            TGT.NTWRK_NODE_ID = STG.NTWRK_NODE_ID,
            TGT.REPORT_TMS = STG.REPORT_TMS,
            TGT.SQNC_NBR = STG.SQNC_NBR,
            TGT.LOAD_EMPTY_IND = STG.LOAD_EMPTY_IND,
            TGT.DRCTN_CD = STG.DRCTN_CD,
            TGT.SOURCE_SYSTEM_NM = STG.SOURCE_SYSTEM_NM,
            TGT.LSOP_PRFL_NBR = STG.LSOP_PRFL_NBR,
            TGT.TITAN_NBR = STG.TITAN_NBR,
            TGT.MARK_CD = STG.MARK_CD,
            TGT.EQPUN_NBR = STG.EQPUN_NBR,
            TGT.OPTRN_LEG_ID = STG.OPTRN_LEG_ID,
            TGT.OPTRN_TMS = STG.OPTRN_TMS,
            TGT.TRAIN_PLAN_LEG_ID = STG.TRAIN_PLAN_LEG_ID,
            TGT.TRAIN_PLAN_EVENT_ID = STG.TRAIN_PLAN_EVENT_ID,
            TGT.RECORD_CREATE_TMS = STG.RECORD_CREATE_TMS,
            TGT.RECORD_UPDATE_TMS = STG.RECORD_UPDATE_TMS,
            TGT.CREATE_USER_ID = STG.CREATE_USER_ID,
            TGT.UPDATE_USER_ID = STG.UPDATE_USER_ID,
            TGT.REPORT_TIME_ZONE = STG.REPORT_TIME_ZONE,
            TGT.ESTRN_STND_REPORT_TMS = STG.ESTRN_STND_REPORT_TMS,
            TGT.CONSIST_ORIGIN_NBR = STG.CONSIST_ORIGIN_NBR,
            TGT.CONSIST_NBR = STG.CONSIST_NBR,
            TGT.COMMON_YARDS_SITE_CD = STG.COMMON_YARDS_SITE_CD,
            TGT.COMMON_YARDS_TRACK_NM = STG.COMMON_YARDS_TRACK_NM,
            TGT.MILE_NBR = STG.MILE_NBR,
            TGT.SHRT_DSTR_NM = STG.SHRT_DSTR_NM,
            TGT.RUN_NBR_CD = STG.RUN_NBR_CD,
            TGT.CYCLE_SERIAL_NBR = STG.CYCLE_SERIAL_NBR,
            TGT.EQPUN_ORNTN_CD = STG.EQPUN_ORNTN_CD,
            TGT.INTRCH_MOVE_ATHRTY_CD = STG.INTRCH_MOVE_ATHRTY_CD,
            TGT.COMMON_YARDS_TAG_ID = STG.COMMON_YARDS_TAG_ID,
            TGT.LGLNT_ID = STG.LGLNT_ID,
            TGT.LGLNT_DATA_BASE_CN = STG.LGLNT_DATA_BASE_CN,
            TGT.LGLNT_VRSN_NBR = STG.LGLNT_VRSN_NBR,
            TGT.CSTMR_ENTITY_IDNTFR_CD = STG.CSTMR_ENTITY_IDNTFR_CD,
            TGT.DMRG_TYPE_CD = STG.DMRG_TYPE_CD,
            TGT.EVENT_STATUS_CD = STG.EVENT_STATUS_CD,
            TGT.DMRG_RPRTNG_EXCPTN_CD = STG.DMRG_RPRTNG_EXCPTN_CD,
            TGT.TRAIN_TYPE_CD = STG.TRAIN_TYPE_CD,
            TGT.AAR_LBLTY_CNTNTY_MSG_CD = STG.AAR_LBLTY_CNTNTY_MSG_CD,
            TGT.TRNSFR_OF_LBLTY_CD = STG.TRNSFR_OF_LBLTY_CD,
            TGT.CNST_DSTNTN_FSAC_CD = STG.CNST_DSTNTN_FSAC_CD,
            TGT.MTP_ROUTE_POINT_SQNC_NBR = STG.MTP_ROUTE_POINT_SQNC_NBR,
            TGT.EQPMT_EVENT_REASON_CD = STG.EQPMT_EVENT_REASON_CD,
            TGT.AEIRD_NBR = STG.AEIRD_NBR,
            TGT.OPTRN_EVENT_ID = STG.OPTRN_EVENT_ID,
            TGT.TRAVEL_DRCTN_CD = STG.TRAVEL_DRCTN_CD,
            TGT.SWITCH_LIST_NBR = STG.SWITCH_LIST_NBR,
            TGT.TYES_TRAIN_ID = STG.TYES_TRAIN_ID,
            TGT.LGLNT_LCTN_STN_RFRNC_ID = STG.LGLNT_LCTN_STN_RFRNC_ID,
            TGT.INDSTR_RLTV_SQNC_NBR = STG.INDSTR_RLTV_SQNC_NBR,
            TGT.TRACK_FSAC_CD = STG.TRACK_FSAC_CD,
            TGT.TRACK_RFRNC_LCTN_ID = STG.TRACK_RFRNC_LCTN_ID,
            TGT.TRACK_SHORT_ENGL_NM = STG.TRACK_SHORT_ENGL_NM,
            TGT.LGLNT_VRSN_ID = STG.LGLNT_VRSN_ID,
            TGT.AAR_SHPR_RJCTN_CD = STG.AAR_SHPR_RJCTN_CD,
            TGT.TRIP_END_IND = STG.TRIP_END_IND,
            TGT.EQPMT_ID = STG.EQPMT_ID,
            TGT.BLOCK_NM = STG.BLOCK_NM,
            TGT.CLASS_CD = STG.CLASS_CD,
            TGT.CLASS_CODE_CTGRY_CD = STG.CLASS_CODE_CTGRY_CD,
            TGT.INTRNL_OPRTNL_HNDLNG_CD = STG.INTRNL_OPRTNL_HNDLNG_CD,
            TGT.OPRTNL_HNDLNG_CD = STG.OPRTNL_HNDLNG_CD,
            TGT.INDSTR_NM = STG.INDSTR_NM,
            TGT.EXCTN_BLOCK_ID = STG.EXCTN_BLOCK_ID,
            TGT.EXCTN_BLOCK_CTGRY_CD = STG.EXCTN_BLOCK_CTGRY_CD,
            TGT.EXCTN_BLOCK_ORIGIN_SCAC_CD = STG.EXCTN_BLOCK_ORIGIN_SCAC_CD,
            TGT.EXCTN_BLOCK_ORIGIN_FSAC_CD = STG.EXCTN_BLOCK_ORIGIN_FSAC_CD,
            TGT.EXCTN_BLOCK_DSTNTN_SCAC_CD = STG.EXCTN_BLOCK_DSTNTN_SCAC_CD,
            TGT.EXCTN_BLOCK_DSTNTN_FSAC_CD = STG.EXCTN_BLOCK_DSTNTN_FSAC_CD,
            TGT.EXCTN_PLND_BLOCK_NM = STG.EXCTN_PLND_BLOCK_NM,
            TGT.EXCTN_RPRTD_BLOCK_NM = STG.EXCTN_RPRTD_BLOCK_NM,
            TGT.SNW_OPERATION_TYPE = STG.SNW_OPERATION_TYPE,
            TGT.SNW_LAST_REPLICATED = STG.SNW_LAST_REPLICATED,
            TGT.SNW_OPERATION_OWNER = STG.SNW_OPERATION_OWNER,
            TGT.IS_DELETED = FALSE,
            TGT.CDC_OPERATION = STG.CDC_OPERATION,
            TGT.CDC_TIMESTAMP = STG.CDC_TIMESTAMP,
            TGT.RECORD_UPDATED_AT = CURRENT_TIMESTAMP(),
            TGT.SOURCE_LOAD_BATCH_ID = STG.SOURCE_LOAD_BATCH_ID
    WHEN NOT MATCHED AND STG.IS_DELETED = FALSE THEN
        INSERT (
            EVENT_ID,
            EQPMT_EVENT_TYPE_ID,
            SCAC_CD,
            FSAC_CD,
            TRSTN_VRSN_NBR,
            RPT_SCAC_CD,
            RPT_FSAC_CD,
            RPT_TRSTN_VRSN_NBR,
            AAR_CAR_TYPE_CD,
            AAR_CAR_TYPE_VRSN_NBR,
            LGLNT_SLCTN_ID,
            SLCTN_VRSN_NBR,
            SLCTN_DATA_BASE_CN,
            LCTN_DATA_BASE_CN,
            LGLNT_LCTN_ID,
            SPLC_CD,
            NTWRK_NODE_ID,
            REPORT_TMS,
            SQNC_NBR,
            LOAD_EMPTY_IND,
            DRCTN_CD,
            SOURCE_SYSTEM_NM,
            LSOP_PRFL_NBR,
            TITAN_NBR,
            MARK_CD,
            EQPUN_NBR,
            OPTRN_LEG_ID,
            OPTRN_TMS,
            TRAIN_PLAN_LEG_ID,
            TRAIN_PLAN_EVENT_ID,
            RECORD_CREATE_TMS,
            RECORD_UPDATE_TMS,
            CREATE_USER_ID,
            UPDATE_USER_ID,
            REPORT_TIME_ZONE,
            ESTRN_STND_REPORT_TMS,
            CONSIST_ORIGIN_NBR,
            CONSIST_NBR,
            COMMON_YARDS_SITE_CD,
            COMMON_YARDS_TRACK_NM,
            MILE_NBR,
            SHRT_DSTR_NM,
            RUN_NBR_CD,
            CYCLE_SERIAL_NBR,
            EQPUN_ORNTN_CD,
            INTRCH_MOVE_ATHRTY_CD,
            COMMON_YARDS_TAG_ID,
            LGLNT_ID,
            LGLNT_DATA_BASE_CN,
            LGLNT_VRSN_NBR,
            CSTMR_ENTITY_IDNTFR_CD,
            DMRG_TYPE_CD,
            EVENT_STATUS_CD,
            DMRG_RPRTNG_EXCPTN_CD,
            TRAIN_TYPE_CD,
            AAR_LBLTY_CNTNTY_MSG_CD,
            TRNSFR_OF_LBLTY_CD,
            CNST_DSTNTN_FSAC_CD,
            MTP_ROUTE_POINT_SQNC_NBR,
            EQPMT_EVENT_REASON_CD,
            AEIRD_NBR,
            OPTRN_EVENT_ID,
            TRAVEL_DRCTN_CD,
            SWITCH_LIST_NBR,
            TYES_TRAIN_ID,
            LGLNT_LCTN_STN_RFRNC_ID,
            INDSTR_RLTV_SQNC_NBR,
            TRACK_FSAC_CD,
            TRACK_RFRNC_LCTN_ID,
            TRACK_SHORT_ENGL_NM,
            LGLNT_VRSN_ID,
            AAR_SHPR_RJCTN_CD,
            TRIP_END_IND,
            EQPMT_ID,
            BLOCK_NM,
            CLASS_CD,
            CLASS_CODE_CTGRY_CD,
            INTRNL_OPRTNL_HNDLNG_CD,
            OPRTNL_HNDLNG_CD,
            INDSTR_NM,
            EXCTN_BLOCK_ID,
            EXCTN_BLOCK_CTGRY_CD,
            EXCTN_BLOCK_ORIGIN_SCAC_CD,
            EXCTN_BLOCK_ORIGIN_FSAC_CD,
            EXCTN_BLOCK_DSTNTN_SCAC_CD,
            EXCTN_BLOCK_DSTNTN_FSAC_CD,
            EXCTN_PLND_BLOCK_NM,
            EXCTN_RPRTD_BLOCK_NM,
            SNW_OPERATION_TYPE,
            SNW_LAST_REPLICATED,
            CDC_OPERATION,
            CDC_TIMESTAMP,
            IS_DELETED,
            RECORD_CREATED_AT,
            RECORD_UPDATED_AT,
            SOURCE_LOAD_BATCH_ID,
            SNW_OPERATION_OWNER
        )
        VALUES (
            STG.EVENT_ID,
            STG.EQPMT_EVENT_TYPE_ID,
            STG.SCAC_CD,
            STG.FSAC_CD,
            STG.TRSTN_VRSN_NBR,
            STG.RPT_SCAC_CD,
            STG.RPT_FSAC_CD,
            STG.RPT_TRSTN_VRSN_NBR,
            STG.AAR_CAR_TYPE_CD,
            STG.AAR_CAR_TYPE_VRSN_NBR,
            STG.LGLNT_SLCTN_ID,
            STG.SLCTN_VRSN_NBR,
            STG.SLCTN_DATA_BASE_CN,
            STG.LCTN_DATA_BASE_CN,
            STG.LGLNT_LCTN_ID,
            STG.SPLC_CD,
            STG.NTWRK_NODE_ID,
            STG.REPORT_TMS,
            STG.SQNC_NBR,
            STG.LOAD_EMPTY_IND,
            STG.DRCTN_CD,
            STG.SOURCE_SYSTEM_NM,
            STG.LSOP_PRFL_NBR,
            STG.TITAN_NBR,
            STG.MARK_CD,
            STG.EQPUN_NBR,
            STG.OPTRN_LEG_ID,
            STG.OPTRN_TMS,
            STG.TRAIN_PLAN_LEG_ID,
            STG.TRAIN_PLAN_EVENT_ID,
            STG.RECORD_CREATE_TMS,
            STG.RECORD_UPDATE_TMS,
            STG.CREATE_USER_ID,
            STG.UPDATE_USER_ID,
            STG.REPORT_TIME_ZONE,
            STG.ESTRN_STND_REPORT_TMS,
            STG.CONSIST_ORIGIN_NBR,
            STG.CONSIST_NBR,
            STG.COMMON_YARDS_SITE_CD,
            STG.COMMON_YARDS_TRACK_NM,
            STG.MILE_NBR,
            STG.SHRT_DSTR_NM,
            STG.RUN_NBR_CD,
            STG.CYCLE_SERIAL_NBR,
            STG.EQPUN_ORNTN_CD,
            STG.INTRCH_MOVE_ATHRTY_CD,
            STG.COMMON_YARDS_TAG_ID,
            STG.LGLNT_ID,
            STG.LGLNT_DATA_BASE_CN,
            STG.LGLNT_VRSN_NBR,
            STG.CSTMR_ENTITY_IDNTFR_CD,
            STG.DMRG_TYPE_CD,
            STG.EVENT_STATUS_CD,
            STG.DMRG_RPRTNG_EXCPTN_CD,
            STG.TRAIN_TYPE_CD,
            STG.AAR_LBLTY_CNTNTY_MSG_CD,
            STG.TRNSFR_OF_LBLTY_CD,
            STG.CNST_DSTNTN_FSAC_CD,
            STG.MTP_ROUTE_POINT_SQNC_NBR,
            STG.EQPMT_EVENT_REASON_CD,
            STG.AEIRD_NBR,
            STG.OPTRN_EVENT_ID,
            STG.TRAVEL_DRCTN_CD,
            STG.SWITCH_LIST_NBR,
            STG.TYES_TRAIN_ID,
            STG.LGLNT_LCTN_STN_RFRNC_ID,
            STG.INDSTR_RLTV_SQNC_NBR,
            STG.TRACK_FSAC_CD,
            STG.TRACK_RFRNC_LCTN_ID,
            STG.TRACK_SHORT_ENGL_NM,
            STG.LGLNT_VRSN_ID,
            STG.AAR_SHPR_RJCTN_CD,
            STG.TRIP_END_IND,
            STG.EQPMT_ID,
            STG.BLOCK_NM,
            STG.CLASS_CD,
            STG.CLASS_CODE_CTGRY_CD,
            STG.INTRNL_OPRTNL_HNDLNG_CD,
            STG.OPRTNL_HNDLNG_CD,
            STG.INDSTR_NM,
            STG.EXCTN_BLOCK_ID,
            STG.EXCTN_BLOCK_CTGRY_CD,
            STG.EXCTN_BLOCK_ORIGIN_SCAC_CD,
            STG.EXCTN_BLOCK_ORIGIN_FSAC_CD,
            STG.EXCTN_BLOCK_DSTNTN_SCAC_CD,
            STG.EXCTN_BLOCK_DSTNTN_FSAC_CD,
            STG.EXCTN_PLND_BLOCK_NM,
            STG.EXCTN_RPRTD_BLOCK_NM,
            STG.SNW_OPERATION_TYPE,
            STG.SNW_LAST_REPLICATED,
            STG.CDC_OPERATION,
            STG.CDC_TIMESTAMP,
            FALSE,
            CURRENT_TIMESTAMP(),
            CURRENT_TIMESTAMP(),
            STG.SOURCE_LOAD_BATCH_ID,
            STG.SNW_OPERATION_OWNER
        );

    ----------------------------------------------------------------------------
    -- STEP 4: CAPTURE MERGE STATISTICS
    ----------------------------------------------------------------------------
    SELECT 
        SUM(CASE WHEN CDC_OPERATION = 'INSERT' THEN 1 ELSE 0 END),
        SUM(CASE WHEN CDC_OPERATION = 'UPDATE' THEN 1 ELSE 0 END),
        SUM(CASE WHEN CDC_OPERATION = 'DELETE' THEN 1 ELSE 0 END)
    INTO v_rows_inserted, v_rows_updated, v_rows_deleted
    FROM D_BRONZE.SADB.EQPMV_RFEQP_MVMNT_EVENT_STAGING;

    v_rows_merged := v_rows_inserted + v_rows_updated + v_rows_deleted;

    ----------------------------------------------------------------------------
    -- STEP 5: LOG EXECUTION RESULTS
    ----------------------------------------------------------------------------
    v_end_time := CURRENT_TIMESTAMP();
    
    INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
        BATCH_ID, TABLE_NAME, EXECUTION_STATUS, ERROR_MESSAGE,
        ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED,
        EXECUTION_START_TIME, EXECUTION_END_TIME
    ) VALUES (
        v_batch_id, 'EQPMV_RFEQP_MVMNT_EVENT', v_execution_status, NULL,
        v_rows_inserted, v_rows_updated, v_rows_deleted,
        v_start_time, v_end_time
    );

    v_result := 'SUCCESS: Processed ' || v_staging_count || ' staged rows. ' ||
                'Inserted: ' || v_rows_inserted || ', ' ||
                'Updated: ' || v_rows_updated || ', ' ||
                'Deleted: ' || v_rows_deleted;

    RETURN v_result;

EXCEPTION
    WHEN OTHER THEN
        v_error_msg := SQLERRM;
        v_execution_status := 'FAILED';
        v_end_time := CURRENT_TIMESTAMP();
        
        INSERT INTO D_BRONZE.MONITORING.CDC_EXECUTION_LOG (
            BATCH_ID, TABLE_NAME, EXECUTION_STATUS, ERROR_MESSAGE,
            ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED,
            EXECUTION_START_TIME, EXECUTION_END_TIME
        ) VALUES (
            v_batch_id, 'EQPMV_RFEQP_MVMNT_EVENT', v_execution_status, v_error_msg,
            0, 0, 0,
            v_start_time, v_end_time
        );
        
        RETURN 'FAILED: ' || v_error_msg;
END;

--------------------------------------------------------------------------------
-- SECTION 6: CREATE TASK FOR SCHEDULED EXECUTION
--------------------------------------------------------------------------------
CREATE OR REPLACE TASK D_BRONZE.SADB.TSK_CDC_EQPMV_RFEQP_MVMNT_EVENT
    WAREHOUSE = INFA_INGEST_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'CDC task for EQPMV_RFEQP_MVMNT_EVENT - v1.0 with proactive staleness detection'
AS
    CALL D_BRONZE.SADB.SP_CDC_EQPMV_RFEQP_MVMNT_EVENT();

--------------------------------------------------------------------------------
-- SECTION 7: ENABLE TASK (COMMENTED OUT FOR SAFETY)
--------------------------------------------------------------------------------
-- ALTER TASK D_BRONZE.SADB.TSK_CDC_EQPMV_RFEQP_MVMNT_EVENT RESUME;

--------------------------------------------------------------------------------
-- SECTION 8: STREAM RECOVERY PROCEDURE
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE D_BRONZE.SADB.SP_RECOVER_STREAM_EQPMV_RFEQP_MVMNT_EVENT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    ALTER TASK D_BRONZE.SADB.TSK_CDC_EQPMV_RFEQP_MVMNT_EVENT SUSPEND;
    
    DROP STREAM IF EXISTS D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM;
    
    CREATE STREAM D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE_HIST_STREAM
    ON TABLE D_RAW.SADB.EQPMV_RFEQP_MVMNT_EVENT_BASE
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE;
    
    RETURN 'Stream recreated successfully. Remember to resume the task manually after verification.';
END;
