dm_dim.dim_location:

CREATE TABLE [DM_DIM].[DIM_LOCATION](
	[DIM_LOCATION_ID] [numeric](18, 0) NOT NULL,
	[EDW_CREATE_USER] [varchar](8) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](8) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NULL,
	[SCAC_CD] [varchar](4) NULL,
	[FSAC_CD] [varchar](5) NULL,
	[SPLC_CD] [varchar](6) NULL,
	[STN_NM] [varchar](30) NULL,
	[STN_SEARCH_NM] [varchar](30) NULL,
	[UMBRL_STN_NM] [varchar](30) NULL,
	[GPLTCL_NM] [varchar](30) NULL,
	[LTD_NBR] [numeric](10, 8) NULL,
	[LNGTD_NBR] [numeric](11, 8) NULL,
	[BSNS_REASON_TXT] [varchar](80) NULL,
	[REGION_NM] [varchar](30) NULL,
	[DIVISION_NM] [varchar](50) NULL,
	[SUB_DIVISION_NM] [varchar](50) NULL,
	[CORRIDOR_NM] [varchar](50) NULL,
	[DYLGHT_SVNGS_TIME_IND] [varchar](1) NULL,
	[PHYSCL_CNTRY_CD] [varchar](2) NULL,
	[LOGICAL_CNTRY_CD] [varchar](2) NULL,
	[CITY_NM] [varchar](30) NULL,
	[LOCATION_EFCTV_DT] [datetime2](7) NULL,
	[LOCATION_EXPIRY_DT] [datetime2](7) NULL,
	[MSA_CD] [varchar](4) NULL,
	[POSTAL_ZIP_CD] [varchar](9) NULL,
	[RATE_POSTAL_ZIP_CD] [varchar](9) NULL,
	[RATE_ZIP_EFCTV_DT] [datetime2](7) NULL,
	[STPRV_CD] [varchar](2) NULL,
	[TIME_ZONE_CD] [varchar](2) NULL,
	[CREW_CHANGE_LCTN_IND] [varchar](1) NULL,
	[EQPMT_FLNG_LCTN_IND] [varchar](1) NULL,
	[EQPMT_INSPCT_LCTN_IND] [varchar](1) NULL,
	[CNTRL_STN_IND] [varchar](1) NULL,
	[ROAD_NBR] [numeric](3, 0) NULL,
	[SUBDIVISION] [varchar](50) NULL,
	[COUNTRY] [varchar](50) NULL,
	[REGION] [varchar](50) NULL,
	[DIVISION] [varchar](50) NULL,
	[ZONE] [varchar](50) NULL,
	[DIR_TERR] [varchar](50) NULL,
	[TERMINAL] [varchar](50) NULL,
	[CREW_TERMINAL] [varchar](50) NULL,
	[WORKLOAD_TERMINAL] [varchar](50) NULL,
	[FSAC_DWELL_IND] [varchar](1) NULL,
	[EW_REGIONS] [varchar](50) NULL,
	[TYES_CNTRL_STN] [varchar](50) NULL,
	[SHORTLINE_IND] [varchar](10) NULL,
	[MILE_POST] [numeric](18, 5) NULL,
	[COUNTY] [varchar](30) NULL,
	[ENG_DVSN] [varchar](20) NULL,
	[LMS_SUPPLY_NAME] [varchar](50) NULL,
	[LMS_SA] [varchar](10) NULL,
	[LCMTV_RESP_AREA] [varchar](20) NULL,
	[SBDVSN_ID] [numeric](4, 0) NULL,
	[RAIL_LINE] [varchar](4) NULL,
 CONSTRAINT [DIM_LOCATION1_PK] PRIMARY KEY CLUSTERED 
(
	[DIM_LOCATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


dm_dim.dim_locomotive:

CREATE TABLE [DM_DIM].[DIM_LOCOMOTIVE](
	[DIM_LOCOMOTIVE_ID] [numeric](18, 0) NOT NULL,
	[EDW_CREATE_USER] [varchar](8) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](8) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NULL,
	[EDW_START_EFCTV_DT] [datetime2](7) NULL,
	[EDW_END_EFCTV_DT] [datetime2](7) NULL,
	[EDW_CURRENT_FLG] [varchar](1) NULL,
	[MARK_CD] [varchar](4) NULL,
	[EQPUN_NBR] [varchar](10) NULL,
	[EIN_NBR] [varchar](10) NULL,
	[OTSD_LENGTH_QTY] [numeric](18, 0) NULL,
	[MODEL_NBR] [varchar](8) NULL,
	[AIR_BRAKE_MDL_NBR] [varchar](5) NULL,
	[AIR_BRAKE_HOOKP_CD] [varchar](1) NULL,
	[AXLE_QTY] [numeric](5, 0) NULL,
	[BLDR_CD] [varchar](1) NULL,
	[BRNG_TYPE_CD] [varchar](1) NULL,
	[FUEL_CPCTY_QTY] [numeric](5, 0) NULL,
	[FUEL_PRHTR_IND] [varchar](1) NULL,
	[FULL_WEIGHT_QTY] [numeric](10, 0) NULL,
	[HRSPWR_QTY] [numeric](5, 0) NULL,
	[MXM_SPEED_QTY] [numeric](5, 0) NULL,
	[TRCTN_MTR_TYPE_CD] [varchar](2) NULL,
	[DISTRIBUTED_POWER_IND] [varchar](1) NULL,
	[FUEL_TRIP_OPTIMIZER_IND] [varchar](1) NULL,
	[WHEEL_SIZE_QTY] [numeric](5, 0) NULL,
	[POWER_AXLE_QTY] [numeric](5, 0) NULL,
	[BRAKE_PIPE_PRSR_MNTNC_IND] [varchar](1) NULL,
	[AUXLRY_LUBE_OIL_CPCTY_QTY] [numeric](3, 0) NULL,
	[SRVC_CLASS_CD] [varchar](7) NULL,
	[CTGRY_CD] [varchar](3) NULL,
	[CNTNS_TRCTV_EFFORT_QTY] [numeric](2, 0) NULL,
	[COOL_SYSTEM_CPCTY_QTY] [numeric](3, 0) NULL,
	[ENGINE_MODEL_NM] [varchar](13) NULL,
	[GEAR_AXL_TEETH_QTY] [numeric](5, 0) NULL,
	[PNN_GEAR_TEETH_QTY] [numeric](5, 0) NULL,
	[GNRTR_MODEL_NM] [varchar](8) NULL,
	[MNTNC_HOME_SHOP_SCAC_CD] [varchar](4) NULL,
	[MNTNC_HOME_SHOP_FSAC_CD] [varchar](5) NULL,
	[LEASE_START_DT] [datetime2](7) NULL,
	[LEASE_END_DT] [datetime2](7) NULL,
	[WRNTY_SRVC_AGRMNT_CD] [varchar](8) NULL,
	[LCMTV_FRA_INSPECT_DT] [datetime2](7) NULL,
	[LCMTV_CTC_INSPECT_DT] [datetime2](7) NULL,
	[FLEET_ASGNMN_MARK_CD] [varchar](4) NULL,
	[SOURCE_SYSTEM_DELETE_TMS] [datetime2](7) NULL,
	[SAP_PTC_STATUS] [varchar](30) NULL,
	[SAP_OPERATOR] [varchar](30) NULL,
	[SAP_RR_CODE_OPERATOR] [varchar](30) NULL,
	[SAP_RR_CODE_OWNER] [varchar](30) NULL,
	[SAP_FLEET_ASGNMNT] [varchar](30) NULL,
	[SAP_BRAKE_SCHEDULE] [varchar](30) NULL,
	[SAP_AIR_FLOW_METER] [varchar](30) NULL,
	[SAP_SMART_START] [varchar](30) NULL,
	[SAP_HORSEPOWER] [numeric](18, 0) NULL,
	[SAP_SERVICE] [varchar](30) NULL,
	[SAP_SYSTEM_STATUS_TEXT] [varchar](30) NULL,
	[SAP_SYSTEM_STATUS] [varchar](4) NULL,
	[SAP_USER_STATUS_TEXT] [varchar](30) NULL,
	[SAP_USER_STATUS] [varchar](4) NULL,
	[SAP_AXLE_QUANTITY] [numeric](18, 0) NULL,
	[SAP_MODEL_NUMBER] [varchar](20) NULL,
	[SAP_MANUFACTURER] [varchar](30) NULL,
	[SAP_WEIGHT] [numeric](18, 5) NULL,
	[SAP_OBJ_NUMBER] [varchar](22) NULL,
	[SAP_PLANNING_PLANT] [varchar](4) NULL,
	[SAP_EQUIP_CATEGORY] [varchar](1) NULL,
	[SAP_LOCOMOTIVE] [varchar](25) NULL,
	[SAP_MAINTENANCE_PLANT] [varchar](4) NULL,
	[SAP_OBJ_TXT] [varchar](40) NULL,
	[SAP_CHAR_SERVICE] [varchar](30) NULL,
	[SAP_EQUIPMENT] [varchar](18) NULL,
	[SAP_VALID_FROM] [varchar](8) NULL,
	[SAP_VALID_TO] [varchar](8) NULL,
	[SAP_OBJ_TYPE] [varchar](10) NULL,
	[SAP_STATUS_INACT] [varchar](1) NULL,
	[SAP_CREATED_ON] [datetime2](7) NULL,
	[SAP_CHANGED_ON] [datetime2](7) NULL,
	[SAP_FUEL_CPCTY_CND] [varchar](30) NULL,
	[SAP_LUB_OIL_CPCTY_QTY] [varchar](30) NULL,
	[SAP_CAMERA_FRONT_IMAGE] [varchar](30) NULL,
	[SAP_LOCOTROL] [varchar](30) NULL,
	[SAP_CAMERA_DEPLOYMENT] [varchar](30) NULL,
	[SAP_CAMERA_CAB_IMAGE] [varchar](30) NULL,
	[BUILT_DT] [date] NULL,
	[RBLT_DT] [date] NULL,
	[MODEL_SHORT_NM] [varchar](6) NULL,
	[AC_FLEET] [varchar](10) NULL,
	[PSTV_TRAIN_CNTRL_SYSTEM_CD] [varchar](2) NULL,
	[PTC_STATUS] [varchar](2) NULL,
	[LVVR_IND] [varchar](1) NULL,
 CONSTRAINT [DIM_LOCOMOTIVE_PK] PRIMARY KEY CLUSTERED 
(
	[DIM_LOCOMOTIVE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


DM_DIM.DIM_EQUIPMENT:


CREATE TABLE [DM_DIM].[DIM_EQUIPMENT](
	[DIM_EQUIPMENT_ID] [numeric](18, 0) NOT NULL,
	[EDW_SRC_BPK_MD5_ID] [varchar](32) NULL,
	[EDW_SRC_BK_MD5_ID] [varchar](32) NULL,
	[EDW_CREATE_USER] [varchar](8) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](8) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NULL,
	[EDW_START_EFCTV_DT] [datetime2](7) NULL,
	[EDW_END_EFCTV_DT] [datetime2](7) NULL,
	[EDW_CURRENT_FLG] [varchar](1) NOT NULL,
	[EQPUN_NBR] [varchar](10) NOT NULL,
	[MARK_CD] [varchar](4) NOT NULL,
	[AAR_CAR_CD] [varchar](4) NOT NULL,
	[AAR_CAR_CD_ID] [numeric](18, 0) NULL,
	[EQPMNT_GROUP_CD] [varchar](4) NULL,
	[AXLE_QTY] [numeric](4, 0) NULL,
	[BUILT_DT] [datetime2](7) NULL,
	[DMTR_UOM_BASIS_CD] [varchar](2) NULL,
	[EIN_NBR] [varchar](10) NULL,
	[GROSS_WEIGHT_QTY] [numeric](7, 0) NULL,
	[GROSS_WEIGHT_UOM_BASIS_CD] [varchar](2) NULL,
	[LINEAL_FRCTNL_UOM_BASIS_CD] [varchar](2) NULL,
	[LINEAL_UOM_BASIS_CD] [varchar](2) NULL,
	[LIQUID_UOM_BASIS_CD] [varchar](2) NULL,
	[OTSD_EXTRM_HEIGHT_QTY] [numeric](4, 0) NULL,
	[OTSD_EXTRM_WIDTH_QTY] [numeric](4, 0) NULL,
	[OTSD_HEIGHT_EXTRM_WIDTH_QTY] [numeric](4, 0) NULL,
	[OTSD_LENGTH_QTY] [numeric](5, 0) NULL,
	[OWNER_MARK_CD] [varchar](4) NULL,
	[LESSEE_MARK_CD] [varchar](4) NULL,
	[PRIOR_EQPUN_NBR] [varchar](10) NULL,
	[PRIOR_MARK_CD] [varchar](4) NULL,
	[SPEED_UOM_BASIS_CD] [varchar](2) NULL,
	[STATUS_CD] [varchar](2) NULL,
	[SRVC_LIFE_CD] [varchar](2) NULL,
	[STNCL_MARK_OWNER_CLASS_CD] [varchar](2) NULL,
	[TARE_WEIGHT_QTY] [numeric](7, 0) NULL,
	[VOLUME_UOM_BASIS_CD] [varchar](2) NULL,
	[WEIGHT_UOM_BASIS_CD] [varchar](2) NULL,
	[MCHNCL_DSGNTN_CD] [varchar](4) NULL,
	[PLATE_CLRNC_CD] [varchar](2) NULL,
	[RBLT_CD] [varchar](1) NULL,
	[RBLT_DT] [datetime2](7) NULL,
	[RATE_CD] [varchar](2) NULL,
	[CAR_OWNERSHIP] [varchar](15) NULL,
	[LEASED_IND] [varchar](10) NULL,
	[TARGET_EQPMT_CTGRY_NM] [varchar](30) NULL,
	[PRDCT_NM] [varchar](30) NULL,
	[FLEET_NM] [varchar](50) NULL,
	[EQPMNT_POOL_ID] [numeric](18, 0) NULL,
	[FLEET_SBGRP_CTGRY_NM] [varchar](30) NULL,
	[PARTY_NM] [varchar](100) NULL,
	[CAR_KIND_CD] [varchar](30) NULL,
	[UCA_CODES] [varchar](10) NULL,
	[CPR_EQPMNT_POOL_ID] [varchar](7) NULL,
	[AAR_EQPMNT_POOL_ID] [varchar](7) NULL,
	[EFCTV_TMS] [datetime2](7) NULL,
	[MAX_EFCTV_TMS] [datetime2](7) NULL,
	[REGISTERED_IND] [varchar](1) NOT NULL,
	[CP_OWNED_IND] [varchar](1) NULL,
	[DLTD_TMS] [datetime2](7) NULL,
 CONSTRAINT [DIM_EQUIPMENT_PK] PRIMARY KEY CLUSTERED 
(
	[DIM_EQUIPMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DM_DIM.DIM_TRAIN


CREATE TABLE [DM_DIM].[DIM_TRAIN](
	[DIM_TRAIN_ID] [numeric](18, 0) NOT NULL,
	[EDW_CREATE_USER] [varchar](8) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](8) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NULL,
	[TRAIN_PLAN_LEG_ID] [numeric](18, 0) NOT NULL,
	[OPTRN_LEG_ID] [numeric](18, 0) NULL,
	[TRAIN_NAME] [varchar](20) NULL,
	[TITAN_NBR] [numeric](6, 0) NULL,
	[TYES_TRAIN_ID] [numeric](18, 0) NULL,
	[TRAIN_DRCTN] [varchar](1) NULL,
	[MTP_OPTRN_PRFL_NM] [varchar](12) NULL,
	[TRAIN_TYPE_CD] [varchar](4) NULL,
	[TRAIN_TYPE_DSCRPT_TXT] [varchar](60) NULL,
	[TRAIN_KIND_CD] [varchar](4) NULL,
	[TRAIN_KIND_DSCRPT_TXT] [varchar](100) NULL,
	[TRAIN_PLAN_LEG_NAME] [varchar](22) NULL,
	[TRN_SERIES_CD] [varchar](1) NULL,
	[TRN_SERIES_NM] [varchar](3) NULL,
	[TRN_SYMBOL] [varchar](3) NULL,
	[BLK_OP_CD] [varchar](10) NULL,
	[EFFECTIVE_START_TMS] [datetime2](7) NULL,
	[EFFECTIVE_END_TMS] [datetime2](7) NULL,
	[ACTIVE_IND] [varchar](1) NULL,
	[ETL_CRC_VAL] [varchar](50) NULL,
	[TRAIN_PRFL_ID] [numeric](12, 0) NULL,
 CONSTRAINT [DIM_TRAIN_PK] PRIMARY KEY CLUSTERED 
(
	[DIM_TRAIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DM_DIM.DIM_SUBDVSN_ZONE:


CREATE TABLE [DM_DIM].[DIM_SUBDVSN_ZONE](
	[EDW_CREATE_USER] [varchar](8) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](8) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NOT NULL,
	[EDW_CREATE_SRC] [varchar](50) NULL,
	[DIM_SUBDVSN_ZONE_ID] [varchar](50) NOT NULL,
	[SBDVSN_NBR] [decimal](18, 0) NULL,
	[SBDVSN_NAME] [varchar](50) NULL,
	[REGION] [varchar](15) NULL,
	[DIVISION_NM] [varchar](50) NULL,
	[ZONE] [varchar](30) NULL,
	[LOW_TRACK_MILE] [decimal](10, 5) NULL,
	[HIGH_TRACK_MILE] [decimal](10, 5) NULL,
 CONSTRAINT [DIM_SUBDVSN_ZONE_PK] PRIMARY KEY CLUSTERED 
(
	[DIM_SUBDVSN_ZONE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DM_DIM.DIM_SUBDVSN:

CREATE TABLE [DM_DIM].[DIM_SUBDVSN](
	[EDW_CREATE_USER] [varchar](15) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](15) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NULL,
	[EDW_CREATE_SRC] [varchar](50) NULL,
	[SBDVSN_NBR] [decimal](18, 0) NOT NULL,
	[SBDVSN_NAME] [varchar](50) NULL,
	[REGION] [varchar](15) NULL,
	[DIVISION_NM] [varchar](50) NULL,
	[ZONE] [varchar](30) NULL,
	[STPRV_CD] [varchar](2) NULL,
	[COUNTRY] [varchar](2) NULL,
	[SERVICE_AREA] [varchar](30) NULL,
	[RAIL_LINE] [varchar](5) NULL,
	[SUBSET_RAIL_LINE] [varchar](5) NULL,
	[CORRIDOR] [varchar](50) NULL,
	[LOW_TRACK_MILE] [decimal](10, 5) NULL,
	[HIGH_TRACK_MILE] [decimal](10, 5) NULL,
	[TRACK_MILES] [decimal](10, 5) NULL,
	[ZONE_MILEAGE_BREAK] [decimal](10, 5) NULL,
	[REGION_BRK_TO_END] [varchar](10) NULL,
	[DIVISION_NM_BRK_TO_END] [varchar](50) NULL,
	[ZONE_BRK_TO_END] [varchar](50) NULL,
 CONSTRAINT [DIM_SUBDVSN_PK] PRIMARY KEY CLUSTERED 
(
	[SBDVSN_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DM_DIM.GIS_ORGN_DSTNTN_MLG


CREATE TABLE [DM_DIM].[GIS_ORGN_DSTNTN_MLG](
	[EDW_CREATE_USER] [varchar](20) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](20) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NULL,
	[EDW_ROW_SRC] [varchar](200) NULL,
	[ORGN_DSTNTN_MLG_ID] [decimal](10, 0) NOT NULL,
	[ORGN_SCAC] [varchar](5) NULL,
	[ORGN_FSAC] [varchar](5) NULL,
	[DSTNTN_SCAC] [varchar](5) NULL,
	[DSTNTN_FSAC] [varchar](5) NULL,
	[MILES] [decimal](10, 5) NULL,
	[ACTV_IND] [varchar](10) NULL,
	[EDW_EFCTV_TMS] [datetime2](7) NULL,
	[EDW_EXPRY_TMS] [datetime2](7) NULL,
 CONSTRAINT [GIS_ORGN_DSTNTN_MLG_PK] PRIMARY KEY CLUSTERED 
(
	[ORGN_DSTNTN_MLG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

DM_DIM.GIS_ORGN_DSTNTN_MLG_BY_STPRV


CREATE TABLE [DM_DIM].[GIS_ORGN_DSTNTN_MLG_BY_STPRV](
	[EDW_CREATE_USER] [varchar](20) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](20) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NULL,
	[EDW_ROW_SRC] [varchar](200) NULL,
	[ORGN_DSTNTN_MLG_BY_STPRV_ID] [decimal](10, 0) NOT NULL,
	[ORGN_DSTNTN_MLG_ID] [decimal](10, 0) NOT NULL,
	[STPRV_CD] [varchar](10) NULL,
	[STPRV_NM] [varchar](100) NULL,
	[SBDVSN_NBR] [decimal](10, 0) NULL,
	[SBDVSN_NM] [varchar](100) NULL,
	[MILES] [decimal](10, 5) NULL,
	[ACTV_IND] [varchar](10) NULL,
	[EDW_EFCTV_TMS] [datetime2](7) NULL,
	[EDW_EXPRY_TMS] [datetime2](7) NULL,
	[COUNTRY] [varchar](10) NULL,
 CONSTRAINT [ORGN_DSTNTN_MLG_BY_STPRV_PK] PRIMARY KEY CLUSTERED 
(
	[ORGN_DSTNTN_MLG_BY_STPRV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [DM_DIM].[GIS_ORGN_DSTNTN_MLG_BY_STPRV]  WITH CHECK ADD  CONSTRAINT [GIS_ORGN_DSTNTN_MLG_BY_STP_R01] FOREIGN KEY([ORGN_DSTNTN_MLG_ID])
REFERENCES [DM_DIM].[GIS_ORGN_DSTNTN_MLG] ([ORGN_DSTNTN_MLG_ID])
GO

ALTER TABLE [DM_DIM].[GIS_ORGN_DSTNTN_MLG_BY_STPRV] CHECK CONSTRAINT [GIS_ORGN_DSTNTN_MLG_BY_STP_R01]
GO

DM_DIM.GIS_ORGN_DSTNTN_MLG_BRKDN:


CREATE TABLE [DM_DIM].[GIS_ORGN_DSTNTN_MLG_BRKDN](
	[EDW_CREATE_USER] [varchar](20) NULL,
	[EDW_CREATE_TMS] [datetime2](7) NULL,
	[EDW_UPDATE_USER] [varchar](20) NULL,
	[EDW_UPDATE_TMS] [datetime2](7) NULL,
	[EDW_ROW_SRC] [varchar](200) NULL,
	[ORGN_DSTNTN_MLG_BRKDN_ID] [decimal](10, 0) NOT NULL,
	[ORGN_DSTNTN_MLG_ID] [decimal](10, 0) NOT NULL,
	[ORGN_SCAC] [varchar](5) NULL,
	[ORGN_FSAC] [varchar](5) NULL,
	[ORGN_SBDVSN_NBR] [decimal](10, 0) NULL,
	[ORGN_SBDVSN_NM] [varchar](100) NULL,
	[DSTNTN_SCAC] [varchar](5) NULL,
	[DSTNTN_FSAC] [varchar](5) NULL,
	[DSTNTN_SBDVSN_NBR] [decimal](10, 0) NULL,
	[DSTNTN_SBDVSN_NM] [varchar](100) NULL,
	[DRCTN] [varchar](10) NULL,
	[MILES] [decimal](10, 5) NULL,
	[ACTV_IND] [varchar](10) NULL,
	[EDW_EFCTV_TMS] [datetime2](7) NULL,
	[EDW_EXPRY_TMS] [datetime2](7) NULL,
	[ORGN_RFRNC_LOW_MLS_QTY] [decimal](10, 5) NULL,
	[DSTN_RFRNC_LOW_MLS_QTY] [decimal](10, 5) NULL,
 CONSTRAINT [GIS_ORGN_DSTNTN_MLG_BRKDN_PK] PRIMARY KEY CLUSTERED 
(
	[ORGN_DSTNTN_MLG_BRKDN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [DM_DIM].[GIS_ORGN_DSTNTN_MLG_BRKDN]  WITH NOCHECK ADD  CONSTRAINT [FK_GIS_ORGN_DSTNTN_MLG_BRKDN_R01] FOREIGN KEY([ORGN_DSTNTN_MLG_ID])
REFERENCES [DM_DIM].[GIS_ORGN_DSTNTN_MLG] ([ORGN_DSTNTN_MLG_ID])
GO