-- =====================================================================================
-- SCD TYPE 2 DYNAMIC TABLES FOR TRAIN_PLAN_LEG
-- Maintains full history of all changes with effective date ranges
-- =====================================================================================
-- ENVIRONMENT PROMOTION: Update these values for each environment
--   DEV:  D_BRONZE, D_SILVER, INFA_INGEST_WH
--   QA:   Q_BRONZE, Q_SILVER, INFA_INGEST_WH
--   PROD: P_BRONZE, P_SILVER, INFA_INGEST_WH
-- =====================================================================================

-- =====================================================================================
-- 1. BASE DYNAMIC TABLE (SCD2) - Initial snapshot with SCD2 columns
-- =====================================================================================
CREATE OR REPLACE DYNAMIC TABLE D_SILVER.SADB.TRAIN_PLAN_LEG_BASE_DT_2(
    TRAIN_PLAN_LEG_SK,
    TRAIN_PLAN_LEG_ID,
    TRAIN_PLAN_ID,
    TRAIN_DRCTN_CD,
    TRAIN_PLAN_LEG_NM,
    MTP_TITAN_NBR,
    RECORD_CREATE_TMS,
    RECORD_UPDATE_TMS,
    CREATE_USER_ID,
    UPDATE_USER_ID,
    TURN_LEG_SQNC_NBR,
    TYES_TRAIN_ID,
    MTP_TOTAL_RTPNT_SENT_QTY,
    MTP_ROUTE_CMPLT_CD,
    MTP_TRAIN_STATE_CD,
    DW_EFFECTIVE_TS,
    DW_EXPIRY_TS,
    DW_IS_CURRENT,
    DW_IS_DELETED,
    DW_VERSION_NBR,
    DW_RECORD_HASH,
    DW_LOAD_TS,
    DW_RECORD_SOURCE
)
TARGET_LAG = 'DOWNSTREAM'
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
WAREHOUSE = INFA_INGEST_WH
DATA_RETENTION_TIME_IN_DAYS = 7
COMMENT = 'SCD Type 2 - Initial snapshot from BASE table with version tracking'
AS
SELECT
    MD5(TRAIN_PLAN_LEG_ID || '~' || COALESCE(TO_VARCHAR(SNW_LAST_REPLICATED), '1900-01-01')) AS TRAIN_PLAN_LEG_SK,
    TRAIN_PLAN_LEG_ID,
    TRAIN_PLAN_ID,
    TRAIN_DRCTN_CD,
    TRAIN_PLAN_LEG_NM,
    MTP_TITAN_NBR,
    RECORD_CREATE_TMS,
    RECORD_UPDATE_TMS,
    CREATE_USER_ID,
    UPDATE_USER_ID,
    TURN_LEG_SQNC_NBR,
    TYES_TRAIN_ID,
    MTP_TOTAL_RTPNT_SENT_QTY,
    MTP_ROUTE_CMPLT_CD,
    MTP_TRAIN_STATE_CD,
    COALESCE(SNW_LAST_REPLICATED, RECORD_UPDATE_TMS, RECORD_CREATE_TMS) AS DW_EFFECTIVE_TS,
    TO_TIMESTAMP_NTZ('9999-12-31 23:59:59') AS DW_EXPIRY_TS,
    TRUE AS DW_IS_CURRENT,
    FALSE AS DW_IS_DELETED,
    1 AS DW_VERSION_NBR,
    MD5(
        COALESCE(TO_VARCHAR(TRAIN_PLAN_ID), '') || '~' ||
        COALESCE(TRAIN_DRCTN_CD, '') || '~' ||
        COALESCE(TRAIN_PLAN_LEG_NM, '') || '~' ||
        COALESCE(TO_VARCHAR(MTP_TITAN_NBR), '') || '~' ||
        COALESCE(TO_VARCHAR(TURN_LEG_SQNC_NBR), '') || '~' ||
        COALESCE(TO_VARCHAR(TYES_TRAIN_ID), '') || '~' ||
        COALESCE(TO_VARCHAR(MTP_TOTAL_RTPNT_SENT_QTY), '') || '~' ||
        COALESCE(MTP_ROUTE_CMPLT_CD, '') || '~' ||
        COALESCE(MTP_TRAIN_STATE_CD, '')
    ) AS DW_RECORD_HASH,
    COALESCE(SNW_LAST_REPLICATED, RECORD_UPDATE_TMS, RECORD_CREATE_TMS) AS DW_LOAD_TS,
    'BASE' AS DW_RECORD_SOURCE
FROM D_BRONZE.SADB.TRAIN_PLAN_LEG_BASE;

-- =====================================================================================
-- 2. CDC DYNAMIC TABLE (SCD2) - Change records with SCD2 columns
-- =====================================================================================
CREATE OR REPLACE DYNAMIC TABLE D_SILVER.SADB.TRAIN_PLAN_LEG_CDC_DT_2(
    TRAIN_PLAN_LEG_SK,
    TRAIN_PLAN_LEG_ID,
    TRAIN_PLAN_ID,
    TRAIN_DRCTN_CD,
    TRAIN_PLAN_LEG_NM,
    MTP_TITAN_NBR,
    RECORD_CREATE_TMS,
    RECORD_UPDATE_TMS,
    CREATE_USER_ID,
    UPDATE_USER_ID,
    TURN_LEG_SQNC_NBR,
    TYES_TRAIN_ID,
    MTP_TOTAL_RTPNT_SENT_QTY,
    MTP_ROUTE_CMPLT_CD,
    MTP_TRAIN_STATE_CD,
    DW_EFFECTIVE_TS,
    DW_EXPIRY_TS,
    DW_IS_CURRENT,
    DW_IS_DELETED,
    DW_VERSION_NBR,
    DW_RECORD_HASH,
    DW_LOAD_TS,
    DW_RECORD_SOURCE,
    DW_CDC_OPERATION
)
TARGET_LAG = 'DOWNSTREAM'
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
WAREHOUSE = INFA_INGEST_WH
DATA_RETENTION_TIME_IN_DAYS = 7
COMMENT = 'SCD Type 2 - CDC changes with operation tracking for history building'
AS
SELECT
    MD5(COALESCE(TRAIN_PLAN_LEG_ID_NEW, TRAIN_PLAN_LEG_ID_OLD) || '~' || COALESCE(TO_VARCHAR(OP_LAST_REPLICATED), '1900-01-01')) AS TRAIN_PLAN_LEG_SK,
    COALESCE(TRAIN_PLAN_LEG_ID_NEW, TRAIN_PLAN_LEG_ID_OLD) AS TRAIN_PLAN_LEG_ID,
    COALESCE(TRAIN_PLAN_ID_NEW, TRAIN_PLAN_ID_OLD) AS TRAIN_PLAN_ID,
    COALESCE(TRAIN_DRCTN_CD_NEW, TRAIN_DRCTN_CD_OLD) AS TRAIN_DRCTN_CD,
    COALESCE(TRAIN_PLAN_LEG_NM_NEW, TRAIN_PLAN_LEG_NM_OLD) AS TRAIN_PLAN_LEG_NM,
    COALESCE(MTP_TITAN_NBR_NEW, MTP_TITAN_NBR_OLD) AS MTP_TITAN_NBR,
    COALESCE(RECORD_CREATE_TMS_NEW, RECORD_CREATE_TMS_OLD) AS RECORD_CREATE_TMS,
    COALESCE(RECORD_UPDATE_TMS_NEW, RECORD_UPDATE_TMS_OLD) AS RECORD_UPDATE_TMS,
    COALESCE(CREATE_USER_ID_NEW, CREATE_USER_ID_OLD) AS CREATE_USER_ID,
    COALESCE(UPDATE_USER_ID_NEW, UPDATE_USER_ID_OLD) AS UPDATE_USER_ID,
    COALESCE(TURN_LEG_SQNC_NBR_NEW, TURN_LEG_SQNC_NBR_OLD) AS TURN_LEG_SQNC_NBR,
    COALESCE(TYES_TRAIN_ID_NEW, TYES_TRAIN_ID_OLD) AS TYES_TRAIN_ID,
    COALESCE(MTP_TOTAL_RTPNT_SENT_QTY_NEW, MTP_TOTAL_RTPNT_SENT_QTY_OLD) AS MTP_TOTAL_RTPNT_SENT_QTY,
    COALESCE(MTP_ROUTE_CMPLT_CD_NEW, MTP_ROUTE_CMPLT_CD_OLD) AS MTP_ROUTE_CMPLT_CD,
    COALESCE(MTP_TRAIN_STATE_CD_NEW, MTP_TRAIN_STATE_CD_OLD) AS MTP_TRAIN_STATE_CD,
    OP_LAST_REPLICATED AS DW_EFFECTIVE_TS,
    TO_TIMESTAMP_NTZ('9999-12-31 23:59:59') AS DW_EXPIRY_TS,
    TRUE AS DW_IS_CURRENT,
    CASE WHEN OP_CODE = 'D' THEN TRUE ELSE FALSE END AS DW_IS_DELETED,
    1 AS DW_VERSION_NBR,
    MD5(
        COALESCE(TO_VARCHAR(COALESCE(TRAIN_PLAN_ID_NEW, TRAIN_PLAN_ID_OLD)), '') || '~' ||
        COALESCE(COALESCE(TRAIN_DRCTN_CD_NEW, TRAIN_DRCTN_CD_OLD), '') || '~' ||
        COALESCE(COALESCE(TRAIN_PLAN_LEG_NM_NEW, TRAIN_PLAN_LEG_NM_OLD), '') || '~' ||
        COALESCE(TO_VARCHAR(COALESCE(MTP_TITAN_NBR_NEW, MTP_TITAN_NBR_OLD)), '') || '~' ||
        COALESCE(TO_VARCHAR(COALESCE(TURN_LEG_SQNC_NBR_NEW, TURN_LEG_SQNC_NBR_OLD)), '') || '~' ||
        COALESCE(TO_VARCHAR(COALESCE(TYES_TRAIN_ID_NEW, TYES_TRAIN_ID_OLD)), '') || '~' ||
        COALESCE(TO_VARCHAR(COALESCE(MTP_TOTAL_RTPNT_SENT_QTY_NEW, MTP_TOTAL_RTPNT_SENT_QTY_OLD)), '') || '~' ||
        COALESCE(COALESCE(MTP_ROUTE_CMPLT_CD_NEW, MTP_ROUTE_CMPLT_CD_OLD), '') || '~' ||
        COALESCE(COALESCE(MTP_TRAIN_STATE_CD_NEW, MTP_TRAIN_STATE_CD_OLD), '')
    ) AS DW_RECORD_HASH,
    OP_LAST_REPLICATED AS DW_LOAD_TS,
    'CDC' AS DW_RECORD_SOURCE,
    OP_CODE AS DW_CDC_OPERATION
FROM D_BRONZE.SADB.TRAIN_PLAN_LEG_BASE_LOG;

-- =====================================================================================
-- 3. HISTORY DYNAMIC TABLE (SCD2) - Full history with proper versioning
-- This table maintains ALL versions of each record with correct date ranges
-- =====================================================================================
CREATE OR REPLACE DYNAMIC TABLE D_SILVER.SADB.TRAIN_PLAN_LEG_CURR_DT_2(
    TRAIN_PLAN_LEG_SK,
    TRAIN_PLAN_LEG_ID,
    TRAIN_PLAN_ID,
    TRAIN_DRCTN_CD,
    TRAIN_PLAN_LEG_NM,
    MTP_TITAN_NBR,
    RECORD_CREATE_TMS,
    RECORD_UPDATE_TMS,
    CREATE_USER_ID,
    UPDATE_USER_ID,
    TURN_LEG_SQNC_NBR,
    TYES_TRAIN_ID,
    MTP_TOTAL_RTPNT_SENT_QTY,
    MTP_ROUTE_CMPLT_CD,
    MTP_TRAIN_STATE_CD,
    DW_EFFECTIVE_TS,
    DW_EXPIRY_TS,
    DW_IS_CURRENT,
    DW_IS_DELETED,
    DW_VERSION_NBR,
    DW_RECORD_HASH,
    DW_LOAD_TS,
    DW_RECORD_SOURCE
)
TARGET_LAG = '5 minutes'
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
WAREHOUSE = INFA_INGEST_WH
DATA_RETENTION_TIME_IN_DAYS = 7
COMMENT = 'SCD Type 2 - Full history table with all versions and date ranges'
AS
WITH all_records AS (
    SELECT
        TRAIN_PLAN_LEG_SK,
        TRAIN_PLAN_LEG_ID,
        TRAIN_PLAN_ID,
        TRAIN_DRCTN_CD,
        TRAIN_PLAN_LEG_NM,
        MTP_TITAN_NBR,
        RECORD_CREATE_TMS,
        RECORD_UPDATE_TMS,
        CREATE_USER_ID,
        UPDATE_USER_ID,
        TURN_LEG_SQNC_NBR,
        TYES_TRAIN_ID,
        MTP_TOTAL_RTPNT_SENT_QTY,
        MTP_ROUTE_CMPLT_CD,
        MTP_TRAIN_STATE_CD,
        DW_EFFECTIVE_TS,
        DW_IS_DELETED,
        DW_RECORD_HASH,
        DW_LOAD_TS,
        DW_RECORD_SOURCE
    FROM D_SILVER.SADB.TRAIN_PLAN_LEG_BASE_DT_2
    
    UNION ALL
    
    SELECT
        TRAIN_PLAN_LEG_SK,
        TRAIN_PLAN_LEG_ID,
        TRAIN_PLAN_ID,
        TRAIN_DRCTN_CD,
        TRAIN_PLAN_LEG_NM,
        MTP_TITAN_NBR,
        RECORD_CREATE_TMS,
        RECORD_UPDATE_TMS,
        CREATE_USER_ID,
        UPDATE_USER_ID,
        TURN_LEG_SQNC_NBR,
        TYES_TRAIN_ID,
        MTP_TOTAL_RTPNT_SENT_QTY,
        MTP_ROUTE_CMPLT_CD,
        MTP_TRAIN_STATE_CD,
        DW_EFFECTIVE_TS,
        DW_IS_DELETED,
        DW_RECORD_HASH,
        DW_LOAD_TS,
        DW_RECORD_SOURCE
    FROM D_SILVER.SADB.TRAIN_PLAN_LEG_CDC_DT_2
),
versioned_records AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY TRAIN_PLAN_LEG_ID 
            ORDER BY DW_EFFECTIVE_TS ASC
        ) AS DW_VERSION_NBR,
        LEAD(DW_EFFECTIVE_TS) OVER (
            PARTITION BY TRAIN_PLAN_LEG_ID 
            ORDER BY DW_EFFECTIVE_TS ASC
        ) AS NEXT_EFFECTIVE_TS,
        ROW_NUMBER() OVER (
            PARTITION BY TRAIN_PLAN_LEG_ID 
            ORDER BY DW_EFFECTIVE_TS DESC
        ) AS REV_RN
    FROM all_records
)
SELECT
    TRAIN_PLAN_LEG_SK,
    TRAIN_PLAN_LEG_ID,
    TRAIN_PLAN_ID,
    TRAIN_DRCTN_CD,
    TRAIN_PLAN_LEG_NM,
    MTP_TITAN_NBR,
    RECORD_CREATE_TMS,
    RECORD_UPDATE_TMS,
    CREATE_USER_ID,
    UPDATE_USER_ID,
    TURN_LEG_SQNC_NBR,
    TYES_TRAIN_ID,
    MTP_TOTAL_RTPNT_SENT_QTY,
    MTP_ROUTE_CMPLT_CD,
    MTP_TRAIN_STATE_CD,
    DW_EFFECTIVE_TS,
    COALESCE(
        DATEADD('SECOND', -1, NEXT_EFFECTIVE_TS),
        TO_TIMESTAMP_NTZ('9999-12-31 23:59:59')
    ) AS DW_EXPIRY_TS,
    CASE WHEN REV_RN = 1 THEN TRUE ELSE FALSE END AS DW_IS_CURRENT,
    DW_IS_DELETED,
    DW_VERSION_NBR,
    DW_RECORD_HASH,
    DW_LOAD_TS,
    DW_RECORD_SOURCE
FROM versioned_records;


-- =====================================================================================
-- HELPER VIEW: Current records only (for easy querying)
-- =====================================================================================
CREATE OR REPLACE VIEW D_SILVER.SADB.TRAIN_PLAN_LEG_CURRENT_V AS
SELECT
    TRAIN_PLAN_LEG_ID,
    TRAIN_PLAN_ID,
    TRAIN_DRCTN_CD,
    TRAIN_PLAN_LEG_NM,
    MTP_TITAN_NBR,
    RECORD_CREATE_TMS,
    RECORD_UPDATE_TMS,
    CREATE_USER_ID,
    UPDATE_USER_ID,
    TURN_LEG_SQNC_NBR,
    TYES_TRAIN_ID,
    MTP_TOTAL_RTPNT_SENT_QTY,
    MTP_ROUTE_CMPLT_CD,
    MTP_TRAIN_STATE_CD,
    DW_VERSION_NBR,
    DW_EFFECTIVE_TS,
    DW_IS_DELETED
FROM D_SILVER.SADB.TRAIN_PLAN_LEG_CURR_DT_2
WHERE DW_IS_CURRENT = TRUE;


-- =====================================================================================
-- HELPER VIEW: Point-in-time query example
-- Usage: SELECT * FROM D_SILVER.SADB.TRAIN_PLAN_LEG_AS_OF_V 
--        WHERE AS_OF_TS = '2024-06-15 10:30:00'
-- =====================================================================================
CREATE OR REPLACE VIEW D_SILVER.SADB.TRAIN_PLAN_LEG_HISTORY_V AS
SELECT
    TRAIN_PLAN_LEG_ID,
    TRAIN_PLAN_ID,
    TRAIN_DRCTN_CD,
    TRAIN_PLAN_LEG_NM,
    MTP_TITAN_NBR,
    RECORD_CREATE_TMS,
    RECORD_UPDATE_TMS,
    DW_VERSION_NBR,
    DW_EFFECTIVE_TS,
    DW_EXPIRY_TS,
    DW_IS_CURRENT,
    DW_IS_DELETED,
    DW_RECORD_SOURCE
FROM D_SILVER.SADB.TRAIN_PLAN_LEG_CURR_DT_2
ORDER BY TRAIN_PLAN_LEG_ID, DW_VERSION_NBR;
