/*
================================================================================
VALIDATION SCRIPT: DIM_EQUIP — Record Count Comparison
================================================================================
Compares row counts across Source (_BASE), Stream, and Target tables
for all 13 DIM_EQUIP CDC data preservation pipelines.
================================================================================
*/

SELECT 'EQPMNT_POOL_ASGNMN' AS TABLE_NAME,
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_POOL_ASGNMN_BASE) AS SOURCE_COUNT,
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_POOL_ASGNMN_BASE_HIST_STREAM) AS STREAM_COUNT,
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMNT_POOL_ASGNMN) AS TARGET_COUNT
UNION ALL
SELECT 'EQPMV_FLEET_POOL',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_POOL_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_POOL_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMV_FLEET_POOL)
UNION ALL
SELECT 'EQPMV_FLEET_SBGRP',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_SBGRP_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_SBGRP_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMV_FLEET_SBGRP)
UNION ALL
SELECT 'EQPMV_FLEET_SBGRP_CTGRY',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_SBGRP_CTGRY_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_SBGRP_CTGRY_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMV_FLEET_SBGRP_CTGRY)
UNION ALL
SELECT 'EQPMV_FLEET',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMV_FLEET)
UNION ALL
SELECT 'EQPMV_FLEET_EQPMT_CTGRY',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_EQPMT_CTGRY_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_FLEET_EQPMT_CTGRY_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMV_FLEET_EQPMT_CTGRY)
UNION ALL
SELECT 'EQPMV_TARGET_EQPMT_CTGRY',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_TARGET_EQPMT_CTGRY_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_TARGET_EQPMT_CTGRY_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMV_TARGET_EQPMT_CTGRY)
UNION ALL
SELECT 'EQPMV_TARGET_PRDCT',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_TARGET_PRDCT_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMV_TARGET_PRDCT_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMV_TARGET_PRDCT)
UNION ALL
SELECT 'EQPMNT_PARTY',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_PARTY_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_PARTY_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMNT_PARTY)
UNION ALL
SELECT 'EQPMNT_POOL',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_POOL_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_POOL_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMNT_POOL)
UNION ALL
SELECT 'EQPMNT_MARK_OWNER_CLASS_CD',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_MARK_OWNER_CLASS_CD_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_MARK_OWNER_CLASS_CD_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMNT_MARK_OWNER_CLASS_CD)
UNION ALL
SELECT 'EQPMNT_NON_RGSTRD',
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_NON_RGSTRD_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.EQPMNT_NON_RGSTRD_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.EQPMNT_NON_RGSTRD)
UNION ALL
SELECT 'CSTMR_RGSTRD_MARK_JN_GRP',
       (SELECT COUNT(*) FROM D_RAW.SADB.CSTMR_RGSTRD_MARK_JN_GRP_BASE),
       (SELECT COUNT(*) FROM D_RAW.SADB.CSTMR_RGSTRD_MARK_JN_GRP_BASE_HIST_STREAM),
       (SELECT COUNT(*) FROM D_BRONZE.SADB.CSTMR_RGSTRD_MARK_JN_GRP)
ORDER BY TABLE_NAME;
